### Analog DAC8831 Adapter Board A2
# Derived from the A-slot adapter-board pin mapping and uz_dac8831_A3.xdc.

set_property PACKAGE_PIN AH7  [get_ports DAC_CLK_P_A2]
set_property PACKAGE_PIN AJ7  [get_ports DAC_CLK_N_A2]
set_property PACKAGE_PIN AK9  [get_ports DAC_CVN_P_A2]
set_property PACKAGE_PIN AK8  [get_ports DAC_CVN_N_A2]

set_property PACKAGE_PIN AB4  [get_ports DAC_IN_P1_A2]
set_property PACKAGE_PIN AC4  [get_ports DAC_IN_N1_A2]
set_property PACKAGE_PIN AJ5  [get_ports DAC_IN_P2_A2]
set_property PACKAGE_PIN AK5  [get_ports DAC_IN_N2_A2]
set_property PACKAGE_PIN AH3  [get_ports DAC_IN_P3_A2]
set_property PACKAGE_PIN AH2  [get_ports DAC_IN_N3_A2]
set_property PACKAGE_PIN AF6  [get_ports DAC_IN_P4_A2]
set_property PACKAGE_PIN AF5  [get_ports DAC_IN_N4_A2]
set_property PACKAGE_PIN AH6  [get_ports DAC_IN_P5_A2]
set_property PACKAGE_PIN AJ6  [get_ports DAC_IN_N5_A2]
set_property PACKAGE_PIN AH4  [get_ports DAC_IN_P6_A2]
set_property PACKAGE_PIN AJ4  [get_ports DAC_IN_N6_A2]
set_property PACKAGE_PIN AG6  [get_ports DAC_IN_P7_A2]
set_property PACKAGE_PIN AG5  [get_ports DAC_IN_N7_A2]
set_property PACKAGE_PIN AJ10 [get_ports DAC_IN_P8_A2]
set_property PACKAGE_PIN AK10 [get_ports DAC_IN_N8_A2]

set_property IOSTANDARD LVDS [get_ports DAC_CLK_P_A2]
set_property IOSTANDARD LVDS [get_ports DAC_CLK_N_A2]
set_property IOSTANDARD LVDS [get_ports DAC_CVN_P_A2]
set_property IOSTANDARD LVDS [get_ports DAC_CVN_N_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P1_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N1_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P2_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N2_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P3_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N3_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P4_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N4_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P5_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N5_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P6_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N6_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P7_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N7_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P8_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N8_A2]
