open_system('gm_ADC_RAW_TO_VALUE');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ADC_RAW_TO_VALUE/ADC_RAW_TO_VALUE/Delay1', 'user1');
annotate_port('gm_ADC_RAW_TO_VALUE/ADC_RAW_TO_VALUE/Delay1', 1, 1, 'cp : 8.059 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ADC_RAW_TO_VALUE/ADC_RAW_TO_VALUE/Add', 'user2');
annotate_port('gm_ADC_RAW_TO_VALUE/ADC_RAW_TO_VALUE/Add', 0, 1, 'cp : 4.055 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ADC_RAW_TO_VALUE/ADC_RAW_TO_VALUE/Logical Operator', 'user1');
annotate_port('gm_ADC_RAW_TO_VALUE/ADC_RAW_TO_VALUE/Logical Operator', 0, 1, 'cp : 1.934 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ADC_RAW_TO_VALUE/ADC_RAW_TO_VALUE/Product1', 'user2');
annotate_port('gm_ADC_RAW_TO_VALUE/ADC_RAW_TO_VALUE/Product1', 0, 1, 'cp : 8.059 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ADC_RAW_TO_VALUE/ADC_RAW_TO_VALUE/Switch1', 'user2');
annotate_port('gm_ADC_RAW_TO_VALUE/ADC_RAW_TO_VALUE/Switch1', 0, 1, 'cp : 2.901 ns');
