-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\jonat\Documents\MA_JL_CIL\ip_cores\uz_JL_invModel_PT1\hdl_prj\hdlsrc\uz_JL_invModel_PT1\uz_JL_InvModel_PT1.vhd
-- Created: 2026-05-11 15:32:57
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: -1
-- Target subsystem base rate: -1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: uz_JL_InvModel_PT1
-- Source Path: uz_JL_InvModel_PT1
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.uz_JL_InvModel_PT1_pkg.ALL;

ENTITY uz_JL_InvModel_PT1 IS
  PORT( IPCORE_CLK                        :   IN    std_logic;  -- ufix1
        IPCORE_RESETN                     :   IN    std_logic;  -- ufix1
        AXI4_ACLK                         :   IN    std_logic;  -- ufix1
        AXI4_ARESETN                      :   IN    std_logic;  -- ufix1
        AXI4_AWID                         :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
        AXI4_AWADDR                       :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
        AXI4_AWLEN                        :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
        AXI4_AWSIZE                       :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
        AXI4_AWBURST                      :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        AXI4_AWLOCK                       :   IN    std_logic;  -- ufix1
        AXI4_AWCACHE                      :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        AXI4_AWPROT                       :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
        AXI4_AWVALID                      :   IN    std_logic;  -- ufix1
        AXI4_WDATA                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI4_WSTRB                        :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        AXI4_WLAST                        :   IN    std_logic;  -- ufix1
        AXI4_WVALID                       :   IN    std_logic;  -- ufix1
        AXI4_BREADY                       :   IN    std_logic;  -- ufix1
        AXI4_ARID                         :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
        AXI4_ARADDR                       :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
        AXI4_ARLEN                        :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
        AXI4_ARSIZE                       :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
        AXI4_ARBURST                      :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        AXI4_ARLOCK                       :   IN    std_logic;  -- ufix1
        AXI4_ARCACHE                      :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        AXI4_ARPROT                       :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
        AXI4_ARVALID                      :   IN    std_logic;  -- ufix1
        AXI4_RREADY                       :   IN    std_logic;  -- ufix1
        InvOut_PL                         :   OUT   std_logic_vector(95 DOWNTO 0);  -- ufix96
        AXI4_AWREADY                      :   OUT   std_logic;  -- ufix1
        AXI4_WREADY                       :   OUT   std_logic;  -- ufix1
        AXI4_BID                          :   OUT   std_logic_vector(12 DOWNTO 0);  -- ufix13
        AXI4_BRESP                        :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
        AXI4_BVALID                       :   OUT   std_logic;  -- ufix1
        AXI4_ARREADY                      :   OUT   std_logic;  -- ufix1
        AXI4_RID                          :   OUT   std_logic_vector(12 DOWNTO 0);  -- ufix13
        AXI4_RDATA                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI4_RRESP                        :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
        AXI4_RLAST                        :   OUT   std_logic;  -- ufix1
        AXI4_RVALID                       :   OUT   std_logic  -- ufix1
        );
END uz_JL_InvModel_PT1;


ARCHITECTURE rtl OF uz_JL_InvModel_PT1 IS

  -- Component Declarations
  COMPONENT uz_JL_InvModel_PT1_reset_sync
    PORT( clk                             :   IN    std_logic;  -- ufix1
          reset_in                        :   IN    std_logic;  -- ufix1
          reset_out                       :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT uz_JL_InvModel_PT1_axi4
    PORT( reset_x                         :   IN    std_logic;
          AXI4_ACLK                       :   IN    std_logic;  -- ufix1
          AXI4_ARESETN                    :   IN    std_logic;  -- ufix1
          AXI4_AWID                       :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
          AXI4_AWADDR                     :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          AXI4_AWLEN                      :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
          AXI4_AWSIZE                     :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
          AXI4_AWBURST                    :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
          AXI4_AWLOCK                     :   IN    std_logic;  -- ufix1
          AXI4_AWCACHE                    :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          AXI4_AWPROT                     :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
          AXI4_AWVALID                    :   IN    std_logic;  -- ufix1
          AXI4_WDATA                      :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI4_WSTRB                      :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          AXI4_WLAST                      :   IN    std_logic;  -- ufix1
          AXI4_WVALID                     :   IN    std_logic;  -- ufix1
          AXI4_BREADY                     :   IN    std_logic;  -- ufix1
          AXI4_ARID                       :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
          AXI4_ARADDR                     :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          AXI4_ARLEN                      :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
          AXI4_ARSIZE                     :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
          AXI4_ARBURST                    :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
          AXI4_ARLOCK                     :   IN    std_logic;  -- ufix1
          AXI4_ARCACHE                    :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          AXI4_ARPROT                     :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
          AXI4_ARVALID                    :   IN    std_logic;  -- ufix1
          AXI4_RREADY                     :   IN    std_logic;  -- ufix1
          read_ip_timestamp               :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          read_InvOut_PS                  :   IN    vector_of_std_logic_vector32(0 TO 2);  -- ufix32 [3]
          AXI4_AWREADY                    :   OUT   std_logic;  -- ufix1
          AXI4_WREADY                     :   OUT   std_logic;  -- ufix1
          AXI4_BID                        :   OUT   std_logic_vector(12 DOWNTO 0);  -- ufix13
          AXI4_BRESP                      :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
          AXI4_BVALID                     :   OUT   std_logic;  -- ufix1
          AXI4_ARREADY                    :   OUT   std_logic;  -- ufix1
          AXI4_RID                        :   OUT   std_logic_vector(12 DOWNTO 0);  -- ufix13
          AXI4_RDATA                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI4_RRESP                      :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
          AXI4_RLAST                      :   OUT   std_logic;  -- ufix1
          AXI4_RVALID                     :   OUT   std_logic;  -- ufix1
          write_axi_enable                :   OUT   std_logic;  -- ufix1
          write_Ualpha                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          write_Ubeta                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          write_PT1_Gain                  :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          write_PT1_Ts                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          write_PT1_reset                 :   OUT   std_logic;  -- ufix1
          reset_internal                  :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  COMPONENT uz_JL_InvModel_PT1_dut
    PORT( clk                             :   IN    std_logic;  -- ufix1
          reset_x                         :   IN    std_logic;
          dut_enable                      :   IN    std_logic;  -- ufix1
          Ualpha                          :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          Ubeta                           :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          PT1_Gain                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          PT1_Ts                          :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          PT1_reset                       :   IN    std_logic;  -- ufix1
          ce_out                          :   OUT   std_logic;  -- ufix1
          InvOut_PL_0                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          InvOut_PL_1                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          InvOut_PL_2                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          InvOut_PS_0                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          InvOut_PS_1                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          InvOut_PS_2                     :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : uz_JL_InvModel_PT1_reset_sync
    USE ENTITY work.uz_JL_InvModel_PT1_reset_sync(rtl);

  FOR ALL : uz_JL_InvModel_PT1_axi4
    USE ENTITY work.uz_JL_InvModel_PT1_axi4(rtl);

  FOR ALL : uz_JL_InvModel_PT1_dut
    USE ENTITY work.uz_JL_InvModel_PT1_dut(rtl);

  -- Signals
  SIGNAL reset_x                          : std_logic;
  SIGNAL ip_timestamp                     : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL reset_cm                         : std_logic;  -- ufix1
  SIGNAL reset_internal                   : std_logic;  -- ufix1
  SIGNAL reset_before_sync                : std_logic;  -- ufix1
  SIGNAL read_InvOut_PS_vec               : vector_of_std_logic_vector32(0 TO 2);  -- ufix32 [3]
  SIGNAL AXI4_BID_tmp                     : std_logic_vector(12 DOWNTO 0);  -- ufix13
  SIGNAL AXI4_BRESP_tmp                   : std_logic_vector(1 DOWNTO 0);  -- ufix2
  SIGNAL AXI4_RID_tmp                     : std_logic_vector(12 DOWNTO 0);  -- ufix13
  SIGNAL AXI4_RDATA_tmp                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL AXI4_RRESP_tmp                   : std_logic_vector(1 DOWNTO 0);  -- ufix2
  SIGNAL write_axi_enable                 : std_logic;  -- ufix1
  SIGNAL write_Ualpha                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL write_Ubeta                      : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL write_PT1_Gain                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL write_PT1_Ts                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL write_PT1_reset                  : std_logic;  -- ufix1
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL InvOut_PL_0_sig                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL InvOut_PL_1_sig                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL InvOut_PL_2_sig                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL InvOut_PL_2_sig_unsigned         : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL InvOut_PL_1_sig_unsigned         : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL InvOut_PL_0_sig_unsigned         : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL InvOut_PL_tmp                    : unsigned(95 DOWNTO 0);  -- ufix96

BEGIN
  u_uz_JL_InvModel_PT1_reset_sync_inst : uz_JL_InvModel_PT1_reset_sync
    PORT MAP( clk => IPCORE_CLK,  -- ufix1
              reset_in => reset_before_sync,  -- ufix1
              reset_out => reset_x
              );

  u_uz_JL_InvModel_PT1_axi4_inst : uz_JL_InvModel_PT1_axi4
    PORT MAP( reset_x => reset_x,
              AXI4_ACLK => AXI4_ACLK,  -- ufix1
              AXI4_ARESETN => AXI4_ARESETN,  -- ufix1
              AXI4_AWID => AXI4_AWID,  -- ufix13
              AXI4_AWADDR => AXI4_AWADDR,  -- ufix16
              AXI4_AWLEN => AXI4_AWLEN,  -- ufix8
              AXI4_AWSIZE => AXI4_AWSIZE,  -- ufix3
              AXI4_AWBURST => AXI4_AWBURST,  -- ufix2
              AXI4_AWLOCK => AXI4_AWLOCK,  -- ufix1
              AXI4_AWCACHE => AXI4_AWCACHE,  -- ufix4
              AXI4_AWPROT => AXI4_AWPROT,  -- ufix3
              AXI4_AWVALID => AXI4_AWVALID,  -- ufix1
              AXI4_WDATA => AXI4_WDATA,  -- ufix32
              AXI4_WSTRB => AXI4_WSTRB,  -- ufix4
              AXI4_WLAST => AXI4_WLAST,  -- ufix1
              AXI4_WVALID => AXI4_WVALID,  -- ufix1
              AXI4_BREADY => AXI4_BREADY,  -- ufix1
              AXI4_ARID => AXI4_ARID,  -- ufix13
              AXI4_ARADDR => AXI4_ARADDR,  -- ufix16
              AXI4_ARLEN => AXI4_ARLEN,  -- ufix8
              AXI4_ARSIZE => AXI4_ARSIZE,  -- ufix3
              AXI4_ARBURST => AXI4_ARBURST,  -- ufix2
              AXI4_ARLOCK => AXI4_ARLOCK,  -- ufix1
              AXI4_ARCACHE => AXI4_ARCACHE,  -- ufix4
              AXI4_ARPROT => AXI4_ARPROT,  -- ufix3
              AXI4_ARVALID => AXI4_ARVALID,  -- ufix1
              AXI4_RREADY => AXI4_RREADY,  -- ufix1
              read_ip_timestamp => std_logic_vector(ip_timestamp),  -- ufix32
              read_InvOut_PS => read_InvOut_PS_vec,  -- ufix32 [3]
              AXI4_AWREADY => AXI4_AWREADY,  -- ufix1
              AXI4_WREADY => AXI4_WREADY,  -- ufix1
              AXI4_BID => AXI4_BID_tmp,  -- ufix13
              AXI4_BRESP => AXI4_BRESP_tmp,  -- ufix2
              AXI4_BVALID => AXI4_BVALID,  -- ufix1
              AXI4_ARREADY => AXI4_ARREADY,  -- ufix1
              AXI4_RID => AXI4_RID_tmp,  -- ufix13
              AXI4_RDATA => AXI4_RDATA_tmp,  -- ufix32
              AXI4_RRESP => AXI4_RRESP_tmp,  -- ufix2
              AXI4_RLAST => AXI4_RLAST,  -- ufix1
              AXI4_RVALID => AXI4_RVALID,  -- ufix1
              write_axi_enable => write_axi_enable,  -- ufix1
              write_Ualpha => write_Ualpha,  -- ufix32
              write_Ubeta => write_Ubeta,  -- ufix32
              write_PT1_Gain => write_PT1_Gain,  -- ufix32
              write_PT1_Ts => write_PT1_Ts,  -- ufix32
              write_PT1_reset => write_PT1_reset,  -- ufix1
              reset_internal => reset_internal  -- ufix1
              );

  u_uz_JL_InvModel_PT1_dut_inst : uz_JL_InvModel_PT1_dut
    PORT MAP( clk => IPCORE_CLK,  -- ufix1
              reset_x => reset_x,
              dut_enable => write_axi_enable,  -- ufix1
              Ualpha => write_Ualpha,  -- ufix32
              Ubeta => write_Ubeta,  -- ufix32
              PT1_Gain => write_PT1_Gain,  -- ufix32
              PT1_Ts => write_PT1_Ts,  -- ufix32
              PT1_reset => write_PT1_reset,  -- ufix1
              ce_out => ce_out_sig,  -- ufix1
              InvOut_PL_0 => InvOut_PL_0_sig,  -- ufix32
              InvOut_PL_1 => InvOut_PL_1_sig,  -- ufix32
              InvOut_PL_2 => InvOut_PL_2_sig,  -- ufix32
              InvOut_PS_0 => read_InvOut_PS_vec(0),  -- ufix32
              InvOut_PS_1 => read_InvOut_PS_vec(1),  -- ufix32
              InvOut_PS_2 => read_InvOut_PS_vec(2)  -- ufix32
              );

  ip_timestamp <= unsigned'(X"9B46D8EC");

  reset_cm <=  NOT IPCORE_RESETN;

  reset_before_sync <= reset_cm OR reset_internal;


  InvOut_PL_2_sig_unsigned <= unsigned(InvOut_PL_2_sig);

  InvOut_PL_1_sig_unsigned <= unsigned(InvOut_PL_1_sig);

  InvOut_PL_0_sig_unsigned <= unsigned(InvOut_PL_0_sig);

  InvOut_PL_tmp <= InvOut_PL_2_sig_unsigned & InvOut_PL_1_sig_unsigned & InvOut_PL_0_sig_unsigned;

  InvOut_PL <= std_logic_vector(InvOut_PL_tmp);

  AXI4_BID <= AXI4_BID_tmp;

  AXI4_BRESP <= AXI4_BRESP_tmp;

  AXI4_RID <= AXI4_RID_tmp;

  AXI4_RDATA <= AXI4_RDATA_tmp;

  AXI4_RRESP <= AXI4_RRESP_tmp;

END rtl;

