SLStudio.Utils.RemoveHighlighting(get_param('uz_mpc_3ph', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_uz_mpc_3ph', 'handle'));
annotate_port('gm_uz_mpc_3ph/uz_sel_resolver/Delay', 0, 1, '');
annotate_port('gm_uz_mpc_3ph/uz_sel_resolver/Delay', 1, 1, '');
annotate_port('uz_mpc_3ph/uz_sel_resolver/Delay', 1, 1, '');
annotate_port('gm_uz_mpc_3ph/uz_sel_resolver/Delay1', 1, 1, '');
annotate_port('uz_mpc_3ph/uz_sel_resolver/Delay1', 1, 1, '');
annotate_port('gm_uz_mpc_3ph/uz_sel_resolver/Delay2', 1, 1, '');
annotate_port('gm_uz_mpc_3ph/uz_sel_resolver/Delay2', 1, 1, '');
annotate_port('uz_mpc_3ph/uz_sel_resolver/Delay2', 1, 1, '');
annotate_port('gm_uz_mpc_3ph/uz_sel_resolver/Delay21', 1, 1, '');
annotate_port('uz_mpc_3ph/uz_sel_resolver/Delay21', 1, 1, '');
annotate_port('gm_uz_mpc_3ph/uz_sel_resolver/Delay28', 1, 1, '');
annotate_port('uz_mpc_3ph/uz_sel_resolver/Delay28', 1, 1, '');
annotate_port('gm_uz_mpc_3ph/uz_sel_resolver/Delay29', 1, 1, '');
annotate_port('uz_mpc_3ph/uz_sel_resolver/Delay29', 1, 1, '');
annotate_port('gm_uz_mpc_3ph/uz_sel_resolver/Delay3', 1, 1, '');
annotate_port('uz_mpc_3ph/uz_sel_resolver/Delay3', 1, 1, '');
annotate_port('gm_uz_mpc_3ph/uz_sel_resolver/Delay4', 1, 1, '');
annotate_port('uz_mpc_3ph/uz_sel_resolver/Delay4', 1, 1, '');
annotate_port('gm_uz_mpc_3ph/uz_sel_resolver/Delay5', 1, 1, '');
annotate_port('uz_mpc_3ph/uz_sel_resolver/Delay5', 1, 1, '');
annotate_port('gm_uz_mpc_3ph/uz_sel_resolver/Switch', 0, 1, '');
