open_system('gm_uz_mpc_3ph');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/uz_sel_resolver/Delay', 'user1');
annotate_port('gm_uz_mpc_3ph/uz_sel_resolver/Delay', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/uz_sel_resolver/Delay2', 'user1');
annotate_port('gm_uz_mpc_3ph/uz_sel_resolver/Delay2', 1, 1, 'cp : 0.39 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/uz_sel_resolver/Switch', 'user2');
annotate_port('gm_uz_mpc_3ph/uz_sel_resolver/Switch', 0, 1, 'cp : 0.39 ns');
