open_system('gm_uz_mpc_3ph');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/counter_f_sw_3ph/Count_f_sw', 'user2');
annotate_port('gm_uz_mpc_3ph/counter_f_sw_3ph/Count_f_sw', 1, 4, 'cp : 1.971 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/counter_f_sw_3ph/reset_old2', 'user1');
annotate_port('gm_uz_mpc_3ph/counter_f_sw_3ph/reset_old2', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/counter_f_sw_3ph/Detec_edge', 'user2');
annotate_port('gm_uz_mpc_3ph/counter_f_sw_3ph/Detec_edge', 0, 1, 'cp : 0.747 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/counter_f_sw_3ph/dtc', 'user2');
annotate_port('gm_uz_mpc_3ph/counter_f_sw_3ph/dtc', 0, 1, 'cp : 1.635 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/counter_f_sw_3ph/Saturation', 'user2');
annotate_port('gm_uz_mpc_3ph/counter_f_sw_3ph/Saturation', 0, 1, 'cp : 1.971 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/counter_f_sw_3ph/Count_f_sw/Count_f_sw', 'user2');
annotate_port('gm_uz_mpc_3ph/counter_f_sw_3ph/Count_f_sw/Count_f_sw', 1, 4, 'cp : 1.971 ns');
