open_system('uz_mpc_3ph');
open_system('gm_uz_mpc_3ph');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/uz_sel_currents/Delay', 'user2');
annotate_port('gm_uz_mpc_3ph/uz_sel_currents/Delay', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_3ph/uz_sel_currents/Delay', 'user2');
annotate_port('uz_mpc_3ph/uz_sel_currents/Delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/uz_sel_currents/Delay1', 'user2');
annotate_port('gm_uz_mpc_3ph/uz_sel_currents/Delay1', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_3ph/uz_sel_currents/Delay1', 'user2');
annotate_port('uz_mpc_3ph/uz_sel_currents/Delay1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/uz_sel_currents/Delay10', 'user2');
annotate_port('gm_uz_mpc_3ph/uz_sel_currents/Delay10', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_3ph/uz_sel_currents/Delay10', 'user2');
annotate_port('uz_mpc_3ph/uz_sel_currents/Delay10', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/uz_sel_currents/Delay11', 'user2');
annotate_port('gm_uz_mpc_3ph/uz_sel_currents/Delay11', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_3ph/uz_sel_currents/Delay11', 'user2');
annotate_port('uz_mpc_3ph/uz_sel_currents/Delay11', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/uz_sel_currents/Delay2', 'user2');
annotate_port('gm_uz_mpc_3ph/uz_sel_currents/Delay2', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_3ph/uz_sel_currents/Delay2', 'user2');
annotate_port('uz_mpc_3ph/uz_sel_currents/Delay2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/uz_sel_currents/Delay21', 'user2');
annotate_port('gm_uz_mpc_3ph/uz_sel_currents/Delay21', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_3ph/uz_sel_currents/Delay21', 'user2');
annotate_port('uz_mpc_3ph/uz_sel_currents/Delay21', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/uz_sel_currents/Delay28', 'user2');
annotate_port('gm_uz_mpc_3ph/uz_sel_currents/Delay28', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_3ph/uz_sel_currents/Delay28', 'user2');
annotate_port('uz_mpc_3ph/uz_sel_currents/Delay28', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/uz_sel_currents/Delay29', 'user2');
annotate_port('gm_uz_mpc_3ph/uz_sel_currents/Delay29', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_3ph/uz_sel_currents/Delay29', 'user2');
annotate_port('uz_mpc_3ph/uz_sel_currents/Delay29', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/uz_sel_currents/Delay3', 'user2');
annotate_port('gm_uz_mpc_3ph/uz_sel_currents/Delay3', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_3ph/uz_sel_currents/Delay3', 'user2');
annotate_port('uz_mpc_3ph/uz_sel_currents/Delay3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/uz_sel_currents/Delay4', 'user2');
annotate_port('gm_uz_mpc_3ph/uz_sel_currents/Delay4', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_3ph/uz_sel_currents/Delay4', 'user2');
annotate_port('uz_mpc_3ph/uz_sel_currents/Delay4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/uz_sel_currents/Delay5', 'user2');
annotate_port('gm_uz_mpc_3ph/uz_sel_currents/Delay5', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_3ph/uz_sel_currents/Delay5', 'user2');
annotate_port('uz_mpc_3ph/uz_sel_currents/Delay5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/uz_sel_currents/Delay6', 'user2');
annotate_port('gm_uz_mpc_3ph/uz_sel_currents/Delay6', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_3ph/uz_sel_currents/Delay6', 'user2');
annotate_port('uz_mpc_3ph/uz_sel_currents/Delay6', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/uz_sel_currents/Delay7', 'user2');
annotate_port('gm_uz_mpc_3ph/uz_sel_currents/Delay7', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_3ph/uz_sel_currents/Delay7', 'user2');
annotate_port('uz_mpc_3ph/uz_sel_currents/Delay7', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/uz_sel_currents/Delay8', 'user2');
annotate_port('gm_uz_mpc_3ph/uz_sel_currents/Delay8', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_3ph/uz_sel_currents/Delay8', 'user2');
annotate_port('uz_mpc_3ph/uz_sel_currents/Delay8', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/uz_sel_currents/Delay9', 'user2');
annotate_port('gm_uz_mpc_3ph/uz_sel_currents/Delay9', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_3ph/uz_sel_currents/Delay9', 'user2');
annotate_port('uz_mpc_3ph/uz_sel_currents/Delay9', 1, 1, 'Block not characterized');
