open_system('uz_mpc_3ph');
open_system('gm_uz_mpc_3ph');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/uz_sel_resolver/Delay', 'user2');
annotate_port('gm_uz_mpc_3ph/uz_sel_resolver/Delay', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_3ph/uz_sel_resolver/Delay', 'user2');
annotate_port('uz_mpc_3ph/uz_sel_resolver/Delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/uz_sel_resolver/Delay1', 'user2');
annotate_port('gm_uz_mpc_3ph/uz_sel_resolver/Delay1', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_3ph/uz_sel_resolver/Delay1', 'user2');
annotate_port('uz_mpc_3ph/uz_sel_resolver/Delay1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/uz_sel_resolver/Delay2', 'user2');
annotate_port('gm_uz_mpc_3ph/uz_sel_resolver/Delay2', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_3ph/uz_sel_resolver/Delay2', 'user2');
annotate_port('uz_mpc_3ph/uz_sel_resolver/Delay2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/uz_sel_resolver/Delay21', 'user2');
annotate_port('gm_uz_mpc_3ph/uz_sel_resolver/Delay21', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_3ph/uz_sel_resolver/Delay21', 'user2');
annotate_port('uz_mpc_3ph/uz_sel_resolver/Delay21', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/uz_sel_resolver/Delay28', 'user2');
annotate_port('gm_uz_mpc_3ph/uz_sel_resolver/Delay28', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_3ph/uz_sel_resolver/Delay28', 'user2');
annotate_port('uz_mpc_3ph/uz_sel_resolver/Delay28', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/uz_sel_resolver/Delay29', 'user2');
annotate_port('gm_uz_mpc_3ph/uz_sel_resolver/Delay29', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_3ph/uz_sel_resolver/Delay29', 'user2');
annotate_port('uz_mpc_3ph/uz_sel_resolver/Delay29', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/uz_sel_resolver/Delay3', 'user2');
annotate_port('gm_uz_mpc_3ph/uz_sel_resolver/Delay3', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_3ph/uz_sel_resolver/Delay3', 'user2');
annotate_port('uz_mpc_3ph/uz_sel_resolver/Delay3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/uz_sel_resolver/Delay4', 'user2');
annotate_port('gm_uz_mpc_3ph/uz_sel_resolver/Delay4', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_3ph/uz_sel_resolver/Delay4', 'user2');
annotate_port('uz_mpc_3ph/uz_sel_resolver/Delay4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/uz_sel_resolver/Delay5', 'user2');
annotate_port('gm_uz_mpc_3ph/uz_sel_resolver/Delay5', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_3ph/uz_sel_resolver/Delay5', 'user2');
annotate_port('uz_mpc_3ph/uz_sel_resolver/Delay5', 1, 1, 'Block not characterized');
