open_system('uz_mpc_3ph');
open_system('gm_uz_mpc_3ph');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/counter_f_sw_3ph/SS_Old', 'user2');
annotate_port('gm_uz_mpc_3ph/counter_f_sw_3ph/SS_Old', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_3ph/counter_f_sw_3ph/SS_Old', 'user2');
annotate_port('uz_mpc_3ph/counter_f_sw_3ph/SS_Old', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/counter_f_sw_3ph/delay', 'user2');
annotate_port('gm_uz_mpc_3ph/counter_f_sw_3ph/delay', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_3ph/counter_f_sw_3ph/delay', 'user2');
annotate_port('uz_mpc_3ph/counter_f_sw_3ph/delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/counter_f_sw_3ph/reset_old2', 'user2');
annotate_port('gm_uz_mpc_3ph/counter_f_sw_3ph/reset_old2', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_3ph/counter_f_sw_3ph/reset_old2', 'user2');
annotate_port('uz_mpc_3ph/counter_f_sw_3ph/reset_old2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/counter_f_sw_3ph/Count_f_sw/Count_f_sw', 'user2');
annotate_port('gm_uz_mpc_3ph/counter_f_sw_3ph/Count_f_sw/Count_f_sw', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_3ph/counter_f_sw_3ph/Count_f_sw/Count_f_sw', 'user2');
annotate_port('gm_uz_mpc_3ph/counter_f_sw_3ph/Count_f_sw/Count_f_sw', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_3ph/counter_f_sw_3ph/Count_f_sw', 'user2');
annotate_port('uz_mpc_3ph/counter_f_sw_3ph/Count_f_sw', 1, 1, 'Block not characterized');
