SLStudio.Utils.RemoveHighlighting(get_param('gmStateSpaceHDL_uz_inverter_3ph', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_gmStateSpaceHDL_uz_inverter_3ph', 'handle'));
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Delay', 1, 1, '');
annotate_port('gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/HDL Subsystem/HDL Algorithm/Mode Iteration Manager/Delay', 1, 1, '');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Delay2', 1, 1, '');
annotate_port('gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/HDL Subsystem/HDL Algorithm/Mode Iteration Manager/Delay2', 1, 1, '');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Rate Transition10', 1, 1, '');
annotate_port('gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/HDL Subsystem/Rate Transition10', 1, 1, '');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Rate Transition11', 1, 1, '');
annotate_port('gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/HDL Subsystem/Rate Transition11', 1, 1, '');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Rate Transition12', 1, 1, '');
annotate_port('gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/HDL Subsystem/Rate Transition12', 1, 1, '');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Rate Transition13', 1, 1, '');
annotate_port('gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/HDL Subsystem/Rate Transition13', 1, 1, '');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Rate Transition14', 1, 1, '');
annotate_port('gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/HDL Subsystem/Rate Transition14', 1, 1, '');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Rate Transition15', 1, 1, '');
annotate_port('gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/HDL Subsystem/Rate Transition15', 1, 1, '');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Rate Transition16', 1, 1, '');
annotate_port('gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/HDL Subsystem/Rate Transition16', 1, 1, '');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Rate Transition17', 1, 1, '');
annotate_port('gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/HDL Subsystem/Rate Transition17', 1, 1, '');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Rate Transition18', 1, 1, '');
annotate_port('gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/HDL Subsystem/Rate Transition18', 1, 1, '');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Rate Transition19', 1, 1, '');
annotate_port('gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/HDL Subsystem/Rate Transition19', 1, 1, '');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Rate Transition20', 1, 1, '');
annotate_port('gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/HDL Subsystem/Rate Transition20', 1, 1, '');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Rate Transition21', 1, 1, '');
annotate_port('gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/HDL Subsystem/Rate Transition21', 1, 1, '');
