open_system('gm_gmStateSpaceHDL_uz_inverter_3ph');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/State Update_out1', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/State Update_out1', 0, 1, 'cp : 4.557 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Mode Iteration Manager_out2', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Mode Iteration Manager_out2', 0, 1, 'cp : 4.557 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Mode Selection_out1', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Mode Selection_out1', 0, 1, 'cp : 4.273 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/State Mode Vector To Index_out1', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/State Mode Vector To Index_out1', 0, 1, 'cp : 4.273 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem8', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem8', 0, 1, 'cp : 1.543 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem7', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem7', 0, 1, 'cp : 1.933 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem6', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem6', 0, 1, 'cp : 2.323 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem5', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem5', 0, 1, 'cp : 2.713 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem4', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem4', 0, 1, 'cp : 3.103 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem3', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem3', 0, 1, 'cp : 3.493 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem2', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem2', 0, 1, 'cp : 3.883 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem1', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem1', 0, 1, 'cp : 4.273 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/modes', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/modes', 0, 1, 'cp : 0.331 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/concatenate', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/concatenate', 0, 1, 'cp : 0.331 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Multiply Input', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Multiply Input', 0, 1, 'cp : 4.557 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Switch11', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Switch11', 0, 1, 'cp : 4.557 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Data Type Conversion2', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Data Type Conversion2', 0, 1, 'cp : 0.331 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Reshape2', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Reshape2', 0, 1, 'cp : 0.331 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/compare_relop', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/compare_relop', 0, 1, 'cp : 0.331 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/compare_relop_outbuff', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/compare_relop_outbuff', 0, 1, 'cp : 0.331 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/adder', 'user1');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/adder', 0, 1, 'cp : 0.331 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/adder_outbuff', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/adder_outbuff', 0, 1, 'cp : 0.331 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Multiply Input_outbuff', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Multiply Input_outbuff', 0, 1, 'cp : 4.557 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/State Delay', 'user1');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/State Delay', 1, 1, 'cp : 4.818 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem8/Bitwise Operator', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem8/Bitwise Operator', 0, 1, 'cp : 0.587 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem8/Bitwise Operator1', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem8/Bitwise Operator1', 0, 1, 'cp : 1.191 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem8/t', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem8/t', 0, 7, 'cp : 0.587 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem8/Bitwise Operator_out1_6_wire', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem8/Bitwise Operator_out1_6_wire', 0, 1, 'cp : 0.587 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem8/Switch', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem8/Switch', 0, 1, 'cp : 1.543 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem1/Switch', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem1/Switch', 0, 1, 'cp : 4.273 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem2/Switch', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem2/Switch', 0, 1, 'cp : 3.883 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem3/Switch', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem3/Switch', 0, 1, 'cp : 3.493 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem4/Switch', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem4/Switch', 0, 1, 'cp : 3.103 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem5/Switch', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem5/Switch', 0, 1, 'cp : 2.713 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem6/Switch', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem6/Switch', 0, 1, 'cp : 2.323 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem7/Switch', 'user2');
annotate_port('gm_gmStateSpaceHDL_uz_inverter_3ph/uz_inverter_3ph/Subsystem7/Switch', 0, 1, 'cp : 1.933 ns');
