open_system('gm_parallel_8_switching_states');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_switching_states/HDL_DUT/Detect Rise Positive', 'user2');
annotate_port('gm_parallel_8_switching_states/HDL_DUT/Detect Rise Positive', 0, 1, 'cp : 1.704 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_switching_states/HDL_DUT/Delay', 'user1');
annotate_port('gm_parallel_8_switching_states/HDL_DUT/Delay', 0, 1, 'cp : 0.33 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_switching_states/HDL_DUT/Delay2', 'user1');
annotate_port('gm_parallel_8_switching_states/HDL_DUT/Delay2', 1, 1, 'cp : 2.293 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_switching_states/HDL_DUT/Switch_on2', 'user2');
annotate_port('gm_parallel_8_switching_states/HDL_DUT/Switch_on2', 0, 1, 'cp : 2.032 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_switching_states/HDL_DUT/Detect Rise Positive/Positive', 'user2');
annotate_port('gm_parallel_8_switching_states/HDL_DUT/Detect Rise Positive/Positive', 0, 1, 'cp : 1.017 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_switching_states/HDL_DUT/Detect Rise Positive/FixPt Relational Operator', 'user2');
annotate_port('gm_parallel_8_switching_states/HDL_DUT/Detect Rise Positive/FixPt Relational Operator', 0, 1, 'cp : 1.704 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_switching_states/HDL_DUT/Detect Rise Positive/Positive/Compare', 'user2');
annotate_port('gm_parallel_8_switching_states/HDL_DUT/Detect Rise Positive/Positive/Compare', 0, 1, 'cp : 1.017 ns');
