### Analog DAC8831 Adapter Board A3
# Derived from the A-slot adapter-board pin mapping and uz_dac8831_A3.xdc.

set_property PACKAGE_PIN L3  [get_ports DAC_CLK_P_A3]
set_property PACKAGE_PIN L2  [get_ports DAC_CLK_N_A3]
set_property PACKAGE_PIN AE2 [get_ports DAC_CVN_P_A3]
set_property PACKAGE_PIN AF2 [get_ports DAC_CVN_N_A3]

set_property PACKAGE_PIN H6  [get_ports DAC_IN_P1_A3]
set_property PACKAGE_PIN J6  [get_ports DAC_IN_N1_A3]
set_property PACKAGE_PIN AB1 [get_ports DAC_IN_P2_A3]
set_property PACKAGE_PIN AC1 [get_ports DAC_IN_N2_A3]
set_property PACKAGE_PIN AC6 [get_ports DAC_IN_P3_A3]
set_property PACKAGE_PIN AB6 [get_ports DAC_IN_N3_A3]
set_property PACKAGE_PIN AD1 [get_ports DAC_IN_P4_A3]
set_property PACKAGE_PIN AD2 [get_ports DAC_IN_N4_A3]
set_property PACKAGE_PIN K4  [get_ports DAC_IN_P5_A3]
set_property PACKAGE_PIN K3  [get_ports DAC_IN_N5_A3]
set_property PACKAGE_PIN AB2 [get_ports DAC_IN_P6_A3]
set_property PACKAGE_PIN AC2 [get_ports DAC_IN_N6_A3]
set_property PACKAGE_PIN J5  [get_ports DAC_IN_P7_A3]
set_property PACKAGE_PIN J4  [get_ports DAC_IN_N7_A3]
set_property PACKAGE_PIN N7  [get_ports DAC_IN_P8_A3]
set_property PACKAGE_PIN N6  [get_ports DAC_IN_N8_A3]

set_property IOSTANDARD LVDS [get_ports DAC_CLK_P_A3]
set_property IOSTANDARD LVDS [get_ports DAC_CLK_N_A3]
set_property IOSTANDARD LVDS [get_ports DAC_CVN_P_A3]
set_property IOSTANDARD LVDS [get_ports DAC_CVN_N_A3]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P1_A3]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N1_A3]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P2_A3]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N2_A3]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P3_A3]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N3_A3]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P4_A3]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N4_A3]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P5_A3]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N5_A3]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P6_A3]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N6_A3]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P7_A3]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N7_A3]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P8_A3]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N8_A3]
