### Analog DAC8831 Adapter Board A2
# Derived from the A-slot adapter-board pin mapping and uz_dac8831_A3.xdc.

set_property PACKAGE_PIN AE5 [get_ports DAC_CLK_P_A2]
set_property PACKAGE_PIN AF5 [get_ports DAC_CLK_N_A2]
set_property PACKAGE_PIN AG4 [get_ports DAC_CVN_P_A2]
set_property PACKAGE_PIN AH4 [get_ports DAC_CVN_N_A2]

set_property PACKAGE_PIN J2  [get_ports DAC_IN_P1_A2]
set_property PACKAGE_PIN K2  [get_ports DAC_IN_N1_A2]
set_property PACKAGE_PIN AH1 [get_ports DAC_IN_P2_A2]
set_property PACKAGE_PIN AH2 [get_ports DAC_IN_N2_A2]
set_property PACKAGE_PIN AG1 [get_ports DAC_IN_P3_A2]
set_property PACKAGE_PIN AF1 [get_ports DAC_IN_N3_A2]
set_property PACKAGE_PIN AG3 [get_ports DAC_IN_P4_A2]
set_property PACKAGE_PIN AH3 [get_ports DAC_IN_N4_A2]
set_property PACKAGE_PIN AD5 [get_ports DAC_IN_P5_A2]
set_property PACKAGE_PIN AD4 [get_ports DAC_IN_N5_A2]
set_property PACKAGE_PIN AE3 [get_ports DAC_IN_P6_A2]
set_property PACKAGE_PIN AF3 [get_ports DAC_IN_N6_A2]
set_property PACKAGE_PIN AC4 [get_ports DAC_IN_P7_A2]
set_property PACKAGE_PIN AC3 [get_ports DAC_IN_N7_A2]
set_property PACKAGE_PIN AG6 [get_ports DAC_IN_P8_A2]
set_property PACKAGE_PIN AG5 [get_ports DAC_IN_N8_A2]

set_property IOSTANDARD LVDS [get_ports DAC_CLK_P_A2]
set_property IOSTANDARD LVDS [get_ports DAC_CLK_N_A2]
set_property IOSTANDARD LVDS [get_ports DAC_CVN_P_A2]
set_property IOSTANDARD LVDS [get_ports DAC_CVN_N_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P1_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N1_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P2_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N2_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P3_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N3_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P4_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N4_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P5_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N5_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P6_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N6_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P7_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N7_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P8_A2]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N8_A2]
