### Analog DAC8831 Adapter Board A1
# Derived from the A-slot adapter-board pin mapping and uz_dac8831_A3.xdc.

set_property PACKAGE_PIN AF7 [get_ports DAC_CLK_P_A1]
set_property PACKAGE_PIN AF6 [get_ports DAC_CLK_N_A1]
set_property PACKAGE_PIN AC9 [get_ports DAC_CVN_P_A1]
set_property PACKAGE_PIN AD9 [get_ports DAC_CVN_N_A1]

set_property PACKAGE_PIN AH8 [get_ports DAC_IN_P1_A1]
set_property PACKAGE_PIN AH7 [get_ports DAC_IN_N1_A1]
set_property PACKAGE_PIN AG9 [get_ports DAC_IN_P2_A1]
set_property PACKAGE_PIN AH9 [get_ports DAC_IN_N2_A1]
set_property PACKAGE_PIN H4  [get_ports DAC_IN_P3_A1]
set_property PACKAGE_PIN H3  [get_ports DAC_IN_N3_A1]
set_property PACKAGE_PIN AD7 [get_ports DAC_IN_P4_A1]
set_property PACKAGE_PIN AE7 [get_ports DAC_IN_N4_A1]
set_property PACKAGE_PIN L7  [get_ports DAC_IN_P5_A1]
set_property PACKAGE_PIN L6  [get_ports DAC_IN_N5_A1]
set_property PACKAGE_PIN AG8 [get_ports DAC_IN_P6_A1]
set_property PACKAGE_PIN AF8 [get_ports DAC_IN_N6_A1]
set_property PACKAGE_PIN AC8 [get_ports DAC_IN_P7_A1]
set_property PACKAGE_PIN AB8 [get_ports DAC_IN_N7_A1]
set_property PACKAGE_PIN AE9 [get_ports DAC_IN_P8_A1]
set_property PACKAGE_PIN AE8 [get_ports DAC_IN_N8_A1]

set_property IOSTANDARD LVDS [get_ports DAC_CLK_P_A1]
set_property IOSTANDARD LVDS [get_ports DAC_CLK_N_A1]
set_property IOSTANDARD LVDS [get_ports DAC_CVN_P_A1]
set_property IOSTANDARD LVDS [get_ports DAC_CVN_N_A1]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P1_A1]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N1_A1]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P2_A1]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N2_A1]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P3_A1]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N3_A1]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P4_A1]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N4_A1]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P5_A1]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N5_A1]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P6_A1]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N6_A1]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P7_A1]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N7_A1]
set_property IOSTANDARD LVDS [get_ports DAC_IN_P8_A1]
set_property IOSTANDARD LVDS [get_ports DAC_IN_N8_A1]
