-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\ELSYS_PC\Documents\repos\ultrazohm_sw\ip_cores\uz_EnDat_IPCore\hdl_prj\hdlsrc\UZ_EnDat\uz_EnDat_src_Compare_To_Constant_block.vhd
-- Created: 2023-12-12 20:30:54
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: uz_EnDat_src_Compare_To_Constant_block
-- Source Path: UZ_EnDat/UZ_ENDAT/Compare To Constant
-- Hierarchy Level: 1
-- Model version: 2.284
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY uz_EnDat_src_Compare_To_Constant_block IS
  PORT( u                                 :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        y                                 :   OUT   std_logic
        );
END uz_EnDat_src_Compare_To_Constant_block;


ARCHITECTURE rtl OF uz_EnDat_src_Compare_To_Constant_block IS

  -- Signals
  SIGNAL u_unsigned                       : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Constant_out1                    : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Compare_relop1                   : std_logic;

BEGIN
  u_unsigned <= unsigned(u);

  Constant_out1 <= to_unsigned(16#1#, 4);

  
  Compare_relop1 <= '1' WHEN u_unsigned = Constant_out1 ELSE
      '0';

  y <= Compare_relop1;

END rtl;

