SLStudio.Utils.RemoveHighlighting(get_param('parallel_8_min_cost_function', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_parallel_8_min_cost_function', 'handle'));
annotate_port('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Detect Rise Positive', 0, 1, '');
annotate_port('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Detect Rise Positive1', 0, 1, '');
annotate_port('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Delay371', 1, 1, '');
annotate_port('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Delay6', 0, 1, '');
annotate_port('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Relational Operator1', 0, 1, '');
annotate_port('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Switch_on1', 0, 1, '');
annotate_port('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Switch_on98', 0, 1, '');
annotate_port('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/MinMax', 1, 1, '');
annotate_port('parallel_8_min_cost_function/Min_cost_function_and_vopt2/MinMax', 1, 1, '');
annotate_port('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/MinMax', 1, 1, '');
annotate_port('parallel_8_min_cost_function/Min_cost_function_and_vopt2/MinMax', 1, 1, '');
annotate_port('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Detect Rise Positive/Positive', 0, 1, '');
annotate_port('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Detect Rise Positive/FixPt Relational Operator', 0, 1, '');
annotate_port('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Detect Rise Positive/Positive/Compare', 0, 1, '');
annotate_port('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Detect Rise Positive1/Positive', 0, 1, '');
annotate_port('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Detect Rise Positive1/FixPt Relational Operator', 0, 1, '');
annotate_port('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Detect Rise Positive1/Positive/Compare', 0, 1, '');
annotate_port('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/MATLAB Function/MATLAB Function', 1, 1, '');
annotate_port('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/MATLAB Function/MATLAB Function', 1, 1, '');
annotate_port('parallel_8_min_cost_function/Min_cost_function_and_vopt2/MATLAB Function', 1, 1, '');
annotate_port('parallel_8_min_cost_function/Min_cost_function_and_vopt2/MinMax', 1, 1, '');
annotate_port('parallel_8_min_cost_function/Min_cost_function_and_vopt2/MinMax', 1, 1, '');
annotate_port('parallel_8_min_cost_function/Min_cost_function_and_vopt2/MinMax', 1, 1, '');
annotate_port('parallel_8_min_cost_function/Min_cost_function_and_vopt2/MinMax', 1, 1, '');
annotate_port('parallel_8_min_cost_function/Min_cost_function_and_vopt2/MinMax', 1, 1, '');
annotate_port('parallel_8_min_cost_function/Min_cost_function_and_vopt2/MinMax', 1, 1, '');
annotate_port('parallel_8_min_cost_function/Min_cost_function_and_vopt2/MinMax', 1, 1, '');
