open_system('gm_parallel_8_min_cost_function');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Detect Rise Positive', 'user2');
annotate_port('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Detect Rise Positive', 0, 1, 'cp : 1.704 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Detect Rise Positive1', 'user2');
annotate_port('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Detect Rise Positive1', 0, 1, 'cp : 4.357 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Delay371', 'user1');
annotate_port('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Delay371', 1, 1, 'cp : 4.946 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Delay6', 'user1');
annotate_port('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Delay6', 0, 1, 'cp : 0.33 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Relational Operator1', 'user2');
annotate_port('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Relational Operator1', 0, 1, 'cp : 2.983 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Switch_on1', 'user2');
annotate_port('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Switch_on1', 0, 1, 'cp : 2.032 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Switch_on98', 'user2');
annotate_port('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Switch_on98', 0, 1, 'cp : 4.685 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Detect Rise Positive/Positive', 'user2');
annotate_port('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Detect Rise Positive/Positive', 0, 1, 'cp : 1.017 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Detect Rise Positive/FixPt Relational Operator', 'user2');
annotate_port('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Detect Rise Positive/FixPt Relational Operator', 0, 1, 'cp : 1.704 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Detect Rise Positive/Positive/Compare', 'user2');
annotate_port('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Detect Rise Positive/Positive/Compare', 0, 1, 'cp : 1.017 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Detect Rise Positive1/Positive', 'user2');
annotate_port('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Detect Rise Positive1/Positive', 0, 1, 'cp : 3.67 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Detect Rise Positive1/FixPt Relational Operator', 'user2');
annotate_port('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Detect Rise Positive1/FixPt Relational Operator', 0, 1, 'cp : 4.357 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Detect Rise Positive1/Positive/Compare', 'user2');
annotate_port('gm_parallel_8_min_cost_function/Min_cost_function_and_vopt2/Detect Rise Positive1/Positive/Compare', 0, 1, 'cp : 3.67 ns');
