SLStudio.Utils.RemoveHighlighting(get_param('FCS_MPC_3Phase_SPMSM_TEST1', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_FCS_MPC_3Phase_SPMSM_TEST1', 'handle'));
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1', 0, 2, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/DelayValue1', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/reset_old2', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/Detec_edge', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/dtc', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/Saturation', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/Switch_on15', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/Switch_on7', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/t1', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/t2', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/t3', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/Reshape', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/Assignment', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/Assignment', 1, 1, '');
annotate_port('FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/gain', 1, 1, '');
annotate_port('FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/Assignment1', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/Assignment1', 1, 1, '');
annotate_port('FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/Assignment2', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/Assignment2', 1, 1, '');
annotate_port('FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/Assignment3', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/Assignment3', 1, 1, '');
annotate_port('FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/Assignment4', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/Assignment4', 1, 1, '');
annotate_port('FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/Assignment5', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/Assignment5', 1, 1, '');
annotate_port('FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/Assignment6', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/Assignment6', 1, 1, '');
annotate_port('FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/Assignment7', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/Assignment7', 1, 1, '');
annotate_port('FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/t', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/t1', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/adder10', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/adder_outbuff1', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/multiplier13', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/dtc7', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/subtract18', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/adder23', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/multiplier32', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/square15', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/divider15', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/subtract33', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/subtract_outbuff15', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/adder32', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function/multiplier74', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1/switch', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1/Reshape', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1/Assignment', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1/Assignment', 1, 1, '');
annotate_port('FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1/switch3', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1/Assignment1', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1/Assignment1', 1, 1, '');
annotate_port('FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1/switch5', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1/Reshape1', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1/switch7', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1/Selector6', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1/switch9', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1/switch11', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1/switch12', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1/Selector14', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1/relop', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1/relop1', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1/relop_outbuff', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1/relop2', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1/relop_outbuff1', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1/dtc1', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1/relop3', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1/relop_outbuff2', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1/relop4', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1/relop_outbuff3', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1/Selector_dtc_comp_dtc_comp1', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1/relop5', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1/relop_outbuff4', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1/relop6', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/MATLAB Function1/relop_outbuff5', 0, 1, '');
