open_system('gm_parallel_min_cost_function_vopt_6phase');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_min_cost_function_vopt_6phase/Min_cost_function_and_vopt/Compare To Constant4', 'user2');
annotate_port('gm_parallel_min_cost_function_vopt_6phase/Min_cost_function_and_vopt/Compare To Constant4', 0, 1, 'cp : 2.91 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_min_cost_function_vopt_6phase/Min_cost_function_and_vopt/Detect Rise Positive', 'user2');
annotate_port('gm_parallel_min_cost_function_vopt_6phase/Min_cost_function_and_vopt/Detect Rise Positive', 0, 1, 'cp : 1.704 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_min_cost_function_vopt_6phase/Min_cost_function_and_vopt/Delay107', 'user1');
annotate_port('gm_parallel_min_cost_function_vopt_6phase/Min_cost_function_and_vopt/Delay107', 1, 1, 'cp : 4.75 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_min_cost_function_vopt_6phase/Min_cost_function_and_vopt/Delay46', 'user1');
annotate_port('gm_parallel_min_cost_function_vopt_6phase/Min_cost_function_and_vopt/Delay46', 0, 1, 'cp : 0.33 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_min_cost_function_vopt_6phase/Min_cost_function_and_vopt/Relational Operator5', 'user2');
annotate_port('gm_parallel_min_cost_function_vopt_6phase/Min_cost_function_and_vopt/Relational Operator5', 0, 1, 'cp : 4.137 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_min_cost_function_vopt_6phase/Min_cost_function_and_vopt/Switch30', 'user2');
annotate_port('gm_parallel_min_cost_function_vopt_6phase/Min_cost_function_and_vopt/Switch30', 0, 1, 'cp : 4.489 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_min_cost_function_vopt_6phase/Min_cost_function_and_vopt/Switch34', 'user2');
annotate_port('gm_parallel_min_cost_function_vopt_6phase/Min_cost_function_and_vopt/Switch34', 0, 1, 'cp : 3.262 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_min_cost_function_vopt_6phase/Min_cost_function_and_vopt/Switch_on29', 'user2');
annotate_port('gm_parallel_min_cost_function_vopt_6phase/Min_cost_function_and_vopt/Switch_on29', 0, 1, 'cp : 2.032 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_min_cost_function_vopt_6phase/Min_cost_function_and_vopt/Compare To Constant4/Compare', 'user2');
annotate_port('gm_parallel_min_cost_function_vopt_6phase/Min_cost_function_and_vopt/Compare To Constant4/Compare', 0, 1, 'cp : 2.91 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_min_cost_function_vopt_6phase/Min_cost_function_and_vopt/Detect Rise Positive/Positive', 'user2');
annotate_port('gm_parallel_min_cost_function_vopt_6phase/Min_cost_function_and_vopt/Detect Rise Positive/Positive', 0, 1, 'cp : 1.017 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_min_cost_function_vopt_6phase/Min_cost_function_and_vopt/Detect Rise Positive/FixPt Relational Operator', 'user2');
annotate_port('gm_parallel_min_cost_function_vopt_6phase/Min_cost_function_and_vopt/Detect Rise Positive/FixPt Relational Operator', 0, 1, 'cp : 1.704 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_min_cost_function_vopt_6phase/Min_cost_function_and_vopt/Detect Rise Positive/Positive/Compare', 'user2');
annotate_port('gm_parallel_min_cost_function_vopt_6phase/Min_cost_function_and_vopt/Detect Rise Positive/Positive/Compare', 0, 1, 'cp : 1.017 ns');
