open_system('gm_uz_mpc_cost_and_optim_state_machine');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay71', 'user1');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay71', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay75', 'user1');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay75', 1, 1, 'cp : 4.876 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Product', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Product', 0, 1, 'cp : 4.876 ns');
