open_system('uz_mpc_cost_and_optim_state_machine');
open_system('gm_uz_mpc_cost_and_optim_state_machine');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Detect Rise Positive', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Detect Rise Positive', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Detect Rise Positive', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Detect Rise Positive', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay1', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay1', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay1', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay10', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay10', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay10', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay10', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay11', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay11', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay11', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay11', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay12', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay12', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay12', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay12', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay13', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay13', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay13', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay13', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay14', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay14', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay14', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay14', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay15', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay15', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay15', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay15', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay16', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay16', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay16', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay16', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay17', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay17', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay17', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay17', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay18', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay18', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay18', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay18', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay19', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay19', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay19', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay19', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay2', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay2', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay2', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay20', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay20', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay20', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay20', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay21', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay21', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay21', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay21', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay22', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay22', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay22', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay22', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay23', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay23', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay23', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay23', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay24', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay24', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay24', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay24', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay25', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay25', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay25', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay25', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay26', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay26', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay26', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay26', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay27', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay27', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay27', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay27', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay28', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay28', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay28', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay28', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay29', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay29', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay29', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay29', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay3', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay3', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay3', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay30', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay30', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay30', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay30', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay31', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay31', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay31', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay31', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay32', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay32', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay32', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay32', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay33', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay33', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay33', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay33', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay34', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay34', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay34', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay34', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay35', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay35', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay35', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay35', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay36', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay36', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay36', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay36', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay37', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay37', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay37', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay37', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay38', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay38', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay38', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay38', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay39', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay39', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay39', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay39', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay4', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay4', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay4', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay40', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay40', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay40', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay40', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay41', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay41', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay41', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay41', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay42', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay42', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay42', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay42', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay43', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay43', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay43', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay43', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay44', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay44', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay44', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay44', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay45', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay45', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay45', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay45', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay46', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay46', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay46', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay46', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay47', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay47', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay47', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay47', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay48', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay48', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay48', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay48', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay49', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay49', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay49', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay49', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay5', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay5', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay5', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay50', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay50', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay50', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay50', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay51', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay51', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay51', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay51', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay52', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay52', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay52', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay52', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay53', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay53', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay53', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay53', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay54', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay54', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay54', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay54', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay55', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay55', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay55', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay55', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay56', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay56', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay56', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay56', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay57', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay57', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay57', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay57', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay58', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay58', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay58', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay58', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay59', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay59', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay59', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay59', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay6', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay6', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay6', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay6', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay60', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay60', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay60', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay60', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay61', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay61', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay61', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay61', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay62', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay62', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay62', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay62', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay63', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay63', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay63', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay63', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay64', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay64', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay64', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay64', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay65', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay65', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay65', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay65', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay66', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay66', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay66', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay66', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay67', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay67', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay67', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay67', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay68', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay68', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay68', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay68', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay69', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay69', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay69', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay69', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay7', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay7', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay7', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay7', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay70', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay70', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay70', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay70', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay71', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay71', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay71', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay71', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay72', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay72', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay72', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay72', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay8', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay8', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay8', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay8', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay9', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay9', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay9', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay9', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay94', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay94', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay94', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay94', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay13_ctrl_delay', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay13_ctrl_delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay22_ctrl_delay', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay22_ctrl_delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay23_ctrl_delay', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay23_ctrl_delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay24_ctrl_delay', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay24_ctrl_delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay35_ctrl_delay', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay35_ctrl_delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay50_ctrl_delay', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/Delay50_ctrl_delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/FiniteControlSetSwitchingTable/FiniteControlSetSwitchingTable', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/FiniteControlSetSwitchingTable/FiniteControlSetSwitchingTable', 0, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/FiniteControlSetSwitchingTable/FiniteControlSetSwitchingTable', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/FiniteControlSetSwitchingTable/FiniteControlSetSwitchingTable', 0, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/FiniteControlSetSwitchingTable', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/FiniteControlSetSwitchingTable', 0, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/MATLAB Function/MATLAB Function', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/MATLAB Function/MATLAB Function', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/MATLAB Function/MATLAB Function', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/MATLAB Function/MATLAB Function', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/MATLAB Function', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/MATLAB Function', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/iterativesearch/iterativesearch', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/iterativesearch/iterativesearch', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/iterativesearch/iterativesearch', 'user2');
annotate_port('gm_uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/iterativesearch/iterativesearch', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/iterativesearch', 'user2');
annotate_port('uz_mpc_cost_and_optim_state_machine/uz_6ph_mpc_costs_and_optimization/iterativesearch', 1, 1, 'Block not characterized');
