open_system('gm_uz_pmsm_model_6LUT_pd');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/Delay1_lowered', 'user1');
annotate_port('gm_uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/Delay1_lowered', 0, 1, 'cp : 0.33 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/in11_repeat', 'user2');
annotate_port('gm_uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/in11_repeat', 0, 1, 'cp : 0.33 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/Ldd Lookup Table/Ldd Lookup Table', 'user2');
annotate_port('gm_uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/Ldd Lookup Table/Ldd Lookup Table', 1, 1, 'cp : 7.651 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/reset_out2', 'user2');
annotate_port('gm_uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/reset_out2', 0, 1, 'cp : 0.72 ns');
