-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\uz_endat_interface_2023a\uz_endat_interface_src_set_offset_to_raw_position_and_wrap.vhd
-- Created: 2025-11-27 13:21:20
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: uz_endat_interface_src_set_offset_to_raw_position_and_wrap
-- Source Path: uz_endat_interface_2023a/uz_endat_interface/set_offset_to_raw_position_and_wrap
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY uz_endat_interface_src_set_offset_to_raw_position_and_wrap IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        mt_raw                            :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        n                                 :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        st_raw                            :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        In4                               :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        n1                                :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        st_raw_with_offset_and_wrapped    :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        mt_raw_with_offset_and_wrapped    :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END uz_endat_interface_src_set_offset_to_raw_position_and_wrap;


ARCHITECTURE rtl OF uz_endat_interface_src_set_offset_to_raw_position_and_wrap IS

  -- Component Declarations
  COMPONENT uz_endat_interface_src_floor_div_pow2
    PORT( dividend                        :   IN    std_logic_vector(63 DOWNTO 0);  -- sfix64
          divisor_power_of_two_bits       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          quotient                        :   OUT   std_logic_vector(63 DOWNTO 0)  -- sfix64
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : uz_endat_interface_src_floor_div_pow2
    USE ENTITY work.uz_endat_interface_src_floor_div_pow2(rtl);

  -- Signals
  SIGNAL mt_raw_unsigned                  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL mt_in                            : signed(63 DOWNTO 0);  -- sfix64
  SIGNAL Delay59_out1                     : signed(63 DOWNTO 0);  -- sfix64
  SIGNAL const5_out1                      : signed(63 DOWNTO 0);  -- sfix64
  SIGNAL n_unsigned                       : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL shift_arithmetic3_k              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL ST_RANGE                         : signed(63 DOWNTO 0);  -- sfix64
  SIGNAL Delay60_out1                     : signed(63 DOWNTO 0);  -- sfix64
  SIGNAL Product3_mul_temp                : signed(127 DOWNTO 0);  -- sfix128
  SIGNAL Product3_out1                    : signed(63 DOWNTO 0);  -- sfix64
  SIGNAL Delay66_out1                     : signed(63 DOWNTO 0);  -- sfix64
  SIGNAL st_raw_unsigned                  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL st_in                            : signed(63 DOWNTO 0);  -- sfix64
  SIGNAL Delay62_out1                     : signed(63 DOWNTO 0);  -- sfix64
  SIGNAL Delay69_out1                     : signed(63 DOWNTO 0);  -- sfix64
  SIGNAL full_raw                         : signed(63 DOWNTO 0);  -- sfix64
  SIGNAL In4_signed                       : signed(31 DOWNTO 0);  -- int32
  SIGNAL off                              : signed(63 DOWNTO 0);  -- sfix64
  SIGNAL Delay63_out1                     : signed(63 DOWNTO 0);  -- sfix64
  SIGNAL Delay70_out1                     : signed(63 DOWNTO 0);  -- sfix64
  SIGNAL full_new                         : signed(63 DOWNTO 0);  -- sfix64
  SIGNAL Delay67_out1                     : signed(63 DOWNTO 0);  -- sfix64
  SIGNAL const1_out1                      : signed(63 DOWNTO 0);  -- sfix64
  SIGNAL Sum3_out1                        : signed(63 DOWNTO 0);  -- sfix64
  SIGNAL st_raw_with_offset_and_wrapped_1 : signed(63 DOWNTO 0);  -- sfix64
  SIGNAL st_raw_with_offset_and_wrapped_tmp : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay61_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay68_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL quotient                         : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL quotient_signed                  : signed(63 DOWNTO 0);  -- sfix64
  SIGNAL const3_out1                      : signed(63 DOWNTO 0);  -- sfix64
  SIGNAL n1_unsigned                      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL shift_arithmetic2_k              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL MT_RANGE                         : signed(63 DOWNTO 0);  -- sfix64
  SIGNAL Delay65_out1                     : signed(63 DOWNTO 0);  -- sfix64
  SIGNAL Delay71_out1                     : signed(63 DOWNTO 0);  -- sfix64
  SIGNAL Sum4_out1                        : signed(63 DOWNTO 0);  -- sfix64
  SIGNAL mt_raw_with_offset_and_wrapped_1 : signed(63 DOWNTO 0);  -- sfix64
  SIGNAL mt_raw_with_offset_and_wrapped_tmp : unsigned(31 DOWNTO 0);  -- uint32

BEGIN
  -- raw mech position with offset and aligned wrap of ST and MT position
  -- modulo for powers of 2

  u_floor_div_pow2 : uz_endat_interface_src_floor_div_pow2
    PORT MAP( dividend => std_logic_vector(full_new),  -- sfix64
              divisor_power_of_two_bits => std_logic_vector(Delay68_out1),  -- uint32
              quotient => quotient  -- sfix64
              );

  mt_raw_unsigned <= unsigned(mt_raw);

  mt_in <= signed(resize(mt_raw_unsigned, 64));

  Delay59_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay59_out1 <= to_signed(0, 64);
      ELSIF enb = '1' THEN
        Delay59_out1 <= mt_in;
      END IF;
    END IF;
  END PROCESS Delay59_process;


  const5_out1 <= to_signed(1, 64);

  n_unsigned <= unsigned(n);

  shift_arithmetic3_k <= n_unsigned;
  ST_RANGE <= const5_out1 sll to_integer(shift_arithmetic3_k);

  Delay60_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay60_out1 <= to_signed(0, 64);
      ELSIF enb = '1' THEN
        Delay60_out1 <= ST_RANGE;
      END IF;
    END IF;
  END PROCESS Delay60_process;


  Product3_mul_temp <= Delay59_out1 * Delay60_out1;
  Product3_out1 <= Product3_mul_temp(63 DOWNTO 0);

  Delay66_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay66_out1 <= to_signed(0, 64);
      ELSIF enb = '1' THEN
        Delay66_out1 <= Product3_out1;
      END IF;
    END IF;
  END PROCESS Delay66_process;


  st_raw_unsigned <= unsigned(st_raw);

  st_in <= signed(resize(st_raw_unsigned, 64));

  Delay62_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay62_out1 <= to_signed(0, 64);
      ELSIF enb = '1' THEN
        Delay62_out1 <= st_in;
      END IF;
    END IF;
  END PROCESS Delay62_process;


  Delay69_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay69_out1 <= to_signed(0, 64);
      ELSIF enb = '1' THEN
        Delay69_out1 <= Delay62_out1;
      END IF;
    END IF;
  END PROCESS Delay69_process;


  full_raw <= Delay66_out1 + Delay69_out1;

  In4_signed <= signed(In4);

  off <= resize(In4_signed, 64);

  Delay63_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay63_out1 <= to_signed(0, 64);
      ELSIF enb = '1' THEN
        Delay63_out1 <= off;
      END IF;
    END IF;
  END PROCESS Delay63_process;


  Delay70_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay70_out1 <= to_signed(0, 64);
      ELSIF enb = '1' THEN
        Delay70_out1 <= Delay63_out1;
      END IF;
    END IF;
  END PROCESS Delay70_process;


  full_new <= full_raw + Delay70_out1;

  Delay67_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay67_out1 <= to_signed(0, 64);
      ELSIF enb = '1' THEN
        Delay67_out1 <= Delay60_out1;
      END IF;
    END IF;
  END PROCESS Delay67_process;


  const1_out1 <= to_signed(1, 64);

  Sum3_out1 <= Delay67_out1 - const1_out1;

  st_raw_with_offset_and_wrapped_1 <= full_new AND Sum3_out1;

  st_raw_with_offset_and_wrapped_tmp <= unsigned(st_raw_with_offset_and_wrapped_1(31 DOWNTO 0));

  st_raw_with_offset_and_wrapped <= std_logic_vector(st_raw_with_offset_and_wrapped_tmp);

  Delay61_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay61_out1 <= to_unsigned(0, 32);
      ELSIF enb = '1' THEN
        Delay61_out1 <= n_unsigned;
      END IF;
    END IF;
  END PROCESS Delay61_process;


  Delay68_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay68_out1 <= to_unsigned(0, 32);
      ELSIF enb = '1' THEN
        Delay68_out1 <= Delay61_out1;
      END IF;
    END IF;
  END PROCESS Delay68_process;


  quotient_signed <= signed(quotient);

  const3_out1 <= to_signed(1, 64);

  n1_unsigned <= unsigned(n1);

  shift_arithmetic2_k <= n1_unsigned;
  MT_RANGE <= const3_out1 sll to_integer(shift_arithmetic2_k);

  Delay65_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay65_out1 <= to_signed(0, 64);
      ELSIF enb = '1' THEN
        Delay65_out1 <= MT_RANGE;
      END IF;
    END IF;
  END PROCESS Delay65_process;


  Delay71_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay71_out1 <= to_signed(0, 64);
      ELSIF enb = '1' THEN
        Delay71_out1 <= Delay65_out1;
      END IF;
    END IF;
  END PROCESS Delay71_process;


  Sum4_out1 <= Delay71_out1 - const1_out1;

  mt_raw_with_offset_and_wrapped_1 <= quotient_signed AND Sum4_out1;

  mt_raw_with_offset_and_wrapped_tmp <= unsigned(mt_raw_with_offset_and_wrapped_1(31 DOWNTO 0));

  mt_raw_with_offset_and_wrapped <= std_logic_vector(mt_raw_with_offset_and_wrapped_tmp);

END rtl;

