open_system('gm_Transformation_dq_alphabeta_123_V1');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Transformation_dq_alphabeta_123_V1/Trans_dq_alphabeta_123_fix_V1/Gain2', 'user2');
annotate_port('gm_Transformation_dq_alphabeta_123_V1/Trans_dq_alphabeta_123_fix_V1/Gain2', 0, 1, 'cp : 7.553 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Transformation_dq_alphabeta_123_V1/Trans_dq_alphabeta_123_fix_V1/out_7_pipe', 'user1');
annotate_port('gm_Transformation_dq_alphabeta_123_V1/Trans_dq_alphabeta_123_fix_V1/out_7_pipe', 1, 1, 'cp : 9.46 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Transformation_dq_alphabeta_123_V1/Trans_dq_alphabeta_123_fix_V1/Add_stage2', 'user2');
annotate_port('gm_Transformation_dq_alphabeta_123_V1/Trans_dq_alphabeta_123_fix_V1/Add_stage2', 0, 1, 'cp : 8.226 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Transformation_dq_alphabeta_123_V1/Trans_dq_alphabeta_123_fix_V1/Add_stage3', 'user2');
annotate_port('gm_Transformation_dq_alphabeta_123_V1/Trans_dq_alphabeta_123_fix_V1/Add_stage3', 0, 1, 'cp : 8.871 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Transformation_dq_alphabeta_123_V1/Trans_dq_alphabeta_123_fix_V1/t', 'user2');
annotate_port('gm_Transformation_dq_alphabeta_123_V1/Trans_dq_alphabeta_123_fix_V1/t', 0, 1, 'cp : 8.871 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Transformation_dq_alphabeta_123_V1/Trans_dq_alphabeta_123_fix_V1/mux', 'user2');
annotate_port('gm_Transformation_dq_alphabeta_123_V1/Trans_dq_alphabeta_123_fix_V1/mux', 0, 1, 'cp : 8.871 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Transformation_dq_alphabeta_123_V1/Trans_dq_alphabeta_123_fix_V1/Product3', 'user2');
annotate_port('gm_Transformation_dq_alphabeta_123_V1/Trans_dq_alphabeta_123_fix_V1/Product3', 0, 1, 'cp : 3.605 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Transformation_dq_alphabeta_123_V1/Trans_dq_alphabeta_123_fix_V1/Subtract1', 'user2');
annotate_port('gm_Transformation_dq_alphabeta_123_V1/Trans_dq_alphabeta_123_fix_V1/Subtract1', 0, 1, 'cp : 4.278 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Transformation_dq_alphabeta_123_V1/Trans_dq_alphabeta_123_fix_V1/Switch_on4', 'user2');
annotate_port('gm_Transformation_dq_alphabeta_123_V1/Trans_dq_alphabeta_123_fix_V1/Switch_on4', 0, 1, 'cp : 9.199 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Transformation_dq_alphabeta_123_V1/Trans_dq_alphabeta_123_fix_V1/delayMatch7', 'user1');
annotate_port('gm_Transformation_dq_alphabeta_123_V1/Trans_dq_alphabeta_123_fix_V1/delayMatch7', 0, 1, 'cp : 0.33 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Transformation_dq_alphabeta_123_V1/Trans_dq_alphabeta_123_fix_V1/Switch_on4_out1', 'user2');
annotate_port('gm_Transformation_dq_alphabeta_123_V1/Trans_dq_alphabeta_123_fix_V1/Switch_on4_out1', 0, 1, 'cp : 9.199 ns');
