# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3

pipelines:
  #branches:
  #  develop:
   default:
    - step:
       script: # Modify the commands below to build your repository.
        - cd docs
        - python -m pip install -U pip
        - pip install -r requirements.txt
        - pip list
        - make html SPHINXOPTS="-W --keep-going -n"
        - cd build
        - ls
    - step:
       script:
        - git fetch --all
        - git branch -r
        - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
        - git config --get remote.origin.fetch
        - git branch -r
        - git remote add mirrorOrigin git@github.com:ultrazohm/ultrazohm_sw.git
        - git push --all mirrorOrigin
   branches:
     main:
      - step:
         name: Deploy to Contabo Server
         deployment: contabo
# trigger: manual  # Uncomment to make this a manual deployment.
         script:
          - python -m pip install -U pip
          - ls
          - cd docs
          - ls
          - pip install -r requirements.txt
          - make html SPHINXOPTS="-W --keep-going -n"
          - ls
          - echo "Deploying to test environment"
          - pipe: atlassian/rsync-deploy:0.4.3
            variables:
                 USER: $ls_user
                 SERVER: $hostname
                 REMOTE_PATH: $docs_path
                 LOCAL_PATH: ./build/html/
                 # The --chmod causes the following
                 # Directories: owner: rwx, group: r-x, other: r-x
                 # Files: owner: rw-, group: r--, other: ---
                 # +X: All files, the owner already had execution right on gets executable
                 # for everybody and directories get accessable
                 EXTRA_ARGS: '-a --delete --chmod=D0755,F0640,+X'
                 SSH_PORT: '22'
