# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.9.7
clone:
  lfs: true


pipelines:
  #branches:
  #  develop:
   default:
        - step:
           name: build and push docker
           script:
            - export BITBUCKET_COMMIT_SHORT="${BITBUCKET_COMMIT::7}" # https://community.atlassian.com/t5/Bitbucket-questions/BITBUCKET-COMMIT-variable-short-7digits-in-pipelines/qaq-p/752782
            - echo $BITBUCKET_COMMIT_SHORT
            - cd .devcontainer
            - ls
            - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
            - docker build -t ultrazohm/ultrazohm_remote_container:BITBUCKET_COMMIT_SHORT .
            - docker push ultrazohm/ultrazohm_remote_container:BITBUCKET_COMMIT_SHORT
           services:
            - docker

   branches:

     develop:
        - step:
           name: docs
           image: ultrazohm/ultrazohm_remote_container
           script: # Modify the commands below to build your repository.
            - mv vitis/software/Baremetal/src/uz/default_uz_global_configuration.h vitis/software/Baremetal/src/uz/uz_global_configuration.h
            - cd docs
            - pip install -r requirements.txt
            - pip list
            - make docs
            - cd build
            - ls
        - step:
           name: Ceedling unit tests
           image: ultrazohm/ultrazohm_remote_container
           script:
            - mv vitis/software/Baremetal/src/uz/default_uz_global_configuration.h vitis/software/Baremetal/src/uz/uz_global_configuration.h
            - cd vitis/software/Baremetal
            - ceedling test:all
        - step:
            name: Cppcheck
            image: ultrazohm/ultrazohm_remote_container
            script:
             - mv vitis/software/Baremetal/src/uz/default_uz_global_configuration.h vitis/software/Baremetal/src/uz/uz_global_configuration.h
             - cppcheck vitis/software/Baremetal/src 
             - cppcheck --addon=cert vitis/software/Baremetal/src 
             - cppcheck --addon=misra --inline-suppr vitis/software/Baremetal/src 
        - step:
           name: Github-Mirror
           image: alpine/git
           script:
            - apk add git-lfs
            - git remote add mirrorOrigin git@github.com:ultrazohm/ultrazohm_sw.git
            - git push --all mirrorOrigin
     main:
      - step:
         name: Deploy to Contabo Server
         deployment: contabo
         script:
          - apt-get update && apt-get -y install --no-install-recommends texlive
          - apt-get -y install --no-install-recommends texlive-latex-extra
          - apt-get -y install --no-install-recommends texlive-pictures
          - apt-get -y install --no-install-recommends texlive-science
          - apt-get -y install --no-install-recommends ghostscript
          - apt-get -y install --no-install-recommends doxygen
          - python -m pip install -U pip
          - mv vitis/software/Baremetal/src/uz/default_uz_global_configuration.h vitis/software/Baremetal/src/uz/uz_global_configuration.h
          - ls
          - cd docs
          - ls
          - pip install -r requirements.txt
          - make doxygen
          - make html SPHINXOPTS="-W --keep-going -n"
          - ls
          - echo "Deploying to test environment"
          - pipe: atlassian/rsync-deploy:0.4.3
            variables:
                 USER: $ls_user
                 SERVER: $hostname
                 REMOTE_PATH: $docs_path
                 LOCAL_PATH: ./build/html/
                 # The --chmod causes the following
                 # Directories: owner: rwx, group: r-x, other: r-x
                 # Files: owner: rw-, group: r--, other: ---
                 # +X: All files, the owner already had execution right on gets executable
                 # for everybody and directories get accessable
                 EXTRA_ARGS: '-a --delete --chmod=D0755,F0640,+X'
                 SSH_PORT: '22'
      - step:
         name: Github-Mirror
         image: alpine/git
         script:
          - apk add git-lfs
          - git remote add mirrorOrigin git@github.com:ultrazohm/ultrazohm_sw.git
          - git push --all mirrorOrigin
