# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
kind: pipeline
name: default


platform:
  os: linux
  arch: amd64

steps:
# pipeline step just opens the vivado project
 - name: Vivado open project
   image: vivado:2020.1
   commands:
   - /bin/bash /opt/Xilinx/Vivado/2020.1/settings64.sh
   - /bin/bash /opt/Xilinx/Vivado/2020.1/bin/vivado -mode batch -nolog -nojournal -source tcl_scripts/ci_vivado_open_project.tcl

# Open vivado project and check the syntax
 - name: Vivado check syntax
   image: vivado:2020.1
   commands:
   - /bin/bash /opt/Xilinx/Vivado/2020.1/settings64.sh
   - /bin/bash /opt/Xilinx/Vivado/2020.1/bin/vivado -mode batch -nolog -nojournal -source tcl_scripts/ci_vivado_check_syntax.tcl

# Open vivado project, open the board design and validate the board design (F6 in Vivado GUI)
 - name: Vivado validate board design
   image: vivado:2020.1
   commands:
   - /bin/bash /opt/Xilinx/Vivado/2020.1/settings64.sh
   - /bin/bash /opt/Xilinx/Vivado/2020.1/bin/vivado -mode batch -nolog -nojournal -source tcl_scripts/ci_vivado_validate_bd_design.tcl

# Runs report_environment from vivado to check if the license is valid for debug reasons (only on main and develop branch)
 - name: Vivado check license
   image: vivado:2020.1
   commands:
   - ip link show
   - /bin/bash /opt/Xilinx/Vivado/2020.1/settings64.sh
   - /bin/bash /opt/Xilinx/Vivado/2020.1/bin/vivado -mode batch -nolog -nojournal -source tcl_scripts/ci_vivado_check_license.tcl
   when:
     branch:
     - main
     - develop
     ref:
     - refs/tags/vivado*

# Generates the bitstream, only on main or develop branch since the step takes ~1.5h, exports the xsa
 - name: Vivado generate bitstream
   image: vivado:2020.1
   commands:
   - ip link show
   - /bin/bash /opt/Xilinx/Vivado/2020.1/settings64.sh
   - /bin/bash /opt/Xilinx/Vivado/2020.1/bin/vivado -mode batch -source tcl_scripts/ci_vivado_generate_bitstream.tcl
   - /bin/bash /opt/Xilinx/Vivado/2020.1/bin/vivado -mode batch -source tcl_scripts/ci_vivado_export_xsa.tcl
   when:
     branch:
     - main
     - develop

# Open vitis and generate the workspace with the existing xsa or with the new generated xsa if it is main/develop
 - name: Vitis generate Workspace
   image: vivado:2020.1
   commands:
   - /bin/bash /opt/Xilinx/Vitis/2020.1/settings64.sh
   - /bin/bash /opt/Xilinx/Vitis/2020.1/bin/xsct tcl_scripts/ci_vitis_generate_workspace.tcl
 
 - name: Baremetal build successful
   image: vivado:2020.1
   commands:
   - /bin/bash /opt/Xilinx/Vitis/2020.1/settings64.sh
   - /bin/bash /opt/Xilinx/Vitis/2020.1/bin/xsct tcl_scripts/ci_vitis_checkIfBaremetalElfExists.tcl
   
 - name: FreeRTOS build successful
   image: vivado:2020.1
   commands:
   - /bin/bash /opt/Xilinx/Vitis/2020.1/settings64.sh
   - /bin/bash /opt/Xilinx/Vitis/2020.1/bin/xsct tcl_scripts/ci_vitis_checkifFreeRTOSElfExists.tcl

# Update the platform just to test the update script (does not update the platform since it did not change)
 - name: Vitis update platform
   image: vivado:2020.1
   commands:
   - /bin/bash /opt/Xilinx/Vitis/2020.1/settings64.sh
   - /bin/bash /opt/Xilinx/Vitis/2020.1/bin/xsct tcl_scripts/ci_vitis_update_platform.tcl

 - name: Push binary
   image: alpine/git
   environment:
     pass:
       from_secret: password
     user:
       from_secret: username
   commands:
   - git status
   - git commit -a -m "[skip ci] Commit Vivado binarys from DroneCI"
   - git status
   - git push --tags --set-upstream https://$user:$pass@bitbucket.org/ultrazohm/ultrazohm_sw.git main 
   when:
     branch:
     - main

 - name: Install autotag
   image: curlimages/curl
   user: root
   volumes:
   - name: m2
     path: /root/.m2
   commands:
   - curl -sL https://git.io/autotag-install | sh -s -- -b /root/.m2/
   when:
     branch:
     - main

 - name: Autotag
   image: alpine/git
   volumes:
   - name: m2
     path: /root/.m2
   commands:
   - ls
   - git status
   - git tag
   - git fetch --all --tags
   - git tag
   - /root/.m2/autotag --scheme=conventional -b=main
   - git tag
   when:
     branch:
     - main

 - name: Create changelog
   image: node
   commands:
   - npm install -g auto-changelog
   - auto-changelog
   when:
     branch:
     - main

 - name: Push Changelog
   image: alpine/git
   environment:
     pass:
       from_secret: password
     user:
       from_secret: username
   commands:
   - git status
   - git commit -a -m "[skip ci] Commit changelog and tag from DroneCI"
   - git status
   - git push --tags --set-upstream https://$user:$pass@bitbucket.org/ultrazohm/ultrazohm_sw.git main 
   when:
     branch:
     - main

volumes:
- name: m2
  temp: {}
