SLStudio.Utils.RemoveHighlighting(get_param('uz_mpc_6ph', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_uz_mpc_6ph', 'handle'));
annotate_port('gm_uz_mpc_6ph/mpc_enable/Detect Rise Positive', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Detect Rise Positive', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Detect Rise Positive1', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Detect Rise Positive1', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Detect Rise Positive2', 0, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Detect Rise Positive2', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Detect Rise Positive2', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Subsystem2', 0, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay1', 0, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay1', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay1', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay10', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay10', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay11', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay11', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay12', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay12', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay129', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay129', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay13', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay13', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay14', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay14', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay15', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay15', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay16', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay16', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay17', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay17', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay18', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay18', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay19', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay19', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay2', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay2', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay20', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay20', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay21', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay21', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay22', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay22', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay23', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay23', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay24', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay24', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay25', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay25', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay25', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay26', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay26', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay27', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay27', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay28', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay28', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay29', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay29', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay3', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay3', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay30', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay30', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay31', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay31', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay32', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay32', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay33', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay33', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay34', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay34', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay35', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay35', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay36', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay36', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay37', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay37', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay38', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay38', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay39', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay39', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay4', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay4', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay40', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay40', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay5', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay5', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay6', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay6', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay64', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay64', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay7', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay7', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay8', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay8', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Delay9', 1, 1, '');
annotate_port('uz_mpc_6ph/mpc_enable/Delay9', 1, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/NOT', 0, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/OR', 0, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Switch1', 0, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Switch14', 0, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Detect Rise Positive2/FixPt Relational Operator', 0, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Detect Rise Positive2/Positive', 0, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Subsystem2/Data Type Conversion2', 0, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Subsystem2/Logical Operator', 0, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Subsystem2/Logical Operator4', 0, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Subsystem2/Logical Operator5', 0, 1, '');
annotate_port('gm_uz_mpc_6ph/mpc_enable/Subsystem2/Switch1', 0, 1, '');
