open_system('gm_uz_mpc_6ph');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_6ph/uz_current_limit/Detect Rise Positive', 'user2');
annotate_port('gm_uz_mpc_6ph/uz_current_limit/Detect Rise Positive', 0, 1, 'cp : 1.374 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_6ph/uz_current_limit/Delay', 'user1');
annotate_port('gm_uz_mpc_6ph/uz_current_limit/Delay', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_6ph/uz_current_limit/Delay14', 'user1');
annotate_port('gm_uz_mpc_6ph/uz_current_limit/Delay14', 1, 1, 'cp : 4.703 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_6ph/uz_current_limit/Abs', 'user2');
annotate_port('gm_uz_mpc_6ph/uz_current_limit/Abs', 0, 1, 'cp : 2.793 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_6ph/uz_current_limit/OR', 'user2');
annotate_port('gm_uz_mpc_6ph/uz_current_limit/OR', 0, 1, 'cp : 4.703 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_6ph/uz_current_limit/Relational Operator', 'user2');
annotate_port('gm_uz_mpc_6ph/uz_current_limit/Relational Operator', 0, 1, 'cp : 3.71 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_6ph/uz_current_limit/Switch1', 'user2');
annotate_port('gm_uz_mpc_6ph/uz_current_limit/Switch1', 0, 1, 'cp : 1.726 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_6ph/uz_current_limit/Detect Rise Positive/FixPt Relational Operator', 'user2');
annotate_port('gm_uz_mpc_6ph/uz_current_limit/Detect Rise Positive/FixPt Relational Operator', 0, 1, 'cp : 1.374 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_6ph/uz_current_limit/Detect Rise Positive/Positive', 'user2');
annotate_port('gm_uz_mpc_6ph/uz_current_limit/Detect Rise Positive/Positive', 0, 1, 'cp : 0.687 ns');
