open_system('uz_mpc_6ph');
open_system('gm_uz_mpc_6ph');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_6ph/uz_current_limit/Detect Rise Positive', 'user2');
annotate_port('gm_uz_mpc_6ph/uz_current_limit/Detect Rise Positive', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_6ph/uz_current_limit/Detect Rise Positive', 'user2');
annotate_port('uz_mpc_6ph/uz_current_limit/Detect Rise Positive', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_6ph/uz_current_limit/Delay', 'user2');
annotate_port('gm_uz_mpc_6ph/uz_current_limit/Delay', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_6ph/uz_current_limit/Delay', 'user2');
annotate_port('uz_mpc_6ph/uz_current_limit/Delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_6ph/uz_current_limit/Delay1', 'user2');
annotate_port('gm_uz_mpc_6ph/uz_current_limit/Delay1', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_6ph/uz_current_limit/Delay1', 'user2');
annotate_port('uz_mpc_6ph/uz_current_limit/Delay1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_6ph/uz_current_limit/Delay10', 'user2');
annotate_port('gm_uz_mpc_6ph/uz_current_limit/Delay10', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_6ph/uz_current_limit/Delay10', 'user2');
annotate_port('uz_mpc_6ph/uz_current_limit/Delay10', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_6ph/uz_current_limit/Delay11', 'user2');
annotate_port('gm_uz_mpc_6ph/uz_current_limit/Delay11', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_6ph/uz_current_limit/Delay11', 'user2');
annotate_port('uz_mpc_6ph/uz_current_limit/Delay11', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_6ph/uz_current_limit/Delay12', 'user2');
annotate_port('gm_uz_mpc_6ph/uz_current_limit/Delay12', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_6ph/uz_current_limit/Delay12', 'user2');
annotate_port('uz_mpc_6ph/uz_current_limit/Delay12', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_6ph/uz_current_limit/Delay13', 'user2');
annotate_port('gm_uz_mpc_6ph/uz_current_limit/Delay13', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_6ph/uz_current_limit/Delay13', 'user2');
annotate_port('uz_mpc_6ph/uz_current_limit/Delay13', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_6ph/uz_current_limit/Delay14', 'user2');
annotate_port('gm_uz_mpc_6ph/uz_current_limit/Delay14', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_6ph/uz_current_limit/Delay14', 'user2');
annotate_port('uz_mpc_6ph/uz_current_limit/Delay14', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_6ph/uz_current_limit/Delay15', 'user2');
annotate_port('gm_uz_mpc_6ph/uz_current_limit/Delay15', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_6ph/uz_current_limit/Delay15', 'user2');
annotate_port('uz_mpc_6ph/uz_current_limit/Delay15', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_6ph/uz_current_limit/Delay16', 'user2');
annotate_port('gm_uz_mpc_6ph/uz_current_limit/Delay16', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_6ph/uz_current_limit/Delay16', 'user2');
annotate_port('uz_mpc_6ph/uz_current_limit/Delay16', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_6ph/uz_current_limit/Delay2', 'user2');
annotate_port('gm_uz_mpc_6ph/uz_current_limit/Delay2', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_6ph/uz_current_limit/Delay2', 'user2');
annotate_port('uz_mpc_6ph/uz_current_limit/Delay2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_6ph/uz_current_limit/Delay3', 'user2');
annotate_port('gm_uz_mpc_6ph/uz_current_limit/Delay3', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_6ph/uz_current_limit/Delay3', 'user2');
annotate_port('uz_mpc_6ph/uz_current_limit/Delay3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_6ph/uz_current_limit/Delay31', 'user2');
annotate_port('gm_uz_mpc_6ph/uz_current_limit/Delay31', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_6ph/uz_current_limit/Delay31', 'user2');
annotate_port('uz_mpc_6ph/uz_current_limit/Delay31', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_6ph/uz_current_limit/Delay4', 'user2');
annotate_port('gm_uz_mpc_6ph/uz_current_limit/Delay4', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_6ph/uz_current_limit/Delay4', 'user2');
annotate_port('uz_mpc_6ph/uz_current_limit/Delay4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_6ph/uz_current_limit/Delay5', 'user2');
annotate_port('gm_uz_mpc_6ph/uz_current_limit/Delay5', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_6ph/uz_current_limit/Delay5', 'user2');
annotate_port('uz_mpc_6ph/uz_current_limit/Delay5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_6ph/uz_current_limit/Delay6', 'user2');
annotate_port('gm_uz_mpc_6ph/uz_current_limit/Delay6', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_6ph/uz_current_limit/Delay6', 'user2');
annotate_port('uz_mpc_6ph/uz_current_limit/Delay6', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_6ph/uz_current_limit/Delay7', 'user2');
annotate_port('gm_uz_mpc_6ph/uz_current_limit/Delay7', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_6ph/uz_current_limit/Delay7', 'user2');
annotate_port('uz_mpc_6ph/uz_current_limit/Delay7', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_6ph/uz_current_limit/Delay8', 'user2');
annotate_port('gm_uz_mpc_6ph/uz_current_limit/Delay8', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_6ph/uz_current_limit/Delay8', 'user2');
annotate_port('uz_mpc_6ph/uz_current_limit/Delay8', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_6ph/uz_current_limit/Delay9', 'user2');
annotate_port('gm_uz_mpc_6ph/uz_current_limit/Delay9', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_6ph/uz_current_limit/Delay9', 'user2');
annotate_port('uz_mpc_6ph/uz_current_limit/Delay9', 1, 1, 'Block not characterized');
