#pragma once
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

typedef struct uz_d_gan_inverter uz_d_gan_inverter;
typedef uz_d_gan_inverter *uz_d_gan_inverter_handle;

uz_d_gan_inverter_handle uz_d_gan_inverter_init(uz_d_gan_inverter_handle self);
int uz_d_gan_inverter_get_PWMFreqTicks_H1(uz_d_gan_inverter_handle self);
int uz_d_gan_inverter_get_PWMhightimeTicks_H1(uz_d_gan_inverter_handle self);
int uz_d_gan_inverter_get_PWMlowtimeTicks_H1(uz_d_gan_inverter_handle self);
float uz_d_gan_inverter_get_PWMdutyCycPerCent_H1(uz_d_gan_inverter_handle self);
int uz_d_gan_inverter_get_PWMFreqTicks_L1(uz_d_gan_inverter_handle self);
int uz_d_gan_inverter_get_PWMhightimeTicks_L1(uz_d_gan_inverter_handle self);
int uz_d_gan_inverter_get_PWMlowtimeTicks_L1(uz_d_gan_inverter_handle self);
float uz_d_gan_inverter_get_PWMdutyCycPerCent_L1(uz_d_gan_inverter_handle self);
int uz_d_gan_inverter_get_PWMFreqTicks_H2(uz_d_gan_inverter_handle self);
int uz_d_gan_inverter_get_PWMhightimeTicks_H2(uz_d_gan_inverter_handle self);
int uz_d_gan_inverter_get_PWMlowtimeTicks_H2(uz_d_gan_inverter_handle self);
float uz_d_gan_inverter_get_PWMdutyCycPerCent_H2(uz_d_gan_inverter_handle self);
int uz_d_gan_inverter_get_PWMFreqTicks_L2(uz_d_gan_inverter_handle self);
int uz_d_gan_inverter_get_PWMhightimeTicks_L2(uz_d_gan_inverter_handle self);
int uz_d_gan_inverter_get_PWMlowtimeTicks_L2(uz_d_gan_inverter_handle self);
float uz_d_gan_inverter_get_PWMdutyCycPerCent_L2(uz_d_gan_inverter_handle self);
int uz_d_gan_inverter_get_OC_GaN_H1(uz_d_gan_inverter_handle self);
int uz_d_gan_inverter_get_OC_GaN_L1(uz_d_gan_inverter_handle self);
int uz_d_gan_inverter_get_OC_GaN_H2(uz_d_gan_inverter_handle self);
int uz_d_gan_inverter_get_OC_GaN_L2(uz_d_gan_inverter_handle self);
int uz_d_gan_inverter_get_OC_GaN_H3(uz_d_gan_inverter_handle self);
int uz_d_gan_inverter_get_OC_GaN_L3(uz_d_gan_inverter_handle self);
int uz_d_gan_inverter_get_FAULT_GaN_H1(uz_d_gan_inverter_handle self);
int uz_d_gan_inverter_get_FAULT_GaN_L1(uz_d_gan_inverter_handle self);
int uz_d_gan_inverter_get_FAULT_GaN_H2(uz_d_gan_inverter_handle self);
int uz_d_gan_inverter_get_FAULT_GaN_L2(uz_d_gan_inverter_handle self);
int uz_d_gan_inverter_get_FAULT_GaN_H3(uz_d_gan_inverter_handle self);
int uz_d_gan_inverter_get_FAULT_GaN_L3(uz_d_gan_inverter_handle self);
int uz_d_gan_inverter_get_I_DIAG(uz_d_gan_inverter_handle self);
int uz_d_gan_inverter_get_I1_DIAG(uz_d_gan_inverter_handle self);
int uz_d_gan_inverter_get_I2_DIAG(uz_d_gan_inverter_handle self);
int uz_d_gan_inverter_get_I3_DIAG(uz_d_gan_inverter_handle self);
void uz_d_gan_inverter_set_PWM_EN(uz_d_gan_inverter_handle self, uint32_t PWM_on_off);
