SLStudio.Utils.RemoveHighlighting(get_param('uz_endat_interface_2023a', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_uz_endat_interface_2023a', 'handle'));
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/Goto30', 0, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/Goto24', 0, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/From5', 0, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/OR', 0, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/Switch17', 0, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/From33', 0, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/RW_data_and_mode_command_control', 1, 1, '');
annotate_port('uz_endat_interface_2023a/uz_endat_interface/S-R Flip-Flop1', 1, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/serial_communication', 0, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/Gray_code_to_binary/gray_to_bin/shift arithmetic', 1, 1, '');
annotate_port('uz_endat_interface_2023a/uz_endat_interface/Gray_code_to_binary/gray_to_bin/Shift Arithmetic', 1, 1, '');
annotate_port('uz_endat_interface_2023a/uz_endat_interface/Gray_code_to_binary/gray_to_bin/S-R Flip-Flop', 1, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/RW_data_and_mode_command_control/Detect Rise Positive2', 0, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/RW_data_and_mode_command_control/HDL Counter1', 1, 2, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/RW_data_and_mode_command_control/AND', 0, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/RW_data_and_mode_command_control/NOT2', 0, 1, '');
annotate_port('uz_endat_interface_2023a/uz_endat_interface/RW_data_and_mode_command_control/S-R Flip-Flop', 1, 1, '');
annotate_port('uz_endat_interface_2023a/uz_endat_interface/RW_data_and_mode_command_control/S-R Flip-Flop1', 1, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/RW_data_and_mode_command_control/Detect Rise Positive2/FixPt Relational Operator', 0, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/RW_data_and_mode_command_control/Detect Rise Positive2/Positive', 0, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/cos_hdl/Look-Up Table', 0, 1, '');
annotate_port('uz_endat_interface_2023a/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/cos_hdl/Look-Up Table', 0, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/Look-Up Table', 0, 1, '');
annotate_port('uz_endat_interface_2023a/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/Look-Up Table', 0, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/serial_communication/ssi_clock_generator', 0, 1, '');
annotate_port('uz_endat_interface_2023a/uz_endat_interface/serial_communication/clk_idle_and_delay_first_clock_function/S-R Flip-Flop', 1, 1, '');
annotate_port('uz_endat_interface_2023a/uz_endat_interface/serial_communication/endat_clock_enable_controller/S-R Flip-Flop', 1, 1, '');
annotate_port('uz_endat_interface_2023a/uz_endat_interface/serial_communication/endat_clock_enable_controller/S-R Flip-Flop1', 1, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/serial_communication/sample_serial_endat_data/Bitwise Operator1', 1, 1, '');
annotate_port('uz_endat_interface_2023a/uz_endat_interface/serial_communication/sample_serial_endat_data/Bitwise Operator1', 1, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/serial_communication/sample_serial_endat_data/shift arithmetic', 1, 1, '');
annotate_port('uz_endat_interface_2023a/uz_endat_interface/serial_communication/sample_serial_endat_data/Shift Arithmetic', 1, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/serial_communication/ssi_clock_generator/Detect Rise Positive1', 0, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/serial_communication/ssi_clock_generator/base_counter', 0, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/serial_communication/ssi_clock_generator/AND', 0, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/serial_communication/ssi_clock_generator/OR', 0, 1, '');
annotate_port('uz_endat_interface_2023a/uz_endat_interface/serial_communication/ssi_clock_generator/S-R Flip-Flop1', 1, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/serial_communication/ssi_clock_generator/Detect Rise Positive1/FixPt Relational Operator', 0, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/serial_communication/ssi_clock_generator/Detect Rise Positive1/Positive', 0, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/set_offset_to_raw_position_and_wrap/shift arithmetic2', 1, 1, '');
annotate_port('uz_endat_interface_2023a/uz_endat_interface/set_offset_to_raw_position_and_wrap/Shift Arithmetic2', 1, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/set_offset_to_raw_position_and_wrap/shift arithmetic3', 1, 1, '');
annotate_port('uz_endat_interface_2023a/uz_endat_interface/set_offset_to_raw_position_and_wrap/Shift Arithmetic3', 1, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/set_offset_to_raw_position_and_wrap/floor_div_pow2/shift arithmetic4', 1, 1, '');
annotate_port('uz_endat_interface_2023a/uz_endat_interface/set_offset_to_raw_position_and_wrap/floor_div_pow2/Shift Arithmetic4', 1, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/set_offset_to_raw_position_and_wrap/floor_div_pow2/shift arithmetic5', 1, 1, '');
annotate_port('uz_endat_interface_2023a/uz_endat_interface/set_offset_to_raw_position_and_wrap/floor_div_pow2/Shift Arithmetic5', 1, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/slice_position_and_CRC/shift arithmetic', 1, 1, '');
annotate_port('uz_endat_interface_2023a/uz_endat_interface/slice_position_and_CRC/Shift Arithmetic', 1, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/slice_position_and_CRC/shift arithmetic1', 1, 1, '');
annotate_port('uz_endat_interface_2023a/uz_endat_interface/slice_position_and_CRC/Shift Arithmetic1', 1, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/slice_position_and_CRC/shift arithmetic2', 1, 1, '');
annotate_port('uz_endat_interface_2023a/uz_endat_interface/slice_position_and_CRC/Shift Arithmetic2', 1, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/slice_position_and_CRC/shift arithmetic3_nonneg', 1, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/slice_position_and_CRC/shift arithmetic3', 1, 1, '');
annotate_port('uz_endat_interface_2023a/uz_endat_interface/slice_position_and_CRC/Shift Arithmetic3', 1, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/slice_position_and_CRC/shift arithmetic4_nonneg', 1, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/slice_position_and_CRC/shift arithmetic4', 1, 1, '');
annotate_port('uz_endat_interface_2023a/uz_endat_interface/slice_position_and_CRC/Shift Arithmetic4', 1, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/position_to_speed_pll/fixed_point_floor/fixed_point_floor', 1, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/position_to_speed_pll/fixed_point_floor/fixed_point_floor', 1, 1, '');
annotate_port('uz_endat_interface_2023a/uz_endat_interface/position_to_speed_pll/fixed_point_floor', 1, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/wrap_2pi/fixed_point_floor/fixed_point_floor', 1, 1, '');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/wrap_2pi/fixed_point_floor/fixed_point_floor', 1, 1, '');
annotate_port('uz_endat_interface_2023a/uz_endat_interface/wrap_2pi/fixed_point_floor', 1, 1, '');
