open_system('gm_uz_endat_interface_2023a');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2023a/uz_endat_interface/Goto30', 'user2');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/Goto30', 0, 1, 'cp : 5.112 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2023a/uz_endat_interface/Goto24', 'user2');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/Goto24', 0, 1, 'cp : 3.729 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2023a/uz_endat_interface/From5', 'user2');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/From5', 0, 1, 'cp : 3.729 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2023a/uz_endat_interface/OR', 'user2');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/OR', 0, 1, 'cp : 4.722 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2023a/uz_endat_interface/Switch17', 'user2');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/Switch17', 0, 1, 'cp : 5.112 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2023a/uz_endat_interface/From33', 'user2');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/From33', 0, 1, 'cp : 5.112 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2023a/uz_endat_interface/RW_data_and_mode_command_control', 'user2');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/RW_data_and_mode_command_control', 1, 1, 'cp : 9.268 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2023a/uz_endat_interface/serial_communication', 'user2');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/serial_communication', 0, 1, 'cp : 3.729 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2023a/uz_endat_interface/RW_data_and_mode_command_control/Detect Rise Positive2', 'user2');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/RW_data_and_mode_command_control/Detect Rise Positive2', 0, 1, 'cp : 6.77 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2023a/uz_endat_interface/RW_data_and_mode_command_control/HDL Counter1', 'user2');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/RW_data_and_mode_command_control/HDL Counter1', 1, 2, 'cp : 9.268 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2023a/uz_endat_interface/RW_data_and_mode_command_control/AND', 'user2');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/RW_data_and_mode_command_control/AND', 0, 1, 'cp : 7.63 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2023a/uz_endat_interface/RW_data_and_mode_command_control/NOT2', 'user2');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/RW_data_and_mode_command_control/NOT2', 0, 1, 'cp : 5.396 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2023a/uz_endat_interface/RW_data_and_mode_command_control/Detect Rise Positive2/FixPt Relational Operator', 'user2');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/RW_data_and_mode_command_control/Detect Rise Positive2/FixPt Relational Operator', 0, 1, 'cp : 6.77 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2023a/uz_endat_interface/RW_data_and_mode_command_control/Detect Rise Positive2/Positive', 'user2');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/RW_data_and_mode_command_control/Detect Rise Positive2/Positive', 0, 1, 'cp : 6.083 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2023a/uz_endat_interface/serial_communication/ssi_clock_generator', 'user2');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/serial_communication/ssi_clock_generator', 0, 1, 'cp : 3.729 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2023a/uz_endat_interface/serial_communication/ssi_clock_generator/Detect Rise Positive1', 'user2');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/serial_communication/ssi_clock_generator/Detect Rise Positive1', 0, 1, 'cp : 1.848 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2023a/uz_endat_interface/serial_communication/ssi_clock_generator/base_counter', 'user2');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/serial_communication/ssi_clock_generator/base_counter', 0, 1, 'cp : 0.33 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2023a/uz_endat_interface/serial_communication/ssi_clock_generator/AND', 'user2');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/serial_communication/ssi_clock_generator/AND', 0, 1, 'cp : 2.736 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2023a/uz_endat_interface/serial_communication/ssi_clock_generator/OR', 'user2');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/serial_communication/ssi_clock_generator/OR', 0, 1, 'cp : 3.729 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2023a/uz_endat_interface/serial_communication/ssi_clock_generator/Detect Rise Positive1/FixPt Relational Operator', 'user2');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/serial_communication/ssi_clock_generator/Detect Rise Positive1/FixPt Relational Operator', 0, 1, 'cp : 1.848 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2023a/uz_endat_interface/serial_communication/ssi_clock_generator/Detect Rise Positive1/Positive', 'user2');
annotate_port('gm_uz_endat_interface_2023a/uz_endat_interface/serial_communication/ssi_clock_generator/Detect Rise Positive1/Positive', 0, 1, 'cp : 1.161 ns');
