#define XPAR_UZ_AXI_TESTIP_0_BASEADDR 0xffff000f

/* DEFINED FOR FAKE XWDTTB */
/* Definitions for driver WDTTB */
#define XPAR_XWDTTB_NUM_INSTANCES 5U

/* FROM FILE xparameters.h*/
#define XPAR_WDTTB_0_DEVICE_ID 0U
#define XPAR_WDTTB_0_BASEADDR 0x80110000U
#define XPAR_WDTTB_0_HIGHADDR 0x8011FFFFU
#define XPAR_WDTTB_0_ENABLE_WINDOW_WDT 1U
#define XPAR_WDTTB_0_MAX_COUNT_WIDTH 32U
#define XPAR_WDTTB_0_SST_COUNT_WIDTH 30U
#define XPAR_WDTTB_0_IS_PL 1U

#define XPAR_FABRIC_AXI_TIMEBASE_WDT_0_WDT_INTERRUPT_INTR 136U
#define XPAR_FABRIC_WDTTB_0_VEC_ID XPAR_FABRIC_AXI_TIMEBASE_WDT_0_WDT_INTERRUPT_INTR

#define XWT_WWDT		1U		    /* Flag for WWDT FROM FILE xwdttb_hw.h*/

#define XREG_CPSR_IRQ_ENABLE			0x80U /* FROM FILE xreg_cortexr5.h*/
#define XREG_CPSR_FIQ_ENABLE			0x40U