SLStudio.Utils.RemoveHighlighting(get_param('IP_Core_SS_Switch_and_PWM', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_IP_Core_SS_Switch_and_PWM', 'handle'));
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM', 0, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/delayMatch', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Triangle shift', 0, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Delay4', 1, 1, '');
annotate_port('IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Delay4', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/out_0_pipe', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/out_0_pipe', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/out_1_pipe', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/out_2_pipe', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/out_3_pipe', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/out_4_pipe', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/out_5_pipe', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/out_6_pipe', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/out_7_pipe', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/out_8_pipe', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/out_9_pipe', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/out_10_pipe', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/out_11_pipe', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/out_12_pipe', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/out_13_pipe', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/out_14_pipe', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/in_0_pipe', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/in_1_pipe', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/in_2_pipe', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/in_3_pipe', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/in_4_pipe', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/in_5_pipe', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/in_6_pipe', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/in_7_pipe', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/in_8_pipe', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/in_9_pipe', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/t', 0, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Relational Operator', 0, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Switch10', 0, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Switch3', 0, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Switch7', 0, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/HDL Counter2', 0, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Counter Ctrl', 0, 2, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Delay', 1, 1, '');
annotate_port('IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Delay', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Delay1', 1, 1, '');
annotate_port('IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Delay1', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Delay2', 1, 1, '');
annotate_port('IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Delay2', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Counter Ctrl_out2', 0, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Counter Ctrl/Delay', 1, 1, '');
annotate_port('IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Counter Ctrl/Delay', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Counter Ctrl/Delay6', 1, 1, '');
annotate_port('IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Counter Ctrl/Delay6', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Counter Ctrl/Product', 0, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Triangle shift/Delay1', 1, 1, '');
annotate_port('IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Triangle shift/Delay1', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Triangle shift/Delay2', 1, 1, '');
annotate_port('IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Triangle shift/Delay2', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Triangle shift/Data Type Conversion1', 0, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Triangle shift/Relational Operator2', 0, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Triangle shift/and1_1', 0, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Triangle shift/and1_2', 0, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Triangle shift/sw1', 0, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Triangle shift/sw2', 0, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Triangle shift/sw3', 0, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/GenPWM/Triangle shift/delayMatch', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/VSI Control Signal Switch/delayMatch', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/VSI Control Signal Switch/delayMatch1', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/VSI Control Signal Switch/delayMatch2', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/VSI Control Signal Switch/delayMatch3', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/VSI Control Signal Switch/delayMatch4', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/VSI Control Signal Switch/delayMatch5', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/VSI Control Signal Switch/delayMatch6', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/VSI Control Signal Switch/delayMatch7', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/VSI Control Signal Switch/delayMatch8', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/VSI Control Signal Switch/delayMatch9', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/VSI Control Signal Switch/delayMatch10', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/VSI Control Signal Switch/delayMatch11', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/VSI Control Signal Switch/delayMatch12', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/VSI Control Signal Switch/delayMatch13', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/VSI Control Signal Switch/delayMatch14', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/VSI Control Signal Switch/delayMatch15', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/VSI Control Signal Switch/delayMatch16', 1, 1, '');
annotate_port('gm_IP_Core_SS_Switch_and_PWM/PWM_and_Switching_Signal_Control/VSI Control Signal Switch/delayMatch17', 1, 1, '');
