#ifndef UZ_ENDAT_INTERFACE_HW_H
#define UZ_ENDAT_INTERFACE_HW_H

#include <stdint.h>
#include <stdbool.h>

void uz_endat_interface_hw_write_endat_clock_divider(uint32_t base_address, uint32_t endat_clk_divider);
void uz_endat_interface_hw_write_endat_encoder_bit_width_single_turn(uint32_t base_address, uint32_t endat_encoder_bit_width_single_turn);
void uz_endat_interface_hw_write_endat_encoder_bit_width_multi_turn(uint32_t base_address, uint32_t endat_encoder_bit_width_multi_turn);
void uz_endat_interface_hw_write_endat_encoder_number_of_CRC_bits(uint32_t base_address, uint32_t endat_encoder_number_of_CRC_bits);
void uz_endat_interface_hw_write_endat_mode_command(uint32_t base_address, uint32_t endat_mode_command);
void uz_endat_interface_hw_write_ip_core_enable(uint32_t base_address, bool ip_core_off_on);
void uz_endat_interface_hw_write_pll_parameters(uint32_t base_address, float sampling_interval, float kp_pll, float ki_pll);
void uz_endat_interface_hw_write_machine_pole_pairs(uint32_t base_address, uint32_t pole_pairs);
void uz_endat_interface_hw_write_position_mech_offset_ticks_single_turn(uint32_t base_address, int32_t mech_offset_ticks_single_turn);

uint32_t uz_endat_interface_hw_read_position_raw_single_turn(uint32_t base_address);
uint32_t uz_endat_interface_hw_read_position_raw_multi_turn(uint32_t base_address);
uint32_t uz_endat_interface_hw_read_position_multi_turn(uint32_t base_address);
float uz_endat_interface_hw_read_position_mech_si_single_turn(uint32_t base_address);
float uz_endat_interface_hw_read_position_el_si_single_turn(uint32_t base_address);
float uz_endat_interface_hw_read_speed_mech_si(uint32_t base_address);
float uz_endat_interface_hw_read_speed_el_si(uint32_t base_address);
float uz_endat_interface_hw_read_speed_mech_rpm(uint32_t base_address);

#endif // UZ_ENDAT_INTERFACE_HW_H
