open_system('gm_Transformation_V11');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Transformation_V11/Trans_123_dq_fix_V11/in_1_pipe', 'user1');
annotate_port('gm_Transformation_V11/Trans_123_dq_fix_V11/in_1_pipe', 0, 1, 'cp : 0.298 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Transformation_V11/Trans_123_dq_fix_V11/Gain2', 'user2');
annotate_port('gm_Transformation_V11/Trans_123_dq_fix_V11/Gain2', 0, 1, 'cp : 4.302 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Transformation_V11/Trans_123_dq_fix_V11/Gain2_outbuff_out_pipe', 'user1');
annotate_port('gm_Transformation_V11/Trans_123_dq_fix_V11/Gain2_outbuff_out_pipe', 1, 1, 'cp : 4.332 ns');
