open_system('Transformation_V11');
open_system('gm_Transformation_V11');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Transformation_V11/Trans_123_dq_fix_V11/dq_transformation/dq_transformation', 'user2');
annotate_port('gm_Transformation_V11/Trans_123_dq_fix_V11/dq_transformation/dq_transformation', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Transformation_V11/Trans_123_dq_fix_V11/dq_transformation/dq_transformation', 'user2');
annotate_port('gm_Transformation_V11/Trans_123_dq_fix_V11/dq_transformation/dq_transformation', 1, 1, 'Block not characterized');
hilite_system('Transformation_V11/Trans_123_dq_fix_V11/dq_transformation', 'user2');
annotate_port('Transformation_V11/Trans_123_dq_fix_V11/dq_transformation', 1, 1, 'Block not characterized');
