open_system('gm_Encoder_Zynq_V24');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Encoder_Zynq_V24/IncreEncoder_V24/out_0_pipe', 'user1');
annotate_port('gm_Encoder_Zynq_V24/IncreEncoder_V24/out_0_pipe', 1, 1, 'cp : 5.696 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Encoder_Zynq_V24/IncreEncoder_V24/hold3', 'user1');
annotate_port('gm_Encoder_Zynq_V24/IncreEncoder_V24/hold3', 0, 1, 'cp : 0.46 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Encoder_Zynq_V24/IncreEncoder_V24/Div_i1', 'user2');
annotate_port('gm_Encoder_Zynq_V24/IncreEncoder_V24/Div_i1', 0, 1, 'cp : 5.696 ns');
