open_system('Encoder_Zynq_V24');
open_system('gm_Encoder_Zynq_V24');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Encoder_Zynq_V24/IncreEncoder_V24/HDL Reciprocal', 'user2');
annotate_port('gm_Encoder_Zynq_V24/IncreEncoder_V24/HDL Reciprocal', 1, 1, 'Block not characterized');
hilite_system('Encoder_Zynq_V24/IncreEncoder_V24/HDL Reciprocal', 'user2');
annotate_port('Encoder_Zynq_V24/IncreEncoder_V24/HDL Reciprocal', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Encoder_Zynq_V24/IncreEncoder_V24/omega_by_measure_time/Count/Count', 'user2');
annotate_port('gm_Encoder_Zynq_V24/IncreEncoder_V24/omega_by_measure_time/Count/Count', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Encoder_Zynq_V24/IncreEncoder_V24/omega_by_measure_time/Count/Count', 'user2');
annotate_port('gm_Encoder_Zynq_V24/IncreEncoder_V24/omega_by_measure_time/Count/Count', 1, 1, 'Block not characterized');
hilite_system('Encoder_Zynq_V24/IncreEncoder_V24/omega_by_measure_time/Count', 'user2');
annotate_port('Encoder_Zynq_V24/IncreEncoder_V24/omega_by_measure_time/Count', 1, 1, 'Block not characterized');
