SLStudio.Utils.RemoveHighlighting(get_param('uz_Deadbeat', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_uz_Deadbeat', 'handle'));
annotate_port('gm_uz_Deadbeat/uz_Deadbeat/Product31', 0, 1, '');
annotate_port('gm_uz_Deadbeat/uz_Deadbeat/Min_stage1', 1, 1, '');
annotate_port('uz_Deadbeat/uz_Deadbeat/Min', 1, 1, '');
annotate_port('gm_uz_Deadbeat/uz_Deadbeat/Min_stage2', 1, 1, '');
annotate_port('uz_Deadbeat/uz_Deadbeat/Min', 1, 1, '');
annotate_port('gm_uz_Deadbeat/uz_Deadbeat/Min1_stage1', 1, 1, '');
annotate_port('uz_Deadbeat/uz_Deadbeat/Min1', 1, 1, '');
annotate_port('gm_uz_Deadbeat/uz_Deadbeat/Min1_stage2', 1, 1, '');
annotate_port('uz_Deadbeat/uz_Deadbeat/Min1', 1, 1, '');
annotate_port('gm_uz_Deadbeat/uz_Deadbeat/Min2_stage1', 1, 1, '');
annotate_port('uz_Deadbeat/uz_Deadbeat/Min2', 1, 1, '');
annotate_port('gm_uz_Deadbeat/uz_Deadbeat/Min3_stage1', 1, 1, '');
annotate_port('uz_Deadbeat/uz_Deadbeat/Min3', 1, 1, '');
annotate_port('gm_uz_Deadbeat/uz_Deadbeat/Min4_stage1', 1, 1, '');
annotate_port('uz_Deadbeat/uz_Deadbeat/Min4', 1, 1, '');
annotate_port('gm_uz_Deadbeat/uz_Deadbeat/Min5_stage1', 1, 1, '');
annotate_port('uz_Deadbeat/uz_Deadbeat/Min5', 1, 1, '');
annotate_port('gm_uz_Deadbeat/uz_Deadbeat/Min6_stage1', 1, 1, '');
annotate_port('uz_Deadbeat/uz_Deadbeat/Min6', 1, 1, '');
annotate_port('gm_uz_Deadbeat/uz_Deadbeat/Min7_stage1', 1, 1, '');
annotate_port('uz_Deadbeat/uz_Deadbeat/Min7', 1, 1, '');
annotate_port('uz_Deadbeat/uz_Deadbeat/Trigonometric Function', 1, 1, '');
annotate_port('gm_uz_Deadbeat/uz_Deadbeat/Trigonometric Function', 1, 1, '');
annotate_port('uz_Deadbeat/uz_Deadbeat/Trigonometric Function', 1, 1, '');
annotate_port('uz_Deadbeat/uz_Deadbeat/Trigonometric Function1', 1, 1, '');
annotate_port('gm_uz_Deadbeat/uz_Deadbeat/Trigonometric Function1', 1, 1, '');
annotate_port('uz_Deadbeat/uz_Deadbeat/Trigonometric Function1', 1, 1, '');
annotate_port('uz_Deadbeat/uz_Deadbeat/Trigonometric Function2', 1, 1, '');
annotate_port('gm_uz_Deadbeat/uz_Deadbeat/Trigonometric Function2', 1, 1, '');
annotate_port('uz_Deadbeat/uz_Deadbeat/Trigonometric Function2', 1, 1, '');
annotate_port('uz_Deadbeat/uz_Deadbeat/Trigonometric Function3', 1, 1, '');
annotate_port('gm_uz_Deadbeat/uz_Deadbeat/Trigonometric Function3', 1, 1, '');
annotate_port('uz_Deadbeat/uz_Deadbeat/Trigonometric Function3', 1, 1, '');
annotate_port('gm_uz_Deadbeat/uz_Deadbeat/PipelineRegister21', 1, 1, '');
annotate_port('gm_uz_Deadbeat/uz_Deadbeat/HwModeRegister43', 0, 1, '');
