open_system('gm_uz_Deadbeat');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_Deadbeat/uz_Deadbeat/Product31', 'user2');
annotate_port('gm_uz_Deadbeat/uz_Deadbeat/Product31', 0, 1, 'cp : 6.882 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_Deadbeat/uz_Deadbeat/PipelineRegister21', 'user1');
annotate_port('gm_uz_Deadbeat/uz_Deadbeat/PipelineRegister21', 1, 1, 'cp : 6.882 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_Deadbeat/uz_Deadbeat/HwModeRegister43', 'user1');
annotate_port('gm_uz_Deadbeat/uz_Deadbeat/HwModeRegister43', 0, 1, 'cp : 0.33 ns');
