SLStudio.Utils.RemoveHighlighting(get_param('uz_park_transformation', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_uz_park_transformation', 'handle'));
annotate_port('gm_uz_park_transformation/uz_park_transformation/Detect Rise Positive', 0, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Detect Rise Positive', 1, 1, '');
annotate_port('uz_park_transformation/uz_park_transformation/Detect Rise Positive', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay', 1, 1, '');
annotate_port('uz_park_transformation/uz_park_transformation/Delay', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay1', 1, 1, '');
annotate_port('uz_park_transformation/uz_park_transformation/Delay1', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay10', 1, 1, '');
annotate_port('uz_park_transformation/uz_park_transformation/Delay10', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay11', 1, 1, '');
annotate_port('uz_park_transformation/uz_park_transformation/Delay11', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay13', 1, 1, '');
annotate_port('uz_park_transformation/uz_park_transformation/Delay13', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay14', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay14', 1, 1, '');
annotate_port('uz_park_transformation/uz_park_transformation/Delay14', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay15', 1, 1, '');
annotate_port('uz_park_transformation/uz_park_transformation/Delay15', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay16', 1, 1, '');
annotate_port('uz_park_transformation/uz_park_transformation/Delay16', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay17', 1, 1, '');
annotate_port('uz_park_transformation/uz_park_transformation/Delay17', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay18', 1, 1, '');
annotate_port('uz_park_transformation/uz_park_transformation/Delay18', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay19', 1, 1, '');
annotate_port('uz_park_transformation/uz_park_transformation/Delay19', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay2', 1, 1, '');
annotate_port('uz_park_transformation/uz_park_transformation/Delay2', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay20', 1, 1, '');
annotate_port('uz_park_transformation/uz_park_transformation/Delay20', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay22', 1, 1, '');
annotate_port('uz_park_transformation/uz_park_transformation/Delay22', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay23', 1, 1, '');
annotate_port('uz_park_transformation/uz_park_transformation/Delay23', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay24', 1, 1, '');
annotate_port('uz_park_transformation/uz_park_transformation/Delay24', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay25', 1, 1, '');
annotate_port('uz_park_transformation/uz_park_transformation/Delay25', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay26', 1, 1, '');
annotate_port('uz_park_transformation/uz_park_transformation/Delay26', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay3', 0, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay3', 1, 1, '');
annotate_port('uz_park_transformation/uz_park_transformation/Delay3', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay7', 1, 1, '');
annotate_port('uz_park_transformation/uz_park_transformation/Delay7', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay8', 1, 1, '');
annotate_port('uz_park_transformation/uz_park_transformation/Delay8', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay9', 1, 1, '');
annotate_port('uz_park_transformation/uz_park_transformation/Delay9', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Gain', 0, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Add2', 0, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Switch4', 0, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay21', 1, 1, '');
annotate_port('uz_park_transformation/uz_park_transformation/Delay21', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay12', 1, 1, '');
annotate_port('uz_park_transformation/uz_park_transformation/Delay12', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay6', 1, 1, '');
annotate_port('uz_park_transformation/uz_park_transformation/Delay6', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay5', 1, 1, '');
annotate_port('uz_park_transformation/uz_park_transformation/Delay5', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay4', 1, 1, '');
annotate_port('uz_park_transformation/uz_park_transformation/Delay4', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/delayMatch', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/delayMatch1', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/delayMatch2', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/delayMatch3', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/delayMatch4', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Detect Rise Positive/FixPt Relational Operator', 0, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Detect Rise Positive/Positive', 0, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Sine HDL Optimized/Look-Up Table', 0, 1, '');
annotate_port('uz_park_transformation/uz_park_transformation/Sine HDL Optimized/sincos hdl/cos_hdl/Look-Up Table', 0, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Sine HDL Optimized/Look-Up Table1', 0, 1, '');
annotate_port('uz_park_transformation/uz_park_transformation/Sine HDL Optimized/sincos hdl/sin_hdl/Look-Up Table', 0, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Sine HDL Optimized/delayMatch', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Sine HDL Optimized/delayMatch1', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Sine HDL Optimized/PipelineRegister', 1, 1, '');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Sine HDL Optimized/PipelineRegister1', 1, 1, '');
