open_system('uz_park_transformation');
open_system('gm_uz_park_transformation');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_park_transformation/uz_park_transformation/Detect Rise Positive', 'user2');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Detect Rise Positive', 1, 1, 'Block not characterized');
hilite_system('uz_park_transformation/uz_park_transformation/Detect Rise Positive', 'user2');
annotate_port('uz_park_transformation/uz_park_transformation/Detect Rise Positive', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_park_transformation/uz_park_transformation/Delay', 'user2');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay', 1, 1, 'Block not characterized');
hilite_system('uz_park_transformation/uz_park_transformation/Delay', 'user2');
annotate_port('uz_park_transformation/uz_park_transformation/Delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_park_transformation/uz_park_transformation/Delay1', 'user2');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay1', 1, 1, 'Block not characterized');
hilite_system('uz_park_transformation/uz_park_transformation/Delay1', 'user2');
annotate_port('uz_park_transformation/uz_park_transformation/Delay1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_park_transformation/uz_park_transformation/Delay10', 'user2');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay10', 1, 1, 'Block not characterized');
hilite_system('uz_park_transformation/uz_park_transformation/Delay10', 'user2');
annotate_port('uz_park_transformation/uz_park_transformation/Delay10', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_park_transformation/uz_park_transformation/Delay11', 'user2');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay11', 1, 1, 'Block not characterized');
hilite_system('uz_park_transformation/uz_park_transformation/Delay11', 'user2');
annotate_port('uz_park_transformation/uz_park_transformation/Delay11', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_park_transformation/uz_park_transformation/Delay13', 'user2');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay13', 1, 1, 'Block not characterized');
hilite_system('uz_park_transformation/uz_park_transformation/Delay13', 'user2');
annotate_port('uz_park_transformation/uz_park_transformation/Delay13', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_park_transformation/uz_park_transformation/Delay14', 'user2');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay14', 1, 1, 'Block not characterized');
hilite_system('uz_park_transformation/uz_park_transformation/Delay14', 'user2');
annotate_port('uz_park_transformation/uz_park_transformation/Delay14', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_park_transformation/uz_park_transformation/Delay15', 'user2');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay15', 1, 1, 'Block not characterized');
hilite_system('uz_park_transformation/uz_park_transformation/Delay15', 'user2');
annotate_port('uz_park_transformation/uz_park_transformation/Delay15', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_park_transformation/uz_park_transformation/Delay16', 'user2');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay16', 1, 1, 'Block not characterized');
hilite_system('uz_park_transformation/uz_park_transformation/Delay16', 'user2');
annotate_port('uz_park_transformation/uz_park_transformation/Delay16', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_park_transformation/uz_park_transformation/Delay17', 'user2');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay17', 1, 1, 'Block not characterized');
hilite_system('uz_park_transformation/uz_park_transformation/Delay17', 'user2');
annotate_port('uz_park_transformation/uz_park_transformation/Delay17', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_park_transformation/uz_park_transformation/Delay2', 'user2');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay2', 1, 1, 'Block not characterized');
hilite_system('uz_park_transformation/uz_park_transformation/Delay2', 'user2');
annotate_port('uz_park_transformation/uz_park_transformation/Delay2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_park_transformation/uz_park_transformation/Delay3', 'user2');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay3', 1, 1, 'Block not characterized');
hilite_system('uz_park_transformation/uz_park_transformation/Delay3', 'user2');
annotate_port('uz_park_transformation/uz_park_transformation/Delay3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_park_transformation/uz_park_transformation/Delay7', 'user2');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay7', 1, 1, 'Block not characterized');
hilite_system('uz_park_transformation/uz_park_transformation/Delay7', 'user2');
annotate_port('uz_park_transformation/uz_park_transformation/Delay7', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_park_transformation/uz_park_transformation/Delay8', 'user2');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay8', 1, 1, 'Block not characterized');
hilite_system('uz_park_transformation/uz_park_transformation/Delay8', 'user2');
annotate_port('uz_park_transformation/uz_park_transformation/Delay8', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_park_transformation/uz_park_transformation/Delay9', 'user2');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay9', 1, 1, 'Block not characterized');
hilite_system('uz_park_transformation/uz_park_transformation/Delay9', 'user2');
annotate_port('uz_park_transformation/uz_park_transformation/Delay9', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_park_transformation/uz_park_transformation/Delay12', 'user2');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay12', 1, 1, 'Block not characterized');
hilite_system('uz_park_transformation/uz_park_transformation/Delay12', 'user2');
annotate_port('uz_park_transformation/uz_park_transformation/Delay12', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_park_transformation/uz_park_transformation/Delay6', 'user2');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay6', 1, 1, 'Block not characterized');
hilite_system('uz_park_transformation/uz_park_transformation/Delay6', 'user2');
annotate_port('uz_park_transformation/uz_park_transformation/Delay6', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_park_transformation/uz_park_transformation/Delay5', 'user2');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay5', 1, 1, 'Block not characterized');
hilite_system('uz_park_transformation/uz_park_transformation/Delay5', 'user2');
annotate_port('uz_park_transformation/uz_park_transformation/Delay5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_park_transformation/uz_park_transformation/Delay4', 'user2');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Delay4', 1, 1, 'Block not characterized');
hilite_system('uz_park_transformation/uz_park_transformation/Delay4', 'user2');
annotate_port('uz_park_transformation/uz_park_transformation/Delay4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_park_transformation/uz_park_transformation/delayMatch', 'user2');
annotate_port('gm_uz_park_transformation/uz_park_transformation/delayMatch', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_park_transformation/uz_park_transformation/delayMatch1', 'user2');
annotate_port('gm_uz_park_transformation/uz_park_transformation/delayMatch1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_park_transformation/uz_park_transformation/delayMatch2', 'user2');
annotate_port('gm_uz_park_transformation/uz_park_transformation/delayMatch2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_park_transformation/uz_park_transformation/delayMatch3', 'user2');
annotate_port('gm_uz_park_transformation/uz_park_transformation/delayMatch3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_park_transformation/uz_park_transformation/delayMatch4', 'user2');
annotate_port('gm_uz_park_transformation/uz_park_transformation/delayMatch4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_park_transformation/uz_park_transformation/Sine HDL Optimized/delayMatch', 'user2');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Sine HDL Optimized/delayMatch', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_park_transformation/uz_park_transformation/Sine HDL Optimized/delayMatch1', 'user2');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Sine HDL Optimized/delayMatch1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_park_transformation/uz_park_transformation/Sine HDL Optimized/PipelineRegister', 'user2');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Sine HDL Optimized/PipelineRegister', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_park_transformation/uz_park_transformation/Sine HDL Optimized/PipelineRegister1', 'user2');
annotate_port('gm_uz_park_transformation/uz_park_transformation/Sine HDL Optimized/PipelineRegister1', 1, 1, 'Block not characterized');
