SLStudio.Utils.RemoveHighlighting(get_param('test_cost_function_only_without_delays', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_test_cost_function_only_without_delays', 'handle'));
annotate_port('gm_test_cost_function_only_without_delays/HDL_DUT1/Detect Rise Positive', 0, 1, '');
annotate_port('gm_test_cost_function_only_without_delays/HDL_DUT1/Subsystem', 0, 1, '');
annotate_port('gm_test_cost_function_only_without_delays/HDL_DUT1/mux', 0, 1, '');
annotate_port('gm_test_cost_function_only_without_delays/HDL_DUT1/Switch_on4', 0, 1, '');
annotate_port('gm_test_cost_function_only_without_delays/HDL_DUT1/Detect Rise Positive/Positive', 0, 1, '');
annotate_port('gm_test_cost_function_only_without_delays/HDL_DUT1/Detect Rise Positive/FixPt Relational Operator', 0, 1, '');
annotate_port('gm_test_cost_function_only_without_delays/HDL_DUT1/Detect Rise Positive/Positive/Compare', 0, 1, '');
annotate_port('gm_test_cost_function_only_without_delays/HDL_DUT1/Subsystem/Subsystem', 0, 1, '');
annotate_port('gm_test_cost_function_only_without_delays/HDL_DUT1/Subsystem/t', 0, 1, '');
annotate_port('gm_test_cost_function_only_without_delays/HDL_DUT1/Subsystem/Demux_mux_1', 0, 1, '');
annotate_port('gm_test_cost_function_only_without_delays/HDL_DUT1/Subsystem/Subsystem/t', 0, 2, '');
annotate_port('gm_test_cost_function_only_without_delays/HDL_DUT1/Subsystem/Subsystem/Prediction_1_1_wire', 0, 1, '');
annotate_port('gm_test_cost_function_only_without_delays/HDL_DUT1/Subsystem/Subsystem/Product1', 0, 1, '');
annotate_port('gm_test_cost_function_only_without_delays/HDL_DUT1/Subsystem/Subsystem/Subtract5', 0, 1, '');
annotate_port('gm_test_cost_function_only_without_delays/HDL_DUT1/Subsystem/Subsystem/Sum of Elements_stage2', 0, 1, '');
annotate_port('gm_test_cost_function_only_without_delays/HDL_DUT1/Subsystem/Subsystem/Sum of Elements_stage3', 0, 1, '');
annotate_port('gm_test_cost_function_only_without_delays/HDL_DUT1/Subsystem/Subsystem/Sum of Elements_stage4', 0, 1, '');
