-- -------------------------------------------------------------
-- 
-- File Name: C:\ultrazohm_sw\ip_cores\FCS_MPC_3Phase_SPMSM\test_ipcore\hdlsrc\FCS_MPC_3Phase_SPMSM_TEST1\Test_FCS_MPC_3Phase_SPMSM_IP_Core_dut.vhd
-- Created: 2022-07-08 11:04:11
-- 
-- Generated by MATLAB 9.12 and HDL Coder 3.20
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Test_FCS_MPC_3Phase_SPMSM_IP_Core_dut
-- Source Path: Test_FCS_MPC_3Phase_SPMSM_IP_Core/Test_FCS_MPC_3Phase_SPMSM_IP_Core_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Test_FCS_MPC_3Phase_SPMSM_IP_Core_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        dq_Done_123_alphabeta_dq          :   IN    std_logic;  -- ufix1
        ialpha                            :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
        ibeta                             :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
        u_dc_link_AXI                     :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
        SampleTime_AXI                    :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En20
        theta_el                          :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En20
        omega_m                           :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En11
        Rs_AXI                            :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
        reciprocal_Ls_AXI                 :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        psiPM_AXI                         :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
        ialpha_ref                        :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
        ibeta_ref                         :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
        pole_pairs_AXI                    :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32
        ce_out                            :   OUT   std_logic;  -- ufix1
        Index                             :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32
        done_MPC                          :   OUT   std_logic  -- ufix1
        );
END Test_FCS_MPC_3Phase_SPMSM_IP_Core_dut;


ARCHITECTURE rtl OF Test_FCS_MPC_3Phase_SPMSM_IP_Core_dut IS

  -- Component Declarations
  COMPONENT Test_FCS_MPC_3Phase_SPMSM_IP_Core_src_Subsystem1
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset                           :   IN    std_logic;
          dq_Done_123_alphabeta_dq        :   IN    std_logic;  -- ufix1
          ialpha                          :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          ibeta                           :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          u_dc_link_AXI                   :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          SampleTime_AXI                  :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En20
          theta_el                        :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En20
          omega_m                         :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En11
          Rs_AXI                          :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          reciprocal_Ls_AXI               :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          psiPM_AXI                       :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          ialpha_ref                      :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          ibeta_ref                       :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          pole_pairs_AXI                  :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32
          ce_out                          :   OUT   std_logic;  -- ufix1
          Index                           :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32
          done_MPC                        :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Test_FCS_MPC_3Phase_SPMSM_IP_Core_src_Subsystem1
    USE ENTITY work.Test_FCS_MPC_3Phase_SPMSM_IP_Core_src_Subsystem1(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL Index_sig                        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL done_MPC_sig                     : std_logic;  -- ufix1

BEGIN
  u_Test_FCS_MPC_3Phase_SPMSM_IP_Core_src_Subsystem1 : Test_FCS_MPC_3Phase_SPMSM_IP_Core_src_Subsystem1
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset => reset,
              dq_Done_123_alphabeta_dq => dq_Done_123_alphabeta_dq,  -- ufix1
              ialpha => ialpha,  -- sfix18_En11
              ibeta => ibeta,  -- sfix18_En11
              u_dc_link_AXI => u_dc_link_AXI,  -- sfix18_En11
              SampleTime_AXI => SampleTime_AXI,  -- sfix24_En20
              theta_el => theta_el,  -- sfix24_En20
              omega_m => omega_m,  -- sfix24_En11
              Rs_AXI => Rs_AXI,  -- sfix18_En11
              reciprocal_Ls_AXI => reciprocal_Ls_AXI,  -- ufix32
              psiPM_AXI => psiPM_AXI,  -- sfix18_En11
              ialpha_ref => ialpha_ref,  -- sfix18_En11
              ibeta_ref => ibeta_ref,  -- sfix18_En11
              pole_pairs_AXI => pole_pairs_AXI,  -- sfix32
              ce_out => ce_out_sig,  -- ufix1
              Index => Index_sig,  -- sfix32
              done_MPC => done_MPC_sig  -- ufix1
              );

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  done_MPC <= done_MPC_sig;

  Index <= Index_sig;

END rtl;

