SLStudio.Utils.RemoveHighlighting(get_param('uz_pwmdutyfreqdetection', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_uz_pwmdutyfreqdetection', 'handle'));
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Detect Rise Positive', 0, 1, '');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Delay6', 1, 1, '');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Delay7', 0, 1, '');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Sum1', 0, 1, '');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Switch1', 0, 1, '');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Switch2', 0, 1, '');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Detect Rise Positive/FixPt Relational Operator', 0, 1, '');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Detect Rise Positive/Positive', 0, 1, '');
