SLStudio.Utils.RemoveHighlighting(get_param('uz_pwmdutyfreqdetection', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_uz_pwmdutyfreqdetection', 'handle'));
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Detect Fall Nonpositive', 0, 1, '');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Detect Fall Nonpositive', 1, 1, '');
annotate_port('uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Detect Fall Nonpositive', 1, 1, '');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Detect Rise Positive', 1, 1, '');
annotate_port('uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Detect Rise Positive', 1, 1, '');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Delay14', 1, 1, '');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Delay14', 1, 1, '');
annotate_port('uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Delay14', 1, 1, '');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Delay2', 1, 1, '');
annotate_port('uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Delay2', 1, 1, '');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Delay4', 1, 1, '');
annotate_port('uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Delay4', 1, 1, '');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Delay5', 1, 1, '');
annotate_port('uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Delay5', 1, 1, '');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Delay7', 0, 1, '');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Delay7', 1, 1, '');
annotate_port('uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Delay7', 1, 1, '');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Product1', 0, 1, '');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Reciprocal', 1, 1, '');
annotate_port('uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Reciprocal', 1, 1, '');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Reciprocal', 1, 1, '');
annotate_port('uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Reciprocal', 1, 1, '');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Delay1', 1, 1, '');
annotate_port('uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Delay1', 1, 1, '');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Switch', 0, 1, '');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Delay3', 1, 1, '');
annotate_port('uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Delay3', 1, 1, '');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Detect Fall Nonpositive/FixPt Relational Operator', 0, 1, '');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Detect Fall Nonpositive/Nonpositive', 0, 1, '');
