open_system('gm_uz_pwmdutyfreqdetection');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Delay14', 'user1');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Delay14', 1, 1, 'cp : 5.225 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Product1', 'user2');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Product1', 0, 1, 'cp : 5.225 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/delayMatch', 'user1');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/delayMatch', 0, 1, 'cp : 0.33 ns');
