open_system('gm_uz_pwmdutyfreqdetection');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Detect Rise Positive', 'user2');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Detect Rise Positive', 0, 1, 'cp : 1.704 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Delay7', 'user1');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Delay7', 0, 1, 'cp : 0.33 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/HDL Counter', 'user2');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/HDL Counter', 1, 1, 'cp : 3.31 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Logical Operator', 'user2');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Logical Operator', 0, 1, 'cp : 2.697 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Detect Rise Positive/FixPt Relational Operator', 'user2');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Detect Rise Positive/FixPt Relational Operator', 0, 1, 'cp : 1.704 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Detect Rise Positive/Positive', 'user2');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Detect Rise Positive/Positive', 0, 1, 'cp : 1.017 ns');
