open_system('uz_pwmdutyfreqdetection');
open_system('gm_uz_pwmdutyfreqdetection');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/HDL Counter1', 'user2');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/HDL Counter1', 1, 1, 'Block not characterized');
hilite_system('uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/HDL Counter1', 'user2');
annotate_port('uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/HDL Counter1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/HDL Counter1', 'user2');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/HDL Counter1', 1, 1, 'Block not characterized');
hilite_system('uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/HDL Counter1', 'user2');
annotate_port('uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/HDL Counter1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Reciprocal', 'user2');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Reciprocal', 1, 1, 'Block not characterized');
hilite_system('uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Reciprocal', 'user2');
annotate_port('uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Reciprocal', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Reciprocal', 'user2');
annotate_port('gm_uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Reciprocal', 1, 1, 'Block not characterized');
hilite_system('uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Reciprocal', 'user2');
annotate_port('uz_pwmdutyfreqdetection/uz_pwmdutyfreqdetection/Reciprocal', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
