SLStudio.Utils.RemoveHighlighting(get_param('uz_pmsm_model_6LUT_pd', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_uz_pmsm_model_6LUT_pd', 'handle'));
annotate_port('gm_uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/Delay1_lowered', 0, 1, '');
annotate_port('gm_uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/in11_repeat', 0, 1, '');
annotate_port('gm_uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/Ldd Lookup Table/Ldd Lookup Table', 1, 1, '');
annotate_port('gm_uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/reset_out2', 0, 1, '');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Flux_d Lookup Table', 1, 1, '');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Flux_d Lookup Table', 1, 1, '');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Flux_d Lookup Table', 1, 1, '');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Flux_d Lookup Table', 1, 1, '');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Flux_d Lookup Table', 1, 1, '');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Flux_q Lookup Table', 1, 1, '');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Flux_q Lookup Table', 1, 1, '');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Flux_q Lookup Table', 1, 1, '');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Flux_q Lookup Table', 1, 1, '');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Flux_q Lookup Table', 1, 1, '');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Ldd Lookup Table', 1, 1, '');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Ldd Lookup Table', 1, 1, '');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Ldd Lookup Table', 1, 1, '');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Ldd Lookup Table', 1, 1, '');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Ldd Lookup Table', 1, 1, '');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Ldq Lookup Table2', 1, 1, '');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Ldq Lookup Table2', 1, 1, '');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Ldq Lookup Table2', 1, 1, '');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Ldq Lookup Table2', 1, 1, '');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Ldq Lookup Table2', 1, 1, '');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Lqd Lookup Table1', 1, 1, '');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Lqd Lookup Table1', 1, 1, '');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Lqd Lookup Table1', 1, 1, '');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Lqd Lookup Table1', 1, 1, '');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Lqd Lookup Table1', 1, 1, '');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Lqq Lookup Table', 1, 1, '');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Lqq Lookup Table', 1, 1, '');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Lqq Lookup Table', 1, 1, '');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Lqq Lookup Table', 1, 1, '');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Lqq Lookup Table', 1, 1, '');
