open_system('uz_pmsm_model_6LUT_pd');
open_system('gm_uz_pmsm_model_6LUT_pd');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Flux_d Lookup Table', 'user2');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Flux_d Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Flux_d Lookup Table', 'user2');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Flux_d Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Flux_d Lookup Table', 'user2');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Flux_d Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Flux_d Lookup Table', 'user2');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Flux_d Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Flux_d Lookup Table', 'user2');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Flux_d Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Flux_q Lookup Table', 'user2');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Flux_q Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Flux_q Lookup Table', 'user2');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Flux_q Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Flux_q Lookup Table', 'user2');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Flux_q Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Flux_q Lookup Table', 'user2');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Flux_q Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Flux_q Lookup Table', 'user2');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Flux_q Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Ldd Lookup Table', 'user2');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Ldd Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Ldd Lookup Table', 'user2');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Ldd Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Ldd Lookup Table', 'user2');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Ldd Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Ldd Lookup Table', 'user2');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Ldd Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Ldd Lookup Table', 'user2');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Ldd Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Ldq Lookup Table2', 'user2');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Ldq Lookup Table2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Ldq Lookup Table2', 'user2');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Ldq Lookup Table2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Ldq Lookup Table2', 'user2');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Ldq Lookup Table2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Ldq Lookup Table2', 'user2');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Ldq Lookup Table2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Ldq Lookup Table2', 'user2');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Ldq Lookup Table2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Lqd Lookup Table1', 'user2');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Lqd Lookup Table1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Lqd Lookup Table1', 'user2');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Lqd Lookup Table1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Lqd Lookup Table1', 'user2');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Lqd Lookup Table1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Lqd Lookup Table1', 'user2');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Lqd Lookup Table1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Lqd Lookup Table1', 'user2');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Lqd Lookup Table1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Lqq Lookup Table', 'user2');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Lqq Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Lqq Lookup Table', 'user2');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Lqq Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Lqq Lookup Table', 'user2');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Lqq Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Lqq Lookup Table', 'user2');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Lqq Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Lqq Lookup Table', 'user2');
annotate_port('uz_pmsm_model_6LUT_pd/uz_pmsm_model_6LUT/pmsm/Lqq Lookup Table', 1, 1, 'Block not characterized');
