-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/uz_dac_spi_interface/uz_dac_spi_interface_src_Detect_Rise_Positive.vhd
-- Created: 2024-07-09 11:53:26
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: uz_dac_spi_interface_src_Detect_Rise_Positive
-- Source Path: uz_dac_spi_interface/uz_dac_spi_interface/Detect Rise Positive
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY uz_dac_spi_interface_src_Detect_Rise_Positive IS
  PORT( clk                               :   IN    std_logic;
        reset_x                           :   IN    std_logic;
        enb_1_32_0                        :   IN    std_logic;
        U                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        Y                                 :   OUT   std_logic
        );
END uz_dac_spi_interface_src_Detect_Rise_Positive;


ARCHITECTURE rtl OF uz_dac_spi_interface_src_Detect_Rise_Positive IS

  -- Signals
  SIGNAL U_signed                         : signed(15 DOWNTO 0);  -- int16
  SIGNAL U_k                              : std_logic;
  SIGNAL U_k_1                            : std_logic;
  SIGNAL FixPt_Relational_Operator_relop1 : std_logic;

BEGIN
  -- Edge
  -- U(k)

  U_signed <= signed(U);

  
  U_k <= '1' WHEN U_signed > to_signed(16#0000#, 16) ELSE
      '0';

  -- 
  -- Store in Global RAM
  Delay_Input1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        U_k_1 <= '0';
      ELSIF enb_1_32_0 = '1' THEN
        U_k_1 <= U_k;
      END IF;
    END IF;
  END PROCESS Delay_Input1_process;


  
  FixPt_Relational_Operator_relop1 <= '1' WHEN U_k > U_k_1 ELSE
      '0';

  Y <= FixPt_Relational_Operator_relop1;

END rtl;

