open_system('gm_uz_sine_generator_16bit');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7', 'user2');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7', 0, 1, 'cp : 5.235 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Product', 'user2');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Product', 0, 1, 'cp : 5.235 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/PipelineRegister', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/PipelineRegister', 1, 1, 'cp : 5.235 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/HwModeRegister1', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/HwModeRegister1', 0, 1, 'cp : 0.33 ns');
