open_system('uz_sine_generator_16bit');
open_system('gm_uz_sine_generator_16bit');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1', 0, 1, 'Delays not moved across due to non-zero or unknown initial value, Delays not moved into or out of an unsupported subsystem');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1', 0, 1, 'Delays not moved across due to non-zero or unknown initial value, Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2', 0, 1, 'Delays not moved across due to non-zero or unknown initial value, Delays not moved into or out of an unsupported subsystem');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2', 0, 1, 'Delays not moved across due to non-zero or unknown initial value, Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3', 0, 1, 'Delays not moved across due to non-zero or unknown initial value, Delays not moved into or out of an unsupported subsystem');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3', 0, 1, 'Delays not moved across due to non-zero or unknown initial value, Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4', 0, 1, 'Delays not moved across due to non-zero or unknown initial value, Delays not moved into or out of an unsupported subsystem');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4', 0, 1, 'Delays not moved across due to non-zero or unknown initial value, Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5', 0, 1, 'Delays not moved across due to non-zero or unknown initial value, Delays not moved into or out of an unsupported subsystem');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5', 0, 1, 'Delays not moved across due to non-zero or unknown initial value, Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6', 0, 1, 'Delays not moved across due to non-zero or unknown initial value, Delays not moved into or out of an unsupported subsystem');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6', 0, 1, 'Delays not moved across due to non-zero or unknown initial value, Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7', 0, 1, 'Delays not moved across due to non-zero or unknown initial value, Delays not moved into or out of an unsupported subsystem');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7', 0, 1, 'Delays not moved across due to non-zero or unknown initial value, Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8', 0, 1, 'Delays not moved across due to non-zero or unknown initial value, Delays not moved into or out of an unsupported subsystem');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8', 0, 1, 'Delays not moved across due to non-zero or unknown initial value, Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /step_value', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /step_value', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /HDL Counter1', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /HDL Counter1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /const', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /const', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /HDL Counter1', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /HDL Counter1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /Compare To Zero', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /Compare To Zero', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /Compare To Zero', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /Compare To Zero', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/Constant1', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/Constant1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/Constant1', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/Constant1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/Constant5', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/Constant5', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/Constant5', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/Constant5', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/step_value', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/step_value', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/HDL Counter', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/HDL Counter', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/const', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/const', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/HDL Counter', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/HDL Counter', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/Modulo by Constant HDL Optimized', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/Modulo by Constant HDL Optimized', 0, 1, 'Delays not moved across an unsupported block, Delays not moved into or out of a subsystem because DistributedPipelining=off');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/Modulo by Constant HDL Optimized', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/Modulo by Constant HDL Optimized', 0, 1, 'Delays not moved across an unsupported block');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/Modulo by Constant HDL Optimized', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/Modulo by Constant HDL Optimized', 0, 1, 'Delays not moved across an unsupported block');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/Trigonometric Function/Trigonometric Function', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/Trigonometric Function/Trigonometric Function', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/Trigonometric Function', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/Trigonometric Function', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/Gain_const', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/Gain_const', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/Gain', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/Gain', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/Multiply_const', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/Multiply_const', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/Multiply', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/Multiply', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/Equal', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/Equal', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/Equal', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_1/Equal', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/Constant1', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/Constant1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/Constant1', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/Constant1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/Constant5', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/Constant5', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/Constant5', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/Constant5', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/step_value', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/step_value', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/HDL Counter', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/HDL Counter', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/const', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/const', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/HDL Counter', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/HDL Counter', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/Modulo by Constant HDL Optimized', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/Modulo by Constant HDL Optimized', 0, 1, 'Delays not moved across an unsupported block, Delays not moved into or out of a subsystem because DistributedPipelining=off');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/Modulo by Constant HDL Optimized', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/Modulo by Constant HDL Optimized', 0, 1, 'Delays not moved across an unsupported block');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/Modulo by Constant HDL Optimized', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/Modulo by Constant HDL Optimized', 0, 1, 'Delays not moved across an unsupported block');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/Trigonometric Function/Trigonometric Function', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/Trigonometric Function/Trigonometric Function', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/Trigonometric Function', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/Trigonometric Function', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/Gain_const', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/Gain_const', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/Gain', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/Gain', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/Multiply_const', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/Multiply_const', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/Multiply', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/Multiply', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/Equal', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/Equal', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/Equal', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_2/Equal', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/Constant1', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/Constant1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/Constant1', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/Constant1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/Constant5', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/Constant5', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/Constant5', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/Constant5', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/step_value', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/step_value', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/HDL Counter', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/HDL Counter', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/const', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/const', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/HDL Counter', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/HDL Counter', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/Modulo by Constant HDL Optimized', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/Modulo by Constant HDL Optimized', 0, 1, 'Delays not moved across an unsupported block, Delays not moved into or out of a subsystem because DistributedPipelining=off');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/Modulo by Constant HDL Optimized', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/Modulo by Constant HDL Optimized', 0, 1, 'Delays not moved across an unsupported block');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/Modulo by Constant HDL Optimized', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/Modulo by Constant HDL Optimized', 0, 1, 'Delays not moved across an unsupported block');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/Trigonometric Function/Trigonometric Function', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/Trigonometric Function/Trigonometric Function', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/Trigonometric Function', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/Trigonometric Function', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/Gain_const', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/Gain_const', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/Gain', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/Gain', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/Multiply_const', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/Multiply_const', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/Multiply', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/Multiply', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/Equal', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/Equal', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/Equal', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_3/Equal', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/Constant1', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/Constant1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/Constant1', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/Constant1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/Constant5', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/Constant5', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/Constant5', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/Constant5', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/step_value', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/step_value', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/HDL Counter', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/HDL Counter', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/const', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/const', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/HDL Counter', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/HDL Counter', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/Modulo by Constant HDL Optimized', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/Modulo by Constant HDL Optimized', 0, 1, 'Delays not moved across an unsupported block, Delays not moved into or out of a subsystem because DistributedPipelining=off');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/Modulo by Constant HDL Optimized', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/Modulo by Constant HDL Optimized', 0, 1, 'Delays not moved across an unsupported block');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/Modulo by Constant HDL Optimized', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/Modulo by Constant HDL Optimized', 0, 1, 'Delays not moved across an unsupported block');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/Trigonometric Function/Trigonometric Function', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/Trigonometric Function/Trigonometric Function', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/Trigonometric Function', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/Trigonometric Function', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/Gain_const', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/Gain_const', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/Gain', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/Gain', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/Multiply_const', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/Multiply_const', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/Multiply', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/Multiply', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/Equal', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/Equal', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/Equal', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_4/Equal', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/Constant1', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/Constant1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/Constant1', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/Constant1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/Constant5', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/Constant5', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/Constant5', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/Constant5', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/step_value', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/step_value', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/HDL Counter', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/HDL Counter', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/const', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/const', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/HDL Counter', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/HDL Counter', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/Modulo by Constant HDL Optimized', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/Modulo by Constant HDL Optimized', 0, 1, 'Delays not moved across an unsupported block, Delays not moved into or out of a subsystem because DistributedPipelining=off');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/Modulo by Constant HDL Optimized', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/Modulo by Constant HDL Optimized', 0, 1, 'Delays not moved across an unsupported block');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/Modulo by Constant HDL Optimized', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/Modulo by Constant HDL Optimized', 0, 1, 'Delays not moved across an unsupported block');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/Trigonometric Function/Trigonometric Function', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/Trigonometric Function/Trigonometric Function', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/Trigonometric Function', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/Trigonometric Function', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/Gain_const', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/Gain_const', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/Gain', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/Gain', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/Multiply_const', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/Multiply_const', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/Multiply', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/Multiply', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/Equal', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/Equal', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/Equal', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_5/Equal', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/Constant1', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/Constant1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/Constant1', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/Constant1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/Constant5', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/Constant5', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/Constant5', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/Constant5', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/step_value', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/step_value', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/HDL Counter', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/HDL Counter', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/const', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/const', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/HDL Counter', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/HDL Counter', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/Modulo by Constant HDL Optimized', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/Modulo by Constant HDL Optimized', 0, 1, 'Delays not moved across an unsupported block, Delays not moved into or out of a subsystem because DistributedPipelining=off');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/Modulo by Constant HDL Optimized', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/Modulo by Constant HDL Optimized', 0, 1, 'Delays not moved across an unsupported block');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/Modulo by Constant HDL Optimized', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/Modulo by Constant HDL Optimized', 0, 1, 'Delays not moved across an unsupported block');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/Trigonometric Function/Trigonometric Function', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/Trigonometric Function/Trigonometric Function', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/Trigonometric Function', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/Trigonometric Function', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/Gain_const', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/Gain_const', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/Gain', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/Gain', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/Multiply_const', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/Multiply_const', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/Multiply', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/Multiply', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/Equal', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/Equal', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/Equal', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_6/Equal', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Constant1', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Constant1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Constant1', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Constant1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Constant5', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Constant5', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Constant5', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Constant5', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/step_value', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/step_value', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/HDL Counter', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/HDL Counter', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/const', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/const', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/HDL Counter', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/HDL Counter', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Modulo by Constant HDL Optimized', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Modulo by Constant HDL Optimized', 0, 1, 'Delays not moved across an unsupported block, Delays not moved into or out of a subsystem because DistributedPipelining=off');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Modulo by Constant HDL Optimized', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Modulo by Constant HDL Optimized', 0, 1, 'Delays not moved across an unsupported block');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Modulo by Constant HDL Optimized', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Modulo by Constant HDL Optimized', 0, 1, 'Delays not moved across an unsupported block');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Trigonometric Function/Trigonometric Function', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Trigonometric Function/Trigonometric Function', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Trigonometric Function', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Trigonometric Function', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Gain_const', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Gain_const', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Gain', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Gain', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Multiply_const', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Multiply_const', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Multiply', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Multiply', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Equal', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Equal', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Equal', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_7/Equal', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/Constant1', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/Constant1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/Constant1', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/Constant1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/Constant5', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/Constant5', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/Constant5', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/Constant5', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/step_value', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/step_value', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/HDL Counter', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/HDL Counter', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/const', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/const', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/HDL Counter', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/HDL Counter', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/Modulo by Constant HDL Optimized', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/Modulo by Constant HDL Optimized', 0, 1, 'Delays not moved across an unsupported block, Delays not moved into or out of a subsystem because DistributedPipelining=off');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/Modulo by Constant HDL Optimized', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/Modulo by Constant HDL Optimized', 0, 1, 'Delays not moved across an unsupported block');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/Modulo by Constant HDL Optimized', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/Modulo by Constant HDL Optimized', 0, 1, 'Delays not moved across an unsupported block');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/Trigonometric Function/Trigonometric Function', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/Trigonometric Function/Trigonometric Function', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/Trigonometric Function', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/Trigonometric Function', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/Gain_const', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/Gain_const', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/Gain', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/Gain', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/Multiply_const', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/Multiply_const', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/Multiply', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/Multiply', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/Equal', 'user1');
annotate_port('gm_uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/Equal', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/Equal', 'user1');
annotate_port('uz_sine_generator_16bit/uz_sine_generator_16bit /sine_gen_8/Equal', 0, 1, 'Delays not moved across due to potential numerical mismatch');
