open_system('gm_Delay_compensation_FCS_MPC_6Phase_PMSM');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Delay_compensation_FCS_MPC_6Phase_PMSM/HDL_DUT/MATLAB Function', 'user2');
annotate_port('gm_Delay_compensation_FCS_MPC_6Phase_PMSM/HDL_DUT/MATLAB Function', 0, 1, 'cp : 2.004 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Delay_compensation_FCS_MPC_6Phase_PMSM/HDL_DUT/MATLAB Function/adder', 'user1');
annotate_port('gm_Delay_compensation_FCS_MPC_6Phase_PMSM/HDL_DUT/MATLAB Function/adder', 0, 1, 'cp : 2.004 ns');
