SLStudio.Utils.RemoveHighlighting(get_param('UZ_EnDat', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_UZ_EnDat', 'handle'));
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/5timestorage', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualSerialize', 0, 2, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/RESPONSESLICER5X', 0, 12, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/Subsystem6', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/Logical Operator4', 0, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/Logical Operator4', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/Dual Port RAM System', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/Dual Port RAM System', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/OUTPUTCONTROLCONTINIOUS', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/Logical Operator11', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/delayMatch11', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/t', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/concat', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Data Type Conversion12', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/concatenate', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/5timestorage/Storage1', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/5timestorage/Multiport Switch', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/5timestorage/Storage1/Switch', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/DATA2CLOCKSYNCER/Divide', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/DATA2CLOCKSYNCER/Divide', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/DATAFLOWCHGER/Divide', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/DATAFLOWCHGER/Divide', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/INITIALOFF/Subsystem6/Divide', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/INITIALOFF/Subsystem6/Divide', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualDeserializere/Logical Operator', 0, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/ManualDeserializere/Logical Operator', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualSerialize/Detect Increase', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualSerialize/padder', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualSerialize/padding1', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualSerialize/padding3', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualSerialize/padding4', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualSerialize/Logical Operator4', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualSerialize/Logical Operator5', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualSerialize/Switch', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualSerialize/Detect Increase/FixPt Relational Operator', 0, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/ManualSerialize/FF1/S-R Flip-Flop', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualSerialize/Triggered Subsystem/Bit Clear', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/ManualSerialize/Triggered Subsystem/Bit Clear', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualSerialize/Triggered Subsystem/Bit Set', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/ManualSerialize/Triggered Subsystem/Bit Set', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualSerialize/padder/Multiport Switch1', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualSerialize/padder/Subtract', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualSerialize/padding1/Bit Slice2', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualSerialize/padding1/Bit Slice2', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualSerialize/padding1/Bit Slice2', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualSerialize/padding1/Data Type Conversion2', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualSerialize/padding1/Data Type Conversion2', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualSerialize/padding1/Data Type Conversion2', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualSerialize/padding1/Switch2', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualSerialize/padding1/Switch2', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualSerialize/padding1/Switch2', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/OUTPUTCONTROLCONTINIOUS/Logical Operator', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/OUTPUTCONTROLCONTINIOUS/Relational Operator1', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/RECOVERYTIMESELECTOR/Divide', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/RECOVERYTIMESELECTOR/Divide', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/RESPONSESLICER5X/19BITSLICER', 0, 11, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/RESPONSESLICER5X/Logical Operator', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/RESPONSESLICER5X/19BITSLICER/responseslicer', 0, 3, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/RESPONSESLICER5X/19BITSLICER/Logical Operator', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/RESPONSESLICER5X/19BITSLICER/responseslicer/Bit Slice1', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/RESPONSESLICER5X/19BITSLICER/responseslicer/Data Type Conversion1', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/Storage16/Single Port RAM System', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/Storage16/Single Port RAM System', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/Subsystem6/Divide', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/Subsystem6/Divide', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/Subsystem6/Divide', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/Subsystem6/Product_out_dtc', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/Subsystem6/PipelineRegister', 0, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/Dual Port RAM System', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/ManualSerialize/Storage16/Single Port RAM System', 1, 1, '');
