SLStudio.Utils.RemoveHighlighting(get_param('UZ_EnDat', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_UZ_EnDat', 'handle'));
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV1', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV2', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV3', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV4', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV5', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV6', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/Data Type Conversion1', 1, 1, '');
annotate_port('UZ_EnDat/UZ_EndDat/Data Type Conversion1', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/Dual Port RAM System', 1, 1, '');
annotate_port('UZ_EnDat/UZ_EndDat/Dual Port RAM System', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV1/Triggered Subsystem', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV1/Logical Operator1', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV1/Triggered Subsystem/not_Trigger_delayed', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV1/Triggered Subsystem/Trigger_delayed_inverted_and_Trigger', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV1/Triggered Subsystem/Trigger_delayed_inverted_and_Trigger', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV1/Triggered Subsystem/Trigger_delayed_inverted_and_Trigger', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV1/Triggered Subsystem/Trigger_delayed_inverted_and_Trigger', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV1/Triggered Subsystem/Trigger_delayed_inverted_and_Trigger', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV1/Triggered Subsystem/Trigger_delayed_inverted_and_Trigger', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV1/Triggered Subsystem/Trigger_delay_ctrl_delay', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV1/Triggered Subsystem/Trigger_delay_switch', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV1/Triggered Subsystem/DbypassMux', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV1/Triggered Subsystem/DbypassMux', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV1/Triggered Subsystem/DbypassMux', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV1/Triggered Subsystem/DbypassMux', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV1/Triggered Subsystem/DbypassMux', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV1/Triggered Subsystem/DbypassMux', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV2/Triggered Subsystem', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV2/Logical Operator1', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV3/Triggered Subsystem', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV3/Logical Operator1', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV4/Triggered Subsystem', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV4/Logical Operator1', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV5/Triggered Subsystem', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV5/Logical Operator1', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV6/Triggered Subsystem', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV6/Logical Operator1', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_EndDat/CLKDIV6/Delay', 1, 1, '');
annotate_port('UZ_EnDat/UZ_EndDat/Dual Port RAM System', 1, 1, '');
