SLStudio.Utils.RemoveHighlighting(get_param('UZ_EnDat', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_UZ_EnDat', 'handle'));
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV1', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV3', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV4', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV5', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV6', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV7', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV8', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV9', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/Data Type Conversion1', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/Data Type Conversion1', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/Dual Port RAM System', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/Dual Port RAM System', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem/Bit Set', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem/Bit Set', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem1/Bit Set', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem1/Bit Set', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem10/Bit Set', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem10/Bit Set', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem11/Bit Set', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem11/Bit Set', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem12/Bit Set', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem12/Bit Set', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem13/Bit Set', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem13/Bit Set', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem14/Bit Set', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem14/Bit Set', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem15/Bit Set', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem15/Bit Set', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem2/Bit Set', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem2/Bit Set', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem3/Bit Set', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem3/Bit Set', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem4/Bit Set', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem4/Bit Set', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem5/Bit Set', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem5/Bit Set', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem6/Bit Set', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem6/Bit Set', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem7/Bit Set', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem7/Bit Set', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem8/Bit Set', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem8/Bit Set', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem9/Bit Set', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem9/Bit Set', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV1/Triggered Subsystem', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV1/Logical Operator1', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV1/Triggered Subsystem/not_Trigger_delayed', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV1/Triggered Subsystem/Trigger_delayed_inverted_and_Trigger', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV1/Triggered Subsystem/Trigger_delayed_inverted_and_Trigger', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV1/Triggered Subsystem/Trigger_delayed_inverted_and_Trigger', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV1/Triggered Subsystem/Trigger_delayed_inverted_and_Trigger', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV1/Triggered Subsystem/Trigger_delayed_inverted_and_Trigger', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV1/Triggered Subsystem/Trigger_delayed_inverted_and_Trigger', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV1/Triggered Subsystem/Trigger_delayed_inverted_and_Trigger', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV1/Triggered Subsystem/Trigger_delayed_inverted_and_Trigger', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV1/Triggered Subsystem/Trigger_delay_ctrl_delay', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV1/Triggered Subsystem/Trigger_delay_switch', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV1/Triggered Subsystem/DbypassMux', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV1/Triggered Subsystem/DbypassMux', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV1/Triggered Subsystem/DbypassMux', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV1/Triggered Subsystem/DbypassMux', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV1/Triggered Subsystem/DbypassMux', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV1/Triggered Subsystem/DbypassMux', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV1/Triggered Subsystem/DbypassMux', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV1/Triggered Subsystem/DbypassMux', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV3/Triggered Subsystem', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV3/Logical Operator1', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV4/Triggered Subsystem', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV4/Logical Operator1', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV5/Triggered Subsystem', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV5/Logical Operator1', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV6/Triggered Subsystem', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV6/Logical Operator1', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV7/Triggered Subsystem', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV7/Logical Operator1', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV8/Triggered Subsystem', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV8/Logical Operator1', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV9/Triggered Subsystem', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV9/Logical Operator1', 0, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CLKDIV9/Delay', 1, 1, '');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/Storage16/Single Port RAM System', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/Storage16/Single Port RAM System', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/Dual Port RAM System', 1, 1, '');
annotate_port('UZ_EnDat/UZ_ENDAT/Storage16/Single Port RAM System', 1, 1, '');
