open_system('gm_UZ_EnDat');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/Subsystem', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/Subsystem', 0, 2, 'cp : 8.343 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/Logical Operator20', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/Logical Operator20', 0, 1, 'cp : 9.231 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/Logical Operator24', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/Logical Operator24', 0, 1, 'cp : 2.33 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/ramselektor', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ramselektor', 0, 1, 'cp : 1.012 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER', 0, 1, 'cp : 2.046 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/CONTROLWORDSTORED', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CONTROLWORDSTORED', 0, 15, 'cp : 2.046 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/delayMatch17', 'user1');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/delayMatch17', 1, 1, 'cp : 9.492 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Subtract', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Subtract', 0, 1, 'cp : 1.694 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Switch', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Switch', 0, 1, 'cp : 2.046 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/CONTROLWORDSTORED/WORDTOBOOL', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CONTROLWORDSTORED/WORDTOBOOL', 0, 15, 'cp : 2.046 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/CONTROLWORDSTORED/WORDTOBOOL/Data Type Conversion14', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CONTROLWORDSTORED/WORDTOBOOL/Data Type Conversion14', 0, 1, 'cp : 2.046 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/CONTROLWORDSTORED/WORDTOBOOL/t', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CONTROLWORDSTORED/WORDTOBOOL/t', 0, 15, 'cp : 2.046 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/CONTROLWORDSTORED/WORDTOBOOL/concatenate', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CONTROLWORDSTORED/WORDTOBOOL/concatenate', 0, 1, 'cp : 2.046 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/CONTROLWORDSTORED/WORDTOBOOL/slice', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/CONTROLWORDSTORED/WORDTOBOOL/slice', 0, 1, 'cp : 2.046 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/ManualDeserializere/ramwatcher/Product', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualDeserializere/ramwatcher/Product', 0, 1, 'cp : 6.866 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/ManualDeserializere/ramwatcher/Product_out1bypassMux', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualDeserializere/ramwatcher/Product_out1bypassMux', 0, 1, 'cp : 7.205 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/Subsystem/ManualDeserializere', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/Subsystem/ManualDeserializere', 0, 1, 'cp : 8.343 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/Subsystem/2CLKDELAY', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/Subsystem/2CLKDELAY', 0, 1, 'cp : 8.343 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/Subsystem/Logical Operator4', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/Subsystem/Logical Operator4', 0, 1, 'cp : 3.323 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/Subsystem/ManualDeserializere/Data Type Conversion', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/Subsystem/ManualDeserializere/Data Type Conversion', 0, 1, 'cp : 3.607 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/Subsystem/ManualDeserializere/Logical Operator', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/Subsystem/ManualDeserializere/Logical Operator', 0, 1, 'cp : 3.607 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/Subsystem/ManualDeserializere/Multiport Switch', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/Subsystem/ManualDeserializere/Multiport Switch', 0, 1, 'cp : 8.343 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/Subsystem/ManualDeserializere/ramwatcher', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/Subsystem/ManualDeserializere/ramwatcher', 0, 1, 'cp : 7.205 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/ramselektor/Increment Stored Integer', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ramselektor/Increment Stored Integer', 0, 1, 'cp : 1.012 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/ramselektor/Delay', 'user1');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ramselektor/Delay', 0, 1, 'cp : 0.33 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/ramselektor/Increment Stored Integer/FixPt Sum1', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ramselektor/Increment Stored Integer/FixPt Sum1', 0, 1, 'cp : 1.012 ns');
