open_system('gm_UZ_EnDat');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/3timestorage', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/3timestorage', 0, 1, 'cp : 7.305 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/ManualDeserialize', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualDeserialize', 0, 2, 'cp : 6.202 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/Subsystem6', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/Subsystem6', 0, 1, 'cp : 0.888 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/signalquality', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/signalquality', 1, 2, 'cp : 9.981 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/OUTPUTCONTROLCONTINIOUS', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/OUTPUTCONTROLCONTINIOUS', 0, 1, 'cp : 2.627 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/3timestorage/Storage1', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/3timestorage/Storage1', 0, 1, 'cp : 6.592 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/3timestorage/Multiport Switch', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/3timestorage/Multiport Switch', 0, 1, 'cp : 7.305 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/3timestorage/Storage1/Switch', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/3timestorage/Storage1/Switch', 0, 1, 'cp : 6.592 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/ManualDeserialize/Detect Increase1', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualDeserialize/Detect Increase1', 0, 1, 'cp : 4.256 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/ManualDeserialize/padder', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualDeserialize/padder', 0, 1, 'cp : 6.202 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/ManualDeserialize/Logical Operator4', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualDeserialize/Logical Operator4', 0, 1, 'cp : 3.569 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/ManualDeserialize/Switch', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualDeserialize/Switch', 0, 1, 'cp : 4.608 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/ManualDeserialize/Detect Increase1/FixPt Relational Operator', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualDeserialize/Detect Increase1/FixPt Relational Operator', 0, 1, 'cp : 4.256 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/ManualDeserialize/padder/Multiport Switch1', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualDeserialize/padder/Multiport Switch1', 0, 1, 'cp : 6.202 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/ManualDeserialize/padder/Subtract', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualDeserialize/padder/Subtract', 0, 1, 'cp : 5.206 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/OUTPUTCONTROLCONTINIOUS/Logical Operator', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/OUTPUTCONTROLCONTINIOUS/Logical Operator', 0, 1, 'cp : 2.627 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/OUTPUTCONTROLCONTINIOUS/Relational Operator1', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/OUTPUTCONTROLCONTINIOUS/Relational Operator1', 0, 1, 'cp : 1.685 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/Subsystem6/Divide', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/Subsystem6/Divide', 0, 1, 'cp : 0.888 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/Subsystem6/Product_out_dtc', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/Subsystem6/Product_out_dtc', 0, 1, 'cp : 0.888 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/Subsystem6/PipelineRegister', 'user1');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/Subsystem6/PipelineRegister', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/signalquality/Compare To Zero', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/signalquality/Compare To Zero', 0, 1, 'cp : 8.173 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/signalquality/Detect Increase1', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/signalquality/Detect Increase1', 0, 1, 'cp : 9.72 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/signalquality/Data Type Conversion4', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/signalquality/Data Type Conversion4', 0, 1, 'cp : 7.305 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/signalquality/Logical Operator8', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/signalquality/Logical Operator8', 0, 1, 'cp : 9.033 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/signalquality/rd_2', 'user1');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/signalquality/rd_2', 1, 1, 'cp : 9.981 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/signalquality/Compare To Zero/Compare', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/signalquality/Compare To Zero/Compare', 0, 1, 'cp : 8.173 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/signalquality/Detect Increase1/FixPt Relational Operator', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/signalquality/Detect Increase1/FixPt Relational Operator', 0, 1, 'cp : 9.72 ns');
