cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Constant10','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Constant11','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Constant12','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Constant13','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Constant14','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Constant6','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Constant7','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Constant8','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Constant9','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Memory','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Memory1','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Memory2','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Memory3','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Memory4','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Memory6','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Memory7','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Memory8','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Memory9','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Subtract10','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Subtract11','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Subtract12','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Subtract13','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Subtract14','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Subtract6','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Subtract7','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Subtract8','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Subtract9','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Switch10','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Switch11','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Switch12','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Switch13','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Switch14','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Switch6','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Switch7','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Switch8','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/16BIT_SPLITTER/Switch9','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/5timestorage/Storage20/Logical Operator3','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/5timestorage/Storage21/Logical Operator3','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/5timestorage/Storage22/Logical Operator3','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/5timestorage/Storage23/Logical Operator3','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/5timestorage/Storage24/Logical Operator3','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/Constant','user1');
