cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('UZ_EnDat/UZ_ENDAT/8BIT_SPLITTER/Compare To Constant8','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/8BIT_SPLITTER/Memory7','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/8BIT_SPLITTER/Switch8','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/CONTROLWORDRAW/WORDTOBOOL/Data Type Conversion','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/CONTROLWORDRAW/WORDTOBOOL/Data Type Conversion1','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/CONTROLWORDRAW/WORDTOBOOL/Data Type Conversion10','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/CONTROLWORDRAW/WORDTOBOOL/Data Type Conversion11','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/CONTROLWORDRAW/WORDTOBOOL/Data Type Conversion14','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/CONTROLWORDRAW/WORDTOBOOL/Data Type Conversion2','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/CONTROLWORDRAW/WORDTOBOOL/Data Type Conversion3','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/CONTROLWORDRAW/WORDTOBOOL/Data Type Conversion4','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/CONTROLWORDRAW/WORDTOBOOL/Data Type Conversion5','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/CONTROLWORDRAW/WORDTOBOOL/Data Type Conversion6','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/CONTROLWORDRAW/WORDTOBOOL/Data Type Conversion7','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/CONTROLWORDRAW/WORDTOBOOL/Data Type Conversion8','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/CONTROLWORDRAW/WORDTOBOOL/Data Type Conversion9','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/CONTROLWORDRAW/WORDTOBOOL/Demux','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/CONTROLWORDSTORED/WORDTOBOOL/Data Type Conversion13','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/CONTROLWORDSTORED/WORDTOBOOL/Demux','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/CRC_Check/Logical Operator','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/CRC_Check/Logical Operator1','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/CRC_Check/Logical Operator2','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/CRC_Check/Logical Operator3','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/CRC_Check/Logical Operator4','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/Constant12','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/Constant13','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/Logical Operator24','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/ManualSerialize/Detect Change','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/Subsystem2/ManualDeserializere/WORDTOBOOL/Data Type Conversion10','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/Subsystem2/ManualDeserializere/WORDTOBOOL/Data Type Conversion11','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/Subsystem2/ManualDeserializere/WORDTOBOOL/Data Type Conversion12','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/Subsystem2/ManualDeserializere/WORDTOBOOL/Data Type Conversion13','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/Subsystem2/ManualDeserializere/WORDTOBOOL/Data Type Conversion14','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/Subsystem2/ManualDeserializere/WORDTOBOOL/Data Type Conversion15','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/Subsystem2/ManualDeserializere/WORDTOBOOL/Data Type Conversion6','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/Subsystem2/ManualDeserializere/WORDTOBOOL/Data Type Conversion7','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/Subsystem2/ManualDeserializere/WORDTOBOOL/Data Type Conversion8','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/Subsystem2/ManualDeserializere/WORDTOBOOL/Data Type Conversion9','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/Subsystem2/ManualDeserializere/WORDTOBOOL/Demux','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/8BIT_SPLITTER/Compare To Constant8/Compare','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/8BIT_SPLITTER/Compare To Constant8/Constant','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/ManualSerialize/Detect Change/Delay Input1','user1');
hilite_system('UZ_EnDat/UZ_ENDAT/ManualSerialize/Detect Change/FixPt Relational Operator','user1');
