open_system('UZ_EnDat');
open_system('gm_UZ_EnDat');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/Dual Port RAM System', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/Dual Port RAM System', 1, 1, 'Block not characterized');
hilite_system('UZ_EnDat/UZ_ENDAT/Dual Port RAM System', 'user2');
annotate_port('UZ_EnDat/UZ_ENDAT/Dual Port RAM System', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem/Bit Set', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem/Bit Set', 1, 1, 'Block not characterized');
hilite_system('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem/Bit Set', 'user2');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem/Bit Set', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem1/Bit Set', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem1/Bit Set', 1, 1, 'Block not characterized');
hilite_system('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem1/Bit Set', 'user2');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem1/Bit Set', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem10/Bit Set', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem10/Bit Set', 1, 1, 'Block not characterized');
hilite_system('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem10/Bit Set', 'user2');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem10/Bit Set', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem11/Bit Set', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem11/Bit Set', 1, 1, 'Block not characterized');
hilite_system('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem11/Bit Set', 'user2');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem11/Bit Set', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem12/Bit Set', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem12/Bit Set', 1, 1, 'Block not characterized');
hilite_system('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem12/Bit Set', 'user2');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem12/Bit Set', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem13/Bit Set', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem13/Bit Set', 1, 1, 'Block not characterized');
hilite_system('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem13/Bit Set', 'user2');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem13/Bit Set', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem14/Bit Set', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem14/Bit Set', 1, 1, 'Block not characterized');
hilite_system('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem14/Bit Set', 'user2');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem14/Bit Set', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem15/Bit Set', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem15/Bit Set', 1, 1, 'Block not characterized');
hilite_system('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem15/Bit Set', 'user2');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem15/Bit Set', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem2/Bit Set', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem2/Bit Set', 1, 1, 'Block not characterized');
hilite_system('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem2/Bit Set', 'user2');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem2/Bit Set', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem3/Bit Set', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem3/Bit Set', 1, 1, 'Block not characterized');
hilite_system('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem3/Bit Set', 'user2');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem3/Bit Set', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem5/Bit Set', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem5/Bit Set', 1, 1, 'Block not characterized');
hilite_system('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem5/Bit Set', 'user2');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem5/Bit Set', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem6/Bit Set', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem6/Bit Set', 1, 1, 'Block not characterized');
hilite_system('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem6/Bit Set', 'user2');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem6/Bit Set', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem7/Bit Set', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem7/Bit Set', 1, 1, 'Block not characterized');
hilite_system('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem7/Bit Set', 'user2');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem7/Bit Set', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem8/Bit Set', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem8/Bit Set', 1, 1, 'Block not characterized');
hilite_system('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem8/Bit Set', 'user2');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem8/Bit Set', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem9/Bit Set', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem9/Bit Set', 1, 1, 'Block not characterized');
hilite_system('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem9/Bit Set', 'user2');
annotate_port('UZ_EnDat/UZ_ENDAT/16bitgather/Subsystem9/Bit Set', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/DATA2CLOCKSYNCER/Subsystem1/Divide', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/DATA2CLOCKSYNCER/Subsystem1/Divide', 1, 1, 'Block not characterized');
hilite_system('UZ_EnDat/UZ_ENDAT/DATA2CLOCKSYNCER/Subsystem1/Divide', 'user2');
annotate_port('UZ_EnDat/UZ_ENDAT/DATA2CLOCKSYNCER/Subsystem1/Divide', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/INITIALOFF/Subsystem6/Divide', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/INITIALOFF/Subsystem6/Divide', 1, 1, 'Block not characterized');
hilite_system('UZ_EnDat/UZ_ENDAT/INITIALOFF/Subsystem6/Divide', 'user2');
annotate_port('UZ_EnDat/UZ_ENDAT/INITIALOFF/Subsystem6/Divide', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/ManualSerialize/Triggered Subsystem/Bit Clear', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualSerialize/Triggered Subsystem/Bit Clear', 1, 1, 'Block not characterized');
hilite_system('UZ_EnDat/UZ_ENDAT/ManualSerialize/Triggered Subsystem/Bit Clear', 'user2');
annotate_port('UZ_EnDat/UZ_ENDAT/ManualSerialize/Triggered Subsystem/Bit Clear', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/ManualSerialize/Triggered Subsystem/Bit Set', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/ManualSerialize/Triggered Subsystem/Bit Set', 1, 1, 'Block not characterized');
hilite_system('UZ_EnDat/UZ_ENDAT/ManualSerialize/Triggered Subsystem/Bit Set', 'user2');
annotate_port('UZ_EnDat/UZ_ENDAT/ManualSerialize/Triggered Subsystem/Bit Set', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT/Storage16/Single Port RAM System', 'user2');
annotate_port('gm_UZ_EnDat/UZ_ENDAT/Storage16/Single Port RAM System', 1, 1, 'Block not characterized');
hilite_system('UZ_EnDat/UZ_ENDAT/Storage16/Single Port RAM System', 'user2');
annotate_port('UZ_EnDat/UZ_ENDAT/Storage16/Single Port RAM System', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('UZ_EnDat/UZ_ENDAT/Dual Port RAM System', 'user2');
annotate_port('UZ_EnDat/UZ_ENDAT/Dual Port RAM System', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('UZ_EnDat/UZ_ENDAT/5timestorage/Storage20/Single Port RAM System', 'user2');
annotate_port('UZ_EnDat/UZ_ENDAT/5timestorage/Storage20/Single Port RAM System', 1, 1, 'Block not characterized');
