open_system('UZ_EnDat');
open_system('gm_UZ_EnDat');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT_ABZ_ADDON/Mod1', 'user1');
annotate_port('gm_UZ_EnDat/UZ_ENDAT_ABZ_ADDON/Mod1', 0, 1, 'Blocks delay absorption: 6 cycles');
hilite_system('UZ_EnDat/UZ_ENDAT_ABZ_ADDON/Mod1', 'user1');
annotate_port('UZ_EnDat/UZ_ENDAT_ABZ_ADDON/Mod1', 0, 1, 'Blocks delay absorption: 6 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT_ABZ_ADDON/Compare To Constant/Compare', 'user1');
annotate_port('gm_UZ_EnDat/UZ_ENDAT_ABZ_ADDON/Compare To Constant/Compare', 0, 1, 'Blocks delay absorption: 21 cycles');
hilite_system('UZ_EnDat/UZ_ENDAT_ABZ_ADDON/Compare To Constant/Compare', 'user1');
annotate_port('UZ_EnDat/UZ_ENDAT_ABZ_ADDON/Compare To Constant/Compare', 0, 1, 'Blocks delay absorption: 21 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT_ABZ_ADDON/Compare To Constant1/Compare', 'user1');
annotate_port('gm_UZ_EnDat/UZ_ENDAT_ABZ_ADDON/Compare To Constant1/Compare', 0, 1, 'Blocks delay absorption: 21 cycles');
hilite_system('UZ_EnDat/UZ_ENDAT_ABZ_ADDON/Compare To Constant1/Compare', 'user1');
annotate_port('UZ_EnDat/UZ_ENDAT_ABZ_ADDON/Compare To Constant1/Compare', 0, 1, 'Blocks delay absorption: 21 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat/UZ_ENDAT_ABZ_ADDON/Compare To Constant2/Compare', 'user1');
annotate_port('gm_UZ_EnDat/UZ_ENDAT_ABZ_ADDON/Compare To Constant2/Compare', 0, 1, 'Blocks delay absorption: 21 cycles');
hilite_system('UZ_EnDat/UZ_ENDAT_ABZ_ADDON/Compare To Constant2/Compare', 'user1');
annotate_port('UZ_EnDat/UZ_ENDAT_ABZ_ADDON/Compare To Constant2/Compare', 0, 1, 'Blocks delay absorption: 21 cycles');
