vlib work
vmap -c
vcom  UZ_EndDat_pac.vhd
vcom  Triggered_Subsystem.vhd
vcom  CLKDIV1.vhd
vcom  CLKDIV2.vhd
vcom  CLKDIV3.vhd
vcom  CLKDIV4.vhd
vcom  CLKDIV5.vhd
vcom  CLKDIV6.vhd
vcom  Compare_To_Constant.vhd
vcom  Detect_Change.vhd
vcom  SetZero.vhd
vcom  Increment_Real_World.vhd
vcom  Triggered_Subsystem_block.vhd
vcom  DualPortRAM_generic.vhd
vcom  alpha16BIT_SPLITTER.vhd
vcom  nfp_convert_fix_16_En0_to_double.vhd
vcom  UZ_EndDat.vhd
