vlib work
vmap -c
vcom  uz_EnDat_src_UZ_EndDat_pac.vhd
vcom  uz_EnDat_src_Triggered_Subsystem.vhd
vcom  uz_EnDat_src_CLKDIV1.vhd
vcom  uz_EnDat_src_CLKDIV2.vhd
vcom  uz_EnDat_src_CLKDIV3.vhd
vcom  uz_EnDat_src_CLKDIV4.vhd
vcom  uz_EnDat_src_CLKDIV5.vhd
vcom  uz_EnDat_src_CLKDIV6.vhd
vcom  uz_EnDat_src_CLKDIV7.vhd
vcom  uz_EnDat_src_CLKDIV8.vhd
vcom  uz_EnDat_src_CLKDIV9.vhd
vcom  uz_EnDat_src_FF0.vhd
vcom  uz_EnDat_src_CRC_Check.vhd
vcom  uz_EnDat_src_Compare_To_Constant.vhd
vcom  uz_EnDat_src_Compare_To_Constant1.vhd
vcom  uz_EnDat_src_Detect_Change.vhd
vcom  uz_EnDat_src_WORDTOBOOL.vhd
vcom  uz_EnDat_src_Increment_Stored_Integer.vhd
vcom  uz_EnDat_src_ramselektor.vhd
vcom  uz_EnDat_src_ManualDeserializer.vhd
vcom  uz_EnDat_src_SetZero.vhd
vcom  uz_EnDat_src_SetZeroBool1.vhd
vcom  uz_EnDat_src_Increment_Stored_Integer_block.vhd
vcom  uz_EnDat_src_ramselektor_block.vhd
vcom  uz_EnDat_src_Subsystem.vhd
vcom  uz_EnDat_src_Subsystem1.vhd
vcom  uz_EnDat_src_Subsystem10.vhd
vcom  uz_EnDat_src_Subsystem11.vhd
vcom  uz_EnDat_src_Subsystem12.vhd
vcom  uz_EnDat_src_Subsystem13.vhd
vcom  uz_EnDat_src_Subsystem14.vhd
vcom  uz_EnDat_src_Subsystem15.vhd
vcom  uz_EnDat_src_Subsystem2.vhd
vcom  uz_EnDat_src_Subsystem3.vhd
vcom  uz_EnDat_src_Subsystem4.vhd
vcom  uz_EnDat_src_Subsystem5.vhd
vcom  uz_EnDat_src_Subsystem6.vhd
vcom  uz_EnDat_src_Subsystem7.vhd
vcom  uz_EnDat_src_Subsystem8.vhd
vcom  uz_EnDat_src_Subsystem9.vhd
vcom  uz_EnDat_src_16bitgather.vhd
vcom  uz_EnDat_src_DualPortRAM_generic.vhd
vcom  uz_EnDat_src_16BIT_SPLITTER.vhd
vcom  uz_EnDat_src_Compare_To_Zero.vhd
vcom  uz_EnDat_src_SinglePortRAM_generic.vhd
vcom  uz_EnDat_src_Storage16.vhd
vcom  uz_EnDat_src_SetZero64.vhd
vcom  uz_EnDat_src_Increment_Stored_Integer_block1.vhd
vcom  uz_EnDat_src_Positional_Counter.vhd
vcom  uz_EnDat_src_CLKCNTER_RAMPUP.vhd
vcom  uz_EnDat_src_OUTPUTCONTROL.vhd
vcom  uz_EnDat_src_SetZero64_block.vhd
vcom  uz_EnDat_src_CLKCNTER_ACT.vhd
vcom  uz_EnDat_src_SetZeroBool.vhd
vcom  uz_EnDat_src_nfp_convert_fix_16_En0_to_double.vhd
vcom  uz_EnDat_src_UZ_EndDat.vhd
