open_system('gm_uz_SVPWM_6ph');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM', 'user2');
annotate_port('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM', 0, 1, 'cp : 8.687 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/LimitSVTime1', 'user2');
annotate_port('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/LimitSVTime1', 0, 1, 'cp : 4.507 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/out_10_pipe', 'user1');
annotate_port('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/out_10_pipe', 1, 1, 'cp : 8.687 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/Add', 'user2');
annotate_port('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/Add', 0, 1, 'cp : 5.18 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/Add2', 'user2');
annotate_port('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/Add2', 0, 1, 'cp : 5.825 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/Add3', 'user2');
annotate_port('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/Add3', 0, 1, 'cp : 6.47 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/Bit Slice', 'user2');
annotate_port('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/Bit Slice', 0, 1, 'cp : 7.684 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/t', 'user2');
annotate_port('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/t', 0, 1, 'cp : 8.426 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/Index Vector', 'user2');
annotate_port('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/Index Vector', 0, 1, 'cp : 2.962 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/MinOrMax', 'user2');
annotate_port('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/MinOrMax', 0, 1, 'cp : 2.355 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/Relational Operator4', 'user2');
annotate_port('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/Relational Operator4', 0, 1, 'cp : 7.332 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/Switch16', 'user2');
annotate_port('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/Switch16', 0, 1, 'cp : 8.426 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/Switch17', 'user2');
annotate_port('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/Switch17', 0, 1, 'cp : 8.036 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/Switch22', 'user2');
annotate_port('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/Switch22', 0, 1, 'cp : 7.684 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/HDL Counter2', 'user2');
annotate_port('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/HDL Counter2', 0, 1, 'cp : 0.33 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/Counter Ctrl', 'user2');
annotate_port('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/Counter Ctrl', 0, 3, 'cp : 1.362 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/Switch2', 'user2');
annotate_port('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/Switch2', 0, 1, 'cp : 3.314 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/Counter Ctrl/Relational Operator1', 'user2');
annotate_port('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/Counter Ctrl/Relational Operator1', 0, 1, 'cp : 1.362 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/LimitSVTime1/Relational Operator1', 'user2');
annotate_port('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/LimitSVTime1/Relational Operator1', 0, 1, 'cp : 4.155 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/LimitSVTime1/Switch', 'user2');
annotate_port('gm_uz_SVPWM_6ph/SVPWM_and_Signal_Control/GenSVPWM/LimitSVTime1/Switch', 0, 1, 'cp : 4.507 ns');
