open_system('gm_uz_count_switching');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_count_switching/uz_count_switching/Count_Changes1', 'user2');
annotate_port('gm_uz_count_switching/uz_count_switching/Count_Changes1', 0, 1, 'cp : 0.33 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_count_switching/uz_count_switching/Delay', 'user1');
annotate_port('gm_uz_count_switching/uz_count_switching/Delay', 1, 1, 'cp : 6.482 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_count_switching/uz_count_switching/Add_stage2', 'user2');
annotate_port('gm_uz_count_switching/uz_count_switching/Add_stage2', 0, 1, 'cp : 1.077 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_count_switching/uz_count_switching/Add_stage3', 'user2');
annotate_port('gm_uz_count_switching/uz_count_switching/Add_stage3', 0, 1, 'cp : 1.796 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_count_switching/uz_count_switching/Add_stage4', 'user2');
annotate_port('gm_uz_count_switching/uz_count_switching/Add_stage4', 0, 1, 'cp : 2.515 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_count_switching/uz_count_switching/Add_stage5', 'user2');
annotate_port('gm_uz_count_switching/uz_count_switching/Add_stage5', 0, 1, 'cp : 3.234 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_count_switching/uz_count_switching/Add_stage6', 'user2');
annotate_port('gm_uz_count_switching/uz_count_switching/Add_stage6', 0, 1, 'cp : 3.953 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_count_switching/uz_count_switching/Add_stage7', 'user2');
annotate_port('gm_uz_count_switching/uz_count_switching/Add_stage7', 0, 1, 'cp : 4.709 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_count_switching/uz_count_switching/Add_stage8', 'user2');
annotate_port('gm_uz_count_switching/uz_count_switching/Add_stage8', 0, 1, 'cp : 5.465 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_count_switching/uz_count_switching/Add_stage9', 'user2');
annotate_port('gm_uz_count_switching/uz_count_switching/Add_stage9', 0, 1, 'cp : 6.221 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_count_switching/uz_count_switching/Count_Changes1/HDL Counter', 'user2');
annotate_port('gm_uz_count_switching/uz_count_switching/Count_Changes1/HDL Counter', 0, 1, 'cp : 0.33 ns');
