open_system('gm_interlock_deadtime');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/DeadtimeModule_instance1', 'user2');
annotate_port('gm_interlock_deadtime/interlock_deadtime/DeadtimeModule_instance1', 0, 1, 'cp : 3.828 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/t6', 'user2');
annotate_port('gm_interlock_deadtime/interlock_deadtime/t6', 0, 1, 'cp : 3.828 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/t7', 'user2');
annotate_port('gm_interlock_deadtime/interlock_deadtime/t7', 0, 1, 'cp : 3.828 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/EnableOutputModule_instance1', 'user2');
annotate_port('gm_interlock_deadtime/interlock_deadtime/EnableOutputModule_instance1', 0, 1, 'cp : 8.247 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/t8', 'user2');
annotate_port('gm_interlock_deadtime/interlock_deadtime/t8', 0, 1, 'cp : 6.779 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/t14', 'user2');
annotate_port('gm_interlock_deadtime/interlock_deadtime/t14', 0, 1, 'cp : 8.247 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/t15', 'user2');
annotate_port('gm_interlock_deadtime/interlock_deadtime/t15', 0, 1, 'cp : 8.247 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/InterlockModule_instance1', 'user2');
annotate_port('gm_interlock_deadtime/interlock_deadtime/InterlockModule_instance1', 0, 1, 'cp : 5.762 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/t16', 'user2');
annotate_port('gm_interlock_deadtime/interlock_deadtime/t16', 0, 1, 'cp : 3.828 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/t19', 'user2');
annotate_port('gm_interlock_deadtime/interlock_deadtime/t19', 0, 1, 'cp : 5.762 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/t20', 'user2');
annotate_port('gm_interlock_deadtime/interlock_deadtime/t20', 0, 1, 'cp : 5.762 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/InverseBotSwitchModule_instance1', 'user2');
annotate_port('gm_interlock_deadtime/interlock_deadtime/InverseBotSwitchModule_instance1', 0, 1, 'cp : 6.779 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/t21', 'user2');
annotate_port('gm_interlock_deadtime/interlock_deadtime/t21', 0, 1, 'cp : 5.762 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/t24', 'user2');
annotate_port('gm_interlock_deadtime/interlock_deadtime/t24', 0, 1, 'cp : 6.779 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/t25', 'user2');
annotate_port('gm_interlock_deadtime/interlock_deadtime/t25', 0, 1, 'cp : 6.779 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/t26', 'user1');
annotate_port('gm_interlock_deadtime/interlock_deadtime/t26', 0, 1, 'cp : 8.247 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/DeadtimeModule_instance1/HDL Counter', 'user1');
annotate_port('gm_interlock_deadtime/interlock_deadtime/DeadtimeModule_instance1/HDL Counter', 0, 1, 'cp : 0.549 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/DeadtimeModule_instance1/Switch', 'user2');
annotate_port('gm_interlock_deadtime/interlock_deadtime/DeadtimeModule_instance1/Switch', 0, 1, 'cp : 2.252 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/DeadtimeModule_instance1/Relational Operator', 'user2');
annotate_port('gm_interlock_deadtime/interlock_deadtime/DeadtimeModule_instance1/Relational Operator', 0, 1, 'cp : 1.569 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/DeadtimeModule_instance1/Logical Operator10', 'user2');
annotate_port('gm_interlock_deadtime/interlock_deadtime/DeadtimeModule_instance1/Logical Operator10', 0, 1, 'cp : 3.828 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/EnableOutputModule_instance1/AND', 'user2');
annotate_port('gm_interlock_deadtime/interlock_deadtime/EnableOutputModule_instance1/AND', 0, 1, 'cp : 8.247 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/InterlockModule_instance1/mux', 'user2');
annotate_port('gm_interlock_deadtime/interlock_deadtime/InterlockModule_instance1/mux', 0, 1, 'cp : 5.762 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/InterlockModule_instance1/Logical Operator3', 'user2');
annotate_port('gm_interlock_deadtime/interlock_deadtime/InterlockModule_instance1/Logical Operator3', 0, 1, 'cp : 4.186 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/InterlockModule_instance1/Logical Operator2', 'user2');
annotate_port('gm_interlock_deadtime/interlock_deadtime/InterlockModule_instance1/Logical Operator2', 0, 1, 'cp : 5.762 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/InterlockModule_instance1/t', 'user2');
annotate_port('gm_interlock_deadtime/interlock_deadtime/InterlockModule_instance1/t', 0, 2, 'cp : 3.828 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/InterlockModule_instance1/In1_1_wire', 'user2');
annotate_port('gm_interlock_deadtime/interlock_deadtime/InterlockModule_instance1/In1_1_wire', 0, 1, 'cp : 3.828 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/InverseBotSwitchModule_instance1/NOT', 'user2');
annotate_port('gm_interlock_deadtime/interlock_deadtime/InverseBotSwitchModule_instance1/NOT', 0, 1, 'cp : 6.12 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/InverseBotSwitchModule_instance1/mux', 'user2');
annotate_port('gm_interlock_deadtime/interlock_deadtime/InverseBotSwitchModule_instance1/mux', 0, 1, 'cp : 6.779 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/InverseBotSwitchModule_instance1/Index Vector', 'user2');
annotate_port('gm_interlock_deadtime/interlock_deadtime/InverseBotSwitchModule_instance1/Index Vector', 0, 1, 'cp : 6.779 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/InverseBotSwitchModule_instance1/t', 'user2');
annotate_port('gm_interlock_deadtime/interlock_deadtime/InverseBotSwitchModule_instance1/t', 0, 2, 'cp : 5.762 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interlock_deadtime/interlock_deadtime/InverseBotSwitchModule_instance1/gate_delay_out_1_wire', 'user2');
annotate_port('gm_interlock_deadtime/interlock_deadtime/InverseBotSwitchModule_instance1/gate_delay_out_1_wire', 0, 1, 'cp : 5.762 ns');
