open_system('uz_endat_interface_2025b');
open_system('gm_uz_endat_interface_2025b');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/cos_hdl/Look-Up Table/Look-Up Table', 'user1');
annotate_port('gm_uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/cos_hdl/Look-Up Table/Look-Up Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/cos_hdl/Look-Up Table', 'user1');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/cos_hdl/Look-Up Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/Look-Up Table/Look-Up Table', 'user1');
annotate_port('gm_uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/Look-Up Table/Look-Up Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/Look-Up Table', 'user1');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/Look-Up Table', 0, 1, 'Lookup Table mapped to RAM');
