open_system('uz_endat_interface_2025b');
open_system('gm_uz_endat_interface_2025b');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_endat_interface_2025b/uz_endat_interface/S-R Flip-Flop1', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/S-R Flip-Flop1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2025b/uz_endat_interface/S-R Flip-Flop1', 'user2');
annotate_port('gm_uz_endat_interface_2025b/uz_endat_interface/S-R Flip-Flop1', 1, 1, 'Block not characterized');
hilite_system('uz_endat_interface_2025b/uz_endat_interface/S-R Flip-Flop1', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/S-R Flip-Flop1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_endat_interface_2025b/uz_endat_interface/RW_data_and_mode_command_control/S-R Flip-Flop', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/RW_data_and_mode_command_control/S-R Flip-Flop', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2025b/uz_endat_interface/RW_data_and_mode_command_control/S-R Flip-Flop', 'user2');
annotate_port('gm_uz_endat_interface_2025b/uz_endat_interface/RW_data_and_mode_command_control/S-R Flip-Flop', 1, 1, 'Block not characterized');
hilite_system('uz_endat_interface_2025b/uz_endat_interface/RW_data_and_mode_command_control/S-R Flip-Flop', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/RW_data_and_mode_command_control/S-R Flip-Flop', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_endat_interface_2025b/uz_endat_interface/RW_data_and_mode_command_control/S-R Flip-Flop1', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/RW_data_and_mode_command_control/S-R Flip-Flop1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2025b/uz_endat_interface/RW_data_and_mode_command_control/S-R Flip-Flop1', 'user2');
annotate_port('gm_uz_endat_interface_2025b/uz_endat_interface/RW_data_and_mode_command_control/S-R Flip-Flop1', 1, 1, 'Block not characterized');
hilite_system('uz_endat_interface_2025b/uz_endat_interface/RW_data_and_mode_command_control/S-R Flip-Flop1', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/RW_data_and_mode_command_control/S-R Flip-Flop1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/fixed_point_floor', 'user2');
annotate_port('gm_uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/fixed_point_floor', 1, 1, 'Block not characterized');
hilite_system('uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/fixed_point_floor', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/fixed_point_floor', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2025b/uz_endat_interface/serial_communication/MATLAB Function1', 'user2');
annotate_port('gm_uz_endat_interface_2025b/uz_endat_interface/serial_communication/MATLAB Function1', 1, 1, 'Block not characterized');
hilite_system('uz_endat_interface_2025b/uz_endat_interface/serial_communication/MATLAB Function1', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/serial_communication/MATLAB Function1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_endat_interface_2025b/uz_endat_interface/serial_communication/clk_idle_and_delay_first_clock_function/S-R Flip-Flop', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/serial_communication/clk_idle_and_delay_first_clock_function/S-R Flip-Flop', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2025b/uz_endat_interface/serial_communication/clk_idle_and_delay_first_clock_function/S-R Flip-Flop', 'user2');
annotate_port('gm_uz_endat_interface_2025b/uz_endat_interface/serial_communication/clk_idle_and_delay_first_clock_function/S-R Flip-Flop', 1, 1, 'Block not characterized');
hilite_system('uz_endat_interface_2025b/uz_endat_interface/serial_communication/clk_idle_and_delay_first_clock_function/S-R Flip-Flop', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/serial_communication/clk_idle_and_delay_first_clock_function/S-R Flip-Flop', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_endat_interface_2025b/uz_endat_interface/serial_communication/endat_clock_enable_controller/S-R Flip-Flop', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/serial_communication/endat_clock_enable_controller/S-R Flip-Flop', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2025b/uz_endat_interface/serial_communication/endat_clock_enable_controller/S-R Flip-Flop', 'user2');
annotate_port('gm_uz_endat_interface_2025b/uz_endat_interface/serial_communication/endat_clock_enable_controller/S-R Flip-Flop', 1, 1, 'Block not characterized');
hilite_system('uz_endat_interface_2025b/uz_endat_interface/serial_communication/endat_clock_enable_controller/S-R Flip-Flop', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/serial_communication/endat_clock_enable_controller/S-R Flip-Flop', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_endat_interface_2025b/uz_endat_interface/serial_communication/endat_clock_enable_controller/S-R Flip-Flop1', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/serial_communication/endat_clock_enable_controller/S-R Flip-Flop1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2025b/uz_endat_interface/serial_communication/endat_clock_enable_controller/S-R Flip-Flop1', 'user2');
annotate_port('gm_uz_endat_interface_2025b/uz_endat_interface/serial_communication/endat_clock_enable_controller/S-R Flip-Flop1', 1, 1, 'Block not characterized');
hilite_system('uz_endat_interface_2025b/uz_endat_interface/serial_communication/endat_clock_enable_controller/S-R Flip-Flop1', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/serial_communication/endat_clock_enable_controller/S-R Flip-Flop1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_endat_interface_2025b/uz_endat_interface/serial_communication/endat_clock_generator/S-R Flip-Flop1', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/serial_communication/endat_clock_generator/S-R Flip-Flop1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2025b/uz_endat_interface/serial_communication/endat_clock_generator/S-R Flip-Flop1', 'user2');
annotate_port('gm_uz_endat_interface_2025b/uz_endat_interface/serial_communication/endat_clock_generator/S-R Flip-Flop1', 1, 1, 'Block not characterized');
hilite_system('uz_endat_interface_2025b/uz_endat_interface/serial_communication/endat_clock_generator/S-R Flip-Flop1', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/serial_communication/endat_clock_generator/S-R Flip-Flop1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2025b/uz_endat_interface/serial_communication/sample_serial_endat_data/Bitwise Operator1', 'user2');
annotate_port('gm_uz_endat_interface_2025b/uz_endat_interface/serial_communication/sample_serial_endat_data/Bitwise Operator1', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_endat_interface_2025b/uz_endat_interface/serial_communication/sample_serial_endat_data/Bitwise Operator1', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/serial_communication/sample_serial_endat_data/Bitwise Operator1', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2025b/uz_endat_interface/serial_communication/sample_serial_endat_data/shift arithmetic', 'user2');
annotate_port('gm_uz_endat_interface_2025b/uz_endat_interface/serial_communication/sample_serial_endat_data/shift arithmetic', 1, 1, 'Block not characterized');
hilite_system('uz_endat_interface_2025b/uz_endat_interface/serial_communication/sample_serial_endat_data/Shift Arithmetic', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/serial_communication/sample_serial_endat_data/Shift Arithmetic', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_endat_interface_2025b/uz_endat_interface/serial_communication/sample_serial_endat_data/S-R Flip-Flop', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/serial_communication/sample_serial_endat_data/S-R Flip-Flop', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2025b/uz_endat_interface/serial_communication/sample_serial_endat_data/S-R Flip-Flop', 'user2');
annotate_port('gm_uz_endat_interface_2025b/uz_endat_interface/serial_communication/sample_serial_endat_data/S-R Flip-Flop', 1, 1, 'Block not characterized');
hilite_system('uz_endat_interface_2025b/uz_endat_interface/serial_communication/sample_serial_endat_data/S-R Flip-Flop', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/serial_communication/sample_serial_endat_data/S-R Flip-Flop', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_endat_interface_2025b/uz_endat_interface/set_offset_to_raw_position_and_wrap/Shift Arithmetic2', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/set_offset_to_raw_position_and_wrap/Shift Arithmetic2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_endat_interface_2025b/uz_endat_interface/set_offset_to_raw_position_and_wrap/Shift Arithmetic3', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/set_offset_to_raw_position_and_wrap/Shift Arithmetic3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_endat_interface_2025b/uz_endat_interface/set_offset_to_raw_position_and_wrap/floor_div_pow2/Shift Arithmetic4', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/set_offset_to_raw_position_and_wrap/floor_div_pow2/Shift Arithmetic4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_endat_interface_2025b/uz_endat_interface/set_offset_to_raw_position_and_wrap/floor_div_pow2/Shift Arithmetic5', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/set_offset_to_raw_position_and_wrap/floor_div_pow2/Shift Arithmetic5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2025b/uz_endat_interface/slice_position_and_CRC/shift arithmetic', 'user2');
annotate_port('gm_uz_endat_interface_2025b/uz_endat_interface/slice_position_and_CRC/shift arithmetic', 1, 1, 'Block not characterized');
hilite_system('uz_endat_interface_2025b/uz_endat_interface/slice_position_and_CRC/Shift Arithmetic', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/slice_position_and_CRC/Shift Arithmetic', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2025b/uz_endat_interface/slice_position_and_CRC/shift arithmetic1', 'user2');
annotate_port('gm_uz_endat_interface_2025b/uz_endat_interface/slice_position_and_CRC/shift arithmetic1', 1, 1, 'Block not characterized');
hilite_system('uz_endat_interface_2025b/uz_endat_interface/slice_position_and_CRC/Shift Arithmetic1', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/slice_position_and_CRC/Shift Arithmetic1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2025b/uz_endat_interface/slice_position_and_CRC/shift arithmetic2', 'user2');
annotate_port('gm_uz_endat_interface_2025b/uz_endat_interface/slice_position_and_CRC/shift arithmetic2', 1, 1, 'Block not characterized');
hilite_system('uz_endat_interface_2025b/uz_endat_interface/slice_position_and_CRC/Shift Arithmetic2', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/slice_position_and_CRC/Shift Arithmetic2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2025b/uz_endat_interface/slice_position_and_CRC/shift arithmetic3_nonneg', 'user2');
annotate_port('gm_uz_endat_interface_2025b/uz_endat_interface/slice_position_and_CRC/shift arithmetic3_nonneg', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2025b/uz_endat_interface/slice_position_and_CRC/shift arithmetic3', 'user2');
annotate_port('gm_uz_endat_interface_2025b/uz_endat_interface/slice_position_and_CRC/shift arithmetic3', 1, 1, 'Block not characterized');
hilite_system('uz_endat_interface_2025b/uz_endat_interface/slice_position_and_CRC/Shift Arithmetic3', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/slice_position_and_CRC/Shift Arithmetic3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2025b/uz_endat_interface/slice_position_and_CRC/shift arithmetic4_nonneg', 'user2');
annotate_port('gm_uz_endat_interface_2025b/uz_endat_interface/slice_position_and_CRC/shift arithmetic4_nonneg', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2025b/uz_endat_interface/slice_position_and_CRC/shift arithmetic4', 'user2');
annotate_port('gm_uz_endat_interface_2025b/uz_endat_interface/slice_position_and_CRC/shift arithmetic4', 1, 1, 'Block not characterized');
hilite_system('uz_endat_interface_2025b/uz_endat_interface/slice_position_and_CRC/Shift Arithmetic4', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/slice_position_and_CRC/Shift Arithmetic4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2025b/uz_endat_interface/wrap_2pi/fixed_point_floor', 'user2');
annotate_port('gm_uz_endat_interface_2025b/uz_endat_interface/wrap_2pi/fixed_point_floor', 1, 1, 'Block not characterized');
hilite_system('uz_endat_interface_2025b/uz_endat_interface/wrap_2pi/fixed_point_floor', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/wrap_2pi/fixed_point_floor', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized/sincos hdl/cos_hdl/Look-Up Table', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized/sincos hdl/cos_hdl/Look-Up Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized/sincos hdl/cos_hdl/Look-Up Table', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized/sincos hdl/cos_hdl/Look-Up Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized/sincos hdl/sin_hdl/Look-Up Table', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized/sincos hdl/sin_hdl/Look-Up Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized/sincos hdl/sin_hdl/Look-Up Table', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized/sincos hdl/sin_hdl/Look-Up Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/cos_hdl/Look-Up Table', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/cos_hdl/Look-Up Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/cos_hdl/Look-Up Table/Look-Up Table', 'user2');
annotate_port('gm_uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/cos_hdl/Look-Up Table/Look-Up Table', 1, 1, 'Block not characterized');
hilite_system('uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/cos_hdl/Look-Up Table', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/cos_hdl/Look-Up Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/Look-Up Table', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/Look-Up Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/Look-Up Table/Look-Up Table', 'user2');
annotate_port('gm_uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/Look-Up Table/Look-Up Table', 1, 1, 'Block not characterized');
hilite_system('uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/Look-Up Table', 'user2');
annotate_port('uz_endat_interface_2025b/uz_endat_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/Look-Up Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
