open_system('gm_uz_typeconv_multi');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_typeconv_multi/uz_typeconv_multi/Detect Rise Positive', 'user2');
annotate_port('gm_uz_typeconv_multi/uz_typeconv_multi/Detect Rise Positive', 0, 1, 'cp : 1.374 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_typeconv_multi/uz_typeconv_multi/Delay2', 'user1');
annotate_port('gm_uz_typeconv_multi/uz_typeconv_multi/Delay2', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_typeconv_multi/uz_typeconv_multi/Delay3', 'user1');
annotate_port('gm_uz_typeconv_multi/uz_typeconv_multi/Delay3', 1, 1, 'cp : 5.912 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_typeconv_multi/uz_typeconv_multi/Product', 'user2');
annotate_port('gm_uz_typeconv_multi/uz_typeconv_multi/Product', 0, 1, 'cp : 5.912 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_typeconv_multi/uz_typeconv_multi/Switch1', 'user2');
annotate_port('gm_uz_typeconv_multi/uz_typeconv_multi/Switch1', 0, 1, 'cp : 1.726 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_typeconv_multi/uz_typeconv_multi/Detect Rise Positive/FixPt Relational Operator', 'user2');
annotate_port('gm_uz_typeconv_multi/uz_typeconv_multi/Detect Rise Positive/FixPt Relational Operator', 0, 1, 'cp : 1.374 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_typeconv_multi/uz_typeconv_multi/Detect Rise Positive/Positive', 'user2');
annotate_port('gm_uz_typeconv_multi/uz_typeconv_multi/Detect Rise Positive/Positive', 0, 1, 'cp : 0.687 ns');
