open_system('uz_typeconv_multi');
open_system('gm_uz_typeconv_multi');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_typeconv_multi/uz_typeconv_multi/Detect Rise Positive', 'user2');
annotate_port('gm_uz_typeconv_multi/uz_typeconv_multi/Detect Rise Positive', 1, 1, 'Block not characterized');
hilite_system('uz_typeconv_multi/uz_typeconv_multi/Detect Rise Positive', 'user2');
annotate_port('uz_typeconv_multi/uz_typeconv_multi/Detect Rise Positive', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_typeconv_multi/uz_typeconv_multi/Delay', 'user2');
annotate_port('gm_uz_typeconv_multi/uz_typeconv_multi/Delay', 1, 1, 'Block not characterized');
hilite_system('uz_typeconv_multi/uz_typeconv_multi/Delay', 'user2');
annotate_port('uz_typeconv_multi/uz_typeconv_multi/Delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_typeconv_multi/uz_typeconv_multi/Delay1', 'user2');
annotate_port('gm_uz_typeconv_multi/uz_typeconv_multi/Delay1', 1, 1, 'Block not characterized');
hilite_system('uz_typeconv_multi/uz_typeconv_multi/Delay1', 'user2');
annotate_port('uz_typeconv_multi/uz_typeconv_multi/Delay1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_typeconv_multi/uz_typeconv_multi/Delay2', 'user2');
annotate_port('gm_uz_typeconv_multi/uz_typeconv_multi/Delay2', 1, 1, 'Block not characterized');
hilite_system('uz_typeconv_multi/uz_typeconv_multi/Delay2', 'user2');
annotate_port('uz_typeconv_multi/uz_typeconv_multi/Delay2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_typeconv_multi/uz_typeconv_multi/Delay3', 'user2');
annotate_port('gm_uz_typeconv_multi/uz_typeconv_multi/Delay3', 1, 1, 'Block not characterized');
hilite_system('uz_typeconv_multi/uz_typeconv_multi/Delay3', 'user2');
annotate_port('uz_typeconv_multi/uz_typeconv_multi/Delay3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_typeconv_multi/uz_typeconv_multi/Delay4', 'user2');
annotate_port('gm_uz_typeconv_multi/uz_typeconv_multi/Delay4', 1, 1, 'Block not characterized');
hilite_system('uz_typeconv_multi/uz_typeconv_multi/Delay4', 'user2');
annotate_port('uz_typeconv_multi/uz_typeconv_multi/Delay4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_typeconv_multi/uz_typeconv_multi/Delay5', 'user2');
annotate_port('gm_uz_typeconv_multi/uz_typeconv_multi/Delay5', 1, 1, 'Block not characterized');
hilite_system('uz_typeconv_multi/uz_typeconv_multi/Delay5', 'user2');
annotate_port('uz_typeconv_multi/uz_typeconv_multi/Delay5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_typeconv_multi/uz_typeconv_multi/Delay6', 'user2');
annotate_port('gm_uz_typeconv_multi/uz_typeconv_multi/Delay6', 1, 1, 'Block not characterized');
hilite_system('uz_typeconv_multi/uz_typeconv_multi/Delay6', 'user2');
annotate_port('uz_typeconv_multi/uz_typeconv_multi/Delay6', 1, 1, 'Block not characterized');
