open_system('gm_uz_pmsm_model_nonlinear');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Delay1_lowered2', 'user1');
annotate_port('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Delay1_lowered2', 0, 1, 'cp : 0.33 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/in6_repeat', 'user2');
annotate_port('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/in6_repeat', 0, 1, 'cp : 0.33 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Ldd Lookup Table/Ldd Lookup Table', 'user2');
annotate_port('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Ldd Lookup Table/Ldd Lookup Table', 1, 1, 'cp : 8.437 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/From', 'user2');
annotate_port('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/From', 0, 1, 'cp : 0.72 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Goto', 'user2');
annotate_port('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Goto', 0, 1, 'cp : 0.72 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/reset_out', 'user2');
annotate_port('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/reset_out', 0, 1, 'cp : 0.72 ns');
