open_system('uz_pmsm_model_nonlinear');
open_system('gm_uz_pmsm_model_nonlinear');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion16', 'user2');
annotate_port('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion16', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion16', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion16', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion12', 'user2');
annotate_port('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion12', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion12', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion12', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion17', 'user2');
annotate_port('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion17', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion17', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion17', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion6', 'user2');
annotate_port('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion6', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion6', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion6', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion2', 'user2');
annotate_port('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion2', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion2', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion2', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion3', 'user2');
annotate_port('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion3', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion3', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion3', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion14', 'user2');
annotate_port('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion14', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion14', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion14', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion5', 'user2');
annotate_port('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion5', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion5', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion5', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion4', 'user2');
annotate_port('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion4', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion4', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion4', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion13', 'user2');
annotate_port('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion13', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion13', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion13', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion11', 'user2');
annotate_port('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion11', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion11', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion11', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion15', 'user2');
annotate_port('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion15', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion15', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion15', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion10', 'user2');
annotate_port('gm_uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion10', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion10', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/Data Type Conversion10', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Flux_d Lookup Table', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Flux_d Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Flux_d Lookup Table', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Flux_d Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Flux_d Lookup Table', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Flux_d Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Flux_d Lookup Table', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Flux_d Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Flux_d Lookup Table', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Flux_d Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Flux_q Lookup Table', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Flux_q Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Flux_q Lookup Table', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Flux_q Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Flux_q Lookup Table', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Flux_q Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Flux_q Lookup Table', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Flux_q Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Flux_q Lookup Table', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Flux_q Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Ldd Lookup Table', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Ldd Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Ldd Lookup Table', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Ldd Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Ldd Lookup Table', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Ldd Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Ldd Lookup Table', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Ldd Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Ldd Lookup Table', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Ldd Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Ldq Lookup Table2', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Ldq Lookup Table2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Ldq Lookup Table2', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Ldq Lookup Table2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Ldq Lookup Table2', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Ldq Lookup Table2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Ldq Lookup Table2', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Ldq Lookup Table2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Ldq Lookup Table2', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Ldq Lookup Table2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Lqd Lookup Table1', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Lqd Lookup Table1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Lqd Lookup Table1', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Lqd Lookup Table1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Lqd Lookup Table1', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Lqd Lookup Table1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Lqd Lookup Table1', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Lqd Lookup Table1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Lqd Lookup Table1', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Lqd Lookup Table1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Lqq Lookup Table', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Lqq Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Lqq Lookup Table', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Lqq Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Lqq Lookup Table', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Lqq Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Lqq Lookup Table', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Lqq Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Lqq Lookup Table', 'user2');
annotate_port('uz_pmsm_model_nonlinear/uz_pmsm_model_nonlinear/pmsm/Lqq Lookup Table', 1, 1, 'Block not characterized');
