SLStudio.Utils.RemoveHighlighting(get_param('inc_enc_v26', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_inc_enc_v26', 'handle'));
annotate_port('gm_inc_enc_v26/IncEnc_V26/AB-Line-Switch', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/AB-Line-Switch', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Check d-Axis-Hit', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/Check d-Axis-Hit', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Check d-Axis-Hit_WithCompare', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/Check d-Axis-Hit_WithCompare', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Counter', 0, 2, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Counter', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/Counter', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Counter_Theta_el_wOffset', 1, 2, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Counter_Theta_el_wOffset', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/Counter_Theta_el_wOffset', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Counter_position', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/Counter_position', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Counter_position_wOffset', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/Counter_position_wOffset', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Direction', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/Direction', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Index_Latch', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/Index_Latch', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/count_lines', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/count_lines', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter1', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter1', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter2', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter2', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter2', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/speed1', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Check d-Axis-Hit/Equal', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/Check d-Axis-Hit/Equal', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Check d-Axis-Hit/Equal1', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/Check d-Axis-Hit/Equal1', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Check d-Axis-Hit_WithCompare/Equal', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/Check d-Axis-Hit_WithCompare/Equal', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Check d-Axis-Hit_WithCompare/Equal', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/Check d-Axis-Hit_WithCompare/Equal', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Counter/Reset_flag', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Counter_Theta_el_wOffset/Constant2', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/Counter_Theta_el_wOffset/Constant2', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Counter_Theta_el_wOffset/Constant5', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/Counter_Theta_el_wOffset/Constant5', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Counter_Theta_el_wOffset/Resett_switch2', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Counter_Theta_el_wOffset/Relational Operator1', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/Counter_Theta_el_wOffset/Relational Operator1', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Counter_Theta_el_wOffset/Resett_switch3', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Counter_Theta_el_wOffset/Resett_switch1', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Counter_Theta_el_wOffset/Relational Operator', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Counter_Theta_el_wOffset/reset_old3', 1, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Counter_position/Constant2', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/Counter_position/Constant2', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Counter_position/Constant5', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/Counter_position/Constant5', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Counter_position/Relational Operator1', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/Counter_position/Relational Operator1', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Direction/TurnLeft', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/Direction/TurnLeft', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Direction/TurnRight', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/Direction/TurnRight', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Index_Latch/Constant', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/Index_Latch/Constant', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/count_lines/Constant2', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/count_lines/Constant2', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/count_lines/Constant4', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/count_lines/Constant4', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter/Subsystem1', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter/Subsystem1', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter/NOT', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter/NOT', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter/NOT1', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter/NOT1', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter/NOT2', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter/NOT2', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter/Subsystem1/AND1', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter/Subsystem1/AND1', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter/Subsystem1/AND', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter/Subsystem1/AND', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter1/Subsystem1', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter1/Subsystem1', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter1/NOT', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter1/NOT', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter1/NOT1', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter1/NOT1', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter1/NOT2', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter1/NOT2', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter1/Subsystem1/AND1', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter1/Subsystem1/AND1', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter1/Subsystem1/AND', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter1/Subsystem1/AND', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter2/Subsystem1', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter2/Subsystem1', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter2/Subsystem1', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter2/AND1', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter2/NOT', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter2/NOT', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter2/NOT1', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter2/NOT1', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter2/NOT2', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter2/NOT2', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter2/NOT2', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter2/rd_4', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter2/Subsystem1/AND1', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter2/Subsystem1/AND1', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter2/Subsystem1/AND', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter2/Subsystem1/AND', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter2/Subsystem1/AND', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/Logical1', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/Logical1', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/Logical2', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/Logical2', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance4', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/calc_omega', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance3', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/calc_omega', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance2', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/calc_omega', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance1', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/calc_omega', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/Average', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/Average', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/align_oversamples', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/align_oversamples', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/oversample_factor', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/oversample_factor', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/Delay7_Initial_Val', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/Delay7_ctrl_const', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance4/invt_mult', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/calc_omega/invt_mult', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance4/Constant4', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/calc_omega/Constant4', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance4/step_value', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/calc_omega/32bit counter', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance4/const', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/calc_omega/32bit counter', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance4/Relational Operator', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/calc_omega/Relational Operator', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance4/invt_mult/HDL Reciprocal', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/calc_omega/invt_mult/HDL Reciprocal', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/align_oversamples/align_oversamples', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/align_oversamples/align_oversamples', 1, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/align_oversamples/align_oversamples', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/align_oversamples', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/align_oversamples/align_oversamples', 1, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/align_oversamples', 1, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/oversample_factor/oversample_factor', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/oversample_factor/oversample_factor', 1, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/oversample_factor/oversample_factor', 0, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/oversample_factor', 0, 1, '');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/oversample_factor/oversample_factor', 1, 1, '');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/oversample_factor', 1, 1, '');
