open_system('gm_inc_enc_v26');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/speed1', 'user2');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1', 0, 1, 'cp : 5.332 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance4', 'user2');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance4', 0, 1, 'cp : 5.332 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance4/invt_mult', 'user2');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance4/invt_mult', 0, 1, 'cp : 5.332 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance4/invt_mult/HDL Reciprocal', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance4/invt_mult/HDL Reciprocal', 0, 1, 'cp : 5.332 ns');
