open_system('inc_enc_v26');
open_system('gm_inc_enc_v26');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V25/speed/OS_factor_logic/align_oversamples/align_oversamples', 'user2');
annotate_port('gm_inc_enc_v26/IncEnc_V25/speed/OS_factor_logic/align_oversamples/align_oversamples', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V25/speed/OS_factor_logic/align_oversamples/align_oversamples', 'user2');
annotate_port('gm_inc_enc_v26/IncEnc_V25/speed/OS_factor_logic/align_oversamples/align_oversamples', 1, 1, 'Block not characterized');
hilite_system('inc_enc_v26/IncEnc_V25/speed/OS_factor_logic/align_oversamples', 'user2');
annotate_port('inc_enc_v26/IncEnc_V25/speed/OS_factor_logic/align_oversamples', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V25/speed/OS_factor_logic/oversample_factor/oversample_factor', 'user2');
annotate_port('gm_inc_enc_v26/IncEnc_V25/speed/OS_factor_logic/oversample_factor/oversample_factor', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V25/speed/OS_factor_logic/oversample_factor/oversample_factor', 'user2');
annotate_port('gm_inc_enc_v26/IncEnc_V25/speed/OS_factor_logic/oversample_factor/oversample_factor', 1, 1, 'Block not characterized');
hilite_system('inc_enc_v26/IncEnc_V25/speed/OS_factor_logic/oversample_factor', 'user2');
annotate_port('inc_enc_v26/IncEnc_V25/speed/OS_factor_logic/oversample_factor', 1, 1, 'Block not characterized');
