open_system('inc_enc_v26');
open_system('gm_inc_enc_v26');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/AB-Line-Switch', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/AB-Line-Switch', 0, 1, 'Delays not moved into or out of an unsupported subsystem');
hilite_system('inc_enc_v26/IncEnc_V26/AB-Line-Switch', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/AB-Line-Switch', 0, 1, 'Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/Check d-Axis-Hit', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Check d-Axis-Hit', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of an unsupported subsystem');
hilite_system('inc_enc_v26/IncEnc_V26/Check d-Axis-Hit', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/Check d-Axis-Hit', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/Check d-Axis-Hit_WithCompare', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Check d-Axis-Hit_WithCompare', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of an unsupported subsystem');
hilite_system('inc_enc_v26/IncEnc_V26/Check d-Axis-Hit_WithCompare', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/Check d-Axis-Hit_WithCompare', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/Counter', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Counter', 0, 1, 'Delays not moved into or out of an unsupported subsystem');
hilite_system('inc_enc_v26/IncEnc_V26/Counter', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/Counter', 0, 1, 'Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/Counter_Theta_el_wOffset', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Counter_Theta_el_wOffset', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of a shared subsystem');
hilite_system('inc_enc_v26/IncEnc_V26/Counter_Theta_el_wOffset', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/Counter_Theta_el_wOffset', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of a shared subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/Counter_position', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Counter_position', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of an unsupported subsystem');
hilite_system('inc_enc_v26/IncEnc_V26/Counter_position', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/Counter_position', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/Counter_position_wOffset', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Counter_position_wOffset', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of a shared subsystem');
hilite_system('inc_enc_v26/IncEnc_V26/Counter_position_wOffset', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/Counter_position_wOffset', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of a shared subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/Direction', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Direction', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of an unsupported subsystem');
hilite_system('inc_enc_v26/IncEnc_V26/Direction', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/Direction', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/Index_Latch', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Index_Latch', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of an unsupported subsystem');
hilite_system('inc_enc_v26/IncEnc_V26/Index_Latch', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/Index_Latch', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/count_lines', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/count_lines', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of an unsupported subsystem');
hilite_system('inc_enc_v26/IncEnc_V26/count_lines', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/count_lines', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/digital_filter', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of an unsupported subsystem');
hilite_system('inc_enc_v26/IncEnc_V26/digital_filter', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/digital_filter1', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter1', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of an unsupported subsystem');
hilite_system('inc_enc_v26/IncEnc_V26/digital_filter1', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter1', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/digital_filter2', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter2', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of an unsupported subsystem');
hilite_system('inc_enc_v26/IncEnc_V26/digital_filter2', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter2', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/speed1', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1', 0, 1, 'Delays not moved across due to non-zero or unknown initial value, Delays not moved into or out of an unsupported subsystem');
hilite_system('inc_enc_v26/IncEnc_V26/speed1', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/speed1', 0, 1, 'Delays not moved across due to non-zero or unknown initial value, Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/Check d-Axis-Hit/Equal', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Check d-Axis-Hit/Equal', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/Check d-Axis-Hit/Equal', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/Check d-Axis-Hit/Equal', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/Check d-Axis-Hit/Equal1', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Check d-Axis-Hit/Equal1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/Check d-Axis-Hit/Equal1', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/Check d-Axis-Hit/Equal1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/Check d-Axis-Hit_WithCompare/Equal', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Check d-Axis-Hit_WithCompare/Equal', 0, 1, 'Internal limitation');
hilite_system('inc_enc_v26/IncEnc_V26/Check d-Axis-Hit_WithCompare/Equal', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/Check d-Axis-Hit_WithCompare/Equal', 0, 1, 'Internal limitation');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/Check d-Axis-Hit_WithCompare/Equal', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Check d-Axis-Hit_WithCompare/Equal', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/Check d-Axis-Hit_WithCompare/Equal', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/Check d-Axis-Hit_WithCompare/Equal', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/Counter_Theta_el_wOffset/Constant2', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Counter_Theta_el_wOffset/Constant2', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/Counter_Theta_el_wOffset/Constant2', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/Counter_Theta_el_wOffset/Constant2', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/Counter_Theta_el_wOffset/Constant5', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Counter_Theta_el_wOffset/Constant5', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/Counter_Theta_el_wOffset/Constant5', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/Counter_Theta_el_wOffset/Constant5', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/Counter_Theta_el_wOffset/Relational Operator1', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Counter_Theta_el_wOffset/Relational Operator1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/Counter_Theta_el_wOffset/Relational Operator1', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/Counter_Theta_el_wOffset/Relational Operator1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/Counter_position/Constant2', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Counter_position/Constant2', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/Counter_position/Constant2', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/Counter_position/Constant2', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/Counter_position/Constant5', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Counter_position/Constant5', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/Counter_position/Constant5', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/Counter_position/Constant5', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/Counter_position/Relational Operator1', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Counter_position/Relational Operator1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/Counter_position/Relational Operator1', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/Counter_position/Relational Operator1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/Direction/TurnLeft', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Direction/TurnLeft', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/Direction/TurnLeft', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/Direction/TurnLeft', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/Direction/TurnRight', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Direction/TurnRight', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/Direction/TurnRight', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/Direction/TurnRight', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/Index_Latch/Constant', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/Index_Latch/Constant', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/Index_Latch/Constant', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/Index_Latch/Constant', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/count_lines/Constant2', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/count_lines/Constant2', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/count_lines/Constant2', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/count_lines/Constant2', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/count_lines/Constant4', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/count_lines/Constant4', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/count_lines/Constant4', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/count_lines/Constant4', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/digital_filter/Subsystem1', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter/Subsystem1', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of an unsupported subsystem');
hilite_system('inc_enc_v26/IncEnc_V26/digital_filter/Subsystem1', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter/Subsystem1', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/digital_filter/NOT', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter/NOT', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/digital_filter/NOT', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter/NOT', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/digital_filter/NOT1', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter/NOT1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/digital_filter/NOT1', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter/NOT1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/digital_filter/NOT2', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter/NOT2', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/digital_filter/NOT2', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter/NOT2', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/digital_filter/Subsystem1/AND1', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter/Subsystem1/AND1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/digital_filter/Subsystem1/AND1', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter/Subsystem1/AND1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/digital_filter/Subsystem1/AND', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter/Subsystem1/AND', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/digital_filter/Subsystem1/AND', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter/Subsystem1/AND', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/digital_filter1/Subsystem1', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter1/Subsystem1', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of an unsupported subsystem');
hilite_system('inc_enc_v26/IncEnc_V26/digital_filter1/Subsystem1', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter1/Subsystem1', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/digital_filter1/NOT', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter1/NOT', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/digital_filter1/NOT', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter1/NOT', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/digital_filter1/NOT1', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter1/NOT1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/digital_filter1/NOT1', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter1/NOT1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/digital_filter1/NOT2', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter1/NOT2', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/digital_filter1/NOT2', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter1/NOT2', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/digital_filter1/Subsystem1/AND1', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter1/Subsystem1/AND1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/digital_filter1/Subsystem1/AND1', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter1/Subsystem1/AND1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/digital_filter1/Subsystem1/AND', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter1/Subsystem1/AND', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/digital_filter1/Subsystem1/AND', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter1/Subsystem1/AND', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/digital_filter2/Subsystem1', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter2/Subsystem1', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of an unsupported subsystem');
hilite_system('inc_enc_v26/IncEnc_V26/digital_filter2/Subsystem1', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter2/Subsystem1', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/digital_filter2/NOT', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter2/NOT', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/digital_filter2/NOT', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter2/NOT', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/digital_filter2/NOT1', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter2/NOT1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/digital_filter2/NOT1', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter2/NOT1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/digital_filter2/NOT2', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter2/NOT2', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/digital_filter2/NOT2', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter2/NOT2', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/digital_filter2/Subsystem1/AND1', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter2/Subsystem1/AND1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/digital_filter2/Subsystem1/AND1', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter2/Subsystem1/AND1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/digital_filter2/Subsystem1/AND', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/digital_filter2/Subsystem1/AND', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/digital_filter2/Subsystem1/AND', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/digital_filter2/Subsystem1/AND', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/speed1/Logical1', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/Logical1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/speed1/Logical1', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/Logical1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/speed1/Logical2', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/Logical2', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/speed1/Logical2', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/Logical2', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance4', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance4', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of a shared subsystem');
hilite_system('inc_enc_v26/IncEnc_V26/speed1/calc_omega', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/calc_omega', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of a shared subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance3', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance3', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of a shared subsystem');
hilite_system('inc_enc_v26/IncEnc_V26/speed1/calc_omega', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/calc_omega', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of a shared subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance2', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance2', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of a shared subsystem');
hilite_system('inc_enc_v26/IncEnc_V26/speed1/calc_omega', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/calc_omega', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of a shared subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic', 0, 1, 'Delays not moved across due to non-zero or unknown initial value, Delays not moved into or out of an unsupported subsystem');
hilite_system('inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic', 0, 1, 'Delays not moved across due to non-zero or unknown initial value, Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance1', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance1', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of a shared subsystem');
hilite_system('inc_enc_v26/IncEnc_V26/speed1/calc_omega', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/calc_omega', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of a shared subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/speed1/Average', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/Average', 0, 1, 'Delays not moved into or out of an unsupported subsystem');
hilite_system('inc_enc_v26/IncEnc_V26/speed1/Average', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/Average', 0, 1, 'Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/align_oversamples', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/align_oversamples', 0, 1, 'Delays not moved across due to non-zero or unknown initial value, Delays not moved into or out of a subsystem because DistributedPipelining=off');
hilite_system('inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/align_oversamples', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/align_oversamples', 0, 1, 'Delays not moved across due to non-zero or unknown initial value, Delays not moved into or out of a subsystem because DistributedPipelining=off');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/oversample_factor', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/oversample_factor', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of a subsystem because DistributedPipelining=off');
hilite_system('inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/oversample_factor', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/oversample_factor', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of a subsystem because DistributedPipelining=off');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/Delay7_Initial_Val', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/Delay7_Initial_Val', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/Delay7_ctrl_const', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/Delay7_ctrl_const', 0, 1, 'Delays not moved across an unsupported block');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance4/invt_mult', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance4/invt_mult', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of an unsupported subsystem');
hilite_system('inc_enc_v26/IncEnc_V26/speed1/calc_omega/invt_mult', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/calc_omega/invt_mult', 0, 1, 'Delays not moved across due to potential numerical mismatch, Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance4/Constant4', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance4/Constant4', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/speed1/calc_omega/Constant4', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/calc_omega/Constant4', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance4/step_value', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance4/step_value', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/speed1/calc_omega/32bit counter', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/calc_omega/32bit counter', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance4/const', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance4/const', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/speed1/calc_omega/32bit counter', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/calc_omega/32bit counter', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance4/Relational Operator', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance4/Relational Operator', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/speed1/calc_omega/Relational Operator', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/calc_omega/Relational Operator', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance4/invt_mult/HDL Reciprocal', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/calc_omega_instance4/invt_mult/HDL Reciprocal', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('inc_enc_v26/IncEnc_V26/speed1/calc_omega/invt_mult/HDL Reciprocal', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/calc_omega/invt_mult/HDL Reciprocal', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/align_oversamples/align_oversamples', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/align_oversamples/align_oversamples', 0, 1, 'Delays not moved across an unsupported block');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/align_oversamples/align_oversamples', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/align_oversamples/align_oversamples', 0, 1, 'Delays not moved across an unsupported block');
hilite_system('inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/align_oversamples', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/align_oversamples', 0, 1, 'Delays not moved across an unsupported block');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/oversample_factor/oversample_factor', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/oversample_factor/oversample_factor', 0, 1, 'Delays not moved across an unsupported block');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/oversample_factor/oversample_factor', 'user1');
annotate_port('gm_inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/oversample_factor/oversample_factor', 0, 1, 'Delays not moved across an unsupported block');
hilite_system('inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/oversample_factor', 'user1');
annotate_port('inc_enc_v26/IncEnc_V26/speed1/OS_factor_logic/oversample_factor', 0, 1, 'Delays not moved across an unsupported block');
