vlib work
vcom  IncEnc_src_IncEnc_V25_pac.vhd
vcom  IncEnc_src_Check_d_Axis_Hit.vhd
vcom  IncEnc_src_Counter.vhd
vcom  IncEnc_src_Counter_Theta_el_wOffset.vhd
vcom  IncEnc_src_Counter_position.vhd
vcom  IncEnc_src_Direction.vhd
vcom  IncEnc_src_Index_Latch.vhd
vcom  IncEnc_src_count_lines.vhd
vcom  IncEnc_src_align_oversamples.vhd
vcom  IncEnc_src_oversample_factor.vhd
vcom  IncEnc_src_OS_factor_logic.vhd
vcom  IncEnc_src_Average.vhd
vcom  IncEnc_src_Math_Reciprocal_core.vhd
vcom  IncEnc_src_Math_Reciprocal.vhd
vcom  IncEnc_src_invt_mult.vhd
vcom  IncEnc_src_calc_omega.vhd
vcom  IncEnc_src_speed.vhd
vcom  IncEnc_src_IncEnc_V25.vhd
