open_system('gm_uz_d_inverter_adapter');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1', 'user2');
annotate_port('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1', 0, 1, 'cp : 3.31 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance6/Detect Rise Positive1', 'user2');
annotate_port('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance6/Detect Rise Positive1', 0, 1, 'cp : 1.704 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance6/Delay15', 'user1');
annotate_port('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance6/Delay15', 0, 1, 'cp : 0.33 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance6/Logical Operator3', 'user2');
annotate_port('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance6/Logical Operator3', 0, 1, 'cp : 2.697 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/Detect Rise Positive1/Positive', 'user2');
annotate_port('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/Detect Rise Positive1/Positive', 0, 1, 'cp : 1.017 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/Detect Rise Positive1/FixPt Relational Operator', 'user2');
annotate_port('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/Detect Rise Positive1/FixPt Relational Operator', 0, 1, 'cp : 1.704 ns');
