open_system('uz_d_inverter_adapter');
open_system('gm_uz_d_inverter_adapter');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/Delay', 'user2');
annotate_port('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/Delay', 1, 1, 'Block not characterized');
hilite_system('uz_d_inverter_adapter/uz_d_inverter_adapter/Delay', 'user2');
annotate_port('uz_d_inverter_adapter/uz_d_inverter_adapter/Delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/Delay1', 'user2');
annotate_port('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/Delay1', 1, 1, 'Block not characterized');
hilite_system('uz_d_inverter_adapter/uz_d_inverter_adapter/Delay1', 'user2');
annotate_port('uz_d_inverter_adapter/uz_d_inverter_adapter/Delay1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/Delay2', 'user2');
annotate_port('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/Delay2', 1, 1, 'Block not characterized');
hilite_system('uz_d_inverter_adapter/uz_d_inverter_adapter/Delay2', 'user2');
annotate_port('uz_d_inverter_adapter/uz_d_inverter_adapter/Delay2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/Delay3', 'user2');
annotate_port('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/Delay3', 1, 1, 'Block not characterized');
hilite_system('uz_d_inverter_adapter/uz_d_inverter_adapter/Delay3', 'user2');
annotate_port('uz_d_inverter_adapter/uz_d_inverter_adapter/Delay3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/Delay4', 'user2');
annotate_port('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/Delay4', 1, 1, 'Block not characterized');
hilite_system('uz_d_inverter_adapter/uz_d_inverter_adapter/Delay4', 'user2');
annotate_port('uz_d_inverter_adapter/uz_d_inverter_adapter/Delay4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/delayMatch', 'user2');
annotate_port('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/delayMatch', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/delayMatch1', 'user2');
annotate_port('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/delayMatch1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/delayMatch2', 'user2');
annotate_port('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/delayMatch2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/delayMatch3', 'user2');
annotate_port('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/delayMatch3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/Detect Rise Positive1', 'user2');
annotate_port('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/Detect Rise Positive1', 1, 1, 'Block not characterized');
hilite_system('uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection/Detect Rise Positive1', 'user2');
annotate_port('uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection/Detect Rise Positive1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/Detect Fall Nonpositive1', 'user2');
annotate_port('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/Detect Fall Nonpositive1', 1, 1, 'Block not characterized');
hilite_system('uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection/Detect Fall Nonpositive1', 'user2');
annotate_port('uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection/Detect Fall Nonpositive1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/Delay15', 'user2');
annotate_port('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/Delay15', 1, 1, 'Block not characterized');
hilite_system('uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection/Delay15', 'user2');
annotate_port('uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection/Delay15', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/Delay14', 'user2');
annotate_port('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/Delay14', 1, 1, 'Block not characterized');
hilite_system('uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection/Delay14', 'user2');
annotate_port('uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection/Delay14', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/Delay13', 'user2');
annotate_port('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/Delay13', 1, 1, 'Block not characterized');
hilite_system('uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection/Delay13', 'user2');
annotate_port('uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection/Delay13', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/Delay12', 'user2');
annotate_port('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/Delay12', 1, 1, 'Block not characterized');
hilite_system('uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection/Delay12', 'user2');
annotate_port('uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection/Delay12', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/Delay10', 'user2');
annotate_port('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/Delay10', 1, 1, 'Block not characterized');
hilite_system('uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection/Delay10', 'user2');
annotate_port('uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection/Delay10', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection/Reciprocal', 'user2');
annotate_port('uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection/Reciprocal', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/Reciprocal', 'user2');
annotate_port('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/Reciprocal', 1, 1, 'Block not characterized');
hilite_system('uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection/Reciprocal', 'user2');
annotate_port('uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection/Reciprocal', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/Delay9', 'user2');
annotate_port('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/Delay9', 1, 1, 'Block not characterized');
hilite_system('uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection/Delay9', 'user2');
annotate_port('uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection/Delay9', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/Delay11', 'user2');
annotate_port('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/Delay11', 1, 1, 'Block not characterized');
hilite_system('uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection/Delay11', 'user2');
annotate_port('uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection/Delay11', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/delayMatch', 'user2');
annotate_port('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/delayMatch', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/delayMatch1', 'user2');
annotate_port('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/delayMatch1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/delayMatch2', 'user2');
annotate_port('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/delayMatch2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/delayMatch3', 'user2');
annotate_port('gm_uz_d_inverter_adapter/uz_d_inverter_adapter/PWMdutyFreqDetection_instance1/delayMatch3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
