vlib work
vcom  uz_d_inverter_adapter_src_uz_d_inverter_adapter_pkg.vhd
vcom  uz_d_inverter_adapter_src_Detect_Rise_Positive1.vhd
vcom  uz_d_inverter_adapter_src_Detect_Fall_Nonpositive1.vhd
vcom  uz_d_inverter_adapter_src_PWMdutyFreqDetection.vhd
vcom  uz_d_inverter_adapter_src_uz_d_inverter_adapter.vhd
