open_system('gm_uz_JL_pmsmModel');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_pmsmModel/uz_JL_pmsmModel/Elektrik', 'user2');
annotate_port('gm_uz_JL_pmsmModel/uz_JL_pmsmModel/Elektrik', 0, 1, 'cp : 3.634 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_pmsmModel/uz_JL_pmsmModel/Elektrik/abc -> dq', 'user2');
annotate_port('gm_uz_JL_pmsmModel/uz_JL_pmsmModel/Elektrik/abc -> dq', 0, 1, 'cp : 3.634 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_pmsmModel/uz_JL_pmsmModel/Elektrik/abc -> dq/Clark Transformation', 'user2');
annotate_port('gm_uz_JL_pmsmModel/uz_JL_pmsmModel/Elektrik/abc -> dq/Clark Transformation', 0, 1, 'cp : 3.634 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_pmsmModel/uz_JL_pmsmModel/Elektrik/abc -> dq/Clark Transformation/Gain', 'user1');
annotate_port('gm_uz_JL_pmsmModel/uz_JL_pmsmModel/Elektrik/abc -> dq/Clark Transformation/Gain', 0, 1, 'cp : 3.634 ns');
