open_system('gm_uz_JL_pmsmModel');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_pmsmModel/uz_JL_pmsmModel/Mechanik', 'user2');
annotate_port('gm_uz_JL_pmsmModel/uz_JL_pmsmModel/Mechanik', 0, 1, 'cp : 3.634 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_pmsmModel/uz_JL_pmsmModel/Mechanik/Drehmomentberechnung', 'user2');
annotate_port('gm_uz_JL_pmsmModel/uz_JL_pmsmModel/Mechanik/Drehmomentberechnung', 0, 1, 'cp : 3.634 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_pmsmModel/uz_JL_pmsmModel/Mechanik/Drehmomentberechnung/Prduct_3', 'user1');
annotate_port('gm_uz_JL_pmsmModel/uz_JL_pmsmModel/Mechanik/Drehmomentberechnung/Prduct_3', 0, 1, 'cp : 3.634 ns');
