open_system('uz_JL_pmsmModel');
open_system('gm_uz_JL_pmsmModel');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_pmsmModel/uz_JL_pmsmModel/Elektrik/Delay', 'user5');
hilite_system('uz_JL_pmsmModel/uz_JL_pmsmModel/Elektrik/Delay', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_pmsmModel/uz_JL_pmsmModel/Elektrik/Delay_absorbed', 'user5');
hilite_system('uz_JL_pmsmModel/uz_JL_pmsmModel/Elektrik/Delay', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_pmsmModel/uz_JL_pmsmModel/Mechanik/Subsystem1', 'user5');
hilite_system('uz_JL_pmsmModel/uz_JL_pmsmModel/Mechanik/Subsystem1', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_pmsmModel/uz_JL_pmsmModel/Mechanik/Drehmomentberechnung/Product1', 'user5');
hilite_system('uz_JL_pmsmModel/uz_JL_pmsmModel/Mechanik/Drehmomentberechnung/Product1', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_pmsmModel/uz_JL_pmsmModel/Mechanik/Drehmomentberechnung/Product2', 'user5');
hilite_system('uz_JL_pmsmModel/uz_JL_pmsmModel/Mechanik/Drehmomentberechnung/Product2', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_pmsmModel/uz_JL_pmsmModel/Mechanik/Drehmomentberechnung/Subtract1', 'user5');
hilite_system('uz_JL_pmsmModel/uz_JL_pmsmModel/Mechanik/Drehmomentberechnung/Subtract1', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_pmsmModel/uz_JL_pmsmModel/Mechanik/Drehmomentberechnung/Gain', 'user5');
hilite_system('uz_JL_pmsmModel/uz_JL_pmsmModel/Mechanik/Drehmomentberechnung/Gain', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_pmsmModel/uz_JL_pmsmModel/Mechanik/Drehmomentberechnung/delayMatch2', 'user5');
