-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\jonat\Documents\MA_JL_CIL\ip_cores\uz_JL_pmsmModel\hdl_prj\hdlsrc\uz_JL_pmsmModel\uz_JL_pmsmModel_src_Elektrik.vhd
-- Created: 2026-05-04 17:47:42
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: uz_JL_pmsmModel_src_Elektrik
-- Source Path: uz_JL_pmsmModel/uz_JL_pmsmModel/Elektrik
-- Hierarchy Level: 1
-- Model version: 1.50
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.uz_JL_pmsmModel_src_uz_JL_pmsmModel_pkg.ALL;

ENTITY uz_JL_pmsmModel_src_Elektrik IS
  PORT( clk                               :   IN    std_logic;
        reset_x                           :   IN    std_logic;
        enb                               :   IN    std_logic;
        enb_1_81_1                        :   IN    std_logic;
        enb_1_81_0                        :   IN    std_logic;
        Uuvw                              :   IN    vector_of_std_logic_vector32(0 TO 2);  -- single [3]
        Omega1                            :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        theta                             :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        mot_R1                            :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        psi_pm                            :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        mot_Ld                            :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        mot_Lq                            :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        Iu                                :   OUT   std_logic_vector(31 DOWNTO 0);  -- single
        Iv                                :   OUT   std_logic_vector(31 DOWNTO 0);  -- single
        Iw                                :   OUT   std_logic_vector(31 DOWNTO 0);  -- single
        Id                                :   OUT   std_logic_vector(31 DOWNTO 0);  -- single
        Iq                                :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
        );
END uz_JL_pmsmModel_src_Elektrik;


ARCHITECTURE rtl OF uz_JL_pmsmModel_src_Elektrik IS

  -- Component Declarations
  COMPONENT uz_JL_pmsmModel_src_abc_dq
    PORT( clk                             :   IN    std_logic;
          reset_x                         :   IN    std_logic;
          enb                             :   IN    std_logic;
          theta                           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          valU                            :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          valV                            :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          valW                            :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          Ud_Motor                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- single
          Uq_Motor                        :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
          );
  END COMPONENT;

  COMPONENT uz_JL_pmsmModel_src_Psi
    PORT( clk                             :   IN    std_logic;
          reset_x                         :   IN    std_logic;
          enb                             :   IN    std_logic;
          enb_1_81_1                      :   IN    std_logic;
          enb_1_81_0                      :   IN    std_logic;
          Ud                              :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          Uq                              :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          Id                              :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          Iq                              :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          omega1                          :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          mot_R1                          :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          psi_pm                          :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          PsiD                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- single
          PsiQ                            :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
          );
  END COMPONENT;

  COMPONENT uz_JL_pmsmModel_src_Subsystem2
    PORT( clk                             :   IN    std_logic;
          reset_x                         :   IN    std_logic;
          enb                             :   IN    std_logic;
          PsiD                            :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          PsiQ                            :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          psi_pm                          :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          rec_mot_Ld                      :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          rec_mot_Lq                      :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          Id                              :   OUT   std_logic_vector(31 DOWNTO 0);  -- single
          Iq                              :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
          );
  END COMPONENT;

  COMPONENT uz_JL_pmsmModel_src_dq_abc
    PORT( clk                             :   IN    std_logic;
          reset_x                         :   IN    std_logic;
          enb                             :   IN    std_logic;
          theta                           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          Id_Motor                        :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          Iq_Motor                        :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          valU                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- single
          valV                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- single
          valW                            :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : uz_JL_pmsmModel_src_abc_dq
    USE ENTITY work.uz_JL_pmsmModel_src_abc_dq(rtl);

  FOR ALL : uz_JL_pmsmModel_src_Psi
    USE ENTITY work.uz_JL_pmsmModel_src_Psi(rtl);

  FOR ALL : uz_JL_pmsmModel_src_Subsystem2
    USE ENTITY work.uz_JL_pmsmModel_src_Subsystem2(rtl);

  FOR ALL : uz_JL_pmsmModel_src_dq_abc
    USE ENTITY work.uz_JL_pmsmModel_src_dq_abc(rtl);

  -- Signals
  SIGNAL mot_Uuvw                         : vector_of_std_logic_vector32(0 TO 2);  -- ufix32 [3]
  SIGNAL mot_Uuvw_1                       : vector_of_std_logic_vector32(0 TO 2);  -- ufix32 [3]
  SIGNAL mot_U                            : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL mot_V                            : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL mot_W                            : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL abc_dq_Ud_Motor                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL abc_dq_Uq_Motor                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Iq_Motor                         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Iq_Motor_1                       : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Delay_bypass_reg                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Delay_out1                       : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Id_Motor                         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Delay1_bypass_reg                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Delay1_out1                      : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Psi_PsiD                         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Psi_PsiQ                         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dq_abc_valU                      : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dq_abc_valV                      : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dq_abc_valW                      : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_abc_dq : uz_JL_pmsmModel_src_abc_dq
    PORT MAP( clk => clk,
              reset_x => reset_x,
              enb => enb,
              theta => theta,  -- single
              valU => mot_U,  -- single
              valV => mot_V,  -- single
              valW => mot_W,  -- single
              Ud_Motor => abc_dq_Ud_Motor,  -- single
              Uq_Motor => abc_dq_Uq_Motor  -- single
              );

  u_Psi : uz_JL_pmsmModel_src_Psi
    PORT MAP( clk => clk,
              reset_x => reset_x,
              enb => enb,
              enb_1_81_1 => enb_1_81_1,
              enb_1_81_0 => enb_1_81_0,
              Ud => abc_dq_Ud_Motor,  -- single
              Uq => abc_dq_Uq_Motor,  -- single
              Id => Delay1_out1,  -- single
              Iq => Delay_out1,  -- single
              omega1 => Omega1,  -- single
              mot_R1 => mot_R1,  -- single
              psi_pm => psi_pm,  -- single
              PsiD => Psi_PsiD,  -- single
              PsiQ => Psi_PsiQ  -- single
              );

  u_Subsystem2 : uz_JL_pmsmModel_src_Subsystem2
    PORT MAP( clk => clk,
              reset_x => reset_x,
              enb => enb,
              PsiD => Psi_PsiD,  -- single
              PsiQ => Psi_PsiQ,  -- single
              psi_pm => psi_pm,  -- single
              rec_mot_Ld => mot_Ld,  -- single
              rec_mot_Lq => mot_Lq,  -- single
              Id => Id_Motor,  -- single
              Iq => Iq_Motor  -- single
              );

  u_dq_abc : uz_JL_pmsmModel_src_dq_abc
    PORT MAP( clk => clk,
              reset_x => reset_x,
              enb => enb,
              theta => theta,  -- single
              Id_Motor => Id_Motor,  -- single
              Iq_Motor => Iq_Motor,  -- single
              valU => dq_abc_valU,  -- single
              valV => dq_abc_valV,  -- single
              valW => dq_abc_valW  -- single
              );

  mot_Uuvw <= Uuvw;

  mot_Uuvw_1 <= mot_Uuvw;

  mot_U <= mot_Uuvw_1(0);

  mot_V <= mot_Uuvw_1(1);

  mot_W <= mot_Uuvw_1(2);

  crp_out_delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Iq_Motor_1 <= X"00000000";
      ELSIF enb = '1' THEN
        Iq_Motor_1 <= Iq_Motor;
      END IF;
    END IF;
  END PROCESS crp_out_delay_process;


  Delay_bypass_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Delay_bypass_reg <= X"00000000";
      ELSIF enb_1_81_1 = '1' THEN
        Delay_bypass_reg <= Iq_Motor_1;
      END IF;
    END IF;
  END PROCESS Delay_bypass_process;

  
  Delay_out1 <= Iq_Motor_1 WHEN enb_1_81_1 = '1' ELSE
      Delay_bypass_reg;

  Delay1_bypass_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Delay1_bypass_reg <= X"00000000";
      ELSIF enb_1_81_1 = '1' THEN
        Delay1_bypass_reg <= Id_Motor;
      END IF;
    END IF;
  END PROCESS Delay1_bypass_process;

  
  Delay1_out1 <= Id_Motor WHEN enb_1_81_1 = '1' ELSE
      Delay1_bypass_reg;

  Iu <= dq_abc_valU;

  Iv <= dq_abc_valV;

  Iw <= dq_abc_valW;

  Id <= Delay1_out1;

  Iq <= Delay_out1;

END rtl;

