-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\jonat\Documents\MA_JL_CIL\ip_cores\uz_JL_pmsmModel\hdl_prj\hdlsrc\uz_JL_pmsmModel\uz_JL_pmsmModel_dut.vhd
-- Created: 2026-05-15 13:51:45
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: uz_JL_pmsmModel_dut
-- Source Path: uz_JL_pmsmModel/uz_JL_pmsmModel_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY uz_JL_pmsmModel_dut IS
  PORT( clk                               :   IN    std_logic;
        reset_x                           :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        mot_U                             :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        mot_V                             :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        mot_W                             :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        Bremse                            :   IN    std_logic;  -- ufix1
        Last_M                            :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        Last_J                            :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        Ud                                :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        switchUabc_dq                     :   IN    std_logic;  -- ufix1
        r1                                :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        psi_pm                            :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        Ld                                :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        Lq                                :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        polpaare                          :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        mot_J                             :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        Uq                                :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        rec_mot_Ld                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        rec_mot_Lq                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        ce_out                            :   OUT   std_logic;  -- ufix1
        omega_mech                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        phi_mech                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        pmsm_M_Mot                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        pmsm_Iu                           :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        pmsm_Iv                           :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        pmsm_Iw                           :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
        );
END uz_JL_pmsmModel_dut;


ARCHITECTURE rtl OF uz_JL_pmsmModel_dut IS

  -- Component Declarations
  COMPONENT uz_JL_pmsmModel_src_uz_JL_pmsmModel
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset_x                         :   IN    std_logic;
          mot_U                           :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          mot_V                           :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          mot_W                           :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          Bremse                          :   IN    std_logic;  -- ufix1
          Last_M                          :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          Last_J                          :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          Ud                              :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          switchUabc_dq                   :   IN    std_logic;  -- ufix1
          r1                              :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          psi_pm                          :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          Ld                              :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          Lq                              :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          polpaare                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          mot_J                           :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          Uq                              :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          rec_mot_Ld                      :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          rec_mot_Lq                      :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          ce_out                          :   OUT   std_logic;  -- ufix1
          omega_mech                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          phi_mech                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          pmsm_M_Mot                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          pmsm_Iu                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          pmsm_Iv                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          pmsm_Iw                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : uz_JL_pmsmModel_src_uz_JL_pmsmModel
    USE ENTITY work.uz_JL_pmsmModel_src_uz_JL_pmsmModel(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL omega_mech_sig                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL phi_mech_sig                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL pmsm_M_Mot_sig                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL pmsm_Iu_sig                      : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL pmsm_Iv_sig                      : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL pmsm_Iw_sig                      : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_uz_JL_pmsmModel_src_uz_JL_pmsmModel : uz_JL_pmsmModel_src_uz_JL_pmsmModel
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset_x => reset_x,
              mot_U => mot_U,  -- ufix32
              mot_V => mot_V,  -- ufix32
              mot_W => mot_W,  -- ufix32
              Bremse => Bremse,  -- ufix1
              Last_M => Last_M,  -- ufix32
              Last_J => Last_J,  -- ufix32
              Ud => Ud,  -- ufix32
              switchUabc_dq => switchUabc_dq,  -- ufix1
              r1 => r1,  -- ufix32
              psi_pm => psi_pm,  -- ufix32
              Ld => Ld,  -- ufix32
              Lq => Lq,  -- ufix32
              polpaare => polpaare,  -- ufix32
              mot_J => mot_J,  -- ufix32
              Uq => Uq,  -- ufix32
              rec_mot_Ld => rec_mot_Ld,  -- ufix32
              rec_mot_Lq => rec_mot_Lq,  -- ufix32
              ce_out => ce_out_sig,  -- ufix1
              omega_mech => omega_mech_sig,  -- ufix32
              phi_mech => phi_mech_sig,  -- ufix32
              pmsm_M_Mot => pmsm_M_Mot_sig,  -- ufix32
              pmsm_Iu => pmsm_Iu_sig,  -- ufix32
              pmsm_Iv => pmsm_Iv_sig,  -- ufix32
              pmsm_Iw => pmsm_Iw_sig  -- ufix32
              );

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  omega_mech <= omega_mech_sig;

  phi_mech <= phi_mech_sig;

  pmsm_M_Mot <= pmsm_M_Mot_sig;

  pmsm_Iu <= pmsm_Iu_sig;

  pmsm_Iv <= pmsm_Iv_sig;

  pmsm_Iw <= pmsm_Iw_sig;

END rtl;

