SLStudio.Utils.RemoveHighlighting(get_param('uz_ssi_interface_2025b', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_uz_ssi_interface_2025b', 'handle'));
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/Gray_code_to_binary', 1, 3, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication', 0, 6, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/Delay32', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/From1', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/From8', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/Goto1', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/Goto17', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/FixPt Relational Operator1', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/Positive1', 0, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/S-R Flip-Flop1', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/S-R Flip-Flop1', 1, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/S-R Flip-Flop1', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/Switch5', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/Gray_code_to_binary/gray_to_bin', 1, 2, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/FixPt Relational Operator', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/Positive', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/shift arithmetic', 1, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/Shift Arithmetic', 1, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/S-R Flip-Flop', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/S-R Flip-Flop', 1, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/S-R Flip-Flop', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/Switch', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/Bitwise OR1', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/Switch3', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/Delay2', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay1', 0, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay1', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay1', 0, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay1', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay13', 0, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay13', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay14', 0, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay14', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay6', 0, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay6', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay7', 0, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay7', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay8', 0, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay8', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay18', 0, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay18', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay2', 0, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay2', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay5', 0, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay5', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay3', 0, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay3', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay4', 0, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay4', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay9', 0, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay9', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay', 0, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay10', 0, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay10', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/fixed_point_floor', 0, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/fixed_point_floor', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/fixed_point_floor', 1, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/fixed_point_floor', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay20', 0, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay20', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay21', 0, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay21', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay19', 0, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay19', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay11', 0, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay11', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay12', 0, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay12', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay22', 0, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay22', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay23', 0, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay23', 0, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/set_offset_to_raw_position_and_wrap/Shift Arithmetic2', 1, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/set_offset_to_raw_position_and_wrap/Shift Arithmetic3', 1, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/set_offset_to_raw_position_and_wrap/floor_div_pow2/Shift Arithmetic4', 1, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/set_offset_to_raw_position_and_wrap/floor_div_pow2/Shift Arithmetic5', 1, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/slice_position_and_status/Shift Arithmetic', 1, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/slice_position_and_status/Shift Arithmetic1', 1, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/slice_position_and_status/Shift Arithmetic2', 1, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/slice_position_and_status/Shift Arithmetic3', 1, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/slice_position_and_status/Shift Arithmetic4', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/From', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/FixPt Relational Operator', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/Positive', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/NOT', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/From7', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/Goto7', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/ssi_clock_enable_for_n_bits', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/Goto', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/clk_idle_and_delay_first_clock_function', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/clk_idle_and_delay_first_clock_function/Switch3', 0, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/clk_idle_and_delay_first_clock_function/S-R Flip-Flop', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/clk_idle_and_delay_first_clock_function/S-R Flip-Flop', 1, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/clk_idle_and_delay_first_clock_function/S-R Flip-Flop', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/sample_serial_ssi_data/Bitwise Operator1', 1, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/sample_serial_ssi_data/Bitwise Operator1', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/sample_serial_ssi_data/shift arithmetic', 1, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/sample_serial_ssi_data/Shift Arithmetic', 1, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/ssi_clock_enable_for_n_bits/S-R Flip-Flop', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/ssi_clock_enable_for_n_bits/S-R Flip-Flop', 1, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/ssi_clock_enable_for_n_bits/S-R Flip-Flop', 1, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/ssi_clock_generator/S-R Flip-Flop1', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/ssi_clock_generator/S-R Flip-Flop1', 1, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/ssi_clock_generator/S-R Flip-Flop1', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/wrap_2pi/fixed_point_floor', 0, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/wrap_2pi/fixed_point_floor', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/wrap_2pi/fixed_point_floor', 1, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/wrap_2pi/fixed_point_floor', 1, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized/sincos hdl/cos_hdl/Look-Up Table', 1, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized/sincos hdl/cos_hdl/Look-Up Table', 1, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized/sincos hdl/sin_hdl/Look-Up Table', 1, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized/sincos hdl/sin_hdl/Look-Up Table', 1, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/cos_hdl/Look-Up Table', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/cos_hdl/Look-Up Table/Look-Up Table', 0, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/cos_hdl/Look-Up Table', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/cos_hdl/Look-Up Table/Look-Up Table', 1, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/cos_hdl/Look-Up Table', 1, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/Look-Up Table', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/Look-Up Table/Look-Up Table', 0, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/Look-Up Table', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/Look-Up Table/Look-Up Table', 1, 1, '');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/Look-Up Table', 1, 1, '');
