open_system('gm_uz_ssi_interface_2025b');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/Gray_code_to_binary', 'user2');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/Gray_code_to_binary', 1, 3, 'cp : 6.699 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication', 'user2');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication', 0, 6, 'cp : 4.066 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/Delay32', 'user1');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/Delay32', 0, 1, 'cp : 0.33 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/From1', 'user2');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/From1', 0, 1, 'cp : 2.056 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/From8', 'user2');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/From8', 0, 1, 'cp : 4.066 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/Goto1', 'user2');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/Goto1', 0, 1, 'cp : 2.056 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/Goto17', 'user2');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/Goto17', 0, 1, 'cp : 4.066 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/FixPt Relational Operator1', 'user2');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/FixPt Relational Operator1', 0, 1, 'cp : 1.704 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/Positive1', 'user2');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/Positive1', 0, 1, 'cp : 1.017 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/Switch5', 'user2');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/Switch5', 0, 1, 'cp : 2.056 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/Gray_code_to_binary/gray_to_bin', 'user2');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/Gray_code_to_binary/gray_to_bin', 1, 2, 'cp : 6.699 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/FixPt Relational Operator', 'user2');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/FixPt Relational Operator', 0, 1, 'cp : 5.44 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/Positive', 'user2');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/Positive', 0, 1, 'cp : 4.753 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/Switch', 'user2');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/Switch', 0, 1, 'cp : 5.792 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/Bitwise OR1', 'user2');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/Bitwise OR1', 0, 1, 'cp : 6.048 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/Switch3', 'user2');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/Switch3', 0, 1, 'cp : 6.438 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/Delay2', 'user1');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/Delay2', 1, 1, 'cp : 6.699 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/From', 'user2');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/From', 0, 1, 'cp : 2.408 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/FixPt Relational Operator', 'user2');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/FixPt Relational Operator', 0, 1, 'cp : 4.066 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/Positive', 'user2');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/Positive', 0, 1, 'cp : 3.379 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/NOT', 'user2');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/NOT', 0, 1, 'cp : 2.692 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/From7', 'user2');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/From7', 0, 1, 'cp : 2.408 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/Goto7', 'user2');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/Goto7', 0, 1, 'cp : 2.408 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/ssi_clock_enable_for_n_bits', 'user2');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/ssi_clock_enable_for_n_bits', 0, 1, 'cp : 2.408 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/Goto', 'user2');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/Goto', 0, 1, 'cp : 2.408 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/clk_idle_and_delay_first_clock_function', 'user2');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/clk_idle_and_delay_first_clock_function', 0, 1, 'cp : 2.408 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/clk_idle_and_delay_first_clock_function/Switch3', 'user2');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/ssi_communication/clk_idle_and_delay_first_clock_function/Switch3', 0, 1, 'cp : 2.408 ns');
