open_system('uz_ssi_interface_2025b');
open_system('gm_uz_ssi_interface_2025b');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay1', 'user1');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay1', 0, 1, 'Delays not moved into or out of an enabled subsystem');
hilite_system('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay1', 'user1');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay1', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay13', 'user1');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay13', 0, 1, 'Delays not moved into or out of an enabled subsystem');
hilite_system('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay13', 'user1');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay13', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay14', 'user1');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay14', 0, 1, 'Delays not moved into or out of an enabled subsystem');
hilite_system('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay14', 'user1');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay14', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay6', 'user1');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay6', 0, 1, 'Delays not moved into or out of an enabled subsystem');
hilite_system('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay6', 'user1');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay6', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay7', 'user1');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay7', 0, 1, 'Delays not moved into or out of an enabled subsystem');
hilite_system('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay7', 'user1');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay7', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay8', 'user1');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay8', 0, 1, 'Delays not moved into or out of an enabled subsystem');
hilite_system('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay8', 'user1');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay8', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay18', 'user1');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay18', 0, 1, 'Delays not moved into or out of an enabled subsystem');
hilite_system('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay18', 'user1');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay18', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay2', 'user1');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay2', 0, 1, 'Delays not moved into or out of an enabled subsystem');
hilite_system('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay2', 'user1');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay2', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay5', 'user1');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay5', 0, 1, 'Delays not moved into or out of an enabled subsystem');
hilite_system('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay5', 'user1');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay5', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay3', 'user1');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay3', 0, 1, 'Delays not moved into or out of an enabled subsystem');
hilite_system('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay3', 'user1');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay3', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay4', 'user1');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay4', 0, 1, 'Delays not moved into or out of an enabled subsystem');
hilite_system('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay4', 'user1');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay4', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay9', 'user1');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay9', 0, 1, 'Delays not moved into or out of an enabled subsystem');
hilite_system('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay9', 'user1');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay9', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay', 'user1');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay', 0, 1, 'Delays not moved into or out of an enabled subsystem');
hilite_system('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay', 'user1');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay10', 'user1');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay10', 0, 1, 'Delays not moved into or out of an enabled subsystem');
hilite_system('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay10', 'user1');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay10', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/fixed_point_floor', 'user1');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/fixed_point_floor', 0, 1, 'Delays not moved into or out of a MATLAB function block. Set its architecture to "MATLAB Datapath"');
hilite_system('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/fixed_point_floor', 'user1');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/fixed_point_floor', 0, 1, 'Delays not moved into or out of a MATLAB function block. Set its architecture to "MATLAB Datapath"');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay20', 'user1');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay20', 0, 1, 'Delays not moved into or out of an enabled subsystem');
hilite_system('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay20', 'user1');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay20', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay21', 'user1');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay21', 0, 1, 'Delays not moved into or out of an enabled subsystem');
hilite_system('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay21', 'user1');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay21', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay19', 'user1');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay19', 0, 1, 'Delays not moved into or out of an enabled subsystem');
hilite_system('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay19', 'user1');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay19', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay11', 'user1');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay11', 0, 1, 'Delays not moved into or out of an enabled subsystem');
hilite_system('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay11', 'user1');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay11', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay12', 'user1');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay12', 0, 1, 'Delays not moved into or out of an enabled subsystem');
hilite_system('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay12', 'user1');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay12', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay22', 'user1');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay22', 0, 1, 'Delays not moved into or out of an enabled subsystem');
hilite_system('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay22', 'user1');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay22', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay23', 'user1');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay23', 0, 1, 'Delays not moved into or out of an enabled subsystem');
hilite_system('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay23', 'user1');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/position_to_speed_pll/Delay23', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2025b/uz_ssi_interface/wrap_2pi/fixed_point_floor', 'user1');
annotate_port('gm_uz_ssi_interface_2025b/uz_ssi_interface/wrap_2pi/fixed_point_floor', 0, 1, 'Delays not moved into or out of a MATLAB function block. Set its architecture to "MATLAB Datapath"');
hilite_system('uz_ssi_interface_2025b/uz_ssi_interface/wrap_2pi/fixed_point_floor', 'user1');
annotate_port('uz_ssi_interface_2025b/uz_ssi_interface/wrap_2pi/fixed_point_floor', 0, 1, 'Delays not moved into or out of a MATLAB function block. Set its architecture to "MATLAB Datapath"');
