open_system('gm_dac_spi');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_dac_spi/HDL_DUT/Delay', 'user1');
annotate_port('gm_dac_spi/HDL_DUT/Delay', 0, 1, 'cp : 0.642 ns');
annotate_port('gm_dac_spi/HDL_DUT/Delay', 1, 1, 'cp : 1.268 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_dac_spi/HDL_DUT/Serializer1D', 'user1');
annotate_port('gm_dac_spi/HDL_DUT/Serializer1D', 0, 2, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_dac_spi/HDL_DUT/AND1', 'user2');
annotate_port('gm_dac_spi/HDL_DUT/AND1', 0, 1, 'cp : 0.284 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_dac_spi/HDL_DUT/AND2', 'user2');
annotate_port('gm_dac_spi/HDL_DUT/AND2', 0, 1, 'cp : 0.926 ns');
