open_system('dac_spi');
open_system('gm_dac_spi');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_dac_spi/HDL_DUT/Detect Rise Positive', 'user2');
annotate_port('gm_dac_spi/HDL_DUT/Detect Rise Positive', 1, 1, 'Block not characterized');
hilite_system('dac_spi/HDL_DUT/Detect Rise Positive', 'user2');
annotate_port('dac_spi/HDL_DUT/Detect Rise Positive', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_dac_spi/HDL_DUT/Serializer1D', 'user2');
annotate_port('gm_dac_spi/HDL_DUT/Serializer1D', 1, 1, 'Block not characterized');
hilite_system('dac_spi/HDL_DUT/Serializer1D', 'user2');
annotate_port('dac_spi/HDL_DUT/Serializer1D', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_dac_spi/HDL_DUT/Serializer1D1', 'user2');
annotate_port('gm_dac_spi/HDL_DUT/Serializer1D1', 1, 1, 'Block not characterized');
hilite_system('dac_spi/HDL_DUT/Serializer1D1', 'user2');
annotate_port('dac_spi/HDL_DUT/Serializer1D1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_dac_spi/HDL_DUT/Serializer1D2', 'user2');
annotate_port('gm_dac_spi/HDL_DUT/Serializer1D2', 1, 1, 'Block not characterized');
hilite_system('dac_spi/HDL_DUT/Serializer1D2', 'user2');
annotate_port('dac_spi/HDL_DUT/Serializer1D2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_dac_spi/HDL_DUT/Serializer1D3', 'user2');
annotate_port('gm_dac_spi/HDL_DUT/Serializer1D3', 1, 1, 'Block not characterized');
hilite_system('dac_spi/HDL_DUT/Serializer1D3', 'user2');
annotate_port('dac_spi/HDL_DUT/Serializer1D3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_dac_spi/HDL_DUT/Serializer1D4', 'user2');
annotate_port('gm_dac_spi/HDL_DUT/Serializer1D4', 1, 1, 'Block not characterized');
hilite_system('dac_spi/HDL_DUT/Serializer1D4', 'user2');
annotate_port('dac_spi/HDL_DUT/Serializer1D4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_dac_spi/HDL_DUT/Serializer1D5', 'user2');
annotate_port('gm_dac_spi/HDL_DUT/Serializer1D5', 1, 1, 'Block not characterized');
hilite_system('dac_spi/HDL_DUT/Serializer1D5', 'user2');
annotate_port('dac_spi/HDL_DUT/Serializer1D5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_dac_spi/HDL_DUT/Serializer1D6', 'user2');
annotate_port('gm_dac_spi/HDL_DUT/Serializer1D6', 1, 1, 'Block not characterized');
hilite_system('dac_spi/HDL_DUT/Serializer1D6', 'user2');
annotate_port('dac_spi/HDL_DUT/Serializer1D6', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_dac_spi/HDL_DUT/Serializer1D7', 'user2');
annotate_port('gm_dac_spi/HDL_DUT/Serializer1D7', 1, 1, 'Block not characterized');
hilite_system('dac_spi/HDL_DUT/Serializer1D7', 'user2');
annotate_port('dac_spi/HDL_DUT/Serializer1D7', 1, 1, 'Block not characterized');
