vlib work
vcom  uz_dac_src_Detect_Rise_Positive.vhd
vcom  uz_dac_src_Subsystem.vhd
vcom  uz_dac_src_Subsystem1.vhd
vcom  uz_dac_src_Subsystem2.vhd
vcom  uz_dac_src_Subsystem3.vhd
vcom  uz_dac_src_Subsystem4.vhd
vcom  uz_dac_src_Subsystem5.vhd
vcom  uz_dac_src_Subsystem6.vhd
vcom  uz_dac_src_Subsystem7.vhd
vcom  uz_dac_src_HDL_DUT_tc.vhd
vcom  uz_dac_src_HDL_DUT.vhd
