-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\ELSYS_PC\Documents\repos\ultrazohm_sw\ip_cores\uz_EnDat_IPCore\hdl_prj\hdlsrc\UZ_EnDat\uz_EnDat_src_ManualSerializeWrap.vhd
-- Created: 2024-07-28 16:43:26
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: uz_EnDat_src_ManualSerializeWrap
-- Source Path: UZ_EnDat/UZ_ENDAT/ManualSerializeWrap
-- Hierarchy Level: 1
-- Model version: 3.24
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY uz_EnDat_src_ManualSerializeWrap IS
  PORT( clk                               :   IN    std_logic;
        reset_x                           :   IN    std_logic;
        enb                               :   IN    std_logic;
        CLK_1                             :   IN    std_logic;
        SLOWCLCK                          :   IN    std_logic;
        DATA                              :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        reset                             :   IN    std_logic;
        Enable                            :   IN    std_logic;
        valin                             :   OUT   std_logic
        );
END uz_EnDat_src_ManualSerializeWrap;


ARCHITECTURE rtl OF uz_EnDat_src_ManualSerializeWrap IS

  -- Component Declarations
  COMPONENT uz_EnDat_src_ManualSerializer
    PORT( clk                             :   IN    std_logic;
          reset_x                         :   IN    std_logic;
          enb                             :   IN    std_logic;
          CLK_1                           :   IN    std_logic;
          SLOWCLCK                        :   IN    std_logic;
          DATA                            :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          reset                           :   IN    std_logic;
          valin                           :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : uz_EnDat_src_ManualSerializer
    USE ENTITY work.uz_EnDat_src_ManualSerializer(rtl);

  -- Signals
  SIGNAL enb_gated                        : std_logic;
  SIGNAL Enable_out5                      : std_logic;
  SIGNAL ManualSerializer_out1            : std_logic;
  SIGNAL ManualSerializer_out1_bypass     : std_logic;
  SIGNAL ManualSerializer_out1_last_value : std_logic;

BEGIN
  u_ManualSerializer : uz_EnDat_src_ManualSerializer
    PORT MAP( clk => clk,
              reset_x => reset_x,
              enb => enb_gated,
              CLK_1 => CLK_1,
              SLOWCLCK => SLOWCLCK,
              DATA => DATA,  -- uint16
              reset => reset,
              valin => ManualSerializer_out1
              );

  Enable_out5 <= Enable;

  enb_gated <= Enable_out5 AND enb;

  valin_bypass_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        ManualSerializer_out1_last_value <= '0';
      ELSIF enb_gated = '1' THEN
        ManualSerializer_out1_last_value <= ManualSerializer_out1_bypass;
      END IF;
    END IF;
  END PROCESS valin_bypass_process;


  
  ManualSerializer_out1_bypass <= ManualSerializer_out1_last_value WHEN Enable_out5 = '0' ELSE
      ManualSerializer_out1;

  valin <= ManualSerializer_out1_bypass;

END rtl;

