SLStudio.Utils.RemoveHighlighting(get_param('UZ_D_GaN_Inverter', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_UZ_D_GaN_Inverter', 'handle'));
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/For Each Subsystem_instance1', 0, 4, '');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/t', 0, 1, '');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/t12', 0, 1, '');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/t13', 0, 1, '');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/t17', 0, 1, '');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/mux', 0, 1, '');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/For Each Subsystem_instance1/Detect Rise Positive', 1, 1, '');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/For Each Subsystem/Detect Rise Positive', 1, 1, '');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/For Each Subsystem_instance1/Detect Fall Nonpositive', 0, 1, '');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/For Each Subsystem_instance1/Detect Fall Nonpositive', 1, 1, '');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/For Each Subsystem/Detect Fall Nonpositive', 1, 1, '');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/For Each Subsystem_instance1/Gain', 0, 1, '');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/For Each Subsystem_instance1/Product', 0, 1, '');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/For Each Subsystem_instance1/Compare To Constant', 0, 1, '');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/For Each Subsystem_instance1/Switch1', 0, 1, '');
