open_system('gm_UZ_D_GaN_Inverter');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection_instance1', 'user2');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection_instance1', 0, 4, 'cp : 22.014 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/t', 'user2');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/t', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/t12', 'user2');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/t12', 0, 1, 'cp : 22.014 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/t13', 'user2');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/t13', 0, 1, 'cp : 22.014 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Bit Slice GaN_Temp1', 'user1');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Bit Slice GaN_Temp1', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/t17', 'user1');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/t17', 0, 1, 'cp : 22.014 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/mux', 'user2');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/mux', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection_instance1/Detect Fall Nonpositive', 'user2');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection_instance1/Detect Fall Nonpositive', 0, 1, 'cp : 2.334 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection_instance1/Gain', 'user2');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection_instance1/Gain', 0, 1, 'cp : 22.014 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection_instance1/Product', 'user2');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection_instance1/Product', 0, 1, 'cp : 13.099 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection_instance1/Compare To Constant', 'user2');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection_instance1/Compare To Constant', 0, 1, 'cp : 3.501 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection_instance1/Switch1', 'user2');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection_instance1/Switch1', 0, 1, 'cp : 4.184 ns');
