open_system('UZ_D_GaN_Inverter');
open_system('gm_UZ_D_GaN_Inverter');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/For Each Subsystem_instance1/Detect Rise Positive', 'user2');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/For Each Subsystem_instance1/Detect Rise Positive', 1, 1, 'Block not characterized');
hilite_system('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/For Each Subsystem/Detect Rise Positive', 'user2');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/For Each Subsystem/Detect Rise Positive', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/For Each Subsystem_instance1/Detect Fall Nonpositive', 'user2');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/For Each Subsystem_instance1/Detect Fall Nonpositive', 1, 1, 'Block not characterized');
hilite_system('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/For Each Subsystem/Detect Fall Nonpositive', 'user2');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/For Each Subsystem/Detect Fall Nonpositive', 1, 1, 'Block not characterized');
