#ifndef UZ_AXI_MYTESTIP_HWADDRESSES_H
#define UZ_AXI_MYTESTIP_HWADDRESSES_H

#define XUZ_AXI_myTestIP_CONTROL_ADDR_A_DATA      0x10
#define XUZ_AXI_myTestIP_CONTROL_BITS_A_DATA      32
#define XUZ_AXI_myTestIP_CONTROL_ADDR_B_DATA      0x18
#define XUZ_AXI_myTestIP_CONTROL_BITS_B_DATA      32
#define XUZ_AXI_myTestIP_CONTROL_ADDR_RESULT_DATA 0x20
#define XUZ_AXI_myTestIP_CONTROL_BITS_RESULT_DATA 32
#define XUZ_AXI_myTestIP_CONTROL_ADDR_RESULT_CTRL 0x24

#endif // UZ_AXI_MYTESTIP_HWADDRESSES_H