open_system('gm_uz_9ph_pmsm_model');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/From7', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/From7', 0, 1, 'cp : 2.506 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Goto9', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Goto9', 0, 1, 'cp : 2.506 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/From81', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/From81', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Goto71', 'user1');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Goto71', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/reset_in4', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/reset_in4', 0, 1, 'cp : 121.509 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Delay1_lowered4', 'user1');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Delay1_lowered4', 1, 1, 'cp : 121.509 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/bus_selector3', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/bus_selector3', 0, 6, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Add', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Add', 0, 1, 'cp : 98.393 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Add_outbuff', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Add_outbuff', 0, 1, 'cp : 98.393 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Data Type Conversion10', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Data Type Conversion10', 0, 1, 'cp : 2.506 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Divide1', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Divide1', 0, 1, 'cp : 86.771 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Divide_outbuff1', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Divide_outbuff1', 0, 1, 'cp : 86.771 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Divide11', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Divide11', 0, 1, 'cp : 75.696 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Divide1_outbuff', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Divide1_outbuff', 0, 1, 'cp : 75.696 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Sum34', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Sum34', 0, 1, 'cp : 121.119 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Sum3_outbuff4', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Sum3_outbuff4', 0, 1, 'cp : 121.119 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Gain4', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Gain4', 0, 1, 'cp : 109.468 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Gain_outbuff4', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Gain_outbuff4', 0, 1, 'cp : 109.468 ns');
