open_system('uz_9ph_pmsm_model');
open_system('gm_uz_9ph_pmsm_model');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Delay', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Delay', 1, 1, 'Block not characterized');
hilite_system('uz_9ph_pmsm_model/uz_pmsm_model_9ph/mechanical_system/Delay', 'user2');
annotate_port('uz_9ph_pmsm_model/uz_pmsm_model_9ph/mechanical_system/Delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Delay1_lowered', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Delay1_lowered', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Delay1_lowered1', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Delay1_lowered1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Delay1_lowered2', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Delay1_lowered2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Delay1_lowered3', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Delay1_lowered3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Delay1_lowered4', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Delay1_lowered4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Delay1_lowered5', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Delay1_lowered5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Delay1_lowered6', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Delay1_lowered6', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Delay1_lowered7', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Delay1_lowered7', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Delay1_lowered8', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Delay1_lowered8', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Delay1_lowered9', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Delay1_lowered9', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Delay1_lowered10', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Delay1_lowered10', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/t1', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/t1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/t2', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/t2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/t4', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/t4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/t5', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/t5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/t6', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/t6', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/t7', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/t7', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/t8', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/t8', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/t9', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/t9', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/t10', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/t10', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/t11', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/t11', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/t12', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/t12', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/PipelineRegister', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/PipelineRegister', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/PipelineRegister1', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/PipelineRegister1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/PipelineRegister2', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/PipelineRegister2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/PipelineRegister3', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/PipelineRegister3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/PipelineRegister4', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/PipelineRegister4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/PipelineRegister5', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/PipelineRegister5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/PipelineRegister6', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/PipelineRegister6', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/PipelineRegister7', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/PipelineRegister7', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/PipelineRegister8', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation/PipelineRegister8', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/t1', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/t1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/t2', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/t2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/MatrixMultiply_out1', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/MatrixMultiply_out1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC/t', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC/PipelineRegister', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC/PipelineRegister', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC1/t', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC1/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC1/PipelineRegister', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC1/PipelineRegister', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC2/t', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC2/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC2/PipelineRegister', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC2/PipelineRegister', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC3/t', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC3/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC3/PipelineRegister', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC3/PipelineRegister', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC4/t', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC4/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC4/PipelineRegister', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC4/PipelineRegister', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC5/t', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC5/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC5/PipelineRegister', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC5/PipelineRegister', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC6/t', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC6/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC6/PipelineRegister', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC6/PipelineRegister', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC7/t', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC7/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC7/PipelineRegister', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC7/PipelineRegister', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC8/t', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC8/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC8/PipelineRegister', 'user2');
annotate_port('gm_uz_9ph_pmsm_model/uz_pmsm_model_9ph/Transformation1/crp_temp_MAC8/PipelineRegister', 1, 1, 'Block not characterized');
