-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/uz_plantModel_pt1/uz_plantModel_pt1_src_uz_plantModel_pt1_pkg.vhd
-- Created: 2021-06-17 10:07:07
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE uz_plantModel_pt1_src_uz_plantModel_pt1_pkg IS
  TYPE vector_of_unsigned52 IS ARRAY (NATURAL RANGE <>) OF unsigned(51 DOWNTO 0);
  TYPE vector_of_unsigned106 IS ARRAY (NATURAL RANGE <>) OF unsigned(105 DOWNTO 0);
  TYPE vector_of_signed14 IS ARRAY (NATURAL RANGE <>) OF signed(13 DOWNTO 0);
  TYPE vector_of_unsigned11 IS ARRAY (NATURAL RANGE <>) OF unsigned(10 DOWNTO 0);
  TYPE vector_of_signed57 IS ARRAY (NATURAL RANGE <>) OF signed(56 DOWNTO 0);
  TYPE vector_of_unsigned56 IS ARRAY (NATURAL RANGE <>) OF unsigned(55 DOWNTO 0);
  TYPE vector_of_unsigned8 IS ARRAY (NATURAL RANGE <>) OF unsigned(7 DOWNTO 0);
  TYPE vector_of_unsigned23 IS ARRAY (NATURAL RANGE <>) OF unsigned(22 DOWNTO 0);
  TYPE vector_of_std_logic_vector32 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(31 DOWNTO 0);
END uz_plantModel_pt1_src_uz_plantModel_pt1_pkg;

