open_system('uz_pmsm_model_6ph_dqxy');
open_system('gm_uz_pmsm_model_6ph_dqxy');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion16', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion16', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion16', 'user2');
annotate_port('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion16', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion12', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion12', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion12', 'user2');
annotate_port('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion12', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion22', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion22', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion22', 'user2');
annotate_port('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion22', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion15', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion15', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion15', 'user2');
annotate_port('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion15', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion3', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion3', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion3', 'user2');
annotate_port('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion3', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion18', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion18', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion18', 'user2');
annotate_port('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion18', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion17', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion17', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion17', 'user2');
annotate_port('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion17', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion4', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion4', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion4', 'user2');
annotate_port('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion4', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion14', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion14', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion14', 'user2');
annotate_port('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion14', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion5', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion5', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion5', 'user2');
annotate_port('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion5', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion2', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion2', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion2', 'user2');
annotate_port('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion2', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion7', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion7', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion7', 'user2');
annotate_port('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion7', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion9', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion9', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion9', 'user2');
annotate_port('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion9', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion8', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion8', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion8', 'user2');
annotate_port('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion8', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion6', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion6', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion6', 'user2');
annotate_port('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion6', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion20', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion20', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion20', 'user2');
annotate_port('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion20', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion10', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion10', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion10', 'user2');
annotate_port('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion10', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion13', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion13', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion13', 'user2');
annotate_port('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion13', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion11', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion11', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion11', 'user2');
annotate_port('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion11', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion21', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion21', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion21', 'user2');
annotate_port('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion21', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion19', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion19', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion19', 'user2');
annotate_port('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion19', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion1', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion1', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion1', 'user2');
annotate_port('uz_pmsm_model_6ph_dqxy/uz_pmsm_model/Data Type Conversion1', 1, 1, 'Block not characterized for this configuration');
