SLStudio.Utils.RemoveHighlighting(get_param('uz_threephase_VSD_transformation', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_uz_threephase_VSD_transformation', 'handle'));
annotate_port('gm_uz_threephase_VSD_transformation/abc_to_dq/Unit Delay', 1, 1, '');
annotate_port('uz_threephase_VSD_transformation/abc_to_dq/Unit Delay', 1, 1, '');
annotate_port('gm_uz_threephase_VSD_transformation/abc_to_dq/Sine HDL Optimized', 0, 1, '');
annotate_port('gm_uz_threephase_VSD_transformation/abc_to_dq/vectorized_in0', 1, 1, '');
annotate_port('gm_uz_threephase_VSD_transformation/abc_to_dq/Row2Col_in0', 1, 1, '');
annotate_port('gm_uz_threephase_VSD_transformation/abc_to_dq/Row2Col_in1', 1, 1, '');
annotate_port('gm_uz_threephase_VSD_transformation/abc_to_dq/reshape_dotProduct', 1, 1, '');
annotate_port('gm_uz_threephase_VSD_transformation/abc_to_dq/reshape_mmulResult', 1, 1, '');
annotate_port('gm_uz_threephase_VSD_transformation/abc_to_dq/t1', 1, 1, '');
annotate_port('gm_uz_threephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/Point501', 0, 1, '');
annotate_port('gm_uz_threephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/Look-Up Table', 0, 1, '');
annotate_port('uz_threephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/sincos hdl/cos_hdl/Look-Up Table', 0, 1, '');
annotate_port('gm_uz_threephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/CastU16En21', 0, 1, '');
annotate_port('gm_uz_threephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/CastU16En31', 0, 1, '');
annotate_port('gm_uz_threephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/CastU16En4', 0, 1, '');
annotate_port('gm_uz_threephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/LTEp251', 0, 1, '');
annotate_port('gm_uz_threephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/LTEp501', 0, 1, '');
annotate_port('gm_uz_threephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/Look-Up Table1', 0, 1, '');
annotate_port('gm_uz_threephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/Look-Up Table1', 0, 1, '');
annotate_port('uz_threephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/sincos hdl/sin_hdl/Look-Up Table', 0, 1, '');
annotate_port('gm_uz_threephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/QuadHandle1', 0, 1, '');
annotate_port('gm_uz_threephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/QuadHandle21', 0, 1, '');
annotate_port('gm_uz_threephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/Saturation1', 0, 1, '');
annotate_port('gm_uz_threephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/Switch1', 0, 1, '');
annotate_port('gm_uz_threephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/PipelineRegister1', 1, 1, '');
annotate_port('gm_uz_threephase_VSD_transformation/abc_to_dq/inverse_Clarke/vectorized_in0', 1, 1, '');
annotate_port('gm_uz_threephase_VSD_transformation/abc_to_dq/inverse_Clarke/Row2Col_in0', 1, 1, '');
annotate_port('gm_uz_threephase_VSD_transformation/abc_to_dq/inverse_Clarke/Row2Col_in1', 1, 1, '');
annotate_port('gm_uz_threephase_VSD_transformation/abc_to_dq/inverse_Clarke/reshape_dotProduct', 1, 1, '');
annotate_port('gm_uz_threephase_VSD_transformation/abc_to_dq/inverse_Clarke/reshape_mmulResult', 1, 1, '');
annotate_port('gm_uz_threephase_VSD_transformation/abc_to_dq/inverse_Clarke/t', 1, 1, '');
