-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\uz_mpc_6ph_sca_hex_new\MPC_incr_encoder_conversion_src_MPC_incr_encoder_theta_conv.vhd
-- Created: 2024-04-26 14:45:34
-- 
-- Generated by MATLAB 9.13 and HDL Coder 4.0
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1e-08
-- Target subsystem base rate: 1e-08
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1e-08
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- out1                          ce_out        1e-08
-- pu_conv_done                  ce_out        1e-08
-- out1_AXI                      ce_out        1e-08
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MPC_incr_encoder_conversion_src_MPC_incr_encoder_theta_conv
-- Source Path: uz_mpc_6ph_sca_hex_new/MPC_incr_encoder_theta_conv
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MPC_incr_encoder_conversion_src_MPC_incr_encoder_theta_conv_pkg.ALL;

ENTITY MPC_incr_encoder_conversion_src_MPC_incr_encoder_theta_conv IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        theta_el                          :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En20
        adc_valid_trigger                 :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        out1                              :   OUT   std_logic_vector(26 DOWNTO 0);  -- sfix27_En20
        pu_conv_done                      :   OUT   std_logic;
        out1_AXI                          :   OUT   std_logic_vector(26 DOWNTO 0)  -- sfix27_En20
        );
END MPC_incr_encoder_conversion_src_MPC_incr_encoder_theta_conv;


ARCHITECTURE rtl OF MPC_incr_encoder_conversion_src_MPC_incr_encoder_theta_conv IS

  -- Component Declarations
  COMPONENT MPC_incr_encoder_conversion_src_Detect_Rise_Positive
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          U                               :   IN    std_logic;
          Y                               :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MPC_incr_encoder_conversion_src_Detect_Rise_Positive
    USE ENTITY work.MPC_incr_encoder_conversion_src_Detect_Rise_Positive(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL Delay32_reg                      : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL Delay32_out1                     : std_logic;
  SIGNAL Detect_Rise_Positive_out1        : std_logic;
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL theta_el_signed                  : signed(23 DOWNTO 0);  -- sfix24_En20
  SIGNAL Delay64_reg                      : vector_of_signed24(0 TO 1);  -- sfix24 [2]
  SIGNAL Delay64_out1                     : signed(23 DOWNTO 0);  -- sfix24_En20
  SIGNAL Switch31_out1                    : signed(23 DOWNTO 0);  -- sfix24_En20
  SIGNAL Delay31_out1                     : signed(23 DOWNTO 0);  -- sfix24_En20
  SIGNAL Data_Type_Conversion20_out1      : signed(26 DOWNTO 0);  -- sfix27_En20
  SIGNAL Delay127_reg                     : vector_of_signed27(0 TO 1);  -- sfix27 [2]
  SIGNAL Delay127_out1                    : signed(26 DOWNTO 0);  -- sfix27_En20
  SIGNAL Delay129_reg                     : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL Delay129_out1                    : std_logic;
  SIGNAL Delay128_reg                     : vector_of_signed27(0 TO 1);  -- sfix27 [2]
  SIGNAL Delay128_out1                    : signed(26 DOWNTO 0);  -- sfix27_En20

BEGIN
  u_Detect_Rise_Positive : MPC_incr_encoder_conversion_src_Detect_Rise_Positive
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              U => Delay32_out1,
              Y => Detect_Rise_Positive_out1
              );

  enb <= clk_enable;

  Delay32_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay32_reg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        Delay32_reg(0) <= adc_valid_trigger;
        Delay32_reg(1) <= Delay32_reg(0);
      END IF;
    END IF;
  END PROCESS Delay32_process;

  Delay32_out1 <= Delay32_reg(1);

  
  switch_compare_1 <= '1' WHEN Detect_Rise_Positive_out1 > '0' ELSE
      '0';

  theta_el_signed <= signed(theta_el);

  Delay64_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay64_reg <= (OTHERS => to_signed(16#000000#, 24));
      ELSIF enb = '1' THEN
        Delay64_reg(0) <= theta_el_signed;
        Delay64_reg(1) <= Delay64_reg(0);
      END IF;
    END IF;
  END PROCESS Delay64_process;

  Delay64_out1 <= Delay64_reg(1);

  Delay31_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay31_out1 <= to_signed(16#000000#, 24);
      ELSIF enb = '1' THEN
        Delay31_out1 <= Switch31_out1;
      END IF;
    END IF;
  END PROCESS Delay31_process;


  
  Switch31_out1 <= Delay31_out1 WHEN switch_compare_1 = '0' ELSE
      Delay64_out1;

  Data_Type_Conversion20_out1 <= resize(Switch31_out1, 27);

  Delay127_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay127_reg <= (OTHERS => to_signed(16#0000000#, 27));
      ELSIF enb = '1' THEN
        Delay127_reg(0) <= Data_Type_Conversion20_out1;
        Delay127_reg(1) <= Delay127_reg(0);
      END IF;
    END IF;
  END PROCESS Delay127_process;

  Delay127_out1 <= Delay127_reg(1);

  out1 <= std_logic_vector(Delay127_out1);

  Delay129_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay129_reg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        Delay129_reg(0) <= Detect_Rise_Positive_out1;
        Delay129_reg(1) <= Delay129_reg(0);
      END IF;
    END IF;
  END PROCESS Delay129_process;

  Delay129_out1 <= Delay129_reg(1);

  Delay128_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay128_reg <= (OTHERS => to_signed(16#0000000#, 27));
      ELSIF enb = '1' THEN
        Delay128_reg(0) <= Data_Type_Conversion20_out1;
        Delay128_reg(1) <= Delay128_reg(0);
      END IF;
    END IF;
  END PROCESS Delay128_process;

  Delay128_out1 <= Delay128_reg(1);

  out1_AXI <= std_logic_vector(Delay128_out1);

  ce_out <= clk_enable;

  pu_conv_done <= Delay129_out1;

END rtl;

