open_system('gm_FCS_MPC_3Phase_SPMSM_TEST1');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/Product', 'user2');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/Product', 0, 1, 'cp : 5.235 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/PipelineRegister', 'user1');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/PipelineRegister', 1, 1, 'cp : 5.235 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/HwModeRegister1', 'user1');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/HwModeRegister1', 0, 1, 'cp : 0.33 ns');
