open_system('FCS_MPC_3Phase_SPMSM_TEST1');
open_system('gm_FCS_MPC_3Phase_SPMSM_TEST1');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/t', 'user2');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/t', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/t1', 'user2');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_TEST1/Microcontroller Software/Subsystem1/t1', 1, 1, 'Obstacle to clock-rate pipelining');
