open_system('gm_parallel_phase_voltages_per_switching_state_6');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_phase_voltages_per_switching_state_6/Phase_voltages_per_switching_state/Detect Rise Positive1', 'user2');
annotate_port('gm_parallel_phase_voltages_per_switching_state_6/Phase_voltages_per_switching_state/Detect Rise Positive1', 0, 1, 'cp : 1.323 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_phase_voltages_per_switching_state_6/Phase_voltages_per_switching_state/Subsystem', 'user2');
annotate_port('gm_parallel_phase_voltages_per_switching_state_6/Phase_voltages_per_switching_state/Subsystem', 1, 3, 'cp : 3.35 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_phase_voltages_per_switching_state_6/Phase_voltages_per_switching_state/Delay12', 'user1');
annotate_port('gm_parallel_phase_voltages_per_switching_state_6/Phase_voltages_per_switching_state/Delay12', 0, 1, 'cp : 0.33 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_phase_voltages_per_switching_state_6/Phase_voltages_per_switching_state/Logical Operator', 'user2');
annotate_port('gm_parallel_phase_voltages_per_switching_state_6/Phase_voltages_per_switching_state/Logical Operator', 0, 1, 'cp : 1.323 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_phase_voltages_per_switching_state_6/Phase_voltages_per_switching_state/Switch_on3', 'user2');
annotate_port('gm_parallel_phase_voltages_per_switching_state_6/Phase_voltages_per_switching_state/Switch_on3', 0, 1, 'cp : 1.651 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_phase_voltages_per_switching_state_6/Phase_voltages_per_switching_state/Detect Rise Positive1/Positive', 'user2');
annotate_port('gm_parallel_phase_voltages_per_switching_state_6/Phase_voltages_per_switching_state/Detect Rise Positive1/Positive', 0, 1, 'cp : 1.323 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_phase_voltages_per_switching_state_6/Phase_voltages_per_switching_state/Detect Rise Positive1/FixPt Relational Operator', 'user2');
annotate_port('gm_parallel_phase_voltages_per_switching_state_6/Phase_voltages_per_switching_state/Detect Rise Positive1/FixPt Relational Operator', 0, 1, 'cp : 1.323 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_phase_voltages_per_switching_state_6/Phase_voltages_per_switching_state/Detect Rise Positive1/Positive/Compare', 'user2');
annotate_port('gm_parallel_phase_voltages_per_switching_state_6/Phase_voltages_per_switching_state/Detect Rise Positive1/Positive/Compare', 0, 1, 'cp : 1.323 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_phase_voltages_per_switching_state_6/Phase_voltages_per_switching_state/Subsystem/MATLAB Function', 'user2');
annotate_port('gm_parallel_phase_voltages_per_switching_state_6/Phase_voltages_per_switching_state/Subsystem/MATLAB Function', 1, 3, 'cp : 3.35 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_phase_voltages_per_switching_state_6/Phase_voltages_per_switching_state/Subsystem/MATLAB Function/adder', 'user2');
annotate_port('gm_parallel_phase_voltages_per_switching_state_6/Phase_voltages_per_switching_state/Subsystem/MATLAB Function/adder', 0, 1, 'cp : 3.089 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_phase_voltages_per_switching_state_6/Phase_voltages_per_switching_state/Subsystem/MATLAB Function/Selector8', 'user2');
annotate_port('gm_parallel_phase_voltages_per_switching_state_6/Phase_voltages_per_switching_state/Subsystem/MATLAB Function/Selector8', 0, 1, 'cp : 3.089 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_phase_voltages_per_switching_state_6/Phase_voltages_per_switching_state/Subsystem/MATLAB Function/adder1', 'user2');
annotate_port('gm_parallel_phase_voltages_per_switching_state_6/Phase_voltages_per_switching_state/Subsystem/MATLAB Function/adder1', 0, 1, 'cp : 2.37 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_phase_voltages_per_switching_state_6/Phase_voltages_per_switching_state/Subsystem/MATLAB Function/delayMatch', 'user1');
annotate_port('gm_parallel_phase_voltages_per_switching_state_6/Phase_voltages_per_switching_state/Subsystem/MATLAB Function/delayMatch', 1, 1, 'cp : 3.35 ns');
