#pragma once

#include "uz_interlockDeadtime2L.h"
uz_interlockDeadtime2L_handle uz_interlockDeadtime2L_staticAllocator_slotD1(void);
uz_interlockDeadtime2L_handle uz_interlockDeadtime2L_staticAllocator_second_inverter(void);
