-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\ELSYS_PC\Documents\repos\ultrazohm_sw\ip_cores\uz_EnDat_IPCore\hdl_prj\hdlsrc\UZ_EnDat\uz_EnDat_src_RECOVERYTIMESELECTOR.vhd
-- Created: 2023-12-23 12:43:54
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: uz_EnDat_src_RECOVERYTIMESELECTOR
-- Source Path: UZ_EnDat/UZ_ENDAT/RECOVERYTIMESELECTOR
-- Hierarchy Level: 1
-- Model version: 2.560
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY uz_EnDat_src_RECOVERYTIMESELECTOR IS
  PORT( clk                               :   IN    std_logic;
        reset_x                           :   IN    std_logic;
        enb                               :   IN    std_logic;
        In1                               :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        FAKTOR                            :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        Out1                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
        );
END uz_EnDat_src_RECOVERYTIMESELECTOR;


ARCHITECTURE rtl OF uz_EnDat_src_RECOVERYTIMESELECTOR IS

  -- Signals
  SIGNAL In1_unsigned                     : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Constant22_out1                  : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Constant21_out1                  : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Constant19_out1                  : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Constant20_out1                  : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Constant25_out1                  : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Constant26_out1                  : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Constant5_out1                   : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Multiport_Switch3_out1           : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Multiport_Switch3_out1_1         : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL FAKTOR_unsigned                  : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL FAKTOR_1                         : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Product_out1                     : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL Product_out1_1                   : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL Product_out1_2                   : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Constant_out1                    : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Divide_out1                      : unsigned(15 DOWNTO 0);  -- uint16

BEGIN
  -- 200khz = 6
  -- 1,5mhz = 12
  -- 3 mhz = 8

  In1_unsigned <= unsigned(In1);

  Constant22_out1 <= to_unsigned(16#00FF#, 16);

  Constant21_out1 <= to_unsigned(16#00C0#, 16);

  Constant19_out1 <= to_unsigned(16#0060#, 16);

  Constant20_out1 <= to_unsigned(16#0030#, 16);

  Constant25_out1 <= to_unsigned(16#0018#, 16);

  Constant26_out1 <= to_unsigned(16#000C#, 16);

  Constant5_out1 <= to_unsigned(16#0006#, 16);

  
  Multiport_Switch3_out1 <= Constant22_out1 WHEN In1_unsigned = to_unsigned(16#0#, 4) ELSE
      Constant21_out1 WHEN In1_unsigned = to_unsigned(16#1#, 4) ELSE
      Constant19_out1 WHEN In1_unsigned = to_unsigned(16#2#, 4) ELSE
      Constant20_out1 WHEN In1_unsigned = to_unsigned(16#3#, 4) ELSE
      Constant25_out1 WHEN In1_unsigned = to_unsigned(16#4#, 4) ELSE
      Constant26_out1 WHEN In1_unsigned = to_unsigned(16#5#, 4) ELSE
      Constant5_out1;

  HwModeRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Multiport_Switch3_out1_1 <= to_unsigned(16#0000#, 16);
      ELSIF enb = '1' THEN
        Multiport_Switch3_out1_1 <= Multiport_Switch3_out1;
      END IF;
    END IF;
  END PROCESS HwModeRegister_process;


  FAKTOR_unsigned <= unsigned(FAKTOR);

  HwModeRegister1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        FAKTOR_1 <= to_unsigned(16#0000#, 16);
      ELSIF enb = '1' THEN
        FAKTOR_1 <= FAKTOR_unsigned;
      END IF;
    END IF;
  END PROCESS HwModeRegister1_process;


  Product_out1 <= Multiport_Switch3_out1_1 * FAKTOR_1;

  PipelineRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Product_out1_1 <= to_unsigned(0, 32);
      ELSIF enb = '1' THEN
        Product_out1_1 <= Product_out1;
      END IF;
    END IF;
  END PROCESS PipelineRegister_process;


  
  Product_out1_2 <= X"FFFF" WHEN Product_out1_1(31 DOWNTO 16) /= X"0000" ELSE
      Product_out1_1(15 DOWNTO 0);

  Constant_out1 <= to_unsigned(16#0064#, 16);

  Divide_output : PROCESS (Constant_out1, Product_out1_2)
    VARIABLE div_temp : unsigned(16 DOWNTO 0);
  BEGIN
    div_temp := to_unsigned(16#00000#, 17);
    IF Constant_out1 = to_unsigned(16#0000#, 16) THEN 
      Divide_out1 <= to_unsigned(16#FFFF#, 16);
    ELSE 
      div_temp := resize(Product_out1_2, 17) / Constant_out1;
      IF div_temp(16) /= '0' THEN 
        Divide_out1 <= X"FFFF";
      ELSE 
        Divide_out1 <= div_temp(15 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS Divide_output;


  Out1 <= std_logic_vector(Divide_out1);

END rtl;

