open_system('two_level_sixphase_f_sw_counter');
open_system('gm_two_level_sixphase_f_sw_counter');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_two_level_sixphase_f_sw_counter/two_level_sixphase_f_sw_counter/SS_Old', 'user2');
annotate_port('gm_two_level_sixphase_f_sw_counter/two_level_sixphase_f_sw_counter/SS_Old', 1, 1, 'Block not characterized');
hilite_system('two_level_sixphase_f_sw_counter/two_level_sixphase_f_sw_counter/SS_Old', 'user2');
annotate_port('two_level_sixphase_f_sw_counter/two_level_sixphase_f_sw_counter/SS_Old', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_two_level_sixphase_f_sw_counter/two_level_sixphase_f_sw_counter/delay', 'user2');
annotate_port('gm_two_level_sixphase_f_sw_counter/two_level_sixphase_f_sw_counter/delay', 1, 1, 'Block not characterized');
hilite_system('two_level_sixphase_f_sw_counter/two_level_sixphase_f_sw_counter/delay', 'user2');
annotate_port('two_level_sixphase_f_sw_counter/two_level_sixphase_f_sw_counter/delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_two_level_sixphase_f_sw_counter/two_level_sixphase_f_sw_counter/reset_old2', 'user2');
annotate_port('gm_two_level_sixphase_f_sw_counter/two_level_sixphase_f_sw_counter/reset_old2', 1, 1, 'Block not characterized');
hilite_system('two_level_sixphase_f_sw_counter/two_level_sixphase_f_sw_counter/reset_old2', 'user2');
annotate_port('two_level_sixphase_f_sw_counter/two_level_sixphase_f_sw_counter/reset_old2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_two_level_sixphase_f_sw_counter/two_level_sixphase_f_sw_counter/Count_f_sw/Count_f_sw', 'user2');
annotate_port('gm_two_level_sixphase_f_sw_counter/two_level_sixphase_f_sw_counter/Count_f_sw/Count_f_sw', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_two_level_sixphase_f_sw_counter/two_level_sixphase_f_sw_counter/Count_f_sw/Count_f_sw', 'user2');
annotate_port('gm_two_level_sixphase_f_sw_counter/two_level_sixphase_f_sw_counter/Count_f_sw/Count_f_sw', 1, 1, 'Block not characterized');
hilite_system('two_level_sixphase_f_sw_counter/two_level_sixphase_f_sw_counter/Count_f_sw', 'user2');
annotate_port('two_level_sixphase_f_sw_counter/two_level_sixphase_f_sw_counter/Count_f_sw', 1, 1, 'Block not characterized');
