open_system('gm_test_switching_states_6Phase_without_delays');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_switching_states_6Phase_without_delays/HDL_DUT2/Delay2', 'user1');
annotate_port('gm_test_switching_states_6Phase_without_delays/HDL_DUT2/Delay2', 0, 1, 'cp : 0.33 ns');
annotate_port('gm_test_switching_states_6Phase_without_delays/HDL_DUT2/Delay2', 1, 1, 'cp : 0.919 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_switching_states_6Phase_without_delays/HDL_DUT2/Switch_on2', 'user2');
annotate_port('gm_test_switching_states_6Phase_without_delays/HDL_DUT2/Switch_on2', 0, 1, 'cp : 0.658 ns');
