SLStudio.Utils.RemoveHighlighting(get_param('uz_ssi_interface_2023a', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_uz_ssi_interface_2023a', 'handle'));
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/Detect Rise Positive1', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data', 1, 5, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/Delay32', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/Switch4', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/Detect Rise Positive1/FixPt Relational Operator', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/Detect Rise Positive1/Positive', 0, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/clk_idle_and_delay_first_clock_function/S-R Flip-Flop', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/Detect Rise Positive2', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/Delay1', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/saturate', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/multiportswitch', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/NOT', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/Switch', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/Detect Rise Positive2/FixPt Relational Operator', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/Detect Rise Positive2/Positive', 0, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/ssi_clock_enable_for_n_bits/S-R Flip-Flop', 1, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/ssi_clock_generator/S-R Flip-Flop1', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/sample_serial_data/sample_serial_data', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/sample_serial_data/sample_serial_data', 1, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/sample_serial_data', 1, 1, '');
