SLStudio.Utils.RemoveHighlighting(get_param('uz_ssi_interface_2023a', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_uz_ssi_interface_2023a', 'handle'));
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/shift arithmetic2', 1, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/Shift Arithmetic2', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/shift arithmetic3', 1, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/Shift Arithmetic3', 1, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/S-R Flip-Flop1', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/shift arithmetic', 1, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/Shift Arithmetic', 1, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/S-R Flip-Flop', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/floor_div_pow2/shift arithmetic4', 1, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/floor_div_pow2/Shift Arithmetic4', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/floor_div_pow2/shift arithmetic5', 1, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/floor_div_pow2/Shift Arithmetic5', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Relational Operator4', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/AND1', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Delay20', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Product1', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Sum5', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/delayMatch5', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/cos_hdl/Look-Up Table', 0, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/cos_hdl/Look-Up Table', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/Look-Up Table', 0, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/Look-Up Table', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/shift arithmetic', 1, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/Shift Arithmetic', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/shift arithmetic1', 1, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/Shift Arithmetic1', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/shift arithmetic2', 1, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/Shift Arithmetic2', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/shift arithmetic3_nonneg', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/shift arithmetic3', 1, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/Shift Arithmetic3', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/shift arithmetic4_nonneg', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/shift arithmetic4', 1, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/Shift Arithmetic4', 1, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/ssi_communication/clk_idle_and_delay_first_clock_function/S-R Flip-Flop', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/ssi_communication/sample_serial_ssi_data/Bitwise Operator1', 1, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/ssi_communication/sample_serial_ssi_data/Bitwise Operator1', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/ssi_communication/sample_serial_ssi_data/shift arithmetic', 1, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/ssi_communication/sample_serial_ssi_data/Shift Arithmetic', 1, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/ssi_communication/ssi_clock_enable_for_n_bits/S-R Flip-Flop', 1, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/ssi_communication/ssi_clock_generator/S-R Flip-Flop1', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/fixed_point_floor/fixed_point_floor', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/fixed_point_floor/fixed_point_floor', 1, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/fixed_point_floor', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/wrap_2pi/fixed_point_floor/fixed_point_floor', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/wrap_2pi/fixed_point_floor/fixed_point_floor', 1, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/wrap_2pi/fixed_point_floor', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Delay20/Delay20', 1, 1, '');
