SLStudio.Utils.RemoveHighlighting(get_param('uz_ssi_interface_2023a', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_uz_ssi_interface_2023a', 'handle'));
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll', 0, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/S-R Flip-Flop1', 1, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/clk_idle_and_delay_first_clock_function/S-R Flip-Flop', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized1', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Delay1', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Delay14', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/mux', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/Look-Up Table', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/CastU16En2', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/CastU16En3', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/CastU16En4', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/LTEp25', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/LTEp50', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/Negate', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/QuadHandle1', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/QuadHandle2', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/Saturation', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/SignCorrected', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/Switch', 0, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Sine HDL Optimized1/sincos hdl/sin_hdl/insig', 0, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/ssi_clock_enable_for_n_bits/S-R Flip-Flop', 1, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/ssi_clock_generator/S-R Flip-Flop1', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/fixed_point_floor/fixed_point_floor', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/fixed_point_floor/fixed_point_floor', 1, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/fixed_point_floor', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/sample_serial_data/sample_serial_data', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/sample_serial_data/sample_serial_data', 1, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/sample_serial_data', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/slice_position_and_status/slice_position_and_status', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/slice_position_and_status/slice_position_and_status', 1, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/slice_position_and_status', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/wrap_2pi/fixed_point_floor/fixed_point_floor', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/wrap_2pi/fixed_point_floor/fixed_point_floor', 1, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/wrap_2pi/fixed_point_floor', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/wrap_2pi_after_offset/fixed_point_floor/fixed_point_floor', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/wrap_2pi_after_offset/fixed_point_floor/fixed_point_floor', 1, 1, '');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/wrap_2pi_after_offset/fixed_point_floor', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Delay1/Delay1', 1, 1, '');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Delay14/Delay14', 0, 1, '');
