open_system('gm_uz_ssi_interface_2023a');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/Detect Rise Positive1', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/Detect Rise Positive1', 0, 1, 'cp : 1.704 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data', 1, 5, 'cp : 6.638 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/Delay32', 'user1');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/Delay32', 0, 1, 'cp : 0.33 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/Switch4', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/Switch4', 0, 1, 'cp : 2.056 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/Detect Rise Positive1/FixPt Relational Operator', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/Detect Rise Positive1/FixPt Relational Operator', 0, 1, 'cp : 1.704 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/Detect Rise Positive1/Positive', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/Detect Rise Positive1/Positive', 0, 1, 'cp : 1.017 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/Detect Rise Positive2', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/Detect Rise Positive2', 0, 1, 'cp : 5.987 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/Delay1', 'user1');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/Delay1', 1, 1, 'cp : 6.638 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/saturate', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/saturate', 0, 1, 'cp : 3.342 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/multiportswitch', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/multiportswitch', 0, 1, 'cp : 4.329 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/NOT', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/NOT', 0, 1, 'cp : 4.613 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/Switch', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/Switch', 0, 1, 'cp : 6.377 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/Detect Rise Positive2/FixPt Relational Operator', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/Detect Rise Positive2/FixPt Relational Operator', 0, 1, 'cp : 5.987 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/Detect Rise Positive2/Positive', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/Detect Rise Positive2/Positive', 0, 1, 'cp : 5.3 ns');
