open_system('gm_uz_ssi_interface_2023a');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll', 0, 1, 'cp : 7.954 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Relational Operator4', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Relational Operator4', 0, 1, 'cp : 6.833 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/AND1', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/AND1', 0, 1, 'cp : 7.693 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Delay20', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Delay20', 1, 1, 'cp : 7.954 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Product1', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Product1', 0, 1, 'cp : 5.206 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Sum5', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Sum5', 0, 1, 'cp : 5.916 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/delayMatch5', 'user1');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/delayMatch5', 0, 1, 'cp : 0.33 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Delay20/Delay20', 'user1');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Delay20/Delay20', 1, 1, 'cp : 7.954 ns');
