open_system('gm_uz_ssi_interface_2023a');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll', 0, 1, 'cp : 8.26 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Constant8', 'user1');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Constant8', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/From14', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/From14', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Goto11', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Goto11', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Relational Operator4', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Relational Operator4', 0, 1, 'cp : 6.503 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/AND1', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/AND1', 0, 1, 'cp : 7.363 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Product1', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Product1', 0, 1, 'cp : 4.876 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Sum5', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Sum5', 0, 1, 'cp : 5.586 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Switch4', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Switch4', 0, 1, 'cp : 7.715 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Delay19', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Delay19', 1, 1, 'cp : 8.26 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Switch3', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Switch3', 0, 1, 'cp : 7.999 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Delay19/Delay19', 'user1');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/Delay19/Delay19', 1, 1, 'cp : 8.26 ns');
