open_system('uz_ssi_interface_2023a');
open_system('gm_uz_ssi_interface_2023a');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/shift arithmetic', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/shift arithmetic', 1, 1, 'Block not characterized');
hilite_system('uz_ssi_interface_2023a/uz_ssi_interface/Shift Arithmetic', 'user2');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/Shift Arithmetic', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/shift arithmetic1', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/shift arithmetic1', 1, 1, 'Block not characterized');
hilite_system('uz_ssi_interface_2023a/uz_ssi_interface/Shift Arithmetic1', 'user2');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/Shift Arithmetic1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_ssi_interface_2023a/uz_ssi_interface/S-R Flip-Flop1', 'user2');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/S-R Flip-Flop1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/shift arithmetic', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/shift arithmetic', 1, 1, 'Block not characterized');
hilite_system('uz_ssi_interface_2023a/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/Shift Arithmetic', 'user2');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/Shift Arithmetic', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_ssi_interface_2023a/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/S-R Flip-Flop', 'user2');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/Gray_code_to_binary/gray_to_bin/S-R Flip-Flop', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/int_div_floor_pow2/shift arithmetic2', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/int_div_floor_pow2/shift arithmetic2', 1, 1, 'Block not characterized');
hilite_system('uz_ssi_interface_2023a/uz_ssi_interface/int_div_floor_pow2/Shift Arithmetic2', 'user2');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/int_div_floor_pow2/Shift Arithmetic2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/int_div_floor_pow2/shift arithmetic3', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/int_div_floor_pow2/shift arithmetic3', 1, 1, 'Block not characterized');
hilite_system('uz_ssi_interface_2023a/uz_ssi_interface/int_div_floor_pow2/Shift Arithmetic3', 'user2');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/int_div_floor_pow2/Shift Arithmetic3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/int_div_floor_pow2/shift arithmetic4', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/int_div_floor_pow2/shift arithmetic4', 1, 1, 'Block not characterized');
hilite_system('uz_ssi_interface_2023a/uz_ssi_interface/int_div_floor_pow2/Shift Arithmetic4', 'user2');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/int_div_floor_pow2/Shift Arithmetic4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/shift arithmetic', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/shift arithmetic', 1, 1, 'Block not characterized');
hilite_system('uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/Shift Arithmetic', 'user2');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/Shift Arithmetic', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/shift arithmetic1', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/shift arithmetic1', 1, 1, 'Block not characterized');
hilite_system('uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/Shift Arithmetic1', 'user2');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/Shift Arithmetic1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/shift arithmetic2', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/shift arithmetic2', 1, 1, 'Block not characterized');
hilite_system('uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/Shift Arithmetic2', 'user2');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/Shift Arithmetic2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/shift arithmetic3_nonneg', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/shift arithmetic3_nonneg', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/shift arithmetic3', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/shift arithmetic3', 1, 1, 'Block not characterized');
hilite_system('uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/Shift Arithmetic3', 'user2');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/Shift Arithmetic3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/shift arithmetic4_nonneg', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/shift arithmetic4_nonneg', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/shift arithmetic4', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/shift arithmetic4', 1, 1, 'Block not characterized');
hilite_system('uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/Shift Arithmetic4', 'user2');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/slice_position_and_status/Shift Arithmetic4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_ssi_interface_2023a/uz_ssi_interface/ssi_communication/clk_idle_and_delay_first_clock_function/S-R Flip-Flop', 'user2');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/ssi_communication/clk_idle_and_delay_first_clock_function/S-R Flip-Flop', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/ssi_communication/sample_serial_ssi_data/Bitwise Operator1', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/ssi_communication/sample_serial_ssi_data/Bitwise Operator1', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_ssi_interface_2023a/uz_ssi_interface/ssi_communication/sample_serial_ssi_data/Bitwise Operator1', 'user2');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/ssi_communication/sample_serial_ssi_data/Bitwise Operator1', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/ssi_communication/sample_serial_ssi_data/shift arithmetic', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/ssi_communication/sample_serial_ssi_data/shift arithmetic', 1, 1, 'Block not characterized');
hilite_system('uz_ssi_interface_2023a/uz_ssi_interface/ssi_communication/sample_serial_ssi_data/Shift Arithmetic', 'user2');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/ssi_communication/sample_serial_ssi_data/Shift Arithmetic', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_ssi_interface_2023a/uz_ssi_interface/ssi_communication/ssi_clock_enable_for_n_bits/S-R Flip-Flop', 'user2');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/ssi_communication/ssi_clock_enable_for_n_bits/S-R Flip-Flop', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_ssi_interface_2023a/uz_ssi_interface/ssi_communication/ssi_clock_generator/S-R Flip-Flop1', 'user2');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/ssi_communication/ssi_clock_generator/S-R Flip-Flop1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/fixed_point_floor/fixed_point_floor', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/fixed_point_floor/fixed_point_floor', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/fixed_point_floor/fixed_point_floor', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/fixed_point_floor/fixed_point_floor', 1, 1, 'Block not characterized');
hilite_system('uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/fixed_point_floor', 'user2');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/position_to_speed_pll/fixed_point_floor', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/wrap_2pi/fixed_point_floor/fixed_point_floor', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/wrap_2pi/fixed_point_floor/fixed_point_floor', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/wrap_2pi/fixed_point_floor/fixed_point_floor', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/wrap_2pi/fixed_point_floor/fixed_point_floor', 1, 1, 'Block not characterized');
hilite_system('uz_ssi_interface_2023a/uz_ssi_interface/wrap_2pi/fixed_point_floor', 'user2');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/wrap_2pi/fixed_point_floor', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
