open_system('uz_ssi_interface_2023a');
open_system('gm_uz_ssi_interface_2023a');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/Data Type Conversion', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/Data Type Conversion', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_ssi_interface_2023a/uz_ssi_interface/Data Type Conversion', 'user2');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/Data Type Conversion', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_ssi_interface_2023a/uz_ssi_interface/ssi_clock_enable_for_n_plus_one_bits/S-R Flip-Flop', 'user2');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/ssi_clock_enable_for_n_plus_one_bits/S-R Flip-Flop', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('uz_ssi_interface_2023a/uz_ssi_interface/ssi_clock_generator/S-R Flip-Flop1', 'user2');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/ssi_clock_generator/S-R Flip-Flop1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/Serial_In_Parallel_Out/Serial_In_Parallel_Out', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/Serial_In_Parallel_Out/Serial_In_Parallel_Out', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/Serial_In_Parallel_Out/Serial_In_Parallel_Out', 'user2');
annotate_port('gm_uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/Serial_In_Parallel_Out/Serial_In_Parallel_Out', 1, 1, 'Block not characterized');
hilite_system('uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/Serial_In_Parallel_Out', 'user2');
annotate_port('uz_ssi_interface_2023a/uz_ssi_interface/sample_serial_ssi_data/Serial_In_Parallel_Out', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
