SLStudio.Utils.RemoveHighlighting(get_param('uz_dac_spi_interface', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_uz_dac_spi_interface', 'handle'));
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Detect Rise Positive', 1, 1, '');
annotate_port('uz_dac_spi_interface/uz_dac_spi_interface/Detect Rise Positive', 1, 1, '');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Delay', 0, 1, '');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Delay', 1, 1, '');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D', 0, 2, '');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D', 1, 1, '');
annotate_port('uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D', 1, 1, '');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D1', 1, 1, '');
annotate_port('uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D1', 1, 1, '');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D2', 1, 1, '');
annotate_port('uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D2', 1, 1, '');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D3', 1, 1, '');
annotate_port('uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D3', 1, 1, '');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D4', 1, 1, '');
annotate_port('uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D4', 1, 1, '');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D5', 1, 1, '');
annotate_port('uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D5', 1, 1, '');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D6', 1, 1, '');
annotate_port('uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D6', 1, 1, '');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D7', 1, 1, '');
annotate_port('uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D7', 1, 1, '');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/AND1', 0, 1, '');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/AND2', 0, 1, '');
