open_system('gm_uz_dac_spi_interface');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_dac_spi_interface/uz_dac_spi_interface/Delay10', 'user1');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Delay10', 0, 1, 'cp : 0.33 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_dac_spi_interface/uz_dac_spi_interface/Rate Transition2', 'user1');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Rate Transition2', 1, 1, 'cp : 3.647 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_dac_spi_interface/uz_dac_spi_interface/OR', 'user2');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/OR', 0, 1, 'cp : 3.386 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_dac_spi_interface/uz_dac_spi_interface/OR1', 'user2');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/OR1', 0, 1, 'cp : 1.272 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_dac_spi_interface/uz_dac_spi_interface/OR3', 'user2');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/OR3', 0, 1, 'cp : 2.444 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_dac_spi_interface/uz_dac_spi_interface/OR4', 'user2');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/OR4', 0, 1, 'cp : 1.556 ns');
