open_system('gm_uz_dac_spi_interface');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_dac_spi_interface/uz_dac_spi_interface/Detect Rise Positive1', 'user2');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Detect Rise Positive1', 0, 1, 'cp : 2.094 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_dac_spi_interface/uz_dac_spi_interface/Detect Rise Positive2', 'user2');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Detect Rise Positive2', 0, 1, 'cp : 3.964 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_dac_spi_interface/uz_dac_spi_interface/keep_high', 'user2');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/keep_high', 0, 1, 'cp : 2.446 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_dac_spi_interface/uz_dac_spi_interface/shadow_register', 'user2');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/shadow_register', 0, 1, 'cp : 4.316 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_dac_spi_interface/uz_dac_spi_interface/Delay9', 'user1');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Delay9', 0, 1, 'cp : 0.33 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_dac_spi_interface/uz_dac_spi_interface/Rate Transition1', 'user1');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Rate Transition1', 1, 1, 'cp : 4.577 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_dac_spi_interface/uz_dac_spi_interface/Switch8', 'user2');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Switch8', 0, 1, 'cp : 0.72 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_dac_spi_interface/uz_dac_spi_interface/Detect Rise Positive1/FixPt Relational Operator', 'user2');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Detect Rise Positive1/FixPt Relational Operator', 0, 1, 'cp : 2.094 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_dac_spi_interface/uz_dac_spi_interface/Detect Rise Positive1/Positive', 'user2');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Detect Rise Positive1/Positive', 0, 1, 'cp : 1.407 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_dac_spi_interface/uz_dac_spi_interface/Detect Rise Positive2/FixPt Relational Operator', 'user2');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Detect Rise Positive2/FixPt Relational Operator', 0, 1, 'cp : 3.964 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_dac_spi_interface/uz_dac_spi_interface/Detect Rise Positive2/Positive', 'user2');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Detect Rise Positive2/Positive', 0, 1, 'cp : 3.277 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_dac_spi_interface/uz_dac_spi_interface/keep_high/Switch17', 'user2');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/keep_high/Switch17', 0, 1, 'cp : 2.446 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_dac_spi_interface/uz_dac_spi_interface/shadow_register/Switch17', 'user2');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/shadow_register/Switch17', 0, 1, 'cp : 4.316 ns');
