open_system('uz_dac_spi_interface');
open_system('gm_uz_dac_spi_interface');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_dac_spi_interface/uz_dac_spi_interface/Detect Rise Positive', 'user2');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Detect Rise Positive', 1, 1, 'Block not characterized');
hilite_system('uz_dac_spi_interface/uz_dac_spi_interface/Detect Rise Positive', 'user2');
annotate_port('uz_dac_spi_interface/uz_dac_spi_interface/Detect Rise Positive', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D', 'user2');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D', 1, 1, 'Block not characterized');
hilite_system('uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D', 'user2');
annotate_port('uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D1', 'user2');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D1', 1, 1, 'Block not characterized');
hilite_system('uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D1', 'user2');
annotate_port('uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D2', 'user2');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D2', 1, 1, 'Block not characterized');
hilite_system('uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D2', 'user2');
annotate_port('uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D3', 'user2');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D3', 1, 1, 'Block not characterized');
hilite_system('uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D3', 'user2');
annotate_port('uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D4', 'user2');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D4', 1, 1, 'Block not characterized');
hilite_system('uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D4', 'user2');
annotate_port('uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D5', 'user2');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D5', 1, 1, 'Block not characterized');
hilite_system('uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D5', 'user2');
annotate_port('uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D6', 'user2');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D6', 1, 1, 'Block not characterized');
hilite_system('uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D6', 'user2');
annotate_port('uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D6', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D7', 'user2');
annotate_port('gm_uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D7', 1, 1, 'Block not characterized');
hilite_system('uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D7', 'user2');
annotate_port('uz_dac_spi_interface/uz_dac_spi_interface/Serializer1D7', 1, 1, 'Block not characterized');
