SLStudio.Utils.RemoveHighlighting(get_param('VSD_and_Park_transformation_6Phase', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_VSD_and_Park_transformation_6Phase', 'handle'));
annotate_port('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Compare To Constant', 1, 1, '');
annotate_port('VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Compare To Constant', 1, 1, '');
annotate_port('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Compare To Constant1', 1, 1, '');
annotate_port('VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Compare To Constant1', 1, 1, '');
annotate_port('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Detect Rise Positive', 1, 1, '');
annotate_port('VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Detect Rise Positive', 1, 1, '');
annotate_port('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Sine HDL Optimized', 0, 1, '');
annotate_port('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Detect Rise Positive/Positive', 1, 1, '');
annotate_port('VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Detect Rise Positive/Positive', 1, 1, '');
annotate_port('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Sine HDL Optimized/sincos hdl', 0, 1, '');
annotate_port('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Sine HDL Optimized/sincos hdl/sin_hdl', 0, 1, '');
annotate_port('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Sine HDL Optimized/sincos hdl/cos_hdl/Look-Up Table', 0, 1, '');
annotate_port('VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Sine HDL Optimized/sincos hdl/cos_hdl/Look-Up Table', 0, 1, '');
annotate_port('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Sine HDL Optimized/sincos hdl/sin_hdl/Point50', 0, 1, '');
annotate_port('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Sine HDL Optimized/sincos hdl/sin_hdl/CastU16En2', 0, 1, '');
annotate_port('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Sine HDL Optimized/sincos hdl/sin_hdl/CastU16En3', 0, 1, '');
annotate_port('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Sine HDL Optimized/sincos hdl/sin_hdl/CastU16En4', 0, 1, '');
annotate_port('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Sine HDL Optimized/sincos hdl/sin_hdl/LTEp25', 0, 1, '');
annotate_port('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Sine HDL Optimized/sincos hdl/sin_hdl/LTEp50', 0, 1, '');
annotate_port('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Sine HDL Optimized/sincos hdl/sin_hdl/Look-Up Table', 0, 1, '');
annotate_port('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Sine HDL Optimized/sincos hdl/sin_hdl/Look-Up Table', 0, 1, '');
annotate_port('VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Sine HDL Optimized/sincos hdl/sin_hdl/Look-Up Table', 0, 1, '');
annotate_port('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Sine HDL Optimized/sincos hdl/sin_hdl/QuadHandle1', 0, 1, '');
annotate_port('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Sine HDL Optimized/sincos hdl/sin_hdl/QuadHandle2', 0, 1, '');
annotate_port('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Sine HDL Optimized/sincos hdl/sin_hdl/Saturation', 0, 1, '');
annotate_port('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Sine HDL Optimized/sincos hdl/sin_hdl/Switch', 0, 1, '');
annotate_port('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Sine HDL Optimized/sincos hdl/sin_hdl/PipelineRegister', 1, 1, '');
annotate_port('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/MATLAB Function/MATLAB Function', 1, 1, '');
annotate_port('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/MATLAB Function/MATLAB Function', 1, 1, '');
annotate_port('VSD_and_Park_transformation_6Phase/vsd_and_park_tra/MATLAB Function', 1, 1, '');
