open_system('VSD_and_Park_transformation_6Phase');
open_system('gm_VSD_and_Park_transformation_6Phase');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Compare To Constant', 'user2');
annotate_port('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Compare To Constant', 1, 1, 'Block not characterized');
hilite_system('VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Compare To Constant', 'user2');
annotate_port('VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Compare To Constant', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Compare To Constant1', 'user2');
annotate_port('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Compare To Constant1', 1, 1, 'Block not characterized');
hilite_system('VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Compare To Constant1', 'user2');
annotate_port('VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Compare To Constant1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Detect Rise Positive', 'user2');
annotate_port('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Detect Rise Positive', 1, 1, 'Block not characterized');
hilite_system('VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Detect Rise Positive', 'user2');
annotate_port('VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Detect Rise Positive', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Detect Rise Positive/Positive', 'user2');
annotate_port('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Detect Rise Positive/Positive', 1, 1, 'Block not characterized');
hilite_system('VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Detect Rise Positive/Positive', 'user2');
annotate_port('VSD_and_Park_transformation_6Phase/vsd_and_park_tra/Detect Rise Positive/Positive', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/MATLAB Function/MATLAB Function', 'user2');
annotate_port('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/MATLAB Function/MATLAB Function', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/MATLAB Function/MATLAB Function', 'user2');
annotate_port('gm_VSD_and_Park_transformation_6Phase/vsd_and_park_tra/MATLAB Function/MATLAB Function', 1, 1, 'Block not characterized');
hilite_system('VSD_and_Park_transformation_6Phase/vsd_and_park_tra/MATLAB Function', 'user2');
annotate_port('VSD_and_Park_transformation_6Phase/vsd_and_park_tra/MATLAB Function', 1, 1, 'Block not characterized');
