SLStudio.Utils.RemoveHighlighting(get_param('parallel_8_delay_compensation', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_parallel_8_delay_compensation', 'handle'));
annotate_port('gm_parallel_8_delay_compensation/HDL_DUT/MATLAB Function', 0, 1, '');
annotate_port('gm_parallel_8_delay_compensation/HDL_DUT/Data Type Conversion', 1, 1, '');
annotate_port('parallel_8_delay_compensation/HDL_DUT/Data Type Conversion', 1, 1, '');
annotate_port('gm_parallel_8_delay_compensation/HDL_DUT/Data Type Conversion1', 1, 1, '');
annotate_port('parallel_8_delay_compensation/HDL_DUT/Data Type Conversion1', 1, 1, '');
annotate_port('gm_parallel_8_delay_compensation/HDL_DUT/Data Type Conversion10', 1, 1, '');
annotate_port('parallel_8_delay_compensation/HDL_DUT/Data Type Conversion10', 1, 1, '');
annotate_port('gm_parallel_8_delay_compensation/HDL_DUT/Data Type Conversion11', 1, 1, '');
annotate_port('parallel_8_delay_compensation/HDL_DUT/Data Type Conversion11', 1, 1, '');
annotate_port('gm_parallel_8_delay_compensation/HDL_DUT/Data Type Conversion12', 1, 1, '');
annotate_port('parallel_8_delay_compensation/HDL_DUT/Data Type Conversion12', 1, 1, '');
annotate_port('gm_parallel_8_delay_compensation/HDL_DUT/Data Type Conversion2', 1, 1, '');
annotate_port('parallel_8_delay_compensation/HDL_DUT/Data Type Conversion2', 1, 1, '');
annotate_port('gm_parallel_8_delay_compensation/HDL_DUT/Data Type Conversion3', 1, 1, '');
annotate_port('parallel_8_delay_compensation/HDL_DUT/Data Type Conversion3', 1, 1, '');
annotate_port('gm_parallel_8_delay_compensation/HDL_DUT/Data Type Conversion4', 1, 1, '');
annotate_port('parallel_8_delay_compensation/HDL_DUT/Data Type Conversion4', 1, 1, '');
annotate_port('gm_parallel_8_delay_compensation/HDL_DUT/Data Type Conversion5', 1, 1, '');
annotate_port('parallel_8_delay_compensation/HDL_DUT/Data Type Conversion5', 1, 1, '');
annotate_port('gm_parallel_8_delay_compensation/HDL_DUT/Data Type Conversion6', 1, 1, '');
annotate_port('parallel_8_delay_compensation/HDL_DUT/Data Type Conversion6', 1, 1, '');
annotate_port('gm_parallel_8_delay_compensation/HDL_DUT/Data Type Conversion7', 1, 1, '');
annotate_port('parallel_8_delay_compensation/HDL_DUT/Data Type Conversion7', 1, 1, '');
annotate_port('gm_parallel_8_delay_compensation/HDL_DUT/Data Type Conversion8', 1, 1, '');
annotate_port('parallel_8_delay_compensation/HDL_DUT/Data Type Conversion8', 1, 1, '');
annotate_port('gm_parallel_8_delay_compensation/HDL_DUT/Data Type Conversion9', 1, 1, '');
annotate_port('parallel_8_delay_compensation/HDL_DUT/Data Type Conversion9', 1, 1, '');
annotate_port('gm_parallel_8_delay_compensation/HDL_DUT/MATLAB Function/adder', 0, 1, '');
