SLStudio.Utils.RemoveHighlighting(get_param('parallel_8_delay_compensation', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_parallel_8_delay_compensation', 'handle'));
annotate_port('gm_parallel_8_delay_compensation/Delay_compensation/MATLAB Function', 0, 1, '');
annotate_port('gm_parallel_8_delay_compensation/Delay_compensation/Data Type Conversion13', 1, 1, '');
annotate_port('parallel_8_delay_compensation/Delay_compensation/Data Type Conversion13', 1, 1, '');
annotate_port('gm_parallel_8_delay_compensation/Delay_compensation/Data Type Conversion14', 1, 1, '');
annotate_port('parallel_8_delay_compensation/Delay_compensation/Data Type Conversion14', 1, 1, '');
annotate_port('gm_parallel_8_delay_compensation/Delay_compensation/Data Type Conversion15', 1, 1, '');
annotate_port('parallel_8_delay_compensation/Delay_compensation/Data Type Conversion15', 1, 1, '');
annotate_port('gm_parallel_8_delay_compensation/Delay_compensation/Data Type Conversion16', 1, 1, '');
annotate_port('parallel_8_delay_compensation/Delay_compensation/Data Type Conversion16', 1, 1, '');
annotate_port('gm_parallel_8_delay_compensation/Delay_compensation/Data Type Conversion17', 1, 1, '');
annotate_port('parallel_8_delay_compensation/Delay_compensation/Data Type Conversion17', 1, 1, '');
annotate_port('gm_parallel_8_delay_compensation/Delay_compensation/Data Type Conversion2', 1, 1, '');
annotate_port('parallel_8_delay_compensation/Delay_compensation/Data Type Conversion2', 1, 1, '');
annotate_port('gm_parallel_8_delay_compensation/Delay_compensation/Data Type Conversion3', 1, 1, '');
annotate_port('parallel_8_delay_compensation/Delay_compensation/Data Type Conversion3', 1, 1, '');
annotate_port('gm_parallel_8_delay_compensation/Delay_compensation/Data Type Conversion5', 1, 1, '');
annotate_port('parallel_8_delay_compensation/Delay_compensation/Data Type Conversion5', 1, 1, '');
annotate_port('gm_parallel_8_delay_compensation/Delay_compensation/Data Type Conversion6', 1, 1, '');
annotate_port('parallel_8_delay_compensation/Delay_compensation/Data Type Conversion6', 1, 1, '');
annotate_port('gm_parallel_8_delay_compensation/Delay_compensation/Data Type Conversion7', 1, 1, '');
annotate_port('parallel_8_delay_compensation/Delay_compensation/Data Type Conversion7', 1, 1, '');
annotate_port('gm_parallel_8_delay_compensation/Delay_compensation/Data Type Conversion8', 1, 1, '');
annotate_port('parallel_8_delay_compensation/Delay_compensation/Data Type Conversion8', 1, 1, '');
annotate_port('gm_parallel_8_delay_compensation/Delay_compensation/Data Type Conversion9', 1, 1, '');
annotate_port('parallel_8_delay_compensation/Delay_compensation/Data Type Conversion9', 1, 1, '');
annotate_port('gm_parallel_8_delay_compensation/Delay_compensation/MATLAB Function/adder', 0, 1, '');
