function CodeDefine() { 
this.def = new Array();
this.def["uz_codegen0.c:factoryConstruct"] = {file: "uz_codegen0_c.html",line:215,type:"fcn"};
this.def["uz_codegen0.c:xnrm2"] = {file: "uz_codegen0_c.html",line:226,type:"fcn"};
this.def["rt_hypotd"] = {file: "uz_codegen0_c.html",line:257,type:"fcn"};
this.def["uz_codegen0.c:xzlarfg"] = {file: "uz_codegen0_c.html",line:278,type:"fcn"};
this.def["uz_codegen0.c:xzlarf"] = {file: "uz_codegen0_c.html",line:340,type:"fcn"};
this.def["uz_codegen0.c:qrf"] = {file: "uz_codegen0_c.html",line:433,type:"fcn"};
this.def["uz_codegen0.c:qrpf"] = {file: "uz_codegen0_c.html",line:461,type:"fcn"};
this.def["uz_codegen0.c:xzgeqp3"] = {file: "uz_codegen0_c.html",line:575,type:"fcn"};
this.def["uz_codegen0.c:computeQ_"] = {file: "uz_codegen0_c.html",line:636,type:"fcn"};
this.def["uz_codegen0.c:ComputeNumDependentEq_"] = {file: "uz_codegen0_c.html",line:781,type:"fcn"};
this.def["uz_codegen0.c:IndexOfDependentEq_"] = {file: "uz_codegen0_c.html",line:822,type:"fcn"};
this.def["uz_codegen0.c:countsort"] = {file: "uz_codegen0_c.html",line:857,type:"fcn"};
this.def["uz_codegen0.c:moveConstraint_"] = {file: "uz_codegen0_c.html",line:899,type:"fcn"};
this.def["uz_codegen0.c:removeEqConstr"] = {file: "uz_codegen0_c.html",line:914,type:"fcn"};
this.def["uz_codegen0.c:RemoveDependentEq_"] = {file: "uz_codegen0_c.html",line:944,type:"fcn"};
this.def["uz_codegen0.c:removeAllIneqConstr"] = {file: "uz_codegen0_c.html",line:1110,type:"fcn"};
this.def["uz_codegen0.c:RemoveDependentIneq_"] = {file: "uz_codegen0_c.html",line:1126,type:"fcn"};
this.def["uz_codegen0.c:factorQR_f"] = {file: "uz_codegen0_c.html",line:1229,type:"fcn"};
this.def["uz_codegen0.c:factorQR"] = {file: "uz_codegen0_c.html",line:1279,type:"fcn"};
this.def["uz_codegen0.c:xgemv"] = {file: "uz_codegen0_c.html",line:1310,type:"fcn"};
this.def["uz_codegen0.c:xgemv_p"] = {file: "uz_codegen0_c.html",line:1344,type:"fcn"};
this.def["uz_codegen0.c:maxConstraintViolation"] = {file: "uz_codegen0_c.html",line:1378,type:"fcn"};
this.def["uz_codegen0.c:xgemv_py"] = {file: "uz_codegen0_c.html",line:1468,type:"fcn"};
this.def["uz_codegen0.c:xgemv_pym"] = {file: "uz_codegen0_c.html",line:1502,type:"fcn"};
this.def["uz_codegen0.c:maxConstraintViolation_p"] = {file: "uz_codegen0_c.html",line:1536,type:"fcn"};
this.def["uz_codegen0.c:feasibleX0ForWorkingSet"] = {file: "uz_codegen0_c.html",line:1626,type:"fcn"};
this.def["uz_codegen0.c:xgemv_pyma"] = {file: "uz_codegen0_c.html",line:1872,type:"fcn"};
this.def["uz_codegen0.c:xgemv_pyma2"] = {file: "uz_codegen0_c.html",line:1906,type:"fcn"};
this.def["uz_codegen0.c:maxConstraintViolation_pn"] = {file: "uz_codegen0_c.html",line:1940,type:"fcn"};
this.def["uz_codegen0.c:PresolveWorkingSet"] = {file: "uz_codegen0_c.html",line:2030,type:"fcn"};
this.def["uz_codegen0.c:modifyOverheadPhaseOne_"] = {file: "uz_codegen0_c.html",line:2054,type:"fcn"};
this.def["uz_codegen0.c:setProblemType"] = {file: "uz_codegen0_c.html",line:2088,type:"fcn"};
this.def["uz_codegen0.c:linearForm_"] = {file: "uz_codegen0_c.html",line:2280,type:"fcn"};
this.def["uz_codegen0.c:computeFval"] = {file: "uz_codegen0_c.html",line:2328,type:"fcn"};
this.def["uz_codegen0.c:xgemv_pyma2z"] = {file: "uz_codegen0_c.html",line:2366,type:"fcn"};
this.def["uz_codegen0.c:computeGrad_StoreHx"] = {file: "uz_codegen0_c.html",line:2398,type:"fcn"};
this.def["uz_codegen0.c:computeFval_ReuseHx"] = {file: "uz_codegen0_c.html",line:2458,type:"fcn"};
this.def["uz_codegen0.c:printHeader"] = {file: "uz_codegen0_c.html",line:2533,type:"fcn"};
this.def["uz_codegen0.c:printInitialInfo"] = {file: "uz_codegen0_c.html",line:2544,type:"fcn"};
this.def["uz_codegen0.c:xrotg"] = {file: "uz_codegen0_c.html",line:2602,type:"fcn"};
this.def["uz_codegen0.c:deleteColMoveEnd"] = {file: "uz_codegen0_c.html",line:2642,type:"fcn"};
this.def["uz_codegen0.c:computeProjectedHessian"] = {file: "uz_codegen0_c.html",line:2761,type:"fcn"};
this.def["uz_codegen0.c:ixamax"] = {file: "uz_codegen0_c.html",line:2847,type:"fcn"};
this.def["uz_codegen0.c:fullColLDL2_"] = {file: "uz_codegen0_c.html",line:2876,type:"fcn"};
this.def["uz_codegen0.c:xgemv_pyma2zx"] = {file: "uz_codegen0_c.html",line:2936,type:"fcn"};
this.def["uz_codegen0.c:compute_deltax"] = {file: "uz_codegen0_c.html",line:2968,type:"fcn"};
this.def["uz_codegen0.c:xnrm2_j"] = {file: "uz_codegen0_c.html",line:3223,type:"fcn"};
this.def["uz_codegen0.c:xgemv_pyma2zxi"] = {file: "uz_codegen0_c.html",line:3256,type:"fcn"};
this.def["uz_codegen0.c:xgemv_pyma2zxid"] = {file: "uz_codegen0_c.html",line:3291,type:"fcn"};
this.def["uz_codegen0.c:ratiotest"] = {file: "uz_codegen0_c.html",line:3326,type:"fcn"};
this.def["uz_codegen0.c:feasibleratiotest"] = {file: "uz_codegen0_c.html",line:3500,type:"fcn"};
this.def["uz_codegen0.c:checkUnboundedOrIllPosed"] = {file: "uz_codegen0_c.html",line:3617,type:"fcn"};
this.def["uz_codegen0.c:addBoundToActiveSetMatrix_"] = {file: "uz_codegen0_c.html",line:3631,type:"fcn"};
this.def["uz_codegen0.c:compute_lambda"] = {file: "uz_codegen0_c.html",line:3672,type:"fcn"};
this.def["uz_codegen0.c:checkStoppingAndUpdateFval"] = {file: "uz_codegen0_c.html",line:3776,type:"fcn"};
this.def["uz_codegen0.c:computeFirstOrderOpt"] = {file: "uz_codegen0_c.html",line:3835,type:"fcn"};
this.def["uz_codegen0.c:printInfo"] = {file: "uz_codegen0_c.html",line:3892,type:"fcn"};
this.def["uz_codegen0.c:iterate"] = {file: "uz_codegen0_c.html",line:4004,type:"fcn"};
this.def["uz_codegen0.c:phaseone"] = {file: "uz_codegen0_c.html",line:4339,type:"fcn"};
this.def["uz_codegen0.c:ComputeNumDependentEq__d"] = {file: "uz_codegen0_c.html",line:4480,type:"fcn"};
this.def["uz_codegen0.c:IndexOfDependentEq__i"] = {file: "uz_codegen0_c.html",line:4560,type:"fcn"};
this.def["uz_codegen0.c:RemoveDependentEq__b"] = {file: "uz_codegen0_c.html",line:4602,type:"fcn"};
this.def["uz_codegen0.c:PresolveWorkingSet_l"] = {file: "uz_codegen0_c.html",line:4657,type:"fcn"};
this.def["uz_codegen0.c:strcmp_m"] = {file: "uz_codegen0_c.html",line:4682,type:"fcn"};
this.def["uz_codegen0.c:phaseone_j"] = {file: "uz_codegen0_c.html",line:4721,type:"fcn"};
this.def["uz_codegen0.c:driver"] = {file: "uz_codegen0_c.html",line:4802,type:"fcn"};
this.def["uz_codegen0.c:linearForm__a"] = {file: "uz_codegen0_c.html",line:4981,type:"fcn"};
this.def["uz_codegen0.c:quadprog"] = {file: "uz_codegen0_c.html",line:5026,type:"fcn"};
this.def["uz_codegen0_step"] = {file: "uz_codegen0_c.html",line:5146,type:"fcn"};
this.def["uz_codegen0_initialize"] = {file: "uz_codegen0_c.html",line:7338,type:"fcn"};
this.def["RT_MODEL"] = {file: "uz_codegen0_h.html",line:64,type:"type"};
this.def["sVm5xLhdFDU5OIlGg0pTc4E"] = {file: "uz_codegen0_h.html",line:87,type:"type"};
this.def["shohwUBaOGHF036TMzc1KEH"] = {file: "uz_codegen0_h.html",line:115,type:"type"};
this.def["sSzLoP8tvZHiR1V2perTtWD"] = {file: "uz_codegen0_h.html",line:140,type:"type"};
this.def["stxriBK2jD81NCGacZ0b8HD"] = {file: "uz_codegen0_h.html",line:194,type:"type"};
this.def["sL9bDKomAYkxZSVrG9w6En"] = {file: "uz_codegen0_h.html",line:214,type:"type"};
this.def["sCS11Pe0E6xKX8jGoaG4cLG"] = {file: "uz_codegen0_h.html",line:239,type:"type"};
this.def["snRDwUdgrIx9qNga56nZ8DE"] = {file: "uz_codegen0_h.html",line:258,type:"type"};
this.def["s4lHOiXA0GHbse0IgoBY6ZF"] = {file: "uz_codegen0_h.html",line:302,type:"type"};
this.def["DW"] = {file: "uz_codegen0_h.html",line:576,type:"type"};
this.def["ExtU"] = {file: "uz_codegen0_h.html",line:613,type:"type"};
this.def["ExtY"] = {file: "uz_codegen0_h.html",line:620,type:"type"};
this.def["int8_T"] = {file: "rtwtypes_h.html",line:53,type:"type"};
this.def["uint8_T"] = {file: "rtwtypes_h.html",line:54,type:"type"};
this.def["int16_T"] = {file: "rtwtypes_h.html",line:55,type:"type"};
this.def["uint16_T"] = {file: "rtwtypes_h.html",line:56,type:"type"};
this.def["int32_T"] = {file: "rtwtypes_h.html",line:57,type:"type"};
this.def["uint32_T"] = {file: "rtwtypes_h.html",line:58,type:"type"};
this.def["int64_T"] = {file: "rtwtypes_h.html",line:59,type:"type"};
this.def["uint64_T"] = {file: "rtwtypes_h.html",line:60,type:"type"};
this.def["real32_T"] = {file: "rtwtypes_h.html",line:61,type:"type"};
this.def["real64_T"] = {file: "rtwtypes_h.html",line:62,type:"type"};
this.def["real_T"] = {file: "rtwtypes_h.html",line:68,type:"type"};
this.def["time_T"] = {file: "rtwtypes_h.html",line:69,type:"type"};
this.def["boolean_T"] = {file: "rtwtypes_h.html",line:70,type:"type"};
this.def["int_T"] = {file: "rtwtypes_h.html",line:71,type:"type"};
this.def["uint_T"] = {file: "rtwtypes_h.html",line:72,type:"type"};
this.def["ulong_T"] = {file: "rtwtypes_h.html",line:73,type:"type"};
this.def["ulonglong_T"] = {file: "rtwtypes_h.html",line:74,type:"type"};
this.def["char_T"] = {file: "rtwtypes_h.html",line:75,type:"type"};
this.def["uchar_T"] = {file: "rtwtypes_h.html",line:76,type:"type"};
this.def["byte_T"] = {file: "rtwtypes_h.html",line:77,type:"type"};
this.def["creal32_T"] = {file: "rtwtypes_h.html",line:87,type:"type"};
this.def["creal64_T"] = {file: "rtwtypes_h.html",line:92,type:"type"};
this.def["creal_T"] = {file: "rtwtypes_h.html",line:97,type:"type"};
this.def["cint8_T"] = {file: "rtwtypes_h.html",line:104,type:"type"};
this.def["cuint8_T"] = {file: "rtwtypes_h.html",line:111,type:"type"};
this.def["cint16_T"] = {file: "rtwtypes_h.html",line:118,type:"type"};
this.def["cuint16_T"] = {file: "rtwtypes_h.html",line:125,type:"type"};
this.def["cint32_T"] = {file: "rtwtypes_h.html",line:132,type:"type"};
this.def["cuint32_T"] = {file: "rtwtypes_h.html",line:139,type:"type"};
this.def["cint64_T"] = {file: "rtwtypes_h.html",line:146,type:"type"};
this.def["cuint64_T"] = {file: "rtwtypes_h.html",line:153,type:"type"};
this.def["pointer_T"] = {file: "rtwtypes_h.html",line:174,type:"type"};
}
CodeDefine.instance = new CodeDefine();
var testHarnessInfo = {OwnerFileName: "", HarnessOwner: "", HarnessName: "", IsTestHarness: "0"};
var relPathToBuildDir = "../ert_main.c";
var fileSep = "\\";
var isPC = true;
function Html2SrcLink() {
	this.html2SrcPath = new Array;
	this.html2Root = new Array;
	this.html2SrcPath["uz_codegen0_c.html"] = "../uz_codegen0.c";
	this.html2Root["uz_codegen0_c.html"] = "uz_codegen0_c.html";
	this.html2SrcPath["uz_codegen0_h.html"] = "../uz_codegen0.h";
	this.html2Root["uz_codegen0_h.html"] = "uz_codegen0_h.html";
	this.html2SrcPath["rtwtypes_h.html"] = "../rtwtypes.h";
	this.html2Root["rtwtypes_h.html"] = "rtwtypes_h.html";
	this.html2SrcPath["rtmodel_h.html"] = "../rtmodel.h";
	this.html2Root["rtmodel_h.html"] = "rtmodel_h.html";
	this.getLink2Src = function (htmlFileName) {
		 if (this.html2SrcPath[htmlFileName])
			 return this.html2SrcPath[htmlFileName];
		 else
			 return null;
	}
	this.getLinkFromRoot = function (htmlFileName) {
		 if (this.html2Root[htmlFileName])
			 return this.html2Root[htmlFileName];
		 else
			 return null;
	}
}
Html2SrcLink.instance = new Html2SrcLink();
var fileList = [
"uz_codegen0_c.html","uz_codegen0_h.html","rtwtypes_h.html","rtmodel_h.html"];
