function CodeDefine() { 
this.def = new Array();
this.def["uz_codegen0.c:factoryConstruct"] = {file: "uz_codegen0_c.html",line:208,type:"fcn"};
this.def["uz_codegen0.c:xnrm2"] = {file: "uz_codegen0_c.html",line:219,type:"fcn"};
this.def["rt_hypotd"] = {file: "uz_codegen0_c.html",line:250,type:"fcn"};
this.def["uz_codegen0.c:xzlarfg"] = {file: "uz_codegen0_c.html",line:271,type:"fcn"};
this.def["uz_codegen0.c:xzlarf"] = {file: "uz_codegen0_c.html",line:333,type:"fcn"};
this.def["uz_codegen0.c:qrf"] = {file: "uz_codegen0_c.html",line:426,type:"fcn"};
this.def["uz_codegen0.c:xzgeqp3"] = {file: "uz_codegen0_c.html",line:454,type:"fcn"};
this.def["uz_codegen0.c:computeQ_"] = {file: "uz_codegen0_c.html",line:612,type:"fcn"};
this.def["uz_codegen0.c:ComputeNumDependentEq_"] = {file: "uz_codegen0_c.html",line:757,type:"fcn"};
this.def["uz_codegen0.c:countsort"] = {file: "uz_codegen0_c.html",line:798,type:"fcn"};
this.def["uz_codegen0.c:moveConstraint_"] = {file: "uz_codegen0_c.html",line:840,type:"fcn"};
this.def["uz_codegen0.c:removeEqConstr"] = {file: "uz_codegen0_c.html",line:855,type:"fcn"};
this.def["uz_codegen0.c:RemoveDependentEq_"] = {file: "uz_codegen0_c.html",line:885,type:"fcn"};
this.def["uz_codegen0.c:removeAllIneqConstr"] = {file: "uz_codegen0_c.html",line:1061,type:"fcn"};
this.def["uz_codegen0.c:RemoveDependentIneq_"] = {file: "uz_codegen0_c.html",line:1077,type:"fcn"};
this.def["uz_codegen0.c:factorQR_e"] = {file: "uz_codegen0_c.html",line:1180,type:"fcn"};
this.def["uz_codegen0.c:factorQR"] = {file: "uz_codegen0_c.html",line:1230,type:"fcn"};
this.def["uz_codegen0.c:xgemv"] = {file: "uz_codegen0_c.html",line:1261,type:"fcn"};
this.def["uz_codegen0.c:xgemv_j"] = {file: "uz_codegen0_c.html",line:1295,type:"fcn"};
this.def["uz_codegen0.c:maxConstraintViolation"] = {file: "uz_codegen0_c.html",line:1329,type:"fcn"};
this.def["uz_codegen0.c:xgemv_jm"] = {file: "uz_codegen0_c.html",line:1419,type:"fcn"};
this.def["uz_codegen0.c:xgemv_jmu"] = {file: "uz_codegen0_c.html",line:1453,type:"fcn"};
this.def["uz_codegen0.c:maxConstraintViolation_b"] = {file: "uz_codegen0_c.html",line:1487,type:"fcn"};
this.def["uz_codegen0.c:feasibleX0ForWorkingSet"] = {file: "uz_codegen0_c.html",line:1577,type:"fcn"};
this.def["uz_codegen0.c:xgemv_jmup"] = {file: "uz_codegen0_c.html",line:1823,type:"fcn"};
this.def["uz_codegen0.c:xgemv_jmupc"] = {file: "uz_codegen0_c.html",line:1857,type:"fcn"};
this.def["uz_codegen0.c:maxConstraintViolation_b0"] = {file: "uz_codegen0_c.html",line:1891,type:"fcn"};
this.def["uz_codegen0.c:PresolveWorkingSet"] = {file: "uz_codegen0_c.html",line:1981,type:"fcn"};
this.def["uz_codegen0.c:modifyOverheadPhaseOne_"] = {file: "uz_codegen0_c.html",line:2005,type:"fcn"};
this.def["uz_codegen0.c:setProblemType"] = {file: "uz_codegen0_c.html",line:2039,type:"fcn"};
this.def["uz_codegen0.c:linearForm_"] = {file: "uz_codegen0_c.html",line:2231,type:"fcn"};
this.def["uz_codegen0.c:computeFval"] = {file: "uz_codegen0_c.html",line:2279,type:"fcn"};
this.def["uz_codegen0.c:xgemv_jmupcy"] = {file: "uz_codegen0_c.html",line:2317,type:"fcn"};
this.def["uz_codegen0.c:computeGrad_StoreHx"] = {file: "uz_codegen0_c.html",line:2349,type:"fcn"};
this.def["uz_codegen0.c:computeFval_ReuseHx"] = {file: "uz_codegen0_c.html",line:2409,type:"fcn"};
this.def["uz_codegen0.c:printHeader"] = {file: "uz_codegen0_c.html",line:2484,type:"fcn"};
this.def["uz_codegen0.c:printInitialInfo"] = {file: "uz_codegen0_c.html",line:2495,type:"fcn"};
this.def["uz_codegen0.c:xrotg"] = {file: "uz_codegen0_c.html",line:2553,type:"fcn"};
this.def["uz_codegen0.c:deleteColMoveEnd"] = {file: "uz_codegen0_c.html",line:2593,type:"fcn"};
this.def["uz_codegen0.c:computeProjectedHessian"] = {file: "uz_codegen0_c.html",line:2715,type:"fcn"};
this.def["uz_codegen0.c:ixamax"] = {file: "uz_codegen0_c.html",line:2801,type:"fcn"};
this.def["uz_codegen0.c:fullColLDL2_"] = {file: "uz_codegen0_c.html",line:2830,type:"fcn"};
this.def["uz_codegen0.c:xgemv_jmupcyx"] = {file: "uz_codegen0_c.html",line:2890,type:"fcn"};
this.def["uz_codegen0.c:compute_deltax"] = {file: "uz_codegen0_c.html",line:2922,type:"fcn"};
this.def["uz_codegen0.c:xnrm2_g"] = {file: "uz_codegen0_c.html",line:3177,type:"fcn"};
this.def["uz_codegen0.c:xgemv_jmupcyxs"] = {file: "uz_codegen0_c.html",line:3210,type:"fcn"};
this.def["uz_codegen0.c:xgemv_jmupcyxsk"] = {file: "uz_codegen0_c.html",line:3245,type:"fcn"};
this.def["uz_codegen0.c:ratiotest"] = {file: "uz_codegen0_c.html",line:3280,type:"fcn"};
this.def["uz_codegen0.c:feasibleratiotest"] = {file: "uz_codegen0_c.html",line:3454,type:"fcn"};
this.def["uz_codegen0.c:checkUnboundedOrIllPosed"] = {file: "uz_codegen0_c.html",line:3571,type:"fcn"};
this.def["uz_codegen0.c:addBoundToActiveSetMatrix_"] = {file: "uz_codegen0_c.html",line:3585,type:"fcn"};
this.def["uz_codegen0.c:compute_lambda"] = {file: "uz_codegen0_c.html",line:3626,type:"fcn"};
this.def["uz_codegen0.c:checkStoppingAndUpdateFval"] = {file: "uz_codegen0_c.html",line:3730,type:"fcn"};
this.def["uz_codegen0.c:computeFirstOrderOpt"] = {file: "uz_codegen0_c.html",line:3789,type:"fcn"};
this.def["uz_codegen0.c:printInfo"] = {file: "uz_codegen0_c.html",line:3846,type:"fcn"};
this.def["uz_codegen0.c:iterate"] = {file: "uz_codegen0_c.html",line:3958,type:"fcn"};
this.def["uz_codegen0.c:phaseone"] = {file: "uz_codegen0_c.html",line:4293,type:"fcn"};
this.def["uz_codegen0.c:ComputeNumDependentEq__b"] = {file: "uz_codegen0_c.html",line:4434,type:"fcn"};
this.def["uz_codegen0.c:RemoveDependentEq__l"] = {file: "uz_codegen0_c.html",line:4514,type:"fcn"};
this.def["uz_codegen0.c:PresolveWorkingSet_g"] = {file: "uz_codegen0_c.html",line:4619,type:"fcn"};
this.def["uz_codegen0.c:strcmp_h"] = {file: "uz_codegen0_c.html",line:4644,type:"fcn"};
this.def["uz_codegen0.c:phaseone_e"] = {file: "uz_codegen0_c.html",line:4683,type:"fcn"};
this.def["uz_codegen0.c:driver"] = {file: "uz_codegen0_c.html",line:4764,type:"fcn"};
this.def["uz_codegen0.c:linearForm__b"] = {file: "uz_codegen0_c.html",line:4943,type:"fcn"};
this.def["uz_codegen0.c:quadprog"] = {file: "uz_codegen0_c.html",line:4988,type:"fcn"};
this.def["uz_codegen0_step"] = {file: "uz_codegen0_c.html",line:5108,type:"fcn"};
this.def["uz_codegen0_initialize"] = {file: "uz_codegen0_c.html",line:7424,type:"fcn"};
this.def["RT_MODEL"] = {file: "uz_codegen0_h.html",line:64,type:"type"};
this.def["svV6yPD1e8CTJu8b18IprLB"] = {file: "uz_codegen0_h.html",line:87,type:"type"};
this.def["shohwUBaOGHF036TMzc1KEH"] = {file: "uz_codegen0_h.html",line:115,type:"type"};
this.def["s1hK3o0EyOqKKjEgDlbhqfF"] = {file: "uz_codegen0_h.html",line:140,type:"type"};
this.def["swcr9qLPQBiG4lNhaNdYq5G"] = {file: "uz_codegen0_h.html",line:194,type:"type"};
this.def["sL9bDKomAYkxZSVrG9w6En"] = {file: "uz_codegen0_h.html",line:214,type:"type"};
this.def["sQyCFUyu0YXOk1LARsZMzaD"] = {file: "uz_codegen0_h.html",line:239,type:"type"};
this.def["s9NoAX0P67ji2P1ZBafS3UG"] = {file: "uz_codegen0_h.html",line:258,type:"type"};
this.def["s4lHOiXA0GHbse0IgoBY6ZF"] = {file: "uz_codegen0_h.html",line:302,type:"type"};
this.def["DW"] = {file: "uz_codegen0_h.html",line:563,type:"type"};
this.def["ExtU"] = {file: "uz_codegen0_h.html",line:598,type:"type"};
this.def["ExtY"] = {file: "uz_codegen0_h.html",line:605,type:"type"};
this.def["int8_T"] = {file: "rtwtypes_h.html",line:53,type:"type"};
this.def["uint8_T"] = {file: "rtwtypes_h.html",line:54,type:"type"};
this.def["int16_T"] = {file: "rtwtypes_h.html",line:55,type:"type"};
this.def["uint16_T"] = {file: "rtwtypes_h.html",line:56,type:"type"};
this.def["int32_T"] = {file: "rtwtypes_h.html",line:57,type:"type"};
this.def["uint32_T"] = {file: "rtwtypes_h.html",line:58,type:"type"};
this.def["int64_T"] = {file: "rtwtypes_h.html",line:59,type:"type"};
this.def["uint64_T"] = {file: "rtwtypes_h.html",line:60,type:"type"};
this.def["real32_T"] = {file: "rtwtypes_h.html",line:61,type:"type"};
this.def["real64_T"] = {file: "rtwtypes_h.html",line:62,type:"type"};
this.def["real_T"] = {file: "rtwtypes_h.html",line:68,type:"type"};
this.def["time_T"] = {file: "rtwtypes_h.html",line:69,type:"type"};
this.def["boolean_T"] = {file: "rtwtypes_h.html",line:70,type:"type"};
this.def["int_T"] = {file: "rtwtypes_h.html",line:71,type:"type"};
this.def["uint_T"] = {file: "rtwtypes_h.html",line:72,type:"type"};
this.def["ulong_T"] = {file: "rtwtypes_h.html",line:73,type:"type"};
this.def["ulonglong_T"] = {file: "rtwtypes_h.html",line:74,type:"type"};
this.def["char_T"] = {file: "rtwtypes_h.html",line:75,type:"type"};
this.def["uchar_T"] = {file: "rtwtypes_h.html",line:76,type:"type"};
this.def["byte_T"] = {file: "rtwtypes_h.html",line:77,type:"type"};
this.def["creal32_T"] = {file: "rtwtypes_h.html",line:87,type:"type"};
this.def["creal64_T"] = {file: "rtwtypes_h.html",line:92,type:"type"};
this.def["creal_T"] = {file: "rtwtypes_h.html",line:97,type:"type"};
this.def["cint8_T"] = {file: "rtwtypes_h.html",line:104,type:"type"};
this.def["cuint8_T"] = {file: "rtwtypes_h.html",line:111,type:"type"};
this.def["cint16_T"] = {file: "rtwtypes_h.html",line:118,type:"type"};
this.def["cuint16_T"] = {file: "rtwtypes_h.html",line:125,type:"type"};
this.def["cint32_T"] = {file: "rtwtypes_h.html",line:132,type:"type"};
this.def["cuint32_T"] = {file: "rtwtypes_h.html",line:139,type:"type"};
this.def["cint64_T"] = {file: "rtwtypes_h.html",line:146,type:"type"};
this.def["cuint64_T"] = {file: "rtwtypes_h.html",line:153,type:"type"};
this.def["pointer_T"] = {file: "rtwtypes_h.html",line:174,type:"type"};
}
CodeDefine.instance = new CodeDefine();
var testHarnessInfo = {OwnerFileName: "", HarnessOwner: "", HarnessName: "", IsTestHarness: "0"};
var relPathToBuildDir = "../ert_main.c";
var fileSep = "\\";
var isPC = true;
function Html2SrcLink() {
	this.html2SrcPath = new Array;
	this.html2Root = new Array;
	this.html2SrcPath["uz_codegen0_c.html"] = "../uz_codegen0.c";
	this.html2Root["uz_codegen0_c.html"] = "uz_codegen0_c.html";
	this.html2SrcPath["uz_codegen0_h.html"] = "../uz_codegen0.h";
	this.html2Root["uz_codegen0_h.html"] = "uz_codegen0_h.html";
	this.html2SrcPath["rtwtypes_h.html"] = "../rtwtypes.h";
	this.html2Root["rtwtypes_h.html"] = "rtwtypes_h.html";
	this.html2SrcPath["rtmodel_h.html"] = "../rtmodel.h";
	this.html2Root["rtmodel_h.html"] = "rtmodel_h.html";
	this.getLink2Src = function (htmlFileName) {
		 if (this.html2SrcPath[htmlFileName])
			 return this.html2SrcPath[htmlFileName];
		 else
			 return null;
	}
	this.getLinkFromRoot = function (htmlFileName) {
		 if (this.html2Root[htmlFileName])
			 return this.html2Root[htmlFileName];
		 else
			 return null;
	}
}
Html2SrcLink.instance = new Html2SrcLink();
var fileList = [
"uz_codegen0_c.html","uz_codegen0_h.html","rtwtypes_h.html","rtmodel_h.html"];
