SLStudio.Utils.RemoveHighlighting(get_param('uz_deadbeat_clean', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_uz_deadbeat_clean', 'handle'));
annotate_port('gm_uz_deadbeat_clean/uz_deadbeat_clean/Product31', 0, 1, '');
annotate_port('gm_uz_deadbeat_clean/uz_deadbeat_clean/Min_stage1', 1, 1, '');
annotate_port('uz_deadbeat_clean/uz_deadbeat_clean/Min', 1, 1, '');
annotate_port('gm_uz_deadbeat_clean/uz_deadbeat_clean/Min_stage2', 1, 1, '');
annotate_port('uz_deadbeat_clean/uz_deadbeat_clean/Min', 1, 1, '');
annotate_port('gm_uz_deadbeat_clean/uz_deadbeat_clean/Min1_stage1', 1, 1, '');
annotate_port('uz_deadbeat_clean/uz_deadbeat_clean/Min1', 1, 1, '');
annotate_port('gm_uz_deadbeat_clean/uz_deadbeat_clean/Min1_stage2', 1, 1, '');
annotate_port('uz_deadbeat_clean/uz_deadbeat_clean/Min1', 1, 1, '');
annotate_port('gm_uz_deadbeat_clean/uz_deadbeat_clean/Min2_stage1', 1, 1, '');
annotate_port('uz_deadbeat_clean/uz_deadbeat_clean/Min2', 1, 1, '');
annotate_port('gm_uz_deadbeat_clean/uz_deadbeat_clean/Min3_stage1', 1, 1, '');
annotate_port('uz_deadbeat_clean/uz_deadbeat_clean/Min3', 1, 1, '');
annotate_port('gm_uz_deadbeat_clean/uz_deadbeat_clean/Min4_stage1', 1, 1, '');
annotate_port('uz_deadbeat_clean/uz_deadbeat_clean/Min4', 1, 1, '');
annotate_port('gm_uz_deadbeat_clean/uz_deadbeat_clean/Min5_stage1', 1, 1, '');
annotate_port('uz_deadbeat_clean/uz_deadbeat_clean/Min5', 1, 1, '');
annotate_port('gm_uz_deadbeat_clean/uz_deadbeat_clean/Min6_stage1', 1, 1, '');
annotate_port('uz_deadbeat_clean/uz_deadbeat_clean/Min6', 1, 1, '');
annotate_port('gm_uz_deadbeat_clean/uz_deadbeat_clean/Min7_stage1', 1, 1, '');
annotate_port('uz_deadbeat_clean/uz_deadbeat_clean/Min7', 1, 1, '');
annotate_port('uz_deadbeat_clean/uz_deadbeat_clean/Trigonometric Function', 1, 1, '');
annotate_port('gm_uz_deadbeat_clean/uz_deadbeat_clean/Trigonometric Function', 1, 1, '');
annotate_port('uz_deadbeat_clean/uz_deadbeat_clean/Trigonometric Function', 1, 1, '');
annotate_port('uz_deadbeat_clean/uz_deadbeat_clean/Trigonometric Function1', 1, 1, '');
annotate_port('gm_uz_deadbeat_clean/uz_deadbeat_clean/Trigonometric Function1', 1, 1, '');
annotate_port('uz_deadbeat_clean/uz_deadbeat_clean/Trigonometric Function1', 1, 1, '');
annotate_port('uz_deadbeat_clean/uz_deadbeat_clean/Trigonometric Function2', 1, 1, '');
annotate_port('gm_uz_deadbeat_clean/uz_deadbeat_clean/Trigonometric Function2', 1, 1, '');
annotate_port('uz_deadbeat_clean/uz_deadbeat_clean/Trigonometric Function2', 1, 1, '');
annotate_port('uz_deadbeat_clean/uz_deadbeat_clean/Trigonometric Function3', 1, 1, '');
annotate_port('gm_uz_deadbeat_clean/uz_deadbeat_clean/Trigonometric Function3', 1, 1, '');
annotate_port('uz_deadbeat_clean/uz_deadbeat_clean/Trigonometric Function3', 1, 1, '');
annotate_port('gm_uz_deadbeat_clean/uz_deadbeat_clean/PipelineRegister', 1, 1, '');
annotate_port('gm_uz_deadbeat_clean/uz_deadbeat_clean/HwModeRegister', 0, 1, '');
