SLStudio.Utils.RemoveHighlighting(get_param('IPCore_3Level_PWM', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_IPCore_3Level_PWM', 'handle'));
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Relational Operator1', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Relational Operator1', 0, 1, '');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Relational Operator7', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Relational Operator7', 0, 1, '');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Subsystem/Relational Operator11', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Subsystem/Relational Operator11', 0, 1, '');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Subsystem1/Relational Operator2', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Subsystem1/Relational Operator2', 0, 1, '');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Subsystem2/Relational Operator9', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Subsystem2/Relational Operator9', 0, 1, '');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Subsystem3/Relational Operator6', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Subsystem3/Relational Operator6', 0, 1, '');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Relational Operator1', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Relational Operator1', 0, 1, '');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Relational Operator7', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Relational Operator7', 0, 1, '');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Subsystem/Relational Operator11', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Subsystem/Relational Operator11', 0, 1, '');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Subsystem1/Relational Operator2', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Subsystem1/Relational Operator2', 0, 1, '');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Subsystem2/Relational Operator9', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Subsystem2/Relational Operator9', 0, 1, '');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Subsystem3/Relational Operator6', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Subsystem3/Relational Operator6', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, '');
