open_system('IPCore_3Level_PWM');
open_system('gm_IPCore_3Level_PWM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Relational Operator1', 'user1');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Relational Operator1', 0, 1, 'Blocks delay absorption: 46 cycles');
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Relational Operator1', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Relational Operator1', 0, 1, 'Blocks delay absorption: 46 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Relational Operator7', 'user1');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Relational Operator7', 0, 1, 'Blocks delay absorption: 46 cycles');
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Relational Operator7', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Relational Operator7', 0, 1, 'Blocks delay absorption: 46 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Subsystem/Relational Operator11', 'user1');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Subsystem/Relational Operator11', 0, 1, 'Blocks delay absorption: 46 cycles');
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Subsystem/Relational Operator11', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Subsystem/Relational Operator11', 0, 1, 'Blocks delay absorption: 46 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Subsystem1/Relational Operator2', 'user1');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Subsystem1/Relational Operator2', 0, 1, 'Blocks delay absorption: 46 cycles');
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Subsystem1/Relational Operator2', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Subsystem1/Relational Operator2', 0, 1, 'Blocks delay absorption: 46 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Subsystem2/Relational Operator9', 'user1');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Subsystem2/Relational Operator9', 0, 1, 'Blocks delay absorption: 46 cycles');
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Subsystem2/Relational Operator9', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Subsystem2/Relational Operator9', 0, 1, 'Blocks delay absorption: 46 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Subsystem3/Relational Operator6', 'user1');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Subsystem3/Relational Operator6', 0, 1, 'Blocks delay absorption: 46 cycles');
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Subsystem3/Relational Operator6', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift1/Subsystem3/Relational Operator6', 0, 1, 'Blocks delay absorption: 46 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Relational Operator1', 'user1');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Relational Operator1', 0, 1, 'Blocks delay absorption: 46 cycles');
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Relational Operator1', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Relational Operator1', 0, 1, 'Blocks delay absorption: 46 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Relational Operator7', 'user1');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Relational Operator7', 0, 1, 'Blocks delay absorption: 46 cycles');
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Relational Operator7', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Relational Operator7', 0, 1, 'Blocks delay absorption: 46 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Subsystem/Relational Operator11', 'user1');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Subsystem/Relational Operator11', 0, 1, 'Blocks delay absorption: 46 cycles');
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Subsystem/Relational Operator11', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Subsystem/Relational Operator11', 0, 1, 'Blocks delay absorption: 46 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Subsystem1/Relational Operator2', 'user1');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Subsystem1/Relational Operator2', 0, 1, 'Blocks delay absorption: 46 cycles');
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Subsystem1/Relational Operator2', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Subsystem1/Relational Operator2', 0, 1, 'Blocks delay absorption: 46 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Subsystem2/Relational Operator9', 'user1');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Subsystem2/Relational Operator9', 0, 1, 'Blocks delay absorption: 46 cycles');
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Subsystem2/Relational Operator9', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Subsystem2/Relational Operator9', 0, 1, 'Blocks delay absorption: 46 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Subsystem3/Relational Operator6', 'user1');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Subsystem3/Relational Operator6', 0, 1, 'Blocks delay absorption: 46 cycles');
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Subsystem3/Relational Operator6', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Triangle_shift2/Subsystem3/Relational Operator6', 0, 1, 'Blocks delay absorption: 46 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 2 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
