open_system('gm_parallel_8_phase_voltages');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state1/Sine HDL Optimized2', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state1/Sine HDL Optimized2', 0, 1, 'cp : 6.303 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state1/Sine HDL Optimized2/Point501', 'user1');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state1/Sine HDL Optimized2/Point501', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state1/Sine HDL Optimized2/CastU16En21', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state1/Sine HDL Optimized2/CastU16En21', 0, 1, 'cp : 2.395 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state1/Sine HDL Optimized2/CastU16En31', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state1/Sine HDL Optimized2/CastU16En31', 0, 1, 'cp : 3.283 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state1/Sine HDL Optimized2/CastU16En4', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state1/Sine HDL Optimized2/CastU16En4', 0, 1, 'cp : 2.395 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state1/Sine HDL Optimized2/LTEp251', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state1/Sine HDL Optimized2/LTEp251', 0, 1, 'cp : 2.043 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state1/Sine HDL Optimized2/LTEp501', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state1/Sine HDL Optimized2/LTEp501', 0, 1, 'cp : 0.85 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state1/Sine HDL Optimized2/Look-Up Table1', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state1/Sine HDL Optimized2/Look-Up Table1', 0, 1, 'cp : 6.042 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state1/Sine HDL Optimized2/QuadHandle1', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state1/Sine HDL Optimized2/QuadHandle1', 0, 1, 'cp : 1.202 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state1/Sine HDL Optimized2/QuadHandle21', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state1/Sine HDL Optimized2/QuadHandle21', 0, 1, 'cp : 2.395 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state1/Sine HDL Optimized2/Saturation1', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state1/Sine HDL Optimized2/Saturation1', 0, 1, 'cp : 4.501 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state1/Sine HDL Optimized2/Switch1', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state1/Sine HDL Optimized2/Switch1', 0, 1, 'cp : 4.785 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state1/Sine HDL Optimized2/PipelineRegister1', 'user1');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state1/Sine HDL Optimized2/PipelineRegister1', 1, 1, 'cp : 6.303 ns');
