open_system('parallel_8_phase_voltages');
open_system('gm_parallel_8_phase_voltages');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion1', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion1', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion1', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion1', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion10', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion10', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion10', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion10', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion11', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion11', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion11', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion11', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion12', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion12', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion12', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion12', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion13', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion13', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion13', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion13', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion14', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion14', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion14', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion14', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion15', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion15', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion15', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion15', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion16', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion16', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion16', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion16', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion17', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion17', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion17', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion17', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion18', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion18', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion18', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion18', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion19', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion19', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion19', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion19', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion2', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion2', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion2', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion2', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion20', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion20', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion20', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion20', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion21', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion21', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion21', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion21', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion22', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion22', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion22', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion22', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion23', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion23', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion23', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion23', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion24', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion24', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion24', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion24', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion25', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion25', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion25', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion25', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion26', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion26', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion26', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion26', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion27', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion27', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion27', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion27', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion28', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion28', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion28', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion28', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion29', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion29', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion29', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion29', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion3', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion3', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion3', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion3', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion30', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion30', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion30', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion30', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion31', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion31', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion31', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion31', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion32', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion32', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion32', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion32', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion33', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion33', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion33', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion33', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion4', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion4', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion4', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion4', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion42', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion42', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion42', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion42', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion5', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion5', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion5', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion5', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion6', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion6', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion6', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion6', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion7', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion7', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion7', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion7', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion8', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion8', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion8', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion8', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion9', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion9', 1, 1, 'Block not characterized for this configuration');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion9', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Data Type Conversion9', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function10/Assignment', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function10/Assignment', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function10', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function10', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function10/Assignment1', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function10/Assignment1', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function10', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function10', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function10/Assignment2', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function10/Assignment2', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function10', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function10', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function10/Assignment3', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function10/Assignment3', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function10', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function10', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function10/t', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function10/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function10/t1', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function10/t1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function10/t2', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function10/t2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function10/t3', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function10/t3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function10/t4', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function10/t4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function10/t5', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function10/t5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function11/Assignment', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function11/Assignment', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function11', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function11', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function11/Assignment1', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function11/Assignment1', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function11', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function11', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function11/Assignment2', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function11/Assignment2', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function11', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function11', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function11/Assignment3', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function11/Assignment3', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function11', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function11', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function11/t', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function11/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function11/t1', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function11/t1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function11/t2', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function11/t2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function11/t3', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function11/t3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function11/t4', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function11/t4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function11/t5', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function11/t5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function12/Assignment', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function12/Assignment', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function12', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function12', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function12/Assignment1', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function12/Assignment1', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function12', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function12', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function12/Assignment2', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function12/Assignment2', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function12', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function12', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function12/Assignment3', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function12/Assignment3', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function12', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function12', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function12/t', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function12/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function12/t1', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function12/t1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function12/t2', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function12/t2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function12/t3', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function12/t3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function12/t4', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function12/t4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function12/t5', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function12/t5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function13/Assignment', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function13/Assignment', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function13', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function13', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function13/Assignment1', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function13/Assignment1', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function13', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function13', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function13/Assignment2', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function13/Assignment2', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function13', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function13', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function13/Assignment3', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function13/Assignment3', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function13', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function13', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function13/t', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function13/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function13/t1', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function13/t1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function13/t2', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function13/t2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function13/t3', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function13/t3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function13/t4', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function13/t4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function13/t5', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function13/t5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function14/Assignment', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function14/Assignment', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function14', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function14', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function14/Assignment1', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function14/Assignment1', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function14', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function14', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function14/Assignment2', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function14/Assignment2', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function14', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function14', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function14/Assignment3', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function14/Assignment3', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function14', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function14', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function14/t', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function14/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function14/t1', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function14/t1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function14/t2', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function14/t2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function14/t3', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function14/t3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function14/t4', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function14/t4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function14/t5', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function14/t5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function15/Assignment', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function15/Assignment', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function15', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function15', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function15/Assignment1', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function15/Assignment1', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function15', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function15', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function15/Assignment2', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function15/Assignment2', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function15', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function15', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function15/Assignment3', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function15/Assignment3', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function15', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function15', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function15/t', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function15/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function15/t1', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function15/t1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function15/t2', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function15/t2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function15/t3', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function15/t3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function15/t4', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function15/t4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function15/t5', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function15/t5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function8/Assignment', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function8/Assignment', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function8', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function8', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function8/Assignment1', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function8/Assignment1', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function8', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function8', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function8/Assignment2', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function8/Assignment2', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function8', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function8', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function8/Assignment3', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function8/Assignment3', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function8', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function8', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function8/t', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function8/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function8/t1', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function8/t1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function8/t2', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function8/t2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function8/t3', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function8/t3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function8/t4', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function8/t4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function8/t5', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function8/t5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function9/Assignment', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function9/Assignment', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function9', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function9', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function9/Assignment1', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function9/Assignment1', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function9', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function9', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function9/Assignment2', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function9/Assignment2', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function9', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function9', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function9/Assignment3', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function9/Assignment3', 1, 1, 'Block not characterized');
hilite_system('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function9', 'user2');
annotate_port('parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function9', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function9/t', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function9/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function9/t1', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function9/t1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function9/t2', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function9/t2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function9/t3', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function9/t3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function9/t4', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function9/t4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function9/t5', 'user2');
annotate_port('gm_parallel_8_phase_voltages/Phase_voltages_per_switching_state2/Subsystem/MATLAB Function9/t5', 1, 1, 'Block not characterized');
