open_system('gm_InterlockDeadtime3L');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_InterlockDeadtime3L/InterlockDeadtime3L/NPC_Interlock', 'user2');
annotate_port('gm_InterlockDeadtime3L/InterlockDeadtime3L/NPC_Interlock', 0, 1, 'cp : 5.048 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_InterlockDeadtime3L/InterlockDeadtime3L/DeadTime_instance1', 'user2');
annotate_port('gm_InterlockDeadtime3L/InterlockDeadtime3L/DeadTime_instance1', 0, 1, 'cp : 2.544 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_InterlockDeadtime3L/InterlockDeadtime3L/t', 'user2');
annotate_port('gm_InterlockDeadtime3L/InterlockDeadtime3L/t', 0, 1, 'cp : 2.544 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_InterlockDeadtime3L/InterlockDeadtime3L/concatenate', 'user2');
annotate_port('gm_InterlockDeadtime3L/InterlockDeadtime3L/concatenate', 0, 1, 'cp : 2.544 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_InterlockDeadtime3L/InterlockDeadtime3L/Delay2', 'user1');
annotate_port('gm_InterlockDeadtime3L/InterlockDeadtime3L/Delay2', 0, 1, 'cp : 0.33 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_InterlockDeadtime3L/InterlockDeadtime3L/t3', 'user1');
annotate_port('gm_InterlockDeadtime3L/InterlockDeadtime3L/t3', 0, 1, 'cp : 6.627 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_InterlockDeadtime3L/InterlockDeadtime3L/Logical Operator', 'user2');
annotate_port('gm_InterlockDeadtime3L/InterlockDeadtime3L/Logical Operator', 0, 1, 'cp : 6.275 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_InterlockDeadtime3L/InterlockDeadtime3L/Switch', 'user2');
annotate_port('gm_InterlockDeadtime3L/InterlockDeadtime3L/Switch', 0, 1, 'cp : 5.387 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_InterlockDeadtime3L/InterlockDeadtime3L/Switch1', 'user2');
annotate_port('gm_InterlockDeadtime3L/InterlockDeadtime3L/Switch1', 0, 1, 'cp : 6.627 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_InterlockDeadtime3L/InterlockDeadtime3L/NPC_Interlock/t1', 'user2');
annotate_port('gm_InterlockDeadtime3L/InterlockDeadtime3L/NPC_Interlock/t1', 0, 1, 'cp : 2.828 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_InterlockDeadtime3L/InterlockDeadtime3L/NPC_Interlock/Logical Operator', 'user2');
annotate_port('gm_InterlockDeadtime3L/InterlockDeadtime3L/NPC_Interlock/Logical Operator', 0, 1, 'cp : 2.828 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_InterlockDeadtime3L/InterlockDeadtime3L/NPC_Interlock/Logical Operator1', 'user2');
annotate_port('gm_InterlockDeadtime3L/InterlockDeadtime3L/NPC_Interlock/Logical Operator1', 0, 1, 'cp : 3.716 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_InterlockDeadtime3L/InterlockDeadtime3L/NPC_Interlock/Logical Operator5', 'user2');
annotate_port('gm_InterlockDeadtime3L/InterlockDeadtime3L/NPC_Interlock/Logical Operator5', 0, 1, 'cp : 4.709 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_InterlockDeadtime3L/InterlockDeadtime3L/NPC_Interlock/Switch', 'user2');
annotate_port('gm_InterlockDeadtime3L/InterlockDeadtime3L/NPC_Interlock/Switch', 0, 1, 'cp : 5.048 ns');
