-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity MatrixMultiplication is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 8;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of MatrixMultiplication is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "MatrixMultiplication_MatrixMultiplication,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvc900-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.507000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=1,HLS_SYN_DSP=0,HLS_SYN_FF=1536,HLS_SYN_LUT=1769,HLS_VERSION=2022_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";

    signal ap_rst_n_inv : STD_LOGIC;
    signal A_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal B_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal C_out_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal C_out_ce0 : STD_LOGIC;
    signal C_out_we0 : STD_LOGIC;
    signal C_out_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal C_out_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal A_rows : STD_LOGIC_VECTOR (63 downto 0);
    signal B_rows : STD_LOGIC_VECTOR (63 downto 0);
    signal B_columns : STD_LOGIC_VECTOR (63 downto 0);
    signal B_columns_read_reg_258 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal B_rows_read_reg_263 : STD_LOGIC_VECTOR (63 downto 0);
    signal A_rows_read_reg_269 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln3_fu_154_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln3_reg_280 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln3_1_fu_158_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln3_1_reg_285 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln3_2_fu_162_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln3_2_reg_290 : STD_LOGIC_VECTOR (2 downto 0);
    signal cmp61_fu_166_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp61_reg_295 : STD_LOGIC_VECTOR (0 downto 0);
    signal m_2_fu_185_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal m_2_reg_302 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal mul_fu_195_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal mul_reg_307 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln15_fu_180_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal mul20_fu_200_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal mul20_reg_312 : STD_LOGIC_VECTOR (2 downto 0);
    signal k_1_fu_210_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal k_1_reg_320 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal trunc_ln18_fu_216_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln18_reg_325 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln18_fu_205_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add215_fu_225_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add215_reg_330 : STD_LOGIC_VECTOR (2 downto 0);
    signal C_out_addr_reg_335 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal bitcast_ln26_fu_238_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln26_reg_340 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal acc_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal acc_ce0 : STD_LOGIC;
    signal acc_we0 : STD_LOGIC;
    signal acc_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_MatrixMultiplication_Pipeline_1_fu_128_ap_start : STD_LOGIC;
    signal grp_MatrixMultiplication_Pipeline_1_fu_128_ap_done : STD_LOGIC;
    signal grp_MatrixMultiplication_Pipeline_1_fu_128_ap_idle : STD_LOGIC;
    signal grp_MatrixMultiplication_Pipeline_1_fu_128_ap_ready : STD_LOGIC;
    signal grp_MatrixMultiplication_Pipeline_1_fu_128_acc_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatrixMultiplication_Pipeline_1_fu_128_acc_ce0 : STD_LOGIC;
    signal grp_MatrixMultiplication_Pipeline_1_fu_128_acc_we0 : STD_LOGIC;
    signal grp_MatrixMultiplication_Pipeline_1_fu_128_acc_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_ap_start : STD_LOGIC;
    signal grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_ap_done : STD_LOGIC;
    signal grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_ap_idle : STD_LOGIC;
    signal grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_ap_ready : STD_LOGIC;
    signal grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_A_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_A_ce0 : STD_LOGIC;
    signal grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_B_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_B_ce0 : STD_LOGIC;
    signal grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_acc_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_acc_ce0 : STD_LOGIC;
    signal grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_acc_we0 : STD_LOGIC;
    signal grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_acc_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_ap_start : STD_LOGIC;
    signal grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_ap_done : STD_LOGIC;
    signal grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_ap_idle : STD_LOGIC;
    signal grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_ap_ready : STD_LOGIC;
    signal grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_acc_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_acc_ce0 : STD_LOGIC;
    signal grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_add239_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_add239_out_ap_vld : STD_LOGIC;
    signal k_reg_117 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_MatrixMultiplication_Pipeline_1_fu_128_ap_start_reg : STD_LOGIC := '0';
    signal grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_ap_start_reg : STD_LOGIC := '0';
    signal grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal zext_ln26_fu_234_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal m_fu_74 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln15_fu_191_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln18_1_fu_221_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component MatrixMultiplication_MatrixMultiplication_Pipeline_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        acc_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        acc_ce0 : OUT STD_LOGIC;
        acc_we0 : OUT STD_LOGIC;
        acc_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component MatrixMultiplication_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        B_rows : IN STD_LOGIC_VECTOR (63 downto 0);
        mul : IN STD_LOGIC_VECTOR (2 downto 0);
        A_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        A_ce0 : OUT STD_LOGIC;
        A_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        trunc_ln3 : IN STD_LOGIC_VECTOR (4 downto 0);
        trunc_ln1 : IN STD_LOGIC_VECTOR (4 downto 0);
        B_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        B_ce0 : OUT STD_LOGIC;
        B_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        acc_ce0 : OUT STD_LOGIC;
        acc_we0 : OUT STD_LOGIC;
        acc_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component MatrixMultiplication_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        bitcast_ln26 : IN STD_LOGIC_VECTOR (31 downto 0);
        B_rows : IN STD_LOGIC_VECTOR (63 downto 0);
        acc_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        acc_ce0 : OUT STD_LOGIC;
        acc_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        add239_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        add239_out_ap_vld : OUT STD_LOGIC );
    end component;


    component MatrixMultiplication_mul_3s_3s_3_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (2 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component MatrixMultiplication_acc_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component MatrixMultiplication_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        A_rows : OUT STD_LOGIC_VECTOR (63 downto 0);
        A_address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        A_ce0 : IN STD_LOGIC;
        A_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        C_out_address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        C_out_ce0 : IN STD_LOGIC;
        C_out_we0 : IN STD_LOGIC;
        C_out_d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        C_out_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        B_rows : OUT STD_LOGIC_VECTOR (63 downto 0);
        B_columns : OUT STD_LOGIC_VECTOR (63 downto 0);
        B_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        B_ce0 : IN STD_LOGIC;
        B_q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    acc_U : component MatrixMultiplication_acc_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => acc_address0,
        ce0 => acc_ce0,
        we0 => acc_we0,
        d0 => acc_d0,
        q0 => acc_q0);

    grp_MatrixMultiplication_Pipeline_1_fu_128 : component MatrixMultiplication_MatrixMultiplication_Pipeline_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_MatrixMultiplication_Pipeline_1_fu_128_ap_start,
        ap_done => grp_MatrixMultiplication_Pipeline_1_fu_128_ap_done,
        ap_idle => grp_MatrixMultiplication_Pipeline_1_fu_128_ap_idle,
        ap_ready => grp_MatrixMultiplication_Pipeline_1_fu_128_ap_ready,
        acc_address0 => grp_MatrixMultiplication_Pipeline_1_fu_128_acc_address0,
        acc_ce0 => grp_MatrixMultiplication_Pipeline_1_fu_128_acc_ce0,
        acc_we0 => grp_MatrixMultiplication_Pipeline_1_fu_128_acc_we0,
        acc_d0 => grp_MatrixMultiplication_Pipeline_1_fu_128_acc_d0);

    grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133 : component MatrixMultiplication_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_ap_start,
        ap_done => grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_ap_done,
        ap_idle => grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_ap_idle,
        ap_ready => grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_ap_ready,
        B_rows => B_rows_read_reg_263,
        mul => mul_reg_307,
        A_address0 => grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_A_address0,
        A_ce0 => grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_A_ce0,
        A_q0 => A_q0,
        trunc_ln3 => trunc_ln3_reg_280,
        trunc_ln1 => trunc_ln18_reg_325,
        B_address0 => grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_B_address0,
        B_ce0 => grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_B_ce0,
        B_q0 => B_q0,
        acc_address0 => grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_acc_address0,
        acc_ce0 => grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_acc_ce0,
        acc_we0 => grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_acc_we0,
        acc_d0 => grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_acc_d0);

    grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146 : component MatrixMultiplication_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_ap_start,
        ap_done => grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_ap_done,
        ap_idle => grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_ap_idle,
        ap_ready => grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_ap_ready,
        bitcast_ln26 => bitcast_ln26_reg_340,
        B_rows => B_rows_read_reg_263,
        acc_address0 => grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_acc_address0,
        acc_ce0 => grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_acc_ce0,
        acc_q0 => acc_q0,
        add239_out => grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_add239_out,
        add239_out_ap_vld => grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_add239_out_ap_vld);

    control_s_axi_U : component MatrixMultiplication_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        A_rows => A_rows,
        A_address0 => grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_A_address0,
        A_ce0 => grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_A_ce0,
        A_q0 => A_q0,
        C_out_address0 => C_out_address0,
        C_out_ce0 => C_out_ce0,
        C_out_we0 => C_out_we0,
        C_out_d0 => C_out_d0,
        C_out_q0 => C_out_q0,
        B_rows => B_rows,
        B_columns => B_columns,
        B_address0 => grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_B_address0,
        B_ce0 => grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_B_ce0,
        B_q0 => B_q0);

    mul_3s_3s_3_1_1_U17 : component MatrixMultiplication_mul_3s_3s_3_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => trunc_ln15_fu_191_p1,
        din1 => trunc_ln3_2_reg_290,
        dout => mul_fu_195_p2);

    mul_3s_3s_3_1_1_U18 : component MatrixMultiplication_mul_3s_3s_3_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => trunc_ln15_fu_191_p1,
        din1 => trunc_ln3_1_reg_285,
        dout => mul20_fu_200_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_MatrixMultiplication_Pipeline_1_fu_128_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_MatrixMultiplication_Pipeline_1_fu_128_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln15_fu_180_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_MatrixMultiplication_Pipeline_1_fu_128_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_MatrixMultiplication_Pipeline_1_fu_128_ap_ready = ap_const_logic_1)) then 
                    grp_MatrixMultiplication_Pipeline_1_fu_128_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln18_fu_205_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_ap_ready = ap_const_logic_1)) then 
                    grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_ap_ready = ap_const_logic_1)) then 
                    grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    k_reg_117_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                k_reg_117 <= k_1_reg_320;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_MatrixMultiplication_Pipeline_1_fu_128_ap_done = ap_const_logic_1))) then 
                k_reg_117 <= ap_const_lv64_0;
            end if; 
        end if;
    end process;

    m_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                m_fu_74 <= ap_const_lv64_0;
            elsif (((icmp_ln18_fu_205_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                m_fu_74 <= m_2_reg_302;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                A_rows_read_reg_269 <= A_rows;
                B_columns_read_reg_258 <= B_columns;
                B_rows_read_reg_263 <= B_rows;
                cmp61_reg_295 <= cmp61_fu_166_p2;
                trunc_ln3_1_reg_285 <= trunc_ln3_1_fu_158_p1;
                trunc_ln3_2_reg_290 <= trunc_ln3_2_fu_162_p1;
                trunc_ln3_reg_280 <= trunc_ln3_fu_154_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((cmp61_reg_295 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                C_out_addr_reg_335 <= zext_ln26_fu_234_p1(3 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln18_fu_205_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                add215_reg_330 <= add215_fu_225_p2;
                trunc_ln18_reg_325 <= trunc_ln18_fu_216_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                bitcast_ln26_reg_340 <= bitcast_ln26_fu_238_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                k_1_reg_320 <= k_1_fu_210_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                m_2_reg_302 <= m_2_fu_185_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln15_fu_180_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                mul20_reg_312 <= mul20_fu_200_p2;
                mul_reg_307 <= mul_fu_195_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, cmp61_reg_295, ap_CS_fsm_state2, icmp_ln15_fu_180_p2, ap_CS_fsm_state4, icmp_ln18_fu_205_p2, ap_CS_fsm_state5, grp_MatrixMultiplication_Pipeline_1_fu_128_ap_done, grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_ap_done, grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state7)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln15_fu_180_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_MatrixMultiplication_Pipeline_1_fu_128_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln18_fu_205_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                if (((cmp61_reg_295 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5) and (grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                elsif (((cmp61_reg_295 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5) and (grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;

    C_out_address0_assign_proc : process(C_out_addr_reg_335, ap_CS_fsm_state5, ap_CS_fsm_state8, zext_ln26_fu_234_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            C_out_address0 <= C_out_addr_reg_335;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            C_out_address0 <= zext_ln26_fu_234_p1(3 - 1 downto 0);
        else 
            C_out_address0 <= "XXX";
        end if; 
    end process;


    C_out_ce0_assign_proc : process(ap_CS_fsm_state5, grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_ap_done, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_ap_done = ap_const_logic_1)))) then 
            C_out_ce0 <= ap_const_logic_1;
        else 
            C_out_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    C_out_d0 <= grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_add239_out;

    C_out_we0_assign_proc : process(cmp61_reg_295, ap_CS_fsm_state8)
    begin
        if (((cmp61_reg_295 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            C_out_we0 <= ap_const_logic_1;
        else 
            C_out_we0 <= ap_const_logic_0;
        end if; 
    end process;


    acc_address0_assign_proc : process(ap_CS_fsm_state5, grp_MatrixMultiplication_Pipeline_1_fu_128_acc_address0, grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_acc_address0, grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_acc_address0, ap_CS_fsm_state3, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            acc_address0 <= grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_acc_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            acc_address0 <= grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_acc_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            acc_address0 <= grp_MatrixMultiplication_Pipeline_1_fu_128_acc_address0;
        else 
            acc_address0 <= "XXXXXXXX";
        end if; 
    end process;


    acc_ce0_assign_proc : process(ap_CS_fsm_state5, grp_MatrixMultiplication_Pipeline_1_fu_128_acc_ce0, grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_acc_ce0, grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_acc_ce0, ap_CS_fsm_state3, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            acc_ce0 <= grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_acc_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            acc_ce0 <= grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_acc_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            acc_ce0 <= grp_MatrixMultiplication_Pipeline_1_fu_128_acc_ce0;
        else 
            acc_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    acc_d0_assign_proc : process(ap_CS_fsm_state5, grp_MatrixMultiplication_Pipeline_1_fu_128_acc_d0, grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_acc_d0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            acc_d0 <= grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_acc_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            acc_d0 <= grp_MatrixMultiplication_Pipeline_1_fu_128_acc_d0;
        else 
            acc_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    acc_we0_assign_proc : process(ap_CS_fsm_state5, grp_MatrixMultiplication_Pipeline_1_fu_128_acc_we0, grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_acc_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            acc_we0 <= grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_acc_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            acc_we0 <= grp_MatrixMultiplication_Pipeline_1_fu_128_acc_we0;
        else 
            acc_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add215_fu_225_p2 <= std_logic_vector(unsigned(trunc_ln18_1_fu_221_p1) + unsigned(mul20_reg_312));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_ST_fsm_state1_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_MatrixMultiplication_Pipeline_1_fu_128_ap_done)
    begin
        if ((grp_MatrixMultiplication_Pipeline_1_fu_128_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_ap_done)
    begin
        if ((grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_ap_done)
    begin
        if ((grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    bitcast_ln26_fu_238_p1 <= C_out_q0;
    cmp61_fu_166_p2 <= "1" when (B_rows = ap_const_lv64_0) else "0";
    grp_MatrixMultiplication_Pipeline_1_fu_128_ap_start <= grp_MatrixMultiplication_Pipeline_1_fu_128_ap_start_reg;
    grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_ap_start <= grp_MatrixMultiplication_Pipeline_VITIS_LOOP_20_3_fu_133_ap_start_reg;
    grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_ap_start <= grp_MatrixMultiplication_Pipeline_VITIS_LOOP_24_4_fu_146_ap_start_reg;
    icmp_ln15_fu_180_p2 <= "1" when (m_fu_74 = A_rows_read_reg_269) else "0";
    icmp_ln18_fu_205_p2 <= "1" when (k_reg_117 = B_columns_read_reg_258) else "0";
    k_1_fu_210_p2 <= std_logic_vector(unsigned(k_reg_117) + unsigned(ap_const_lv64_1));
    m_2_fu_185_p2 <= std_logic_vector(unsigned(m_fu_74) + unsigned(ap_const_lv64_1));
    trunc_ln15_fu_191_p1 <= m_fu_74(3 - 1 downto 0);
    trunc_ln18_1_fu_221_p1 <= k_reg_117(3 - 1 downto 0);
    trunc_ln18_fu_216_p1 <= k_reg_117(5 - 1 downto 0);
    trunc_ln3_1_fu_158_p1 <= B_columns(3 - 1 downto 0);
    trunc_ln3_2_fu_162_p1 <= B_rows(3 - 1 downto 0);
    trunc_ln3_fu_154_p1 <= B_columns(5 - 1 downto 0);
    zext_ln26_fu_234_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add215_reg_330),64));
end behav;
