// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module uz_NN_uz_NN_Pipeline_burst_B1mat (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_arrays_AWVALID,
        m_axi_arrays_AWREADY,
        m_axi_arrays_AWADDR,
        m_axi_arrays_AWID,
        m_axi_arrays_AWLEN,
        m_axi_arrays_AWSIZE,
        m_axi_arrays_AWBURST,
        m_axi_arrays_AWLOCK,
        m_axi_arrays_AWCACHE,
        m_axi_arrays_AWPROT,
        m_axi_arrays_AWQOS,
        m_axi_arrays_AWREGION,
        m_axi_arrays_AWUSER,
        m_axi_arrays_WVALID,
        m_axi_arrays_WREADY,
        m_axi_arrays_WDATA,
        m_axi_arrays_WSTRB,
        m_axi_arrays_WLAST,
        m_axi_arrays_WID,
        m_axi_arrays_WUSER,
        m_axi_arrays_ARVALID,
        m_axi_arrays_ARREADY,
        m_axi_arrays_ARADDR,
        m_axi_arrays_ARID,
        m_axi_arrays_ARLEN,
        m_axi_arrays_ARSIZE,
        m_axi_arrays_ARBURST,
        m_axi_arrays_ARLOCK,
        m_axi_arrays_ARCACHE,
        m_axi_arrays_ARPROT,
        m_axi_arrays_ARQOS,
        m_axi_arrays_ARREGION,
        m_axi_arrays_ARUSER,
        m_axi_arrays_RVALID,
        m_axi_arrays_RREADY,
        m_axi_arrays_RDATA,
        m_axi_arrays_RLAST,
        m_axi_arrays_RID,
        m_axi_arrays_RFIFONUM,
        m_axi_arrays_RUSER,
        m_axi_arrays_RRESP,
        m_axi_arrays_BVALID,
        m_axi_arrays_BREADY,
        m_axi_arrays_BRESP,
        m_axi_arrays_BID,
        m_axi_arrays_BUSER,
        sext_ln62,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_39_address0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_39_ce0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_39_we0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_39_d0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_35_address0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_35_ce0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_35_we0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_35_d0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_34_address0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_34_ce0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_34_we0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_34_d0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_33_address0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_33_ce0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_33_we0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_33_d0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_32_address0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_32_ce0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_32_we0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_32_d0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_31_address0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_31_ce0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_31_we0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_31_d0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_30_address0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_30_ce0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_30_we0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_30_d0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_38_address0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_38_ce0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_38_we0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_38_d0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_37_address0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_37_ce0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_37_we0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_37_d0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_36_address0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_36_ce0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_36_we0,
        uz_NN_float_float_float_float_float_float_float_float_float_fl_36_d0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_10_address0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_10_ce0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_10_we0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_10_d0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_11_address0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_11_ce0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_11_we0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_11_d0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_12_address0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_12_ce0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_12_we0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_12_d0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_13_address0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_13_ce0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_13_we0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_13_d0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_14_address0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_14_ce0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_14_we0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_14_d0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_15_address0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_15_ce0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_15_we0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_15_d0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_16_address0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_16_ce0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_16_we0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_16_d0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_17_address0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_17_ce0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_17_we0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_17_d0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_18_address0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_18_ce0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_18_we0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_18_d0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_19_address0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_19_ce0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_19_we0,
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_19_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_arrays_AWVALID;
input   m_axi_arrays_AWREADY;
output  [63:0] m_axi_arrays_AWADDR;
output  [0:0] m_axi_arrays_AWID;
output  [31:0] m_axi_arrays_AWLEN;
output  [2:0] m_axi_arrays_AWSIZE;
output  [1:0] m_axi_arrays_AWBURST;
output  [1:0] m_axi_arrays_AWLOCK;
output  [3:0] m_axi_arrays_AWCACHE;
output  [2:0] m_axi_arrays_AWPROT;
output  [3:0] m_axi_arrays_AWQOS;
output  [3:0] m_axi_arrays_AWREGION;
output  [0:0] m_axi_arrays_AWUSER;
output   m_axi_arrays_WVALID;
input   m_axi_arrays_WREADY;
output  [127:0] m_axi_arrays_WDATA;
output  [15:0] m_axi_arrays_WSTRB;
output   m_axi_arrays_WLAST;
output  [0:0] m_axi_arrays_WID;
output  [0:0] m_axi_arrays_WUSER;
output   m_axi_arrays_ARVALID;
input   m_axi_arrays_ARREADY;
output  [63:0] m_axi_arrays_ARADDR;
output  [0:0] m_axi_arrays_ARID;
output  [31:0] m_axi_arrays_ARLEN;
output  [2:0] m_axi_arrays_ARSIZE;
output  [1:0] m_axi_arrays_ARBURST;
output  [1:0] m_axi_arrays_ARLOCK;
output  [3:0] m_axi_arrays_ARCACHE;
output  [2:0] m_axi_arrays_ARPROT;
output  [3:0] m_axi_arrays_ARQOS;
output  [3:0] m_axi_arrays_ARREGION;
output  [0:0] m_axi_arrays_ARUSER;
input   m_axi_arrays_RVALID;
output   m_axi_arrays_RREADY;
input  [127:0] m_axi_arrays_RDATA;
input   m_axi_arrays_RLAST;
input  [0:0] m_axi_arrays_RID;
input  [8:0] m_axi_arrays_RFIFONUM;
input  [0:0] m_axi_arrays_RUSER;
input  [1:0] m_axi_arrays_RRESP;
input   m_axi_arrays_BVALID;
output   m_axi_arrays_BREADY;
input  [1:0] m_axi_arrays_BRESP;
input  [0:0] m_axi_arrays_BID;
input  [0:0] m_axi_arrays_BUSER;
input  [59:0] sext_ln62;
output  [5:0] uz_NN_float_float_float_float_float_float_float_float_float_fl_39_address0;
output   uz_NN_float_float_float_float_float_float_float_float_float_fl_39_ce0;
output   uz_NN_float_float_float_float_float_float_float_float_float_fl_39_we0;
output  [31:0] uz_NN_float_float_float_float_float_float_float_float_float_fl_39_d0;
output  [5:0] uz_NN_float_float_float_float_float_float_float_float_float_fl_35_address0;
output   uz_NN_float_float_float_float_float_float_float_float_float_fl_35_ce0;
output   uz_NN_float_float_float_float_float_float_float_float_float_fl_35_we0;
output  [31:0] uz_NN_float_float_float_float_float_float_float_float_float_fl_35_d0;
output  [5:0] uz_NN_float_float_float_float_float_float_float_float_float_fl_34_address0;
output   uz_NN_float_float_float_float_float_float_float_float_float_fl_34_ce0;
output   uz_NN_float_float_float_float_float_float_float_float_float_fl_34_we0;
output  [31:0] uz_NN_float_float_float_float_float_float_float_float_float_fl_34_d0;
output  [5:0] uz_NN_float_float_float_float_float_float_float_float_float_fl_33_address0;
output   uz_NN_float_float_float_float_float_float_float_float_float_fl_33_ce0;
output   uz_NN_float_float_float_float_float_float_float_float_float_fl_33_we0;
output  [31:0] uz_NN_float_float_float_float_float_float_float_float_float_fl_33_d0;
output  [5:0] uz_NN_float_float_float_float_float_float_float_float_float_fl_32_address0;
output   uz_NN_float_float_float_float_float_float_float_float_float_fl_32_ce0;
output   uz_NN_float_float_float_float_float_float_float_float_float_fl_32_we0;
output  [31:0] uz_NN_float_float_float_float_float_float_float_float_float_fl_32_d0;
output  [5:0] uz_NN_float_float_float_float_float_float_float_float_float_fl_31_address0;
output   uz_NN_float_float_float_float_float_float_float_float_float_fl_31_ce0;
output   uz_NN_float_float_float_float_float_float_float_float_float_fl_31_we0;
output  [31:0] uz_NN_float_float_float_float_float_float_float_float_float_fl_31_d0;
output  [5:0] uz_NN_float_float_float_float_float_float_float_float_float_fl_30_address0;
output   uz_NN_float_float_float_float_float_float_float_float_float_fl_30_ce0;
output   uz_NN_float_float_float_float_float_float_float_float_float_fl_30_we0;
output  [31:0] uz_NN_float_float_float_float_float_float_float_float_float_fl_30_d0;
output  [5:0] uz_NN_float_float_float_float_float_float_float_float_float_fl_38_address0;
output   uz_NN_float_float_float_float_float_float_float_float_float_fl_38_ce0;
output   uz_NN_float_float_float_float_float_float_float_float_float_fl_38_we0;
output  [31:0] uz_NN_float_float_float_float_float_float_float_float_float_fl_38_d0;
output  [5:0] uz_NN_float_float_float_float_float_float_float_float_float_fl_37_address0;
output   uz_NN_float_float_float_float_float_float_float_float_float_fl_37_ce0;
output   uz_NN_float_float_float_float_float_float_float_float_float_fl_37_we0;
output  [31:0] uz_NN_float_float_float_float_float_float_float_float_float_fl_37_d0;
output  [5:0] uz_NN_float_float_float_float_float_float_float_float_float_fl_36_address0;
output   uz_NN_float_float_float_float_float_float_float_float_float_fl_36_ce0;
output   uz_NN_float_float_float_float_float_float_float_float_float_fl_36_we0;
output  [31:0] uz_NN_float_float_float_float_float_float_float_float_float_fl_36_d0;
output  [5:0] p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_10_address0;
output   p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_10_ce0;
output   p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_10_we0;
output  [31:0] p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_10_d0;
output  [5:0] p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_11_address0;
output   p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_11_ce0;
output   p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_11_we0;
output  [31:0] p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_11_d0;
output  [5:0] p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_12_address0;
output   p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_12_ce0;
output   p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_12_we0;
output  [31:0] p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_12_d0;
output  [5:0] p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_13_address0;
output   p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_13_ce0;
output   p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_13_we0;
output  [31:0] p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_13_d0;
output  [5:0] p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_14_address0;
output   p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_14_ce0;
output   p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_14_we0;
output  [31:0] p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_14_d0;
output  [5:0] p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_15_address0;
output   p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_15_ce0;
output   p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_15_we0;
output  [31:0] p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_15_d0;
output  [5:0] p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_16_address0;
output   p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_16_ce0;
output   p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_16_we0;
output  [31:0] p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_16_d0;
output  [5:0] p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_17_address0;
output   p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_17_ce0;
output   p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_17_we0;
output  [31:0] p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_17_d0;
output  [5:0] p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_18_address0;
output   p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_18_ce0;
output   p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_18_we0;
output  [31:0] p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_18_d0;
output  [5:0] p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_19_address0;
output   p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_19_ce0;
output   p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_19_we0;
output  [31:0] p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_19_d0;

reg ap_idle;
reg m_axi_arrays_RREADY;
reg uz_NN_float_float_float_float_float_float_float_float_float_fl_39_ce0;
reg uz_NN_float_float_float_float_float_float_float_float_float_fl_39_we0;
reg uz_NN_float_float_float_float_float_float_float_float_float_fl_35_ce0;
reg uz_NN_float_float_float_float_float_float_float_float_float_fl_35_we0;
reg uz_NN_float_float_float_float_float_float_float_float_float_fl_34_ce0;
reg uz_NN_float_float_float_float_float_float_float_float_float_fl_34_we0;
reg uz_NN_float_float_float_float_float_float_float_float_float_fl_33_ce0;
reg uz_NN_float_float_float_float_float_float_float_float_float_fl_33_we0;
reg uz_NN_float_float_float_float_float_float_float_float_float_fl_32_ce0;
reg uz_NN_float_float_float_float_float_float_float_float_float_fl_32_we0;
reg uz_NN_float_float_float_float_float_float_float_float_float_fl_31_ce0;
reg uz_NN_float_float_float_float_float_float_float_float_float_fl_31_we0;
reg uz_NN_float_float_float_float_float_float_float_float_float_fl_30_ce0;
reg uz_NN_float_float_float_float_float_float_float_float_float_fl_30_we0;
reg uz_NN_float_float_float_float_float_float_float_float_float_fl_38_ce0;
reg uz_NN_float_float_float_float_float_float_float_float_float_fl_38_we0;
reg uz_NN_float_float_float_float_float_float_float_float_float_fl_37_ce0;
reg uz_NN_float_float_float_float_float_float_float_float_float_fl_37_we0;
reg uz_NN_float_float_float_float_float_float_float_float_float_fl_36_ce0;
reg uz_NN_float_float_float_float_float_float_float_float_float_fl_36_we0;
reg p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_10_ce0;
reg p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_10_we0;
reg p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_11_ce0;
reg p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_11_we0;
reg p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_12_ce0;
reg p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_12_we0;
reg p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_13_ce0;
reg p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_13_we0;
reg p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_14_ce0;
reg p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_14_we0;
reg p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_15_ce0;
reg p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_15_we0;
reg p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_16_ce0;
reg p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_16_we0;
reg p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_17_ce0;
reg p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_17_we0;
reg p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_18_ce0;
reg p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_18_we0;
reg p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_19_ce0;
reg p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_19_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] icmp_ln62_reg_587;
reg   [0:0] icmp_ln64_reg_596;
reg    ap_predicate_op27_read_state2;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln62_fu_447_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    arrays_blk_n_R;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln62_reg_587_pp0_iter1_reg;
wire   [5:0] trunc_ln62_fu_459_p1;
reg   [5:0] trunc_ln62_reg_591;
reg   [5:0] trunc_ln62_reg_591_pp0_iter1_reg;
wire   [0:0] icmp_ln64_fu_467_p2;
reg   [0:0] icmp_ln64_reg_596_pp0_iter1_reg;
reg   [4:0] trunc_ln64_1_reg_600;
reg   [4:0] trunc_ln64_1_reg_600_pp0_iter1_reg;
reg   [127:0] arrays_addr_read_reg_604;
reg    ap_condition_exit_pp0_iter1_stage0;
reg   [127:0] ap_phi_mux_empty_73_phi_fu_424_p4;
wire   [127:0] ap_phi_reg_pp0_iter2_empty_73_reg_421;
wire   [127:0] zext_ln62_fu_497_p1;
wire   [63:0] zext_ln64_fu_540_p1;
reg   [95:0] shiftreg66_fu_142;
wire    ap_loop_init;
reg   [10:0] i_1_fu_146;
wire   [10:0] add_ln62_fu_453_p2;
reg   [10:0] ap_sig_allocacmp_i;
wire   [31:0] bitcast_ln64_fu_506_p1;
wire   [1:0] trunc_ln62_1_fu_463_p1;
wire   [31:0] trunc_ln64_fu_502_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

uz_NN_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln62_fu_447_p2 == 1'd0))) begin
            i_1_fu_146 <= add_ln62_fu_453_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_1_fu_146 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            shiftreg66_fu_142 <= 96'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            shiftreg66_fu_142 <= {{ap_phi_mux_empty_73_phi_fu_424_p4[127:32]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln62_reg_587 <= icmp_ln62_fu_447_p2;
        icmp_ln62_reg_587_pp0_iter1_reg <= icmp_ln62_reg_587;
        icmp_ln64_reg_596_pp0_iter1_reg <= icmp_ln64_reg_596;
        trunc_ln62_reg_591_pp0_iter1_reg <= trunc_ln62_reg_591;
        trunc_ln64_1_reg_600_pp0_iter1_reg <= trunc_ln64_1_reg_600;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_op27_read_state2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        arrays_addr_read_reg_604 <= m_axi_arrays_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln62_fu_447_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln64_reg_596 <= icmp_ln64_fu_467_p2;
        trunc_ln62_reg_591 <= trunc_ln62_fu_459_p1;
        trunc_ln64_1_reg_600 <= {{ap_sig_allocacmp_i[10:6]}};
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln62_fu_447_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln62_reg_587 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln62_reg_587_pp0_iter1_reg == 1'd0)) begin
        if ((icmp_ln64_reg_596_pp0_iter1_reg == 1'd0)) begin
            ap_phi_mux_empty_73_phi_fu_424_p4 = zext_ln62_fu_497_p1;
        end else if ((icmp_ln64_reg_596_pp0_iter1_reg == 1'd1)) begin
            ap_phi_mux_empty_73_phi_fu_424_p4 = arrays_addr_read_reg_604;
        end else begin
            ap_phi_mux_empty_73_phi_fu_424_p4 = ap_phi_reg_pp0_iter2_empty_73_reg_421;
        end
    end else begin
        ap_phi_mux_empty_73_phi_fu_424_p4 = ap_phi_reg_pp0_iter2_empty_73_reg_421;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_i = 11'd0;
    end else begin
        ap_sig_allocacmp_i = i_1_fu_146;
    end
end

always @ (*) begin
    if (((ap_predicate_op27_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        arrays_blk_n_R = m_axi_arrays_RVALID;
    end else begin
        arrays_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op27_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_arrays_RREADY = 1'b1;
    end else begin
        m_axi_arrays_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_10_ce0 = 1'b1;
    end else begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd10) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_10_we0 = 1'b1;
    end else begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_11_ce0 = 1'b1;
    end else begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd11) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_11_we0 = 1'b1;
    end else begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_12_ce0 = 1'b1;
    end else begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd12) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_12_we0 = 1'b1;
    end else begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_13_ce0 = 1'b1;
    end else begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd13) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_13_we0 = 1'b1;
    end else begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_14_ce0 = 1'b1;
    end else begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd14) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_14_we0 = 1'b1;
    end else begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_15_ce0 = 1'b1;
    end else begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd15) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_15_we0 = 1'b1;
    end else begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_16_ce0 = 1'b1;
    end else begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_16_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd16) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_16_we0 = 1'b1;
    end else begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_16_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_17_ce0 = 1'b1;
    end else begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_17_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd17) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_17_we0 = 1'b1;
    end else begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_17_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_18_ce0 = 1'b1;
    end else begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_18_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd18) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_18_we0 = 1'b1;
    end else begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_18_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_19_ce0 = 1'b1;
    end else begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_19_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & ((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd19) | ((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd20) | ((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd21) | ((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd22) | ((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd23) | ((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd24) | ((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd25) | ((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd26) | ((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd27) | ((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd28) | ((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd29) | ((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd30) | (trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd31))))))))))))))) begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_19_we0 = 1'b1;
    end else begin
        p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_19_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_30_ce0 = 1'b1;
    end else begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_30_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd6) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_30_we0 = 1'b1;
    end else begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_30_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_31_ce0 = 1'b1;
    end else begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_31_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd5) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_31_we0 = 1'b1;
    end else begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_31_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_32_ce0 = 1'b1;
    end else begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_32_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd4) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_32_we0 = 1'b1;
    end else begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_32_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_33_ce0 = 1'b1;
    end else begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_33_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_33_we0 = 1'b1;
    end else begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_33_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_34_ce0 = 1'b1;
    end else begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_34_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_34_we0 = 1'b1;
    end else begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_34_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_35_ce0 = 1'b1;
    end else begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_35_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_35_we0 = 1'b1;
    end else begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_35_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_36_ce0 = 1'b1;
    end else begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_36_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd9) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_36_we0 = 1'b1;
    end else begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_36_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_37_ce0 = 1'b1;
    end else begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_37_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd8) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_37_we0 = 1'b1;
    end else begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_37_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_38_ce0 = 1'b1;
    end else begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_38_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd7) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_38_we0 = 1'b1;
    end else begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_38_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_39_ce0 = 1'b1;
    end else begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_39_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln64_1_reg_600_pp0_iter1_reg == 5'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_39_we0 = 1'b1;
    end else begin
        uz_NN_float_float_float_float_float_float_float_float_float_fl_39_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln62_fu_453_p2 = (ap_sig_allocacmp_i + 11'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_predicate_op27_read_state2 == 1'b1) & (m_axi_arrays_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_predicate_op27_read_state2 == 1'b1) & (m_axi_arrays_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((ap_predicate_op27_read_state2 == 1'b1) & (m_axi_arrays_RVALID == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter2_empty_73_reg_421 = 'bx;

always @ (*) begin
    ap_predicate_op27_read_state2 = ((icmp_ln64_reg_596 == 1'd1) & (icmp_ln62_reg_587 == 1'd0));
end

assign bitcast_ln64_fu_506_p1 = trunc_ln64_fu_502_p1;

assign icmp_ln62_fu_447_p2 = ((ap_sig_allocacmp_i == 11'd1280) ? 1'b1 : 1'b0);

assign icmp_ln64_fu_467_p2 = ((trunc_ln62_1_fu_463_p1 == 2'd0) ? 1'b1 : 1'b0);

assign m_axi_arrays_ARADDR = 64'd0;

assign m_axi_arrays_ARBURST = 2'd0;

assign m_axi_arrays_ARCACHE = 4'd0;

assign m_axi_arrays_ARID = 1'd0;

assign m_axi_arrays_ARLEN = 32'd0;

assign m_axi_arrays_ARLOCK = 2'd0;

assign m_axi_arrays_ARPROT = 3'd0;

assign m_axi_arrays_ARQOS = 4'd0;

assign m_axi_arrays_ARREGION = 4'd0;

assign m_axi_arrays_ARSIZE = 3'd0;

assign m_axi_arrays_ARUSER = 1'd0;

assign m_axi_arrays_ARVALID = 1'b0;

assign m_axi_arrays_AWADDR = 64'd0;

assign m_axi_arrays_AWBURST = 2'd0;

assign m_axi_arrays_AWCACHE = 4'd0;

assign m_axi_arrays_AWID = 1'd0;

assign m_axi_arrays_AWLEN = 32'd0;

assign m_axi_arrays_AWLOCK = 2'd0;

assign m_axi_arrays_AWPROT = 3'd0;

assign m_axi_arrays_AWQOS = 4'd0;

assign m_axi_arrays_AWREGION = 4'd0;

assign m_axi_arrays_AWSIZE = 3'd0;

assign m_axi_arrays_AWUSER = 1'd0;

assign m_axi_arrays_AWVALID = 1'b0;

assign m_axi_arrays_BREADY = 1'b0;

assign m_axi_arrays_WDATA = 128'd0;

assign m_axi_arrays_WID = 1'd0;

assign m_axi_arrays_WLAST = 1'b0;

assign m_axi_arrays_WSTRB = 16'd0;

assign m_axi_arrays_WUSER = 1'd0;

assign m_axi_arrays_WVALID = 1'b0;

assign p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_10_address0 = zext_ln64_fu_540_p1;

assign p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_10_d0 = bitcast_ln64_fu_506_p1;

assign p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_11_address0 = zext_ln64_fu_540_p1;

assign p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_11_d0 = bitcast_ln64_fu_506_p1;

assign p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_12_address0 = zext_ln64_fu_540_p1;

assign p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_12_d0 = bitcast_ln64_fu_506_p1;

assign p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_13_address0 = zext_ln64_fu_540_p1;

assign p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_13_d0 = bitcast_ln64_fu_506_p1;

assign p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_14_address0 = zext_ln64_fu_540_p1;

assign p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_14_d0 = bitcast_ln64_fu_506_p1;

assign p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_15_address0 = zext_ln64_fu_540_p1;

assign p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_15_d0 = bitcast_ln64_fu_506_p1;

assign p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_16_address0 = zext_ln64_fu_540_p1;

assign p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_16_d0 = bitcast_ln64_fu_506_p1;

assign p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_17_address0 = zext_ln64_fu_540_p1;

assign p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_17_d0 = bitcast_ln64_fu_506_p1;

assign p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_18_address0 = zext_ln64_fu_540_p1;

assign p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_18_d0 = bitcast_ln64_fu_506_p1;

assign p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_19_address0 = zext_ln64_fu_540_p1;

assign p_ZZ5uz_NNPfS_S_S_S_S_S_S_S_S_bjjjjPVbS1_E2B1_19_d0 = bitcast_ln64_fu_506_p1;

assign trunc_ln62_1_fu_463_p1 = ap_sig_allocacmp_i[1:0];

assign trunc_ln62_fu_459_p1 = ap_sig_allocacmp_i[5:0];

assign trunc_ln64_fu_502_p1 = ap_phi_mux_empty_73_phi_fu_424_p4[31:0];

assign uz_NN_float_float_float_float_float_float_float_float_float_fl_30_address0 = zext_ln64_fu_540_p1;

assign uz_NN_float_float_float_float_float_float_float_float_float_fl_30_d0 = bitcast_ln64_fu_506_p1;

assign uz_NN_float_float_float_float_float_float_float_float_float_fl_31_address0 = zext_ln64_fu_540_p1;

assign uz_NN_float_float_float_float_float_float_float_float_float_fl_31_d0 = bitcast_ln64_fu_506_p1;

assign uz_NN_float_float_float_float_float_float_float_float_float_fl_32_address0 = zext_ln64_fu_540_p1;

assign uz_NN_float_float_float_float_float_float_float_float_float_fl_32_d0 = bitcast_ln64_fu_506_p1;

assign uz_NN_float_float_float_float_float_float_float_float_float_fl_33_address0 = zext_ln64_fu_540_p1;

assign uz_NN_float_float_float_float_float_float_float_float_float_fl_33_d0 = bitcast_ln64_fu_506_p1;

assign uz_NN_float_float_float_float_float_float_float_float_float_fl_34_address0 = zext_ln64_fu_540_p1;

assign uz_NN_float_float_float_float_float_float_float_float_float_fl_34_d0 = bitcast_ln64_fu_506_p1;

assign uz_NN_float_float_float_float_float_float_float_float_float_fl_35_address0 = zext_ln64_fu_540_p1;

assign uz_NN_float_float_float_float_float_float_float_float_float_fl_35_d0 = bitcast_ln64_fu_506_p1;

assign uz_NN_float_float_float_float_float_float_float_float_float_fl_36_address0 = zext_ln64_fu_540_p1;

assign uz_NN_float_float_float_float_float_float_float_float_float_fl_36_d0 = bitcast_ln64_fu_506_p1;

assign uz_NN_float_float_float_float_float_float_float_float_float_fl_37_address0 = zext_ln64_fu_540_p1;

assign uz_NN_float_float_float_float_float_float_float_float_float_fl_37_d0 = bitcast_ln64_fu_506_p1;

assign uz_NN_float_float_float_float_float_float_float_float_float_fl_38_address0 = zext_ln64_fu_540_p1;

assign uz_NN_float_float_float_float_float_float_float_float_float_fl_38_d0 = bitcast_ln64_fu_506_p1;

assign uz_NN_float_float_float_float_float_float_float_float_float_fl_39_address0 = zext_ln64_fu_540_p1;

assign uz_NN_float_float_float_float_float_float_float_float_float_fl_39_d0 = bitcast_ln64_fu_506_p1;

assign zext_ln62_fu_497_p1 = shiftreg66_fu_142;

assign zext_ln64_fu_540_p1 = trunc_ln62_reg_591_pp0_iter1_reg;

endmodule //uz_NN_uz_NN_Pipeline_burst_B1mat
