open_system('uz_JL_SigmaDelta_Interface');
open_system('gm_uz_JL_SigmaDelta_Interface');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SigmaDelta_Interface/uz_JL_SigmaDelta_Inferface/Delay11', 'user2');
annotate_port('gm_uz_JL_SigmaDelta_Interface/uz_JL_SigmaDelta_Inferface/Delay11', 1, 1, 'Block not characterized');
hilite_system('uz_JL_SigmaDelta_Interface/uz_JL_SigmaDelta_Inferface/Delay11', 'user2');
annotate_port('uz_JL_SigmaDelta_Interface/uz_JL_SigmaDelta_Inferface/Delay11', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SigmaDelta_Interface/uz_JL_SigmaDelta_Inferface/Subsystem1/CLk1/Delay1', 'user2');
annotate_port('gm_uz_JL_SigmaDelta_Interface/uz_JL_SigmaDelta_Inferface/Subsystem1/CLk1/Delay1', 1, 1, 'Block not characterized');
hilite_system('uz_JL_SigmaDelta_Interface/uz_JL_SigmaDelta_Inferface/Subsystem1/CLk1/Delay1', 'user2');
annotate_port('uz_JL_SigmaDelta_Interface/uz_JL_SigmaDelta_Inferface/Subsystem1/CLk1/Delay1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
