SLStudio.Utils.RemoveHighlighting(get_param('Copy_of_uz_pmsm_model_9ph_21b_all_double', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double', 'handle'));
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Sine HDL Optimized', 0, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/From18', 0, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Goto15', 0, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/vectorized_in0', 1, 1, '');
annotate_port('Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Line-Line to Phase voltage/abc   to   alpha_beta_0/Gain4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Row2Col_in0', 1, 1, '');
annotate_port('Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Line-Line to Phase voltage/abc   to   alpha_beta_0/Gain4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Row2Col_in1', 1, 1, '');
annotate_port('Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Line-Line to Phase voltage/abc   to   alpha_beta_0/Gain4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/reshape_dotProduct', 1, 1, '');
annotate_port('Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Line-Line to Phase voltage/abc   to   alpha_beta_0/Gain4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/reshape_mmulResult', 1, 1, '');
annotate_port('Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Line-Line to Phase voltage/abc   to   alpha_beta_0/Gain4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/t10', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/vectorized_in01', 1, 1, '');
annotate_port('Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Line-Line to Phase voltage/alpha_beta_0   to   abc/Gain4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Row2Col_in01', 1, 1, '');
annotate_port('Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Line-Line to Phase voltage/alpha_beta_0   to   abc/Gain4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Row2Col_in11', 1, 1, '');
annotate_port('Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Line-Line to Phase voltage/alpha_beta_0   to   abc/Gain4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/reshape_dotProduct1', 1, 1, '');
annotate_port('Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Line-Line to Phase voltage/alpha_beta_0   to   abc/Gain4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/reshape_mmulResult1', 1, 1, '');
annotate_port('Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Line-Line to Phase voltage/alpha_beta_0   to   abc/Gain4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/t11', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/vectorized_in02', 1, 1, '');
annotate_port('Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Line-Line to Phase voltage1/abc   to   alpha_beta_0/Gain4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Row2Col_in02', 1, 1, '');
annotate_port('Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Line-Line to Phase voltage1/abc   to   alpha_beta_0/Gain4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Row2Col_in12', 1, 1, '');
annotate_port('Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Line-Line to Phase voltage1/abc   to   alpha_beta_0/Gain4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/reshape_dotProduct2', 1, 1, '');
annotate_port('Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Line-Line to Phase voltage1/abc   to   alpha_beta_0/Gain4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/reshape_mmulResult2', 1, 1, '');
annotate_port('Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Line-Line to Phase voltage1/abc   to   alpha_beta_0/Gain4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/t12', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/vectorized_in03', 1, 1, '');
annotate_port('Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Line-Line to Phase voltage1/alpha_beta_0   to   abc/Gain4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Row2Col_in03', 1, 1, '');
annotate_port('Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Line-Line to Phase voltage1/alpha_beta_0   to   abc/Gain4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Row2Col_in13', 1, 1, '');
annotate_port('Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Line-Line to Phase voltage1/alpha_beta_0   to   abc/Gain4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/reshape_dotProduct3', 1, 1, '');
annotate_port('Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Line-Line to Phase voltage1/alpha_beta_0   to   abc/Gain4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/reshape_mmulResult3', 1, 1, '');
annotate_port('Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Line-Line to Phase voltage1/alpha_beta_0   to   abc/Gain4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/t13', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/vectorized_in04', 1, 1, '');
annotate_port('Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Line-Line to Phase voltage2/abc   to   alpha_beta_0/Gain4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Row2Col_in04', 1, 1, '');
annotate_port('Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Line-Line to Phase voltage2/abc   to   alpha_beta_0/Gain4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Row2Col_in14', 1, 1, '');
annotate_port('Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Line-Line to Phase voltage2/abc   to   alpha_beta_0/Gain4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/reshape_dotProduct4', 1, 1, '');
annotate_port('Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Line-Line to Phase voltage2/abc   to   alpha_beta_0/Gain4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/reshape_mmulResult4', 1, 1, '');
annotate_port('Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Line-Line to Phase voltage2/abc   to   alpha_beta_0/Gain4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/t14', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/vectorized_in05', 1, 1, '');
annotate_port('Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Line-Line to Phase voltage2/alpha_beta_0   to   abc/Gain4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Row2Col_in05', 1, 1, '');
annotate_port('Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Line-Line to Phase voltage2/alpha_beta_0   to   abc/Gain4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Row2Col_in15', 1, 1, '');
annotate_port('Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Line-Line to Phase voltage2/alpha_beta_0   to   abc/Gain4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/reshape_dotProduct5', 1, 1, '');
annotate_port('Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Line-Line to Phase voltage2/alpha_beta_0   to   abc/Gain4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/reshape_mmulResult5', 1, 1, '');
annotate_port('Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Line-Line to Phase voltage2/alpha_beta_0   to   abc/Gain4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/t15', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/t16', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/t17', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/t18', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/t22', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/t24', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/t25', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/t26', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/t27', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/t28', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/t29', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/t30', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/t31', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/t32', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd1', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd2', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd3', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd4', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd5', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd6', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd7', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd8', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd9', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd10', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd11', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd12', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd13', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd14', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd15', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd16', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd17', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd18', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd19', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd20', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd21', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd22', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd23', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd24', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd25', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd26', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd27', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd28', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd29', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd30', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd31', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd32', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd33', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd34', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd35', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd36', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd37', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd38', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd39', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd40', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd41', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd42', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd43', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd44', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd45', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd46', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd47', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd48', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd49', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd50', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd51', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd52', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd53', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd54', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd55', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd56', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd57', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd58', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd59', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd60', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd61', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd62', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd63', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd64', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd65', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd66', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd67', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd68', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd69', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd70', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd71', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd72', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd73', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd74', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd75', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd76', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd77', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd78', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd79', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/_adder_MultiplyAdd80', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/delayMatch158', 1, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Sine HDL Optimized/Point501', 0, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Sine HDL Optimized/Sine', 0, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Sine HDL Optimized/Sine1', 0, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Sine HDL Optimized/CastU16En21', 0, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Sine HDL Optimized/CastU16En31', 0, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Sine HDL Optimized/CastU16En4', 0, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Sine HDL Optimized/LTEp251', 0, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Sine HDL Optimized/LTEp501', 0, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Sine HDL Optimized/Look-Up Table1', 0, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Sine HDL Optimized/Negate1', 0, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Sine HDL Optimized/QuadHandle1', 0, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Sine HDL Optimized/QuadHandle21', 0, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Sine HDL Optimized/Saturation1', 0, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Sine HDL Optimized/SignCorrected1', 0, 1, '');
annotate_port('gm_Copy_of_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Sine HDL Optimized/Switch1', 0, 1, '');
