SLStudio.Utils.RemoveHighlighting(get_param('uz_pmsm_model_9ph_21b_all_double', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_uz_pmsm_model_9ph_21b_all_double', 'handle'));
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq', 0, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Sine HDL Optimized/Point501', 0, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Sine HDL Optimized/CastU16En21', 0, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Sine HDL Optimized/CastU16En31', 0, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Sine HDL Optimized/CastU16En4', 0, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Sine HDL Optimized/LTEp251', 0, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Sine HDL Optimized/LTEp501', 0, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Sine HDL Optimized/Look-Up Table1', 0, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Sine HDL Optimized/Negate1', 0, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Sine HDL Optimized/QuadHandle1', 0, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Sine HDL Optimized/QuadHandle21', 0, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Sine HDL Optimized/Saturation1', 0, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Sine HDL Optimized/SignCorrected1', 0, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Sine HDL Optimized/Switch1', 0, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/crp_temp_MAC/t', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/crp_temp_MAC1/t', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/crp_temp_MAC2/t', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/crp_temp_MAC3/t', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/crp_temp_MAC4/t', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/crp_temp_MAC5/t', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/crp_temp_MAC6/t', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/crp_temp_MAC7/t', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/crp_temp_MAC8/t', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Divide1/HwModeRegister', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd1/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd2/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd3/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd4/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd5/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd6/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd7/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd8/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd9/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd10/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd11/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd12/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd13/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd14/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd15/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd16/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd17/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd18/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd19/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd20/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd21/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd22/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd23/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd24/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd25/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd26/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd27/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd28/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd29/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd30/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd31/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd32/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd33/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd34/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd35/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd36/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd37/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd38/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd39/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd40/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd41/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd42/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd43/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd44/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd45/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd46/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd47/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd48/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd49/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd50/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd51/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd52/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd53/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd54/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd55/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd56/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd57/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd58/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd59/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd60/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd61/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd62/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd63/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd64/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd65/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd66/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd67/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd68/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd69/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd70/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd71/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd72/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd73/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd74/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd75/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd76/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd77/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd78/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd79/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/_adder_MultiplyAdd80/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Delay1', 1, 1, '');
annotate_port('uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Delay1', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Unit Delay', 1, 1, '');
annotate_port('uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/Unit Delay', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/From18', 0, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Sine HDL Optimized', 0, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Goto15', 0, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/t10', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/vectorized_in0', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Row2Col_in0', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Row2Col_in1', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/reshape_dotProduct', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/reshape_mmulResult', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/t11', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/vectorized_in01', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Row2Col_in01', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Row2Col_in11', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/reshape_dotProduct1', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/reshape_mmulResult1', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/t12', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/vectorized_in02', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Row2Col_in02', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Row2Col_in12', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/reshape_dotProduct2', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/reshape_mmulResult2', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/t13', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/vectorized_in03', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Row2Col_in03', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Row2Col_in13', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/reshape_dotProduct3', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/reshape_mmulResult3', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/t14', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/vectorized_in04', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Row2Col_in04', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Row2Col_in14', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/reshape_dotProduct4', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/reshape_mmulResult4', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/t15', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/vectorized_in05', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Row2Col_in05', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Row2Col_in15', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/reshape_dotProduct5', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/reshape_mmulResult5', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/t16', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/t17', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/t18', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/t22', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/abc_to_dq/abc_to_dq/Divide1', 1, 1, '');
