open_system('gm_UZ_D_GaN_Inverter_reduced');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter_reduced/UZ_D_GaN_Inverter/PWMdutycycFreqDetection', 'user2');
annotate_port('gm_UZ_D_GaN_Inverter_reduced/UZ_D_GaN_Inverter/PWMdutycycFreqDetection', 0, 4, 'cp : 22.014 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter_reduced/UZ_D_GaN_Inverter/PWMdutycycFreqDetection/Detect Fall Nonpositive', 'user2');
annotate_port('gm_UZ_D_GaN_Inverter_reduced/UZ_D_GaN_Inverter/PWMdutycycFreqDetection/Detect Fall Nonpositive', 0, 1, 'cp : 2.334 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter_reduced/UZ_D_GaN_Inverter/PWMdutycycFreqDetection/Gain', 'user1');
annotate_port('gm_UZ_D_GaN_Inverter_reduced/UZ_D_GaN_Inverter/PWMdutycycFreqDetection/Gain', 0, 1, 'cp : 22.014 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter_reduced/UZ_D_GaN_Inverter/PWMdutycycFreqDetection/Compare To Constant', 'user2');
annotate_port('gm_UZ_D_GaN_Inverter_reduced/UZ_D_GaN_Inverter/PWMdutycycFreqDetection/Compare To Constant', 0, 1, 'cp : 3.501 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter_reduced/UZ_D_GaN_Inverter/PWMdutycycFreqDetection/Product', 'user2');
annotate_port('gm_UZ_D_GaN_Inverter_reduced/UZ_D_GaN_Inverter/PWMdutycycFreqDetection/Product', 0, 1, 'cp : 13.099 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter_reduced/UZ_D_GaN_Inverter/PWMdutycycFreqDetection/Switch1', 'user2');
annotate_port('gm_UZ_D_GaN_Inverter_reduced/UZ_D_GaN_Inverter/PWMdutycycFreqDetection/Switch1', 0, 1, 'cp : 4.184 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter_reduced/UZ_D_GaN_Inverter/PWMdutycycFreqDetection/Detect Fall Nonpositive/FixPt Relational Operator', 'user2');
annotate_port('gm_UZ_D_GaN_Inverter_reduced/UZ_D_GaN_Inverter/PWMdutycycFreqDetection/Detect Fall Nonpositive/FixPt Relational Operator', 0, 1, 'cp : 2.334 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter_reduced/UZ_D_GaN_Inverter/PWMdutycycFreqDetection/Detect Fall Nonpositive/Nonpositive', 'user1');
annotate_port('gm_UZ_D_GaN_Inverter_reduced/UZ_D_GaN_Inverter/PWMdutycycFreqDetection/Detect Fall Nonpositive/Nonpositive', 0, 1, 'cp : 1.167 ns');
