-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/inc_enc_v26/IncEnc_V2_ip_src_count_lines.vhd
-- Created: 2024-12-15 21:07:15
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: IncEnc_V2_ip_src_count_lines
-- Source Path: inc_enc_v26/IncEnc_V26/count_lines
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY IncEnc_V2_ip_src_count_lines IS
  PORT( clk                               :   IN    std_logic;
        reset_x                           :   IN    std_logic;
        enb                               :   IN    std_logic;
        Edge_rsvd                         :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        Reset                             :   IN    std_logic;
        IncsPerTurn                       :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        count                             :   OUT   std_logic_vector(15 DOWNTO 0)  -- int16
        );
END IncEnc_V2_ip_src_count_lines;


ARCHITECTURE rtl OF IncEnc_V2_ip_src_count_lines IS

  -- Signals
  SIGNAL Use_new_value                    : std_logic;
  SIGNAL Use_new_value_1                  : std_logic;
  SIGNAL Constant4_out1                   : signed(15 DOWNTO 0);  -- int16
  SIGNAL IncsPerTurn_unsigned             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL IncsPerTurn_1                    : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Reset_when_overflow_add_cast     : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL Reset_when_overflow_add_temp     : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL Reset_when_overflow_out1         : signed(15 DOWNTO 0);  -- int16
  SIGNAL Reset_when_overflow_out1_1       : signed(15 DOWNTO 0);  -- int16
  SIGNAL Edge_signed                      : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant3_out1                   : signed(15 DOWNTO 0);  -- int16
  SIGNAL Constant2_out1                   : signed(15 DOWNTO 0);  -- int16
  SIGNAL Constant2_out1_1                 : signed(15 DOWNTO 0);  -- int16
  SIGNAL speed_old_switch1_out1           : signed(15 DOWNTO 0);  -- int16
  SIGNAL Constant1_out1                   : signed(15 DOWNTO 0);  -- int16
  SIGNAL Resett_switch1_out1              : signed(15 DOWNTO 0);  -- int16
  SIGNAL Add1_out1                        : signed(15 DOWNTO 0);  -- int16
  SIGNAL Resett_switch2_out1              : signed(15 DOWNTO 0);  -- int16
  SIGNAL Resett_switch2_out1_1            : signed(15 DOWNTO 0);  -- int16
  SIGNAL Relational_Operator_relop1       : std_logic;
  SIGNAL Relational_Operator_out1         : std_logic;
  SIGNAL reset_old_switch1_out1           : signed(15 DOWNTO 0);  -- int16
  SIGNAL reset_old_switch1_out1_1         : signed(15 DOWNTO 0);  -- int16

BEGIN
  -- Set new counter value
  -- Check if count is to big in order to safe for value overflow
  -- Count
  -- omega by counting lines, can be used for high-speed, but is not recommended for small drives! 
  -- However, for using this approach, we need a quite long time window in order to get an accurate speed. 
  -- For small drives a long time window is not acceptable, since the mechanical time constant is small.
  -- e.g. using just 100us (since the speed control has this period at 10kHz) we can calculate as following:
  -- speed = 5034rpm, Increments = 5000, QuadratureFactor = 4, f_cc = 10000 kHz
  -- In the test, 169 lines are counted in 100us in the described example.
  -- -> 169*(10000/(4*5000))*60 = 5070rpm (so this is not accurate!) 
  -- However, a longer time window is not acceptabel for speed control with10kHz. More increments is not common, since 
  -- 5000 are already a lot

  Use_new_value <= Reset;

  rd_2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Use_new_value_1 <= '0';
      ELSIF enb = '1' THEN
        Use_new_value_1 <= Use_new_value;
      END IF;
    END IF;
  END PROCESS rd_2_process;


  Constant4_out1 <= to_signed(16#000A#, 16);

  IncsPerTurn_unsigned <= unsigned(IncsPerTurn);

  rd_0_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        IncsPerTurn_1 <= to_unsigned(16#0000#, 16);
      ELSIF enb = '1' THEN
        IncsPerTurn_1 <= IncsPerTurn_unsigned;
      END IF;
    END IF;
  END PROCESS rd_0_process;


  Reset_when_overflow_add_cast <= signed(resize(IncsPerTurn_1, 18));
  Reset_when_overflow_add_temp <= resize(Constant4_out1, 18) + Reset_when_overflow_add_cast;
  Reset_when_overflow_out1 <= Reset_when_overflow_add_temp(15 DOWNTO 0);

  rd_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Reset_when_overflow_out1_1 <= to_signed(16#0000#, 16);
      ELSIF enb = '1' THEN
        Reset_when_overflow_out1_1 <= Reset_when_overflow_out1;
      END IF;
    END IF;
  END PROCESS rd_1_process;


  Edge_signed <= signed(Edge_rsvd);

  Constant3_out1 <= to_signed(16#0000#, 16);

  Constant2_out1 <= to_signed(16#0001#, 16);

  rd_3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Constant2_out1_1 <= to_signed(16#0000#, 16);
      ELSIF enb = '1' THEN
        Constant2_out1_1 <= Constant2_out1;
      END IF;
    END IF;
  END PROCESS rd_3_process;


  
  speed_old_switch1_out1 <= Constant3_out1 WHEN Edge_signed = to_signed(16#00#, 8) ELSE
      Constant2_out1_1;

  Constant1_out1 <= to_signed(16#0000#, 16);

  Add1_out1 <= speed_old_switch1_out1 + Resett_switch1_out1;

  
  Resett_switch2_out1 <= Add1_out1 WHEN Use_new_value_1 = '0' ELSE
      Constant1_out1;

  rd_4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Resett_switch2_out1_1 <= to_signed(16#0000#, 16);
      ELSIF enb = '1' THEN
        Resett_switch2_out1_1 <= Resett_switch2_out1;
      END IF;
    END IF;
  END PROCESS rd_4_process;


  
  Relational_Operator_relop1 <= '1' WHEN Resett_switch1_out1 > Reset_when_overflow_out1_1 ELSE
      '0';

  rd_5_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Relational_Operator_out1 <= '0';
      ELSIF enb = '1' THEN
        Relational_Operator_out1 <= Relational_Operator_relop1;
      END IF;
    END IF;
  END PROCESS rd_5_process;


  
  Resett_switch1_out1 <= Resett_switch2_out1_1 WHEN Relational_Operator_out1 = '0' ELSE
      Constant1_out1;

  rd_6_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        reset_old_switch1_out1_1 <= to_signed(16#0000#, 16);
      ELSIF enb = '1' THEN
        reset_old_switch1_out1_1 <= reset_old_switch1_out1;
      END IF;
    END IF;
  END PROCESS rd_6_process;


  
  reset_old_switch1_out1 <= reset_old_switch1_out1_1 WHEN Use_new_value_1 = '0' ELSE
      Resett_switch1_out1;

  count <= std_logic_vector(reset_old_switch1_out1);

END rtl;

