SLStudio.Utils.RemoveHighlighting(get_param('gmStateSpaceHDL_HalfWaveRectifier_HDL', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL', 'handle'));
annotate_port('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Counter Limited', 0, 1, '');
annotate_port('gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/HDL Algorithm/Mode Iteration Manager/Counter Limited', 0, 1, '');
annotate_port('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Delay', 1, 1, '');
annotate_port('gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/HDL Algorithm/Mode Iteration Manager/Delay', 1, 1, '');
annotate_port('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Delay2', 1, 1, '');
annotate_port('gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/HDL Algorithm/Mode Iteration Manager/Delay2', 1, 1, '');
annotate_port('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Delay1', 1, 1, '');
annotate_port('gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/HDL Algorithm/Delay1', 1, 1, '');
annotate_port('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Rate Transition2', 1, 1, '');
annotate_port('gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Rate Transition2', 1, 1, '');
annotate_port('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Multiply Input', 1, 1, '');
annotate_port('gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/HDL Algorithm/State Update/Multiply Input', 1, 1, '');
annotate_port('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/compare_relop', 1, 1, '');
annotate_port('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Output Sum', 0, 1, '');
annotate_port('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Multiply Input1', 1, 1, '');
annotate_port('gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/HDL Algorithm/Output/Multiply Input', 1, 1, '');
annotate_port('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Multiply State', 1, 1, '');
annotate_port('gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/HDL Algorithm/Output/Multiply State', 1, 1, '');
annotate_port('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Subsystem2/Bitwise Operator1', 1, 1, '');
annotate_port('gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/HDL Algorithm/Mode Selection/State Mode Vector To Index/Subsystem1/Bitwise Operator1', 1, 1, '');
annotate_port('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Subsystem1/Bitwise Operator1', 1, 1, '');
annotate_port('gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/HDL Algorithm/Mode Selection/State Mode Vector To Index/Subsystem1/Bitwise Operator1', 1, 1, '');
