open_system('gmStateSpaceHDL_HalfWaveRectifier_HDL');
open_system('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Counter Limited', 'user2');
annotate_port('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Counter Limited', 0, 1, 'Obstacle to clock-rate pipelining');
hilite_system('gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/HDL Algorithm/Mode Iteration Manager/Counter Limited', 'user2');
annotate_port('gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/HDL Algorithm/Mode Iteration Manager/Counter Limited', 0, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Delay', 'user2');
annotate_port('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Delay', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/HDL Algorithm/Mode Iteration Manager/Delay', 'user2');
annotate_port('gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/HDL Algorithm/Mode Iteration Manager/Delay', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Delay2', 'user2');
annotate_port('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Delay2', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/HDL Algorithm/Mode Iteration Manager/Delay2', 'user2');
annotate_port('gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/HDL Algorithm/Mode Iteration Manager/Delay2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Delay1', 'user2');
annotate_port('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Delay1', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/HDL Algorithm/Delay1', 'user2');
annotate_port('gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/HDL Algorithm/Delay1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Rate Transition2', 'user2');
annotate_port('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Rate Transition2', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Rate Transition2', 'user2');
annotate_port('gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Rate Transition2', 1, 1, 'Obstacle to clock-rate pipelining');
