open_system('gmStateSpaceHDL_HalfWaveRectifier_HDL');
open_system('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Multiply Input', 'user2');
annotate_port('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Multiply Input', 1, 1, 'Block not characterized');
hilite_system('gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/HDL Algorithm/State Update/Multiply Input', 'user2');
annotate_port('gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/HDL Algorithm/State Update/Multiply Input', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/compare_relop', 'user2');
annotate_port('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/compare_relop', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Multiply Input1', 'user2');
annotate_port('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Multiply Input1', 1, 1, 'Block not characterized');
hilite_system('gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/HDL Algorithm/Output/Multiply Input', 'user2');
annotate_port('gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/HDL Algorithm/Output/Multiply Input', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Multiply State', 'user2');
annotate_port('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Multiply State', 1, 1, 'Block not characterized');
hilite_system('gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/HDL Algorithm/Output/Multiply State', 'user2');
annotate_port('gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/HDL Algorithm/Output/Multiply State', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Subsystem2/Bitwise Operator1', 'user2');
annotate_port('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Subsystem2/Bitwise Operator1', 1, 1, 'Block not characterized for this configuration');
hilite_system('gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/HDL Algorithm/Mode Selection/State Mode Vector To Index/Subsystem1/Bitwise Operator1', 'user2');
annotate_port('gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/HDL Algorithm/Mode Selection/State Mode Vector To Index/Subsystem1/Bitwise Operator1', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Subsystem1/Bitwise Operator1', 'user2');
annotate_port('gm_gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/Subsystem1/Bitwise Operator1', 1, 1, 'Block not characterized for this configuration');
hilite_system('gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/HDL Algorithm/Mode Selection/State Mode Vector To Index/Subsystem1/Bitwise Operator1', 'user2');
annotate_port('gmStateSpaceHDL_HalfWaveRectifier_HDL/Simscape_system/HDL Subsystem/HDL Algorithm/Mode Selection/State Mode Vector To Index/Subsystem1/Bitwise Operator1', 1, 1, 'Block not characterized for this configuration');
