SLStudio.Utils.RemoveHighlighting(get_param('AXI_testIP', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_AXI_testIP', 'handle'));
annotate_port('gm_AXI_testIP/AXI_testIP/Delay2', 0, 1, '');
annotate_port('gm_AXI_testIP/AXI_testIP/transpose', 1, 1, '');
annotate_port('gm_AXI_testIP/AXI_testIP/Product', 0, 1, '');
annotate_port('gm_AXI_testIP/AXI_testIP/Reshape', 1, 1, '');
annotate_port('AXI_testIP/AXI_testIP/Reshape', 1, 1, '');
annotate_port('gm_AXI_testIP/AXI_testIP/Reshape1', 1, 1, '');
annotate_port('AXI_testIP/AXI_testIP/Reshape1', 1, 1, '');
annotate_port('gm_AXI_testIP/AXI_testIP/Reshape2', 1, 1, '');
annotate_port('AXI_testIP/AXI_testIP/Reshape2', 1, 1, '');
annotate_port('gm_AXI_testIP/AXI_testIP/delayMatch', 1, 1, '');
