open_system('gm_AXI_testIP');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AXI_testIP/AXI_testIP/Delay2', 'user1');
annotate_port('gm_AXI_testIP/AXI_testIP/Delay2', 0, 1, 'cp : 0.298 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AXI_testIP/AXI_testIP/Product', 'user2');
annotate_port('gm_AXI_testIP/AXI_testIP/Product', 0, 1, 'cp : 9.213 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AXI_testIP/AXI_testIP/delayMatch', 'user1');
annotate_port('gm_AXI_testIP/AXI_testIP/delayMatch', 1, 1, 'cp : 9.243 ns');
