open_system('AXI_testIP');
open_system('gm_AXI_testIP');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AXI_testIP/AXI_testIP/transpose', 'user2');
annotate_port('gm_AXI_testIP/AXI_testIP/transpose', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AXI_testIP/AXI_testIP/Reshape', 'user2');
annotate_port('gm_AXI_testIP/AXI_testIP/Reshape', 1, 1, 'Block not characterized');
hilite_system('AXI_testIP/AXI_testIP/Reshape', 'user2');
annotate_port('AXI_testIP/AXI_testIP/Reshape', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AXI_testIP/AXI_testIP/Reshape1', 'user2');
annotate_port('gm_AXI_testIP/AXI_testIP/Reshape1', 1, 1, 'Block not characterized');
hilite_system('AXI_testIP/AXI_testIP/Reshape1', 'user2');
annotate_port('AXI_testIP/AXI_testIP/Reshape1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AXI_testIP/AXI_testIP/Reshape2', 'user2');
annotate_port('gm_AXI_testIP/AXI_testIP/Reshape2', 1, 1, 'Block not characterized');
hilite_system('AXI_testIP/AXI_testIP/Reshape2', 'user2');
annotate_port('AXI_testIP/AXI_testIP/Reshape2', 1, 1, 'Block not characterized');
