open_system('uz_plantModel_pt1');
open_system('gm_uz_plantModel_pt1');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_plantModel_pt1/uz_plantModel_pt1/Delay3', 'user2');
annotate_port('gm_uz_plantModel_pt1/uz_plantModel_pt1/Delay3', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('uz_plantModel_pt1/uz_plantModel_pt1/Delay3', 'user2');
annotate_port('uz_plantModel_pt1/uz_plantModel_pt1/Delay3', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_plantModel_pt1/uz_plantModel_pt1/Delay4', 'user2');
annotate_port('gm_uz_plantModel_pt1/uz_plantModel_pt1/Delay4', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('uz_plantModel_pt1/uz_plantModel_pt1/Delay4', 'user2');
annotate_port('uz_plantModel_pt1/uz_plantModel_pt1/Delay4', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_plantModel_pt1/uz_plantModel_pt1/Delay5', 'user2');
annotate_port('gm_uz_plantModel_pt1/uz_plantModel_pt1/Delay5', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('uz_plantModel_pt1/uz_plantModel_pt1/Delay5', 'user2');
annotate_port('uz_plantModel_pt1/uz_plantModel_pt1/Delay5', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_plantModel_pt1/uz_plantModel_pt1/Delay6', 'user2');
annotate_port('gm_uz_plantModel_pt1/uz_plantModel_pt1/Delay6', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('uz_plantModel_pt1/uz_plantModel_pt1/Delay6', 'user2');
annotate_port('uz_plantModel_pt1/uz_plantModel_pt1/Delay6', 1, 1, 'Obstacle to clock-rate pipelining');
