-- -------------------------------------------------------------
-- 
-- File Name: C:\ultrazohm_sw\ip_cores\Trans_123_dq_V12_ip\Simulation\hdlsrc\Transformation_V12\Trans_123_alphabeta_dq_V12_ip.vhd
-- Created: 2022-05-03 14:00:47
-- 
-- Generated by MATLAB 9.12 and HDL Coder 3.20
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: -1
-- Target subsystem base rate: -1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Trans_123_alphabeta_dq_V12_ip
-- Source Path: Trans_123_alphabeta_dq_V12_ip
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Trans_123_alphabeta_dq_V12_ip IS
  PORT( IPCORE_CLK                        :   IN    std_logic;  -- ufix1
        IPCORE_RESETN                     :   IN    std_logic;  -- ufix1
        i_ph1                             :   IN    std_logic_vector(17 DOWNTO 0);  -- ufix18
        i_ph2                             :   IN    std_logic_vector(17 DOWNTO 0);  -- ufix18
        i_ph3                             :   IN    std_logic_vector(17 DOWNTO 0);  -- ufix18
        theta                             :   IN    std_logic_vector(23 DOWNTO 0);  -- ufix24
        CurrentValid_in                   :   IN    std_logic;  -- ufix1
        AXI4_Lite_ACLK                    :   IN    std_logic;  -- ufix1
        AXI4_Lite_ARESETN                 :   IN    std_logic;  -- ufix1
        AXI4_Lite_AWADDR                  :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
        AXI4_Lite_AWVALID                 :   IN    std_logic;  -- ufix1
        AXI4_Lite_WDATA                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI4_Lite_WSTRB                   :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        AXI4_Lite_WVALID                  :   IN    std_logic;  -- ufix1
        AXI4_Lite_BREADY                  :   IN    std_logic;  -- ufix1
        AXI4_Lite_ARADDR                  :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
        AXI4_Lite_ARVALID                 :   IN    std_logic;  -- ufix1
        AXI4_Lite_RREADY                  :   IN    std_logic;  -- ufix1
        id                                :   OUT   std_logic_vector(17 DOWNTO 0);  -- ufix18
        iq                                :   OUT   std_logic_vector(17 DOWNTO 0);  -- ufix18
        dq_Done                           :   OUT   std_logic;  -- ufix1
        sin                               :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
        cos                               :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
        ialpha                            :   OUT   std_logic_vector(17 DOWNTO 0);  -- ufix18
        ibeta                             :   OUT   std_logic_vector(17 DOWNTO 0);  -- ufix18
        AXI4_Lite_AWREADY                 :   OUT   std_logic;  -- ufix1
        AXI4_Lite_WREADY                  :   OUT   std_logic;  -- ufix1
        AXI4_Lite_BRESP                   :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
        AXI4_Lite_BVALID                  :   OUT   std_logic;  -- ufix1
        AXI4_Lite_ARREADY                 :   OUT   std_logic;  -- ufix1
        AXI4_Lite_RDATA                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI4_Lite_RRESP                   :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
        AXI4_Lite_RVALID                  :   OUT   std_logic  -- ufix1
        );
END Trans_123_alphabeta_dq_V12_ip;


ARCHITECTURE rtl OF Trans_123_alphabeta_dq_V12_ip IS

  -- Component Declarations
  COMPONENT Trans_123_alphabeta_dq_V12_ip_reset_sync
    PORT( clk                             :   IN    std_logic;  -- ufix1
          reset_in                        :   IN    std_logic;  -- ufix1
          reset_out                       :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT Trans_123_alphabeta_dq_V12_ip_axi_lite
    PORT( reset                           :   IN    std_logic;
          AXI4_Lite_ACLK                  :   IN    std_logic;  -- ufix1
          AXI4_Lite_ARESETN               :   IN    std_logic;  -- ufix1
          AXI4_Lite_AWADDR                :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          AXI4_Lite_AWVALID               :   IN    std_logic;  -- ufix1
          AXI4_Lite_WDATA                 :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI4_Lite_WSTRB                 :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          AXI4_Lite_WVALID                :   IN    std_logic;  -- ufix1
          AXI4_Lite_BREADY                :   IN    std_logic;  -- ufix1
          AXI4_Lite_ARADDR                :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          AXI4_Lite_ARVALID               :   IN    std_logic;  -- ufix1
          AXI4_Lite_RREADY                :   IN    std_logic;  -- ufix1
          read_ip_timestamp               :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          read_id_AXI                     :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          read_iq_AXI                     :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          read_i1_AXI                     :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          read_i2_AXI                     :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          read_i3_AXI                     :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          read_ialpha_AXI                 :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          read_ibeta_AXI                  :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          AXI4_Lite_AWREADY               :   OUT   std_logic;  -- ufix1
          AXI4_Lite_WREADY                :   OUT   std_logic;  -- ufix1
          AXI4_Lite_BRESP                 :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
          AXI4_Lite_BVALID                :   OUT   std_logic;  -- ufix1
          AXI4_Lite_ARREADY               :   OUT   std_logic;  -- ufix1
          AXI4_Lite_RDATA                 :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI4_Lite_RRESP                 :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
          AXI4_Lite_RVALID                :   OUT   std_logic;  -- ufix1
          write_axi_enable                :   OUT   std_logic;  -- ufix1
          write_theta_offset_AXI          :   OUT   std_logic_vector(23 DOWNTO 0);  -- sfix24_En20
          reset_internal                  :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  COMPONENT Trans_123_alphabeta_dq_V12_ip_dut
    PORT( clk                             :   IN    std_logic;  -- ufix1
          reset                           :   IN    std_logic;
          dut_enable                      :   IN    std_logic;  -- ufix1
          i_ph1                           :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          i_ph2                           :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          i_ph3                           :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          theta                           :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En20
          theta_offset_AXI                :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En20
          CurrentValid_in                 :   IN    std_logic;  -- ufix1
          ce_out                          :   OUT   std_logic;  -- ufix1
          id                              :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          iq                              :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          id_AXI                          :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          iq_AXI                          :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          dq_Done                         :   OUT   std_logic;  -- ufix1
          sin                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          cos                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          i1_AXI                          :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          i2_AXI                          :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          i3_AXI                          :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          ialpha                          :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          ialpha_AXI                      :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          ibeta                           :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          ibeta_AXI                       :   OUT   std_logic_vector(17 DOWNTO 0)  -- sfix18_En11
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Trans_123_alphabeta_dq_V12_ip_reset_sync
    USE ENTITY work.Trans_123_alphabeta_dq_V12_ip_reset_sync(rtl);

  FOR ALL : Trans_123_alphabeta_dq_V12_ip_axi_lite
    USE ENTITY work.Trans_123_alphabeta_dq_V12_ip_axi_lite(rtl);

  FOR ALL : Trans_123_alphabeta_dq_V12_ip_dut
    USE ENTITY work.Trans_123_alphabeta_dq_V12_ip_dut(rtl);

  -- Signals
  SIGNAL reset                            : std_logic;
  SIGNAL ip_timestamp                     : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL reset_cm                         : std_logic;  -- ufix1
  SIGNAL i_ph1_unsigned                   : unsigned(17 DOWNTO 0);  -- ufix18
  SIGNAL i_ph1_sig                        : signed(17 DOWNTO 0);  -- sfix18_En11
  SIGNAL i_ph2_unsigned                   : unsigned(17 DOWNTO 0);  -- ufix18
  SIGNAL i_ph2_sig                        : signed(17 DOWNTO 0);  -- sfix18_En11
  SIGNAL i_ph3_unsigned                   : unsigned(17 DOWNTO 0);  -- ufix18
  SIGNAL i_ph3_sig                        : signed(17 DOWNTO 0);  -- sfix18_En11
  SIGNAL theta_unsigned                   : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL theta_sig                        : signed(23 DOWNTO 0);  -- sfix24_En20
  SIGNAL reset_internal                   : std_logic;  -- ufix1
  SIGNAL reset_before_sync                : std_logic;  -- ufix1
  SIGNAL id_AXI_sig                       : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL iq_AXI_sig                       : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL i1_AXI_sig                       : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL i2_AXI_sig                       : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL i3_AXI_sig                       : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL ialpha_AXI_sig                   : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL ibeta_AXI_sig                    : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL AXI4_Lite_BRESP_tmp              : std_logic_vector(1 DOWNTO 0);  -- ufix2
  SIGNAL AXI4_Lite_RDATA_tmp              : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL AXI4_Lite_RRESP_tmp              : std_logic_vector(1 DOWNTO 0);  -- ufix2
  SIGNAL write_axi_enable                 : std_logic;  -- ufix1
  SIGNAL write_theta_offset_AXI           : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL id_sig                           : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL iq_sig                           : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL dq_Done_sig                      : std_logic;  -- ufix1
  SIGNAL sin_sig                          : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL cos_sig                          : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL ialpha_sig                       : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL ibeta_sig                        : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL id_sig_signed                    : signed(17 DOWNTO 0);  -- sfix18_En11
  SIGNAL id_tmp                           : unsigned(17 DOWNTO 0);  -- ufix18
  SIGNAL iq_sig_signed                    : signed(17 DOWNTO 0);  -- sfix18_En11
  SIGNAL iq_tmp                           : unsigned(17 DOWNTO 0);  -- ufix18
  SIGNAL sin_sig_signed                   : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL sin_tmp                          : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL cos_sig_signed                   : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL cos_tmp                          : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL ialpha_sig_signed                : signed(17 DOWNTO 0);  -- sfix18_En11
  SIGNAL ialpha_tmp                       : unsigned(17 DOWNTO 0);  -- ufix18
  SIGNAL ibeta_sig_signed                 : signed(17 DOWNTO 0);  -- sfix18_En11
  SIGNAL ibeta_tmp                        : unsigned(17 DOWNTO 0);  -- ufix18

BEGIN
  u_Trans_123_alphabeta_dq_V12_ip_reset_sync_inst : Trans_123_alphabeta_dq_V12_ip_reset_sync
    PORT MAP( clk => IPCORE_CLK,  -- ufix1
              reset_in => reset_before_sync,  -- ufix1
              reset_out => reset
              );

  u_Trans_123_alphabeta_dq_V12_ip_axi_lite_inst : Trans_123_alphabeta_dq_V12_ip_axi_lite
    PORT MAP( reset => reset,
              AXI4_Lite_ACLK => AXI4_Lite_ACLK,  -- ufix1
              AXI4_Lite_ARESETN => AXI4_Lite_ARESETN,  -- ufix1
              AXI4_Lite_AWADDR => AXI4_Lite_AWADDR,  -- ufix16
              AXI4_Lite_AWVALID => AXI4_Lite_AWVALID,  -- ufix1
              AXI4_Lite_WDATA => AXI4_Lite_WDATA,  -- ufix32
              AXI4_Lite_WSTRB => AXI4_Lite_WSTRB,  -- ufix4
              AXI4_Lite_WVALID => AXI4_Lite_WVALID,  -- ufix1
              AXI4_Lite_BREADY => AXI4_Lite_BREADY,  -- ufix1
              AXI4_Lite_ARADDR => AXI4_Lite_ARADDR,  -- ufix16
              AXI4_Lite_ARVALID => AXI4_Lite_ARVALID,  -- ufix1
              AXI4_Lite_RREADY => AXI4_Lite_RREADY,  -- ufix1
              read_ip_timestamp => std_logic_vector(ip_timestamp),  -- ufix32
              read_id_AXI => id_AXI_sig,  -- sfix18_En11
              read_iq_AXI => iq_AXI_sig,  -- sfix18_En11
              read_i1_AXI => i1_AXI_sig,  -- sfix18_En11
              read_i2_AXI => i2_AXI_sig,  -- sfix18_En11
              read_i3_AXI => i3_AXI_sig,  -- sfix18_En11
              read_ialpha_AXI => ialpha_AXI_sig,  -- sfix18_En11
              read_ibeta_AXI => ibeta_AXI_sig,  -- sfix18_En11
              AXI4_Lite_AWREADY => AXI4_Lite_AWREADY,  -- ufix1
              AXI4_Lite_WREADY => AXI4_Lite_WREADY,  -- ufix1
              AXI4_Lite_BRESP => AXI4_Lite_BRESP_tmp,  -- ufix2
              AXI4_Lite_BVALID => AXI4_Lite_BVALID,  -- ufix1
              AXI4_Lite_ARREADY => AXI4_Lite_ARREADY,  -- ufix1
              AXI4_Lite_RDATA => AXI4_Lite_RDATA_tmp,  -- ufix32
              AXI4_Lite_RRESP => AXI4_Lite_RRESP_tmp,  -- ufix2
              AXI4_Lite_RVALID => AXI4_Lite_RVALID,  -- ufix1
              write_axi_enable => write_axi_enable,  -- ufix1
              write_theta_offset_AXI => write_theta_offset_AXI,  -- sfix24_En20
              reset_internal => reset_internal  -- ufix1
              );

  u_Trans_123_alphabeta_dq_V12_ip_dut_inst : Trans_123_alphabeta_dq_V12_ip_dut
    PORT MAP( clk => IPCORE_CLK,  -- ufix1
              reset => reset,
              dut_enable => write_axi_enable,  -- ufix1
              i_ph1 => std_logic_vector(i_ph1_sig),  -- sfix18_En11
              i_ph2 => std_logic_vector(i_ph2_sig),  -- sfix18_En11
              i_ph3 => std_logic_vector(i_ph3_sig),  -- sfix18_En11
              theta => std_logic_vector(theta_sig),  -- sfix24_En20
              theta_offset_AXI => write_theta_offset_AXI,  -- sfix24_En20
              CurrentValid_in => CurrentValid_in,  -- ufix1
              ce_out => ce_out_sig,  -- ufix1
              id => id_sig,  -- sfix18_En11
              iq => iq_sig,  -- sfix18_En11
              id_AXI => id_AXI_sig,  -- sfix18_En11
              iq_AXI => iq_AXI_sig,  -- sfix18_En11
              dq_Done => dq_Done_sig,  -- ufix1
              sin => sin_sig,  -- sfix16_En14
              cos => cos_sig,  -- sfix16_En14
              i1_AXI => i1_AXI_sig,  -- sfix18_En11
              i2_AXI => i2_AXI_sig,  -- sfix18_En11
              i3_AXI => i3_AXI_sig,  -- sfix18_En11
              ialpha => ialpha_sig,  -- sfix18_En11
              ialpha_AXI => ialpha_AXI_sig,  -- sfix18_En11
              ibeta => ibeta_sig,  -- sfix18_En11
              ibeta_AXI => ibeta_AXI_sig  -- sfix18_En11
              );

  ip_timestamp <= unsigned'(X"836E1BE8");

  reset_cm <=  NOT IPCORE_RESETN;

  i_ph1_unsigned <= unsigned(i_ph1);

  i_ph1_sig <= signed(i_ph1_unsigned);

  i_ph2_unsigned <= unsigned(i_ph2);

  i_ph2_sig <= signed(i_ph2_unsigned);

  i_ph3_unsigned <= unsigned(i_ph3);

  i_ph3_sig <= signed(i_ph3_unsigned);

  theta_unsigned <= unsigned(theta);

  theta_sig <= signed(theta_unsigned);

  reset_before_sync <= reset_cm OR reset_internal;

  id_sig_signed <= signed(id_sig);

  id_tmp <= unsigned(id_sig_signed);

  id <= std_logic_vector(id_tmp);

  iq_sig_signed <= signed(iq_sig);

  iq_tmp <= unsigned(iq_sig_signed);

  iq <= std_logic_vector(iq_tmp);

  sin_sig_signed <= signed(sin_sig);

  sin_tmp <= unsigned(sin_sig_signed);

  sin <= std_logic_vector(sin_tmp);

  cos_sig_signed <= signed(cos_sig);

  cos_tmp <= unsigned(cos_sig_signed);

  cos <= std_logic_vector(cos_tmp);

  ialpha_sig_signed <= signed(ialpha_sig);

  ialpha_tmp <= unsigned(ialpha_sig_signed);

  ialpha <= std_logic_vector(ialpha_tmp);

  ibeta_sig_signed <= signed(ibeta_sig);

  ibeta_tmp <= unsigned(ibeta_sig_signed);

  ibeta <= std_logic_vector(ibeta_tmp);

  dq_Done <= dq_Done_sig;

  AXI4_Lite_BRESP <= AXI4_Lite_BRESP_tmp;

  AXI4_Lite_RDATA <= AXI4_Lite_RDATA_tmp;

  AXI4_Lite_RRESP <= AXI4_Lite_RRESP_tmp;

END rtl;

