SLStudio.Utils.RemoveHighlighting(get_param('uz_pmsm_model', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_uz_pmsm_model', 'handle'));
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion16', 1, 1, '');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion16', 1, 1, '');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion12', 1, 1, '');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion12', 1, 1, '');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion17', 1, 1, '');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion17', 1, 1, '');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion4', 1, 1, '');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion4', 1, 1, '');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion14', 1, 1, '');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion14', 1, 1, '');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion5', 1, 1, '');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion5', 1, 1, '');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Product11', 0, 1, '');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion13', 1, 1, '');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion13', 1, 1, '');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion11', 1, 1, '');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion11', 1, 1, '');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion2', 1, 1, '');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion2', 1, 1, '');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion15', 1, 1, '');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion15', 1, 1, '');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion8', 1, 1, '');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion8', 1, 1, '');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion6', 1, 1, '');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion6', 1, 1, '');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion7', 1, 1, '');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion7', 1, 1, '');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion9', 1, 1, '');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion9', 1, 1, '');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion3', 1, 1, '');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion3', 1, 1, '');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion10', 1, 1, '');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion10', 1, 1, '');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/delayMatch', 1, 1, '');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/delayMatch1', 1, 1, '');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/delayMatch2', 1, 1, '');
