open_system('uz_pmsm_model');
open_system('gm_uz_pmsm_model');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/out_2_pipe_in_pipe', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/out_2_pipe_in_pipe', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/out_3_pipe_in_pipe', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/out_3_pipe_in_pipe', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/out_0_pipe_in_pipe', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/out_0_pipe_in_pipe', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/out_1_pipe_in_pipe', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/out_1_pipe_in_pipe', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/delayMatch', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/delayMatch', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/delayMatch1', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/delayMatch1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/delayMatch2', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/delayMatch2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/delayMatch3', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/delayMatch3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/delayMatch4', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/delayMatch4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/delayMatch5', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/delayMatch5', 1, 1, 'Block not characterized');
