open_system('uz_pmsm_model');
open_system('gm_uz_pmsm_model');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion15', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion15', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model/uz_pmsm_model/Data Type Conversion15', 'user2');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion15', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion6', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion6', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model/uz_pmsm_model/Data Type Conversion6', 'user2');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion6', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion8', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion8', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model/uz_pmsm_model/Data Type Conversion8', 'user2');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion8', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion9', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion9', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model/uz_pmsm_model/Data Type Conversion9', 'user2');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion9', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion3', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion3', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model/uz_pmsm_model/Data Type Conversion3', 'user2');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion3', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion17', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion17', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model/uz_pmsm_model/Data Type Conversion17', 'user2');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion17', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion12', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion12', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model/uz_pmsm_model/Data Type Conversion12', 'user2');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion12', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion13', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion13', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model/uz_pmsm_model/Data Type Conversion13', 'user2');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion13', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion14', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion14', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model/uz_pmsm_model/Data Type Conversion14', 'user2');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion14', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion5', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion5', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model/uz_pmsm_model/Data Type Conversion5', 'user2');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion5', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion4', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion4', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model/uz_pmsm_model/Data Type Conversion4', 'user2');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion4', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion2', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion2', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model/uz_pmsm_model/Data Type Conversion2', 'user2');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion2', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion7', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion7', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model/uz_pmsm_model/Data Type Conversion7', 'user2');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion7', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion11', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion11', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model/uz_pmsm_model/Data Type Conversion11', 'user2');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion11', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion16', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion16', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model/uz_pmsm_model/Data Type Conversion16', 'user2');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion16', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion10', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion10', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model/uz_pmsm_model/Data Type Conversion10', 'user2');
annotate_port('uz_pmsm_model/uz_pmsm_model/Data Type Conversion10', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/delayMatch', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/delayMatch', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/delayMatch1', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/delayMatch1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/delayMatch2', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/delayMatch2', 1, 1, 'Block not characterized');
