open_system('uz_pmsm_model');
open_system('gm_uz_pmsm_model');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion9', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion9', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model/uz_pmsm_model/pmsm/Data Type Conversion9', 'user2');
annotate_port('uz_pmsm_model/uz_pmsm_model/pmsm/Data Type Conversion9', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion1', 'user2');
annotate_port('gm_uz_pmsm_model/uz_pmsm_model/Data Type Conversion1', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model/uz_pmsm_model/pmsm/Data Type Conversion1', 'user2');
annotate_port('uz_pmsm_model/uz_pmsm_model/pmsm/Data Type Conversion1', 1, 1, 'Block not characterized for this configuration');
