SLStudio.Utils.RemoveHighlighting(get_param('uz_sixphase_VSD_transformation', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_uz_sixphase_VSD_transformation', 'handle'));
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/Unit Delay', 1, 1, '');
annotate_port('uz_sixphase_VSD_transformation/abc_to_dq/Unit Delay', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/Sine HDL Optimized', 0, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/t7', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/t8', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/vectorized_in0', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/Row2Col_in0', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/Row2Col_in1', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/reshape_dotProduct', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/reshape_mmulResult', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/t9', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/vectorized_in01', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/Row2Col_in01', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/Row2Col_in11', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/reshape_dotProduct1', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/reshape_mmulResult1', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/t10', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/vectorized_in02', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/Row2Col_in02', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/Row2Col_in12', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/reshape_dotProduct2', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/reshape_mmulResult2', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/t11', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/vectorized_in03', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/Row2Col_in03', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/Row2Col_in13', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/reshape_dotProduct3', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/reshape_mmulResult3', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/t12', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/t13', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/t17', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/Sine HDL Optimized/Point501', 0, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/Sine HDL Optimized/Look-Up Table', 0, 1, '');
annotate_port('uz_sixphase_VSD_transformation/abc_to_dq/Sine HDL Optimized/sincos hdl/cos_hdl/Look-Up Table', 0, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/Sine HDL Optimized/CastU16En21', 0, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/Sine HDL Optimized/CastU16En31', 0, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/Sine HDL Optimized/CastU16En4', 0, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/Sine HDL Optimized/LTEp251', 0, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/Sine HDL Optimized/LTEp501', 0, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/Sine HDL Optimized/Look-Up Table1', 0, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/Sine HDL Optimized/Look-Up Table1', 0, 1, '');
annotate_port('uz_sixphase_VSD_transformation/abc_to_dq/Sine HDL Optimized/sincos hdl/sin_hdl/Look-Up Table', 0, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/Sine HDL Optimized/QuadHandle1', 0, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/Sine HDL Optimized/QuadHandle21', 0, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/Sine HDL Optimized/Saturation1', 0, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/Sine HDL Optimized/Switch1', 0, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/Sine HDL Optimized/PipelineRegister1', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/crp_temp_MAC/t', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/crp_temp_MAC1/t', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/crp_temp_MAC2/t', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/crp_temp_MAC3/t', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/crp_temp_MAC4/t', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/crp_temp_MAC5/t', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd1/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd2/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd3/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd4/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd5/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd6/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd7/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd8/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd9/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd10/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd11/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd12/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd13/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd14/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd15/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd16/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd17/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd18/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd19/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd20/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd21/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd22/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd23/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd24/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd25/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd26/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd27/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd28/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd29/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd30/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd31/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd32/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd33/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd34/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_sixphase_VSD_transformation/abc_to_dq/_adder_MultiplyAdd35/_adder_MultiplyAdd', 1, 1, '');
