SLStudio.Utils.RemoveHighlighting(get_param('uz_JL_SDDemodulator', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_uz_JL_SDDemodulator', 'handle'));
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/CLk', 0, 1, '');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem', 0, 1, '');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Delay11', 1, 1, '');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/CLk/HDL Counter2', 0, 1, '');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/CLk/Relational Operator', 0, 1, '');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem/trigger_sec_edge', 0, 2, '');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem/Logical Operator', 0, 1, '');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem/Switch1', 0, 1, '');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem/trigger_sec_edge/Add', 0, 1, '');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem/trigger_sec_edge/Logical Operator1', 0, 1, '');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem/trigger_sec_edge/Logical Operator2', 0, 1, '');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem/trigger_sec_edge/NOT', 0, 1, '');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem/trigger_sec_edge/Relational Operator1', 0, 1, '');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem/trigger_sec_edge/Switch', 0, 1, '');
