open_system('gm_uz_JL_SDDemodulator');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem5', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem5', 0, 1, 'cp : 3.872 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Unit Delay8', 'user1');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Unit Delay8', 1, 1, 'cp : 4.485 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/HDL Counter', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/HDL Counter', 0, 1, 'cp : 0.33 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Relational Operator', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Relational Operator', 0, 1, 'cp : 1.017 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Switch4', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Switch4', 0, 1, 'cp : 4.224 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem5/Add', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem5/Add', 0, 1, 'cp : 2.116 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem5/Logical Operator', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem5/Logical Operator', 0, 1, 'cp : 3.872 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem5/Relational Operator', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem5/Relational Operator', 0, 1, 'cp : 2.984 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem5/Switch', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem5/Switch', 0, 1, 'cp : 1.369 ns');
