open_system('gm_uz_JL_SDDemodulator');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/CLk', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/CLk', 0, 1, 'cp : 1.532 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Sinc3_Filter_U', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Sinc3_Filter_U', 1, 2, 'cp : 9.386 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem', 0, 1, 'cp : 5.949 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/gen_slow_clk_U', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/gen_slow_clk_U', 0, 1, 'cp : 8.804 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/CLk/HDL Counter', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/CLk/HDL Counter', 0, 1, 'cp : 0.682 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/CLk/Relational Operator', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/CLk/Relational Operator', 0, 1, 'cp : 1.532 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Sinc3_Filter_U/Delay One Step', 'user1');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Sinc3_Filter_U/Delay One Step', 1, 2, 'cp : 9.386 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem/trigger_sec_edge', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem/trigger_sec_edge', 0, 2, 'cp : 5.665 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem/Switch2', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem/Switch2', 0, 1, 'cp : 5.949 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem/trigger_sec_edge/Add', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem/trigger_sec_edge/Add', 0, 1, 'cp : 3.803 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem/trigger_sec_edge/Logical Operator1', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem/trigger_sec_edge/Logical Operator1', 0, 1, 'cp : 2.704 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem/trigger_sec_edge/Logical Operator2', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem/trigger_sec_edge/Logical Operator2', 0, 1, 'cp : 5.665 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem/trigger_sec_edge/NOT', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem/trigger_sec_edge/NOT', 0, 1, 'cp : 1.816 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem/trigger_sec_edge/Relational Operator1', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem/trigger_sec_edge/Relational Operator1', 0, 1, 'cp : 4.805 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem/trigger_sec_edge/Switch', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem/trigger_sec_edge/Switch', 0, 1, 'cp : 3.056 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/gen_slow_clk_U/Add', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/gen_slow_clk_U/Add', 0, 1, 'cp : 7.048 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/gen_slow_clk_U/Logical Operator', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/gen_slow_clk_U/Logical Operator', 0, 1, 'cp : 8.804 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/gen_slow_clk_U/Relational Operator', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/gen_slow_clk_U/Relational Operator', 0, 1, 'cp : 7.916 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/gen_slow_clk_U/Switch', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/gen_slow_clk_U/Switch', 0, 1, 'cp : 6.301 ns');
