open_system('gm_uz_JL_SDDemodulator');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem1', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem1', 0, 1, 'cp : 5.949 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem5', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem5', 0, 1, 'cp : 8.804 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Delay One Step', 'user1');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Delay One Step', 1, 2, 'cp : 9.386 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/HDL Counter', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/HDL Counter', 0, 1, 'cp : 0.682 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Relational Operator', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Relational Operator', 0, 1, 'cp : 1.532 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Switch1', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Switch1', 0, 1, 'cp : 1.922 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem1/Add', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem1/Add', 0, 1, 'cp : 4.193 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem1/Logical Operator', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem1/Logical Operator', 0, 1, 'cp : 5.949 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem1/Logical Operator1', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem1/Logical Operator1', 0, 1, 'cp : 3.094 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem1/NOT', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem1/NOT', 0, 1, 'cp : 2.206 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem1/Relational Operator', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem1/Relational Operator', 0, 1, 'cp : 5.061 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem1/Switch', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem1/Switch', 0, 1, 'cp : 3.446 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem5/Add', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem5/Add', 0, 1, 'cp : 7.048 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem5/Logical Operator', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem5/Logical Operator', 0, 1, 'cp : 8.804 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem5/Relational Operator', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem5/Relational Operator', 0, 1, 'cp : 7.916 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem5/Switch', 'user2');
annotate_port('gm_uz_JL_SDDemodulator/uz_JL_SDDemodulator/Subsystem5/Switch', 0, 1, 'cp : 6.301 ns');
