vlib work
vcom  uz_JL_SDDemod_src_Differentierer.vhd
vcom  uz_JL_SDDemod_src_Integratoren.vhd
vcom  uz_JL_SDDemod_src_Subsystem1.vhd
vcom  uz_JL_SDDemod_src_Subsystem5.vhd
vcom  uz_JL_SDDemod_src_uz_JL_SDDemodulator.vhd
