SLStudio.Utils.RemoveHighlighting(get_param('uz_pu_conversion', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_uz_pu_conversion', 'handle'));
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Detect Rise Positive', 0, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Detect Rise Positive', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Detect Rise Positive', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay1', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay1', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay10', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay10', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay11', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay11', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay12', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay12', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay13', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay13', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay14', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay14', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay15', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay15', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay16', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay16', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay17', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay17', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay18', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay18', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay19', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay19', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay2', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay2', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay20', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay20', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay21', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay21', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay22', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay22', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay23', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay23', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay24', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay24', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay25', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay25', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay26', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay26', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay27', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay27', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay28', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay28', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay29', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay29', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay3', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay3', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay30', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay30', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay31', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay31', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay32', 0, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay32', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay32', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay4', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay4', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay5', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay5', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay6', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay6', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay7', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay7', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay8', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay8', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay9', 1, 1, '');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay9', 1, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Product', 0, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Switch', 0, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Detect Rise Positive/FixPt Relational Operator', 0, 1, '');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Detect Rise Positive/Positive', 0, 1, '');
