open_system('gm_uz_pu_conversion');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Product', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Product', 0, 1, 'cp : 6.23 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/ctr_0_31', 'user1');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/ctr_0_31', 0, 1, 'cp : 0.358 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Serializer_Subnetwork1', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Serializer_Subnetwork1', 0, 1, 'cp : 1.354 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Product0_deserializer', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Product0_deserializer', 1, 1, 'cp : 6.23 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Serializer_Subnetwork1/splitcomp_multiport', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Serializer_Subnetwork1/splitcomp_multiport', 0, 1, 'cp : 1.354 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Product0_deserializer/Product0_deserializer', 'user1');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Product0_deserializer/Product0_deserializer', 1, 1, 'cp : 6.23 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Product0_deserializer/Product0_deserializer_in_buff', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Product0_deserializer/Product0_deserializer_in_buff', 0, 1, 'cp : 6.23 ns');
