open_system('uz_pu_conversion');
open_system('gm_uz_pu_conversion');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Detect Rise Positive', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Detect Rise Positive', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Detect Rise Positive', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Detect Rise Positive', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay1', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay1', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay1', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay10', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay10', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay10', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay10', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay100', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay100', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay100', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay100', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay101', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay101', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay101', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay101', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay102', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay102', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay102', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay102', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay103', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay103', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay103', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay103', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay104', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay104', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay104', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay104', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay105', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay105', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay105', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay105', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay106', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay106', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay106', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay106', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay107', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay107', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay107', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay107', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay108', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay108', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay108', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay108', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay109', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay109', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay109', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay109', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay11', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay11', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay11', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay11', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay110', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay110', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay110', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay110', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay111', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay111', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay111', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay111', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay112', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay112', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay112', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay112', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay113', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay113', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay113', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay113', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay114', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay114', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay114', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay114', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay115', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay115', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay115', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay115', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay116', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay116', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay116', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay116', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay117', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay117', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay117', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay117', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay118', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay118', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay118', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay118', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay119', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay119', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay119', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay119', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay12', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay12', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay12', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay12', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay120', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay120', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay120', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay120', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay121', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay121', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay121', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay121', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay122', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay122', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay122', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay122', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay123', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay123', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay123', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay123', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay124', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay124', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay124', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay124', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay125', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay125', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay125', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay125', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay126', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay126', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay126', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay126', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay127', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay127', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay127', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay127', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay128', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay128', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay128', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay128', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay129', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay129', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay129', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay129', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay13', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay13', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay13', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay13', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay14', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay14', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay14', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay14', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay15', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay15', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay15', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay15', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay16', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay16', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay16', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay16', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay17', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay17', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay17', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay17', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay18', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay18', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay18', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay18', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay19', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay19', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay19', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay19', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay2', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay2', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay2', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay20', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay20', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay20', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay20', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay21', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay21', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay21', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay21', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay22', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay22', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay22', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay22', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay23', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay23', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay23', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay23', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay24', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay24', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay24', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay24', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay25', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay25', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay25', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay25', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay26', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay26', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay26', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay26', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay27', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay27', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay27', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay27', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay28', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay28', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay28', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay28', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay29', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay29', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay29', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay29', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay3', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay3', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay3', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay30', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay30', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay30', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay30', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay31', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay31', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay31', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay31', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay32', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay32', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay32', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay32', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay33', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay33', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay33', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay33', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay34', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay34', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay34', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay34', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay35', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay35', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay35', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay35', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay36', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay36', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay36', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay36', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay37', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay37', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay37', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay37', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay38', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay38', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay38', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay38', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay39', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay39', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay39', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay39', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay4', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay4', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay4', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay40', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay40', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay40', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay40', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay41', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay41', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay41', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay41', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay42', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay42', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay42', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay42', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay43', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay43', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay43', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay43', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay44', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay44', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay44', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay44', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay45', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay45', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay45', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay45', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay46', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay46', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay46', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay46', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay47', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay47', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay47', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay47', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay48', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay48', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay48', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay48', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay49', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay49', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay49', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay49', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay5', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay5', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay5', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay50', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay50', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay50', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay50', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay51', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay51', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay51', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay51', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay52', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay52', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay52', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay52', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay53', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay53', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay53', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay53', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay54', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay54', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay54', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay54', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay55', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay55', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay55', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay55', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay56', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay56', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay56', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay56', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay57', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay57', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay57', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay57', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay58', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay58', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay58', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay58', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay59', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay59', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay59', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay59', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay6', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay6', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay6', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay6', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay60', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay60', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay60', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay60', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay61', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay61', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay61', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay61', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay62', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay62', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay62', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay62', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay63', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay63', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay63', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay63', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay64', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay64', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay64', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay64', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay65', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay65', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay65', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay65', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay66', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay66', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay66', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay66', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay67', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay67', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay67', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay67', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay68', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay68', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay68', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay68', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay69', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay69', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay69', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay69', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay7', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay7', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay7', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay7', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay70', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay70', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay70', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay70', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay71', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay71', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay71', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay71', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay72', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay72', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay72', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay72', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay73', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay73', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay73', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay73', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay74', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay74', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay74', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay74', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay75', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay75', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay75', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay75', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay76', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay76', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay76', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay76', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay77', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay77', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay77', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay77', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay78', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay78', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay78', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay78', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay79', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay79', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay79', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay79', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay8', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay8', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay8', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay8', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay80', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay80', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay80', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay80', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay81', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay81', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay81', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay81', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay82', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay82', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay82', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay82', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay83', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay83', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay83', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay83', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay84', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay84', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay84', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay84', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay85', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay85', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay85', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay85', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay86', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay86', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay86', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay86', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay87', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay87', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay87', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay87', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay88', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay88', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay88', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay88', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay89', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay89', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay89', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay89', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay9', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay9', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay9', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay9', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay90', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay90', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay90', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay90', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay91', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay91', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay91', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay91', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay92', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay92', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay92', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay92', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay93', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay93', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay93', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay93', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay94', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay94', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay94', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay94', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay95', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay95', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay95', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay95', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay96', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay96', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay96', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay96', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay97', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay97', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay97', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay97', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay98', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay98', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay98', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay98', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Delay99', 'user2');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Delay99', 1, 1, 'Block not characterized');
hilite_system('uz_pu_conversion/uz_pu_conversion/Delay99', 'user2');
annotate_port('uz_pu_conversion/uz_pu_conversion/Delay99', 1, 1, 'Block not characterized');
