open_system('gm_uz_pu_conversion');
open_system('uz_pu_conversion');
clearhighlighting;
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pu_conversion/uz_pu_conversion/Product', 'user1');
annotate_port('gm_uz_pu_conversion/uz_pu_conversion/Product', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product1', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product1', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product2', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product2', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product3', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product3', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product4', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product4', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product5', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product5', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product6', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product6', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product7', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product7', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product8', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product8', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product9', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product9', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product10', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product10', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product11', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product11', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product12', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product12', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product13', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product13', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product14', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product14', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product15', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product15', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product16', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product16', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product17', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product17', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product24', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product24', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product25', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product25', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product26', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product26', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product27', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product27', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product28', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product28', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product29', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product29', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product30', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product30', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product31', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product31', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product18', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product18', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product19', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product19', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product20', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product20', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product21', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product21', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product22', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product22', 0, 1, 'Sharing Group 1');
hilite_system('uz_pu_conversion/uz_pu_conversion/Product23', 'user1');
annotate_port('uz_pu_conversion/uz_pu_conversion/Product23', 0, 1, 'Sharing Group 1');
