SLStudio.Utils.RemoveHighlighting(get_param('uz_interlockDeadtime2L', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_uz_interlockDeadtime2L', 'handle'));
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/DeadtimeModule_instance1', 0, 1, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/t6', 0, 1, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/t7', 0, 1, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/EnableOutputModule_instance1', 0, 1, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/t8', 0, 1, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/t14', 0, 1, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/t15', 0, 1, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/InterlockModule_instance1', 0, 1, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/t16', 0, 1, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/t19', 0, 1, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/t20', 0, 1, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/InverseBotSwitchModule_instance1', 0, 1, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/t21', 0, 1, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/t24', 0, 1, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/t25', 0, 1, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/t26', 0, 1, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/DeadtimeModule_instance1/Detect Fall Nonpositive2', 1, 1, '');
annotate_port('uz_interlockDeadtime2L/uz_interlockDeadtime2L/DeadtimeModule/Detect Fall Nonpositive2', 1, 1, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/DeadtimeModule_instance1/HDL Counter', 0, 1, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/DeadtimeModule_instance1/Switch', 0, 1, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/DeadtimeModule_instance1/Relational Operator', 0, 1, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/DeadtimeModule_instance1/Logical Operator10', 0, 1, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/EnableOutputModule_instance1/AND', 0, 1, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/InterlockModule_instance1/mux', 0, 1, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/InterlockModule_instance1/Logical Operator3', 0, 1, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/InterlockModule_instance1/Logical Operator2', 0, 1, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/InterlockModule_instance1/t', 0, 2, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/InterlockModule_instance1/In1_1_wire', 0, 1, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/InverseBotSwitchModule_instance1/NOT', 0, 1, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/InverseBotSwitchModule_instance1/mux', 0, 1, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/InverseBotSwitchModule_instance1/Index Vector', 0, 1, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/InverseBotSwitchModule_instance1/t', 0, 2, '');
annotate_port('gm_uz_interlockDeadtime2L/uz_interlockDeadtime2L/InverseBotSwitchModule_instance1/gate_delay_out_1_wire', 0, 1, '');
