vlib work
vcom  uz_interlockDeadtime2L_src_InverseBotSwitchModule.vhd
vcom  uz_interlockDeadtime2L_src_InterlockModule.vhd
vcom  uz_interlockDeadtime2L_src_Detect_Fall_Nonpositive2.vhd
vcom  uz_interlockDeadtime2L_src_DeadtimeModule.vhd
vcom  uz_interlockDeadtime2L_src_EnableOutputModule.vhd
vcom  uz_interlockDeadtime2L_src_uz_interlockDeadtime2L.vhd
