SLStudio.Utils.RemoveHighlighting(get_param('uz_inverter_3phgm', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_uz_inverter_3phgm', 'handle'));
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Delay', 1, 1, '');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/HDL Algorithm/Mode Iteration Manager/Delay', 1, 1, '');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Delay2', 1, 1, '');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/HDL Algorithm/Mode Iteration Manager/Delay2', 1, 1, '');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition10', 1, 1, '');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition10', 1, 1, '');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition11', 1, 1, '');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition11', 1, 1, '');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition12', 1, 1, '');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition12', 1, 1, '');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition13', 1, 1, '');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition13', 1, 1, '');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition14', 1, 1, '');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition14', 1, 1, '');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition15', 1, 1, '');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition15', 1, 1, '');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition16', 1, 1, '');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition16', 1, 1, '');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition17', 1, 1, '');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition17', 1, 1, '');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition18', 1, 1, '');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition18', 1, 1, '');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition19', 1, 1, '');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition19', 1, 1, '');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition9', 1, 1, '');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition9', 1, 1, '');
