SLStudio.Utils.RemoveHighlighting(get_param('uz_inverter_3phgm', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_uz_inverter_3phgm', 'handle'));
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Multiply Input', 1, 1, '');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/HDL Algorithm/State Update/Multiply Input', 1, 1, '');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Multiply State', 1, 1, '');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/HDL Algorithm/Output/Multiply State', 1, 1, '');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion1', 1, 1, '');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion1', 1, 1, '');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion8', 1, 1, '');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion8', 1, 1, '');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion7', 1, 1, '');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion7', 1, 1, '');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Output Sum', 0, 1, '');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion12', 1, 1, '');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion12', 1, 1, '');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion13', 1, 1, '');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion13', 1, 1, '');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion14', 1, 1, '');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion14', 1, 1, '');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion15', 1, 1, '');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion15', 1, 1, '');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion16', 1, 1, '');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion16', 1, 1, '');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion11', 1, 1, '');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion11', 1, 1, '');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion10', 1, 1, '');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion10', 1, 1, '');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion3', 1, 1, '');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion3', 1, 1, '');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion4', 1, 1, '');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion4', 1, 1, '');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion9', 1, 1, '');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion9', 1, 1, '');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion6', 1, 1, '');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion6', 1, 1, '');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion', 1, 1, '');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion', 1, 1, '');
