open_system('uz_inverter_3phgm');
open_system('gm_uz_inverter_3phgm');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Delay', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Delay', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/HDL Algorithm/Mode Iteration Manager/Delay', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/HDL Algorithm/Mode Iteration Manager/Delay', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Delay2', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Delay2', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/HDL Algorithm/Mode Iteration Manager/Delay2', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/HDL Algorithm/Mode Iteration Manager/Delay2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition10', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition10', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition10', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition10', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition11', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition11', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition11', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition11', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition12', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition12', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition12', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition12', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition13', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition13', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition13', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition13', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition14', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition14', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition14', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition14', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition15', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition15', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition15', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition15', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition16', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition16', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition16', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition16', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition17', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition17', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition17', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition17', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition18', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition18', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition18', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition18', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition19', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition19', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition19', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition19', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition20', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition20', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition20', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition20', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition21', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Rate Transition21', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition21', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/Rate Transition21', 1, 1, 'Obstacle to clock-rate pipelining');
