open_system('uz_inverter_3phgm');
open_system('gm_uz_inverter_3phgm');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Multiply Input', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Multiply Input', 1, 1, 'Block not characterized');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/HDL Algorithm/State Update/Multiply Input', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/HDL Algorithm/State Update/Multiply Input', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Multiply State', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Multiply State', 1, 1, 'Block not characterized');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/HDL Algorithm/Output/Multiply State', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/HDL Subsystem/HDL Algorithm/Output/Multiply State', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion1', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion1', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion1', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion1', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion8', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion8', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion8', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion8', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion7', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion7', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion7', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion7', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion12', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion12', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion12', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion12', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion13', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion13', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion13', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion13', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion14', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion14', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion14', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion14', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion15', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion15', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion15', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion15', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion16', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion16', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion16', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion16', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion11', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion11', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion11', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion11', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion10', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion10', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion10', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion10', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion3', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion3', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion3', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion3', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion4', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion4', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion4', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion4', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion9', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion9', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion9', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion9', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion6', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion6', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion6', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion6', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion', 'user2');
annotate_port('gm_uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion', 'user2');
annotate_port('uz_inverter_3phgm/uz_inverter_3ph/Data Type Conversion', 1, 1, 'Block not characterized for this configuration');
