#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("in_r_address0", 3, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("in_r_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("in_r_d0", 32, hls_out, 0, "ap_memory", "mem_din", 1),
	Port_Property("in_r_q0", 32, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("in_r_we0", 1, hls_out, 0, "ap_memory", "mem_we", 1),
	Port_Property("in_r_address1", 3, hls_out, 0, "ap_memory", "MemPortADDR2", 1),
	Port_Property("in_r_ce1", 1, hls_out, 0, "ap_memory", "MemPortCE2", 1),
	Port_Property("in_r_d1", 32, hls_out, 0, "ap_memory", "mem_din", 1),
	Port_Property("in_r_q1", 32, hls_in, 0, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("in_r_we1", 1, hls_out, 0, "ap_memory", "mem_we", 1),
	Port_Property("out_1", 32, hls_out, 1, "ap_vld", "out_data", 1),
	Port_Property("out_2", 32, hls_out, 2, "ap_vld", "out_data", 1),
	Port_Property("out_3", 32, hls_out, 3, "ap_vld", "out_data", 1),
	Port_Property("out_4", 32, hls_out, 4, "ap_vld", "out_data", 1),
	Port_Property("out_5", 32, hls_out, 5, "ap_vld", "out_data", 1),
	Port_Property("out_6", 32, hls_out, 6, "ap_vld", "out_data", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("out_1_ap_vld", 1, hls_out, 1, "ap_vld", "out_vld", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("out_2_ap_vld", 1, hls_out, 2, "ap_vld", "out_vld", 1),
	Port_Property("out_3_ap_vld", 1, hls_out, 3, "ap_vld", "out_vld", 1),
	Port_Property("out_4_ap_vld", 1, hls_out, 4, "ap_vld", "out_vld", 1),
	Port_Property("out_5_ap_vld", 1, hls_out, 5, "ap_vld", "out_vld", 1),
	Port_Property("out_6_ap_vld", 1, hls_out, 6, "ap_vld", "out_vld", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "uz_VSD_6ph_asym";
