SLStudio.Utils.RemoveHighlighting(get_param('parallel_8_cost_function', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_parallel_8_cost_function', 'handle'));
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Detect Rise Positive', 0, 1, '');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Subsystem', 0, 1, '');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/mux', 0, 1, '');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Switch_on4', 0, 1, '');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Detect Rise Positive/Positive', 0, 1, '');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Detect Rise Positive/FixPt Relational Operator', 0, 1, '');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Detect Rise Positive/Positive/Compare', 0, 1, '');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Subsystem/Subsystem', 0, 1, '');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Subsystem/t', 0, 1, '');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Subsystem/Demux_mux_1', 0, 1, '');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Subsystem/Subsystem/t', 0, 2, '');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Subsystem/Subsystem/Prediction_1_1_wire', 0, 1, '');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Subsystem/Subsystem/Product1', 0, 1, '');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Subsystem/Subsystem/Subtract5', 0, 1, '');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Subsystem/Subsystem/Sum of Elements_stage2', 0, 1, '');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Subsystem/Subsystem/Sum of Elements_stage3', 0, 1, '');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Subsystem/Subsystem/Sum of Elements_stage4', 0, 1, '');
