open_system('gm_parallel_8_cost_function');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_cost_function/HDL_DUT4/Detect Rise Positive', 'user2');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Detect Rise Positive', 0, 1, 'cp : 1.374 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_cost_function/HDL_DUT4/Subsystem', 'user2');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Subsystem', 0, 1, 'cp : 8.364 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_cost_function/HDL_DUT4/mux', 'user1');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/mux', 0, 1, 'cp : 8.364 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_cost_function/HDL_DUT4/Switch_on4', 'user2');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Switch_on4', 0, 1, 'cp : 1.702 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_cost_function/HDL_DUT4/Detect Rise Positive/Positive', 'user2');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Detect Rise Positive/Positive', 0, 1, 'cp : 0.687 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_cost_function/HDL_DUT4/Detect Rise Positive/FixPt Relational Operator', 'user2');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Detect Rise Positive/FixPt Relational Operator', 0, 1, 'cp : 1.374 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_cost_function/HDL_DUT4/Detect Rise Positive/Positive/Compare', 'user1');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Detect Rise Positive/Positive/Compare', 0, 1, 'cp : 0.687 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_cost_function/HDL_DUT4/Subsystem/Subsystem', 'user2');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Subsystem/Subsystem', 0, 1, 'cp : 8.364 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_cost_function/HDL_DUT4/Subsystem/t', 'user2');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Subsystem/t', 0, 1, 'cp : 1.702 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_cost_function/HDL_DUT4/Subsystem/Demux_mux_1', 'user2');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Subsystem/Demux_mux_1', 0, 1, 'cp : 1.702 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_cost_function/HDL_DUT4/Subsystem/Subsystem/t', 'user2');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Subsystem/Subsystem/t', 0, 2, 'cp : 1.702 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_cost_function/HDL_DUT4/Subsystem/Subsystem/Prediction_1_1_wire', 'user2');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Subsystem/Subsystem/Prediction_1_1_wire', 0, 1, 'cp : 1.702 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_cost_function/HDL_DUT4/Subsystem/Subsystem/Product1', 'user2');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Subsystem/Subsystem/Product1', 0, 1, 'cp : 6.323 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_cost_function/HDL_DUT4/Subsystem/Subsystem/Subtract5', 'user2');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Subsystem/Subsystem/Subtract5', 0, 1, 'cp : 2.375 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_cost_function/HDL_DUT4/Subsystem/Subsystem/Sum of Elements_stage2', 'user2');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Subsystem/Subsystem/Sum of Elements_stage2', 0, 1, 'cp : 6.996 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_cost_function/HDL_DUT4/Subsystem/Subsystem/Sum of Elements_stage3', 'user2');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Subsystem/Subsystem/Sum of Elements_stage3', 0, 1, 'cp : 7.68 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_parallel_8_cost_function/HDL_DUT4/Subsystem/Subsystem/Sum of Elements_stage4', 'user2');
annotate_port('gm_parallel_8_cost_function/HDL_DUT4/Subsystem/Subsystem/Sum of Elements_stage4', 0, 1, 'cp : 8.364 ns');
