-- -------------------------------------------------------------
-- 
-- File Name: C:\Ultrazohm\ultrazohm_sw\ip_cores\SS_debug_block\hdlsrc\SS_debug\Subsystem_ip_dut.vhd
-- Created: 2025-12-02 18:39:40
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem_ip_dut
-- Source Path: Subsystem_ip/Subsystem_ip_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Subsystem_ip_dut IS
  PORT( AXI_SS0_in                        :   IN    std_logic;  -- ufix1
        AXI_SS1_in                        :   IN    std_logic;  -- ufix1
        AXI_SS2_in                        :   IN    std_logic;  -- ufix1
        AXI_SS3_in                        :   IN    std_logic;  -- ufix1
        SS0_in                            :   IN    std_logic;  -- ufix1
        SS1_in                            :   IN    std_logic;  -- ufix1
        SS2_in                            :   IN    std_logic;  -- ufix1
        SS3_in                            :   IN    std_logic;  -- ufix1
        SS0_out                           :   OUT   std_logic;  -- ufix1
        SS1_out                           :   OUT   std_logic;  -- ufix1
        SS2_out                           :   OUT   std_logic;  -- ufix1
        SS3_out                           :   OUT   std_logic;  -- ufix1
        AXI_SS0_out                       :   OUT   std_logic;  -- ufix1
        AXI_SS1_out                       :   OUT   std_logic;  -- ufix1
        AXI_SS2_out                       :   OUT   std_logic;  -- ufix1
        AXI_SS3_out                       :   OUT   std_logic  -- ufix1
        );
END Subsystem_ip_dut;


ARCHITECTURE rtl OF Subsystem_ip_dut IS

  -- Component Declarations
  COMPONENT Subsystem_ip_src_Subsystem
    PORT( AXI_SS0_in                      :   IN    std_logic;  -- ufix1
          AXI_SS1_in                      :   IN    std_logic;  -- ufix1
          AXI_SS2_in                      :   IN    std_logic;  -- ufix1
          AXI_SS3_in                      :   IN    std_logic;  -- ufix1
          SS0_in                          :   IN    std_logic;  -- ufix1
          SS1_in                          :   IN    std_logic;  -- ufix1
          SS2_in                          :   IN    std_logic;  -- ufix1
          SS3_in                          :   IN    std_logic;  -- ufix1
          SS0_out                         :   OUT   std_logic;  -- ufix1
          SS1_out                         :   OUT   std_logic;  -- ufix1
          SS2_out                         :   OUT   std_logic;  -- ufix1
          SS3_out                         :   OUT   std_logic;  -- ufix1
          AXI_SS0_out                     :   OUT   std_logic;  -- ufix1
          AXI_SS1_out                     :   OUT   std_logic;  -- ufix1
          AXI_SS2_out                     :   OUT   std_logic;  -- ufix1
          AXI_SS3_out                     :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Subsystem_ip_src_Subsystem
    USE ENTITY work.Subsystem_ip_src_Subsystem(rtl);

  -- Signals
  SIGNAL AXI_SS0_in_sig                   : std_logic;  -- ufix1
  SIGNAL AXI_SS1_in_sig                   : std_logic;  -- ufix1
  SIGNAL AXI_SS2_in_sig                   : std_logic;  -- ufix1
  SIGNAL AXI_SS3_in_sig                   : std_logic;  -- ufix1
  SIGNAL SS0_in_sig                       : std_logic;  -- ufix1
  SIGNAL SS1_in_sig                       : std_logic;  -- ufix1
  SIGNAL SS2_in_sig                       : std_logic;  -- ufix1
  SIGNAL SS3_in_sig                       : std_logic;  -- ufix1
  SIGNAL SS0_out_sig                      : std_logic;  -- ufix1
  SIGNAL SS1_out_sig                      : std_logic;  -- ufix1
  SIGNAL SS2_out_sig                      : std_logic;  -- ufix1
  SIGNAL SS3_out_sig                      : std_logic;  -- ufix1
  SIGNAL AXI_SS0_out_sig                  : std_logic;  -- ufix1
  SIGNAL AXI_SS1_out_sig                  : std_logic;  -- ufix1
  SIGNAL AXI_SS2_out_sig                  : std_logic;  -- ufix1
  SIGNAL AXI_SS3_out_sig                  : std_logic;  -- ufix1

BEGIN
  u_Subsystem_ip_src_Subsystem : Subsystem_ip_src_Subsystem
    PORT MAP( AXI_SS0_in => AXI_SS0_in_sig,  -- ufix1
              AXI_SS1_in => AXI_SS1_in_sig,  -- ufix1
              AXI_SS2_in => AXI_SS2_in_sig,  -- ufix1
              AXI_SS3_in => AXI_SS3_in_sig,  -- ufix1
              SS0_in => SS0_in_sig,  -- ufix1
              SS1_in => SS1_in_sig,  -- ufix1
              SS2_in => SS2_in_sig,  -- ufix1
              SS3_in => SS3_in_sig,  -- ufix1
              SS0_out => SS0_out_sig,  -- ufix1
              SS1_out => SS1_out_sig,  -- ufix1
              SS2_out => SS2_out_sig,  -- ufix1
              SS3_out => SS3_out_sig,  -- ufix1
              AXI_SS0_out => AXI_SS0_out_sig,  -- ufix1
              AXI_SS1_out => AXI_SS1_out_sig,  -- ufix1
              AXI_SS2_out => AXI_SS2_out_sig,  -- ufix1
              AXI_SS3_out => AXI_SS3_out_sig  -- ufix1
              );

  AXI_SS0_in_sig <= AXI_SS0_in;

  AXI_SS1_in_sig <= AXI_SS1_in;

  AXI_SS2_in_sig <= AXI_SS2_in;

  AXI_SS3_in_sig <= AXI_SS3_in;

  SS0_in_sig <= SS0_in;

  SS1_in_sig <= SS1_in;

  SS2_in_sig <= SS2_in;

  SS3_in_sig <= SS3_in;

  SS0_out <= SS0_out_sig;

  SS1_out <= SS1_out_sig;

  SS2_out <= SS2_out_sig;

  SS3_out <= SS3_out_sig;

  AXI_SS0_out <= AXI_SS0_out_sig;

  AXI_SS1_out <= AXI_SS1_out_sig;

  AXI_SS2_out <= AXI_SS2_out_sig;

  AXI_SS3_out <= AXI_SS3_out_sig;

END rtl;

