-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\uz_mpc_3ph\uz_pu_con_ip_dut.vhd
-- Created: 2023-10-04 15:36:04
-- 
-- Generated by MATLAB 9.10 and HDL Coder 3.18
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: uz_pu_con_ip_dut
-- Source Path: uz_pu_con_ip/uz_pu_con_ip_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY uz_pu_con_ip_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        in0                               :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En15
        in1                               :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En15
        in2                               :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En15
        in3                               :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En15
        AXI_pu_conv_in0                   :   IN    std_logic_vector(17 DOWNTO 0);  -- ufix18_En18
        AXI_pu_conv_in1                   :   IN    std_logic_vector(17 DOWNTO 0);  -- ufix18_En18
        AXI_pu_conv_in2                   :   IN    std_logic_vector(17 DOWNTO 0);  -- ufix18_En18
        AXI_pu_conv_in3                   :   IN    std_logic_vector(17 DOWNTO 0);  -- ufix18_En18
        adc_valid_trigger                 :   IN    std_logic;  -- ufix1
        ce_out                            :   OUT   std_logic;  -- ufix1
        out0                              :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        out1                              :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        out2                              :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        out3                              :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        pu_conv_done                      :   OUT   std_logic;  -- ufix1
        out0_AXI                          :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        out1_AXI                          :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        out2_AXI                          :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        out3_AXI                          :   OUT   std_logic_vector(17 DOWNTO 0)  -- sfix18_En15
        );
END uz_pu_con_ip_dut;


ARCHITECTURE rtl OF uz_pu_con_ip_dut IS

  -- Component Declarations
  COMPONENT uz_pu_con_ip_src_uz_pu_conversion
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset                           :   IN    std_logic;
          in0                             :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En15
          in1                             :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En15
          in2                             :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En15
          in3                             :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En15
          AXI_pu_conv_in0                 :   IN    std_logic_vector(17 DOWNTO 0);  -- ufix18_En18
          AXI_pu_conv_in1                 :   IN    std_logic_vector(17 DOWNTO 0);  -- ufix18_En18
          AXI_pu_conv_in2                 :   IN    std_logic_vector(17 DOWNTO 0);  -- ufix18_En18
          AXI_pu_conv_in3                 :   IN    std_logic_vector(17 DOWNTO 0);  -- ufix18_En18
          adc_valid_trigger               :   IN    std_logic;  -- ufix1
          ce_out                          :   OUT   std_logic;  -- ufix1
          out0                            :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
          out1                            :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
          out2                            :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
          out3                            :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
          pu_conv_done                    :   OUT   std_logic;  -- ufix1
          out0_AXI                        :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
          out1_AXI                        :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
          out2_AXI                        :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
          out3_AXI                        :   OUT   std_logic_vector(17 DOWNTO 0)  -- sfix18_En15
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : uz_pu_con_ip_src_uz_pu_conversion
    USE ENTITY work.uz_pu_con_ip_src_uz_pu_conversion(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL adc_valid_trigger_sig            : std_logic;  -- ufix1
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL out0_sig                         : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL out1_sig                         : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL out2_sig                         : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL out3_sig                         : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL pu_conv_done_sig                 : std_logic;  -- ufix1
  SIGNAL out0_AXI_sig                     : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL out1_AXI_sig                     : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL out2_AXI_sig                     : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL out3_AXI_sig                     : std_logic_vector(17 DOWNTO 0);  -- ufix18

BEGIN
  u_uz_pu_con_ip_src_uz_pu_conversion : uz_pu_con_ip_src_uz_pu_conversion
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset => reset,
              in0 => in0,  -- sfix27_En15
              in1 => in1,  -- sfix27_En15
              in2 => in2,  -- sfix27_En15
              in3 => in3,  -- sfix27_En15
              AXI_pu_conv_in0 => AXI_pu_conv_in0,  -- ufix18_En18
              AXI_pu_conv_in1 => AXI_pu_conv_in1,  -- ufix18_En18
              AXI_pu_conv_in2 => AXI_pu_conv_in2,  -- ufix18_En18
              AXI_pu_conv_in3 => AXI_pu_conv_in3,  -- ufix18_En18
              adc_valid_trigger => adc_valid_trigger_sig,  -- ufix1
              ce_out => ce_out_sig,  -- ufix1
              out0 => out0_sig,  -- sfix18_En15
              out1 => out1_sig,  -- sfix18_En15
              out2 => out2_sig,  -- sfix18_En15
              out3 => out3_sig,  -- sfix18_En15
              pu_conv_done => pu_conv_done_sig,  -- ufix1
              out0_AXI => out0_AXI_sig,  -- sfix18_En15
              out1_AXI => out1_AXI_sig,  -- sfix18_En15
              out2_AXI => out2_AXI_sig,  -- sfix18_En15
              out3_AXI => out3_AXI_sig  -- sfix18_En15
              );

  adc_valid_trigger_sig <= adc_valid_trigger;

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  out0 <= out0_sig;

  out1 <= out1_sig;

  out2 <= out2_sig;

  out3 <= out3_sig;

  pu_conv_done <= pu_conv_done_sig;

  out0_AXI <= out0_AXI_sig;

  out1_AXI <= out1_AXI_sig;

  out2_AXI <= out2_AXI_sig;

  out3_AXI <= out3_AXI_sig;

END rtl;

