open_system('gm_min_cost_function_and_vopt_FCS_MPC_6Phase_PMSM');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_min_cost_function_and_vopt_FCS_MPC_6Phase_PMSM/HDL_DUT1/Compare To Constant', 'user2');
annotate_port('gm_min_cost_function_and_vopt_FCS_MPC_6Phase_PMSM/HDL_DUT1/Compare To Constant', 0, 1, 'cp : 2.866 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_min_cost_function_and_vopt_FCS_MPC_6Phase_PMSM/HDL_DUT1/Detect Rise Positive', 'user2');
annotate_port('gm_min_cost_function_and_vopt_FCS_MPC_6Phase_PMSM/HDL_DUT1/Detect Rise Positive', 0, 1, 'cp : 1.704 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_min_cost_function_and_vopt_FCS_MPC_6Phase_PMSM/HDL_DUT1/Delay', 'user1');
annotate_port('gm_min_cost_function_and_vopt_FCS_MPC_6Phase_PMSM/HDL_DUT1/Delay', 1, 1, 'cp : 4.706 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_min_cost_function_and_vopt_FCS_MPC_6Phase_PMSM/HDL_DUT1/Delay46', 'user1');
annotate_port('gm_min_cost_function_and_vopt_FCS_MPC_6Phase_PMSM/HDL_DUT1/Delay46', 0, 1, 'cp : 0.33 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_min_cost_function_and_vopt_FCS_MPC_6Phase_PMSM/HDL_DUT1/Relational Operator', 'user2');
annotate_port('gm_min_cost_function_and_vopt_FCS_MPC_6Phase_PMSM/HDL_DUT1/Relational Operator', 0, 1, 'cp : 4.093 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_min_cost_function_and_vopt_FCS_MPC_6Phase_PMSM/HDL_DUT1/Switch', 'user2');
annotate_port('gm_min_cost_function_and_vopt_FCS_MPC_6Phase_PMSM/HDL_DUT1/Switch', 0, 1, 'cp : 3.218 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_min_cost_function_and_vopt_FCS_MPC_6Phase_PMSM/HDL_DUT1/Switch1', 'user2');
annotate_port('gm_min_cost_function_and_vopt_FCS_MPC_6Phase_PMSM/HDL_DUT1/Switch1', 0, 1, 'cp : 4.445 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_min_cost_function_and_vopt_FCS_MPC_6Phase_PMSM/HDL_DUT1/Switch_on1', 'user2');
annotate_port('gm_min_cost_function_and_vopt_FCS_MPC_6Phase_PMSM/HDL_DUT1/Switch_on1', 0, 1, 'cp : 2.032 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_min_cost_function_and_vopt_FCS_MPC_6Phase_PMSM/HDL_DUT1/Compare To Constant/Compare', 'user2');
annotate_port('gm_min_cost_function_and_vopt_FCS_MPC_6Phase_PMSM/HDL_DUT1/Compare To Constant/Compare', 0, 1, 'cp : 2.866 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_min_cost_function_and_vopt_FCS_MPC_6Phase_PMSM/HDL_DUT1/Detect Rise Positive/Positive', 'user2');
annotate_port('gm_min_cost_function_and_vopt_FCS_MPC_6Phase_PMSM/HDL_DUT1/Detect Rise Positive/Positive', 0, 1, 'cp : 1.017 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_min_cost_function_and_vopt_FCS_MPC_6Phase_PMSM/HDL_DUT1/Detect Rise Positive/FixPt Relational Operator', 'user2');
annotate_port('gm_min_cost_function_and_vopt_FCS_MPC_6Phase_PMSM/HDL_DUT1/Detect Rise Positive/FixPt Relational Operator', 0, 1, 'cp : 1.704 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_min_cost_function_and_vopt_FCS_MPC_6Phase_PMSM/HDL_DUT1/Detect Rise Positive/Positive/Compare', 'user2');
annotate_port('gm_min_cost_function_and_vopt_FCS_MPC_6Phase_PMSM/HDL_DUT1/Detect Rise Positive/Positive/Compare', 0, 1, 'cp : 1.017 ns');
