open_system('gm_UZ_EnDat_be4_segregation');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV1', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV1', 0, 1, 'cp : 3.125 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV3', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV3', 0, 1, 'cp : 5.256 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV4', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV4', 0, 1, 'cp : 7.387 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV5', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV5', 0, 1, 'cp : 9.518 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV6', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV6', 0, 1, 'cp : 11.649 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV7', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV7', 0, 1, 'cp : 13.78 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV8', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV8', 0, 1, 'cp : 15.911 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV9', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV9', 0, 1, 'cp : 18.042 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/Subsystem', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/Subsystem', 1, 5, 'cp : 21.572 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV1/Triggered Subsystem', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV1/Triggered Subsystem', 0, 1, 'cp : 2.841 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV1/Logical Operator1', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV1/Logical Operator1', 0, 1, 'cp : 3.125 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV1/Triggered Subsystem/not_Trigger_delayed', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV1/Triggered Subsystem/not_Trigger_delayed', 0, 1, 'cp : 0.966 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV1/Triggered Subsystem/Trigger_delayed_inverted_and_Trigger', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV1/Triggered Subsystem/Trigger_delayed_inverted_and_Trigger', 0, 1, 'cp : 1.854 ns');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV1/Triggered Subsystem/Trigger_delayed_inverted_and_Trigger', 0, 1, 'cp : 3.985 ns');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV1/Triggered Subsystem/Trigger_delayed_inverted_and_Trigger', 0, 1, 'cp : 6.116 ns');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV1/Triggered Subsystem/Trigger_delayed_inverted_and_Trigger', 0, 1, 'cp : 8.247 ns');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV1/Triggered Subsystem/Trigger_delayed_inverted_and_Trigger', 0, 1, 'cp : 10.378 ns');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV1/Triggered Subsystem/Trigger_delayed_inverted_and_Trigger', 0, 1, 'cp : 12.509 ns');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV1/Triggered Subsystem/Trigger_delayed_inverted_and_Trigger', 0, 1, 'cp : 14.64 ns');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV1/Triggered Subsystem/Trigger_delayed_inverted_and_Trigger', 0, 1, 'cp : 16.771 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV1/Triggered Subsystem/Trigger_delay_switch', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV1/Triggered Subsystem/Trigger_delay_switch', 0, 1, 'cp : 0.682 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV1/Triggered Subsystem/Trigger_delay_ctrl_delay', 'user1');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV1/Triggered Subsystem/Trigger_delay_ctrl_delay', 0, 1, 'cp : 0.33 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV1/Triggered Subsystem/DbypassMux', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV1/Triggered Subsystem/DbypassMux', 0, 1, 'cp : 2.841 ns');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV1/Triggered Subsystem/DbypassMux', 0, 1, 'cp : 4.972 ns');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV1/Triggered Subsystem/DbypassMux', 0, 1, 'cp : 7.103 ns');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV1/Triggered Subsystem/DbypassMux', 0, 1, 'cp : 9.234 ns');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV1/Triggered Subsystem/DbypassMux', 0, 1, 'cp : 11.365 ns');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV1/Triggered Subsystem/DbypassMux', 0, 1, 'cp : 13.496 ns');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV1/Triggered Subsystem/DbypassMux', 0, 1, 'cp : 15.627 ns');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV1/Triggered Subsystem/DbypassMux', 0, 1, 'cp : 17.758 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV3/Triggered Subsystem', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV3/Triggered Subsystem', 0, 1, 'cp : 4.972 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV3/Logical Operator1', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV3/Logical Operator1', 0, 1, 'cp : 5.256 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV4/Triggered Subsystem', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV4/Triggered Subsystem', 0, 1, 'cp : 7.103 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV4/Logical Operator1', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV4/Logical Operator1', 0, 1, 'cp : 7.387 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV5/Triggered Subsystem', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV5/Triggered Subsystem', 0, 1, 'cp : 9.234 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV5/Logical Operator1', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV5/Logical Operator1', 0, 1, 'cp : 9.518 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV6/Triggered Subsystem', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV6/Triggered Subsystem', 0, 1, 'cp : 11.365 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV6/Logical Operator1', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV6/Logical Operator1', 0, 1, 'cp : 11.649 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV7/Triggered Subsystem', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV7/Triggered Subsystem', 0, 1, 'cp : 13.496 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV7/Logical Operator1', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV7/Logical Operator1', 0, 1, 'cp : 13.78 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV8/Triggered Subsystem', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV8/Triggered Subsystem', 0, 1, 'cp : 15.627 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV8/Logical Operator1', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV8/Logical Operator1', 0, 1, 'cp : 15.911 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV9/Triggered Subsystem', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV9/Triggered Subsystem', 0, 1, 'cp : 17.758 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV9/Logical Operator1', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/CLKDIV9/Logical Operator1', 0, 1, 'cp : 18.042 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/ManualDeserializere/ramwatcher/Trigger_delayed_inverted_and_Trigger', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/ManualDeserializere/ramwatcher/Trigger_delayed_inverted_and_Trigger', 0, 1, 'cp : 19.186 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/ManualDeserializere/ramwatcher/Product_out1bypassMux', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/ManualDeserializere/ramwatcher/Product_out1bypassMux', 0, 1, 'cp : 20.173 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/Subsystem/ManualDeserializere', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/Subsystem/ManualDeserializere', 0, 1, 'cp : 21.311 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/Subsystem/2CLKDELAY', 'user1');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/Subsystem/2CLKDELAY', 1, 1, 'cp : 21.572 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/Subsystem/ManualDeserializere/Multiport Switch', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/Subsystem/ManualDeserializere/Multiport Switch', 0, 1, 'cp : 21.311 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/Subsystem/ManualDeserializere/Switch', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/Subsystem/ManualDeserializere/Switch', 0, 1, 'cp : 18.326 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/Subsystem/ManualDeserializere/ramwatcher', 'user2');
annotate_port('gm_UZ_EnDat_be4_segregation/UZ_ENDAT/Subsystem/ManualDeserializere/ramwatcher', 0, 1, 'cp : 20.173 ns');
