vlib work
vmap -c
vcom  uz_EnDat_src_UZ_ENDAT_pac.vhd
vcom  uz_EnDat_src_Compare_To_Constant.vhd
vcom  uz_EnDat_src_Compare_To_Constant1.vhd
vcom  uz_EnDat_src_Compare_To_Constant2.vhd
vcom  uz_EnDat_src_Compare_To_Constant3.vhd
vcom  uz_EnDat_src_Compare_To_Constant4.vhd
vcom  uz_EnDat_src_Compare_To_Zero.vhd
vcom  uz_EnDat_src_SinglePortRAM_generic.vhd
vcom  uz_EnDat_src_Storage20.vhd
vcom  uz_EnDat_src_Compare_To_Zero_block.vhd
vcom  uz_EnDat_src_Storage21.vhd
vcom  uz_EnDat_src_Compare_To_Zero_block1.vhd
vcom  uz_EnDat_src_Storage22.vhd
vcom  uz_EnDat_src_Compare_To_Zero_block2.vhd
vcom  uz_EnDat_src_Storage23.vhd
vcom  uz_EnDat_src_Compare_To_Zero_block3.vhd
vcom  uz_EnDat_src_Storage24.vhd
vcom  uz_EnDat_src_Increment_Real_World.vhd
vcom  uz_EnDat_src_Wrap_To_Zero.vhd
vcom  uz_EnDat_src_Counter_Limited.vhd
vcom  uz_EnDat_src_Triggered_Subsystem.vhd
vcom  uz_EnDat_src_5timestorage.vhd
vcom  uz_EnDat_src_Triggered_Subsystem_block.vhd
vcom  uz_EnDat_src_CLKDIV1.vhd
vcom  uz_EnDat_src_CLKDIV2.vhd
vcom  uz_EnDat_src_CLKDIV3.vhd
vcom  uz_EnDat_src_CLKDIV4.vhd
vcom  uz_EnDat_src_CLKDIV5.vhd
vcom  uz_EnDat_src_CLKDIV6.vhd
vcom  uz_EnDat_src_CLKDIV7.vhd
vcom  uz_EnDat_src_CLKDIV8.vhd
vcom  uz_EnDat_src_CLKDIV9.vhd
vcom  uz_EnDat_src_WORDTOBOOL.vhd
vcom  uz_EnDat_src_CONTROLWORDRAW.vhd
vcom  uz_EnDat_src_FF0.vhd
vcom  uz_EnDat_src_CRC_Check.vhd
vcom  uz_EnDat_src_Compare_To_Constant_block.vhd
vcom  uz_EnDat_src_Compare_To_Constant1_block.vhd
vcom  uz_EnDat_src_Compare_To_Constant2_block.vhd
vcom  uz_EnDat_src_Detect_Change.vhd
vcom  uz_EnDat_src_WORDTOBOOL_block.vhd
vcom  uz_EnDat_src_Increment_Stored_Integer.vhd
vcom  uz_EnDat_src_ramwatcher.vhd
vcom  uz_EnDat_src_ManualDeserializere.vhd
vcom  uz_EnDat_src_SetZero32.vhd
vcom  uz_EnDat_src_Increment_Stored_Integer_block.vhd
vcom  uz_EnDat_src_Positional_Counter.vhd
vcom  uz_EnDat_src_CLKCNTER_RECIEVE.vhd
vcom  uz_EnDat_src_Compare_To_Zero_block4.vhd
vcom  uz_EnDat_src_Storage16.vhd
vcom  uz_EnDat_src_Triggered_Subsystem_block1.vhd
vcom  uz_EnDat_src_SetZero64.vhd
vcom  uz_EnDat_src_ManualSerialize.vhd
vcom  uz_EnDat_src_SetZero.vhd
vcom  uz_EnDat_src_SetZeroBool1.vhd
vcom  uz_EnDat_src_SetZero64_block.vhd
vcom  uz_EnDat_src_Increment_Stored_Integer_block1.vhd
vcom  uz_EnDat_src_Positional_Counter_block.vhd
vcom  uz_EnDat_src_CLKCNTERBOOTUP.vhd
vcom  uz_EnDat_src_WORDTOBOOL_block1.vhd
vcom  uz_EnDat_src_ManualDeserializere_block.vhd
vcom  uz_EnDat_src_OUTPUTCONTROLCONTINIOUS.vhd
vcom  uz_EnDat_src_Subsystem.vhd
vcom  uz_EnDat_src_Increment_Stored_Integer_block2.vhd
vcom  uz_EnDat_src_ramselektor.vhd
vcom  uz_EnDat_src_Subsystem_block.vhd
vcom  uz_EnDat_src_Subsystem1.vhd
vcom  uz_EnDat_src_Subsystem10.vhd
vcom  uz_EnDat_src_Subsystem11.vhd
vcom  uz_EnDat_src_Subsystem12.vhd
vcom  uz_EnDat_src_Subsystem13.vhd
vcom  uz_EnDat_src_Subsystem14.vhd
vcom  uz_EnDat_src_Subsystem15.vhd
vcom  uz_EnDat_src_Subsystem2.vhd
vcom  uz_EnDat_src_Subsystem3.vhd
vcom  uz_EnDat_src_Subsystem4.vhd
vcom  uz_EnDat_src_Subsystem5.vhd
vcom  uz_EnDat_src_Subsystem6.vhd
vcom  uz_EnDat_src_Subsystem7.vhd
vcom  uz_EnDat_src_Subsystem8.vhd
vcom  uz_EnDat_src_Subsystem9.vhd
vcom  uz_EnDat_src_16bitgather.vhd
vcom  uz_EnDat_src_DualPortRAM_generic.vhd
vcom  uz_EnDat_src_16BIT_SPLITTER.vhd
vcom  uz_EnDat_src_Compare_To_Zero_block5.vhd
vcom  uz_EnDat_src_Storage16_block.vhd
vcom  uz_EnDat_src_WORDTOBOOL_block2.vhd
vcom  uz_EnDat_src_CONTROLWORDSTORED.vhd
vcom  uz_EnDat_src_SetZero32_block.vhd
vcom  uz_EnDat_src_CLKCNTER_RAMPUP.vhd
vcom  uz_EnDat_src_OUTPUTCONTROLCONTINIOUS_block.vhd
vcom  uz_EnDat_src_SetZero32_block1.vhd
vcom  uz_EnDat_src_CLKCNTER_ACT.vhd
vcom  uz_EnDat_src_SetZeroBool.vhd
vcom  uz_EnDat_src_nfp_convert_fix_64_En0_to_double.vhd
vcom  uz_EnDat_src_SimpleDualPortRAM_generic.vhd
vcom  uz_EnDat_src_UZ_ENDAT.vhd
