open_system('gm_test_min_cost_function_without_delays');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Detect Rise Positive', 'user2');
annotate_port('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Detect Rise Positive', 0, 1, 'cp : 1.374 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Logical Operator', 'user2');
annotate_port('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Logical Operator', 0, 1, 'cp : 3.541 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Relational Operator1', 'user2');
annotate_port('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Relational Operator1', 0, 1, 'cp : 2.653 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Switch7', 'user1');
annotate_port('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Switch7', 0, 1, 'cp : 3.893 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Switch_on1', 'user2');
annotate_port('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Switch_on1', 0, 1, 'cp : 1.702 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Detect Rise Positive/Positive', 'user2');
annotate_port('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Detect Rise Positive/Positive', 0, 1, 'cp : 0.687 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Detect Rise Positive/FixPt Relational Operator', 'user2');
annotate_port('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Detect Rise Positive/FixPt Relational Operator', 0, 1, 'cp : 1.374 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Detect Rise Positive/Positive/Compare', 'user1');
annotate_port('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Detect Rise Positive/Positive/Compare', 0, 1, 'cp : 0.687 ns');
