open_system('test_min_cost_function_without_delays');
open_system('gm_test_min_cost_function_without_delays');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant', 'user2');
annotate_port('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant', 1, 1, 'Block not characterized');
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant1', 'user2');
annotate_port('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant1', 1, 1, 'Block not characterized');
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant1', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant10', 'user2');
annotate_port('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant10', 1, 1, 'Block not characterized');
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant10', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant10', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant11', 'user2');
annotate_port('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant11', 1, 1, 'Block not characterized');
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant11', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant11', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant12', 'user2');
annotate_port('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant12', 1, 1, 'Block not characterized');
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant12', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant12', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant13', 'user2');
annotate_port('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant13', 1, 1, 'Block not characterized');
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant13', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant13', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant14', 'user2');
annotate_port('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant14', 1, 1, 'Block not characterized');
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant14', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant14', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant15', 'user2');
annotate_port('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant15', 1, 1, 'Block not characterized');
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant15', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant15', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant2', 'user2');
annotate_port('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant2', 1, 1, 'Block not characterized');
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant2', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant3', 'user2');
annotate_port('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant3', 1, 1, 'Block not characterized');
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant3', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant4', 'user2');
annotate_port('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant4', 1, 1, 'Block not characterized');
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant4', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant5', 'user2');
annotate_port('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant5', 1, 1, 'Block not characterized');
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant5', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant6', 'user2');
annotate_port('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant6', 1, 1, 'Block not characterized');
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant6', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant6', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant7', 'user2');
annotate_port('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant7', 1, 1, 'Block not characterized');
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant7', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant7', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant8', 'user2');
annotate_port('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant8', 1, 1, 'Block not characterized');
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant8', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant8', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant9', 'user2');
annotate_port('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant9', 1, 1, 'Block not characterized');
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant9', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Compare To Constant9', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Detect Rise Positive1', 'user2');
annotate_port('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Detect Rise Positive1', 1, 1, 'Block not characterized');
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Detect Rise Positive1', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Detect Rise Positive1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 'user2');
annotate_port('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 1, 1, 'Block not characterized');
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 'user2');
annotate_port('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 1, 1, 'Block not characterized');
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Detect Rise Positive1/Positive', 'user2');
annotate_port('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Detect Rise Positive1/Positive', 1, 1, 'Block not characterized');
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Detect Rise Positive1/Positive', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/Detect Rise Positive1/Positive', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MATLAB Function/MATLAB Function', 'user2');
annotate_port('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MATLAB Function/MATLAB Function', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MATLAB Function/MATLAB Function', 'user2');
annotate_port('gm_test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MATLAB Function/MATLAB Function', 1, 1, 'Block not characterized');
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MATLAB Function', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MATLAB Function', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 'user2');
annotate_port('test_min_cost_function_without_delays/Min_cost_function_and_vopt1/MinMax', 1, 1, 'Block not characterized');
