open_system('gm_uz_6ph_spacevector_decode');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_6ph_spacevector_decode/uz_6ph_spacevector_decode/Delay6', 'user1');
annotate_port('gm_uz_6ph_spacevector_decode/uz_6ph_spacevector_decode/Delay6', 0, 1, 'cp : 0.33 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_6ph_spacevector_decode/uz_6ph_spacevector_decode/HDL Counter', 'user2');
annotate_port('gm_uz_6ph_spacevector_decode/uz_6ph_spacevector_decode/HDL Counter', 1, 2, 'cp : 3.339 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_6ph_spacevector_decode/uz_6ph_spacevector_decode/Bit Concat', 'user2');
annotate_port('gm_uz_6ph_spacevector_decode/uz_6ph_spacevector_decode/Bit Concat', 0, 1, 'cp : 0.33 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_6ph_spacevector_decode/uz_6ph_spacevector_decode/Cast To Double1', 'user2');
annotate_port('gm_uz_6ph_spacevector_decode/uz_6ph_spacevector_decode/Cast To Double1', 0, 1, 'cp : 1.701 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_6ph_spacevector_decode/uz_6ph_spacevector_decode/Compare To Constant15', 'user2');
annotate_port('gm_uz_6ph_spacevector_decode/uz_6ph_spacevector_decode/Compare To Constant15', 0, 1, 'cp : 1.701 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_6ph_spacevector_decode/uz_6ph_spacevector_decode/Detec_edge', 'user2');
annotate_port('gm_uz_6ph_spacevector_decode/uz_6ph_spacevector_decode/Detec_edge', 0, 1, 'cp : 1.014 ns');
