open_system('gm_external_state_machine');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay46', 'user1');
annotate_port('gm_external_state_machine/cost_opt/Delay46', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay69', 'user1');
annotate_port('gm_external_state_machine/cost_opt/Delay69', 1, 1, 'cp : 4.905 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Product', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Product', 0, 1, 'cp : 4.905 ns');
