-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\external_state_machine\ctrl_stat_ip_src_resetable_counter.vhd
-- Created: 2023-06-15 08:35:39
-- 
-- Generated by MATLAB 9.10 and HDL Coder 3.18
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ctrl_stat_ip_src_resetable_counter
-- Source Path: external_state_machine/ctrl_state_machine/resetable_counter
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ctrl_stat_ip_src_resetable_counter IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        enb_1                             :   IN    std_logic;
        rst                               :   IN    std_logic;
        cnt                               :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END ctrl_stat_ip_src_resetable_counter;


ARCHITECTURE rtl OF ctrl_stat_ip_src_resetable_counter IS

  -- Signals
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL Constant3_out1                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Constant5_out1                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL trigger                          : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL switch_compare_1_1               : std_logic;
  SIGNAL Constant6_out1                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Constant1_out1                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Add_out1                         : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Delay4_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Add1_out1                        : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL trigger_1                        : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Add_op_stage1                    : unsigned(7 DOWNTO 0);  -- ufix8

BEGIN
  
  switch_compare_1 <= '1' WHEN enb_1 > '0' ELSE
      '0';

  Constant3_out1 <= to_unsigned(16#00#, 8);

  Constant5_out1 <= to_unsigned(16#01#, 8);

  
  trigger <= Constant3_out1 WHEN switch_compare_1 = '0' ELSE
      Constant5_out1;

  
  switch_compare_1_1 <= '1' WHEN rst > '0' ELSE
      '0';

  Constant6_out1 <= to_unsigned(16#00#, 8);

  Constant1_out1 <= to_unsigned(16#00#, 8);

  Delay4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay4_out1 <= to_unsigned(16#00#, 8);
      ELSIF enb = '1' THEN
        Delay4_out1 <= Add_out1;
      END IF;
    END IF;
  END PROCESS Delay4_process;


  Add1_out1 <= Delay4_out1 - Constant1_out1;

  
  trigger_1 <= Constant6_out1 WHEN switch_compare_1_1 = '0' ELSE
      Add1_out1;

  Add_op_stage1 <= trigger - trigger_1;

  Add_out1 <= Add_op_stage1 + Delay4_out1;

  cnt <= std_logic_vector(Add_out1);

END rtl;

