open_system('external_state_machine');
open_system('gm_external_state_machine');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Detect Rise Positive', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Detect Rise Positive', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Detect Rise Positive', 'user2');
annotate_port('external_state_machine/cost_opt/Detect Rise Positive', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay', 'user2');
annotate_port('external_state_machine/cost_opt/Delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay1', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay1', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay1', 'user2');
annotate_port('external_state_machine/cost_opt/Delay1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay10', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay10', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay10', 'user2');
annotate_port('external_state_machine/cost_opt/Delay10', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay11', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay11', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay11', 'user2');
annotate_port('external_state_machine/cost_opt/Delay11', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay12', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay12', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay12', 'user2');
annotate_port('external_state_machine/cost_opt/Delay12', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay14', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay14', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay14', 'user2');
annotate_port('external_state_machine/cost_opt/Delay14', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay15', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay15', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay15', 'user2');
annotate_port('external_state_machine/cost_opt/Delay15', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay16', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay16', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay16', 'user2');
annotate_port('external_state_machine/cost_opt/Delay16', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay17', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay17', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay17', 'user2');
annotate_port('external_state_machine/cost_opt/Delay17', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay18', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay18', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay18', 'user2');
annotate_port('external_state_machine/cost_opt/Delay18', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay19', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay19', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay19', 'user2');
annotate_port('external_state_machine/cost_opt/Delay19', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay2', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay2', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay2', 'user2');
annotate_port('external_state_machine/cost_opt/Delay2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay20', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay20', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay20', 'user2');
annotate_port('external_state_machine/cost_opt/Delay20', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay21', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay21', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay21', 'user2');
annotate_port('external_state_machine/cost_opt/Delay21', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay23', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay23', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay23', 'user2');
annotate_port('external_state_machine/cost_opt/Delay23', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay24', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay24', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay24', 'user2');
annotate_port('external_state_machine/cost_opt/Delay24', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay25', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay25', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay25', 'user2');
annotate_port('external_state_machine/cost_opt/Delay25', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay26', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay26', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay26', 'user2');
annotate_port('external_state_machine/cost_opt/Delay26', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay27', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay27', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay27', 'user2');
annotate_port('external_state_machine/cost_opt/Delay27', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay28', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay28', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay28', 'user2');
annotate_port('external_state_machine/cost_opt/Delay28', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay29', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay29', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay29', 'user2');
annotate_port('external_state_machine/cost_opt/Delay29', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay3', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay3', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay3', 'user2');
annotate_port('external_state_machine/cost_opt/Delay3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay30', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay30', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay30', 'user2');
annotate_port('external_state_machine/cost_opt/Delay30', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay31', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay31', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay31', 'user2');
annotate_port('external_state_machine/cost_opt/Delay31', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay32', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay32', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay32', 'user2');
annotate_port('external_state_machine/cost_opt/Delay32', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay33', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay33', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay33', 'user2');
annotate_port('external_state_machine/cost_opt/Delay33', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay34', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay34', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay34', 'user2');
annotate_port('external_state_machine/cost_opt/Delay34', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay35', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay35', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay35', 'user2');
annotate_port('external_state_machine/cost_opt/Delay35', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay36', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay36', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay36', 'user2');
annotate_port('external_state_machine/cost_opt/Delay36', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay37', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay37', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay37', 'user2');
annotate_port('external_state_machine/cost_opt/Delay37', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay38', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay38', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay38', 'user2');
annotate_port('external_state_machine/cost_opt/Delay38', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay39', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay39', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay39', 'user2');
annotate_port('external_state_machine/cost_opt/Delay39', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay4', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay4', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay4', 'user2');
annotate_port('external_state_machine/cost_opt/Delay4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay40', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay40', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay40', 'user2');
annotate_port('external_state_machine/cost_opt/Delay40', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay41', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay41', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay41', 'user2');
annotate_port('external_state_machine/cost_opt/Delay41', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay42', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay42', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay42', 'user2');
annotate_port('external_state_machine/cost_opt/Delay42', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay43', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay43', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay43', 'user2');
annotate_port('external_state_machine/cost_opt/Delay43', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay44', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay44', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay44', 'user2');
annotate_port('external_state_machine/cost_opt/Delay44', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay45', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay45', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay45', 'user2');
annotate_port('external_state_machine/cost_opt/Delay45', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay46', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay46', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay46', 'user2');
annotate_port('external_state_machine/cost_opt/Delay46', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay47', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay47', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay47', 'user2');
annotate_port('external_state_machine/cost_opt/Delay47', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay48', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay48', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay48', 'user2');
annotate_port('external_state_machine/cost_opt/Delay48', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay49', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay49', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay49', 'user2');
annotate_port('external_state_machine/cost_opt/Delay49', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay5', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay5', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay5', 'user2');
annotate_port('external_state_machine/cost_opt/Delay5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay50', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay50', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay50', 'user2');
annotate_port('external_state_machine/cost_opt/Delay50', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay51', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay51', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay51', 'user2');
annotate_port('external_state_machine/cost_opt/Delay51', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay52', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay52', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay52', 'user2');
annotate_port('external_state_machine/cost_opt/Delay52', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay53', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay53', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay53', 'user2');
annotate_port('external_state_machine/cost_opt/Delay53', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay54', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay54', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay54', 'user2');
annotate_port('external_state_machine/cost_opt/Delay54', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay55', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay55', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay55', 'user2');
annotate_port('external_state_machine/cost_opt/Delay55', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay56', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay56', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay56', 'user2');
annotate_port('external_state_machine/cost_opt/Delay56', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay57', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay57', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay57', 'user2');
annotate_port('external_state_machine/cost_opt/Delay57', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay58', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay58', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay58', 'user2');
annotate_port('external_state_machine/cost_opt/Delay58', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay59', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay59', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay59', 'user2');
annotate_port('external_state_machine/cost_opt/Delay59', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay6', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay6', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay6', 'user2');
annotate_port('external_state_machine/cost_opt/Delay6', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay60', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay60', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay60', 'user2');
annotate_port('external_state_machine/cost_opt/Delay60', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay61', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay61', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay61', 'user2');
annotate_port('external_state_machine/cost_opt/Delay61', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay62', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay62', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay62', 'user2');
annotate_port('external_state_machine/cost_opt/Delay62', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay63', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay63', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay63', 'user2');
annotate_port('external_state_machine/cost_opt/Delay63', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay64', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay64', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay64', 'user2');
annotate_port('external_state_machine/cost_opt/Delay64', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay65', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay65', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay65', 'user2');
annotate_port('external_state_machine/cost_opt/Delay65', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay66', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay66', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay66', 'user2');
annotate_port('external_state_machine/cost_opt/Delay66', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay67', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay67', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay67', 'user2');
annotate_port('external_state_machine/cost_opt/Delay67', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay68', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay68', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay68', 'user2');
annotate_port('external_state_machine/cost_opt/Delay68', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay69', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay69', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay69', 'user2');
annotate_port('external_state_machine/cost_opt/Delay69', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay7', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay7', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay7', 'user2');
annotate_port('external_state_machine/cost_opt/Delay7', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay70', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay70', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay70', 'user2');
annotate_port('external_state_machine/cost_opt/Delay70', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay71', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay71', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay71', 'user2');
annotate_port('external_state_machine/cost_opt/Delay71', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay72', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay72', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay72', 'user2');
annotate_port('external_state_machine/cost_opt/Delay72', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay73', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay73', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay73', 'user2');
annotate_port('external_state_machine/cost_opt/Delay73', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay8', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay8', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay8', 'user2');
annotate_port('external_state_machine/cost_opt/Delay8', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay9', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay9', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay9', 'user2');
annotate_port('external_state_machine/cost_opt/Delay9', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay94', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay94', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/Delay94', 'user2');
annotate_port('external_state_machine/cost_opt/Delay94', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay23_ctrl_delay', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay23_ctrl_delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay24_ctrl_delay', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay24_ctrl_delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay35_ctrl_delay', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay35_ctrl_delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay50_ctrl_delay', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay50_ctrl_delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/Delay73_ctrl_delay', 'user2');
annotate_port('gm_external_state_machine/cost_opt/Delay73_ctrl_delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/FiniteControlSetSwitchingTable/FiniteControlSetSwitchingTable', 'user2');
annotate_port('gm_external_state_machine/cost_opt/FiniteControlSetSwitchingTable/FiniteControlSetSwitchingTable', 0, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/FiniteControlSetSwitchingTable/FiniteControlSetSwitchingTable', 'user2');
annotate_port('gm_external_state_machine/cost_opt/FiniteControlSetSwitchingTable/FiniteControlSetSwitchingTable', 0, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/FiniteControlSetSwitchingTable', 'user2');
annotate_port('external_state_machine/cost_opt/FiniteControlSetSwitchingTable', 0, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/MATLAB Function/MATLAB Function', 'user2');
annotate_port('gm_external_state_machine/cost_opt/MATLAB Function/MATLAB Function', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/MATLAB Function/MATLAB Function', 'user2');
annotate_port('gm_external_state_machine/cost_opt/MATLAB Function/MATLAB Function', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/MATLAB Function', 'user2');
annotate_port('external_state_machine/cost_opt/MATLAB Function', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/iterativesearch/iterativesearch', 'user2');
annotate_port('gm_external_state_machine/cost_opt/iterativesearch/iterativesearch', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/cost_opt/iterativesearch/iterativesearch', 'user2');
annotate_port('gm_external_state_machine/cost_opt/iterativesearch/iterativesearch', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/cost_opt/iterativesearch', 'user2');
annotate_port('external_state_machine/cost_opt/iterativesearch', 1, 1, 'Block not characterized');
