open_system('external_state_machine');
open_system('gm_external_state_machine');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Detect Rise Positive', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Detect Rise Positive', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Detect Rise Positive', 'user2');
annotate_port('external_state_machine/mpc_enable/Detect Rise Positive', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay1', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay1', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay1', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay10', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay10', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay10', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay10', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay11', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay11', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay11', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay11', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay12', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay12', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay12', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay12', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay129', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay129', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay129', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay129', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay13', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay13', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay13', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay13', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay14', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay14', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay14', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay14', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay15', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay15', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay15', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay15', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay16', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay16', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay16', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay16', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay17', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay17', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay17', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay17', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay18', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay18', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay18', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay18', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay19', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay19', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay19', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay19', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay2', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay2', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay2', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay20', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay20', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay20', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay20', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay21', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay21', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay21', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay21', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay22', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay22', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay22', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay22', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay23', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay23', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay23', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay23', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay24', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay24', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay24', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay24', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay25', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay25', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay25', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay25', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay26', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay26', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay26', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay26', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay27', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay27', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay27', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay27', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay28', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay28', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay28', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay28', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay29', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay29', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay29', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay29', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay3', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay3', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay3', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay30', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay30', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay30', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay30', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay31', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay31', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay31', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay31', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay32', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay32', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay32', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay32', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay33', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay33', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay33', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay33', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay34', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay34', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay34', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay34', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay35', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay35', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay35', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay35', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay36', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay36', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay36', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay36', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay37', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay37', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay37', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay37', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay38', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay38', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay38', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay38', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay4', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay4', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay4', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay5', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay5', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay5', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay6', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay6', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay6', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay6', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay64', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay64', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay64', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay64', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay7', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay7', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay7', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay7', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay8', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay8', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay8', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay8', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/mpc_enable/Delay9', 'user2');
annotate_port('gm_external_state_machine/mpc_enable/Delay9', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/mpc_enable/Delay9', 'user2');
annotate_port('external_state_machine/mpc_enable/Delay9', 1, 1, 'Block not characterized');
