open_system('external_state_machine');
open_system('gm_external_state_machine');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_debug_switch_measurements/Delay', 'user2');
annotate_port('gm_external_state_machine/uz_debug_switch_measurements/Delay', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/uz_debug_switch_measurements/Delay', 'user2');
annotate_port('external_state_machine/uz_debug_switch_measurements/Delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_debug_switch_measurements/Delay1', 'user2');
annotate_port('gm_external_state_machine/uz_debug_switch_measurements/Delay1', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/uz_debug_switch_measurements/Delay1', 'user2');
annotate_port('external_state_machine/uz_debug_switch_measurements/Delay1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_debug_switch_measurements/Delay10', 'user2');
annotate_port('gm_external_state_machine/uz_debug_switch_measurements/Delay10', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/uz_debug_switch_measurements/Delay10', 'user2');
annotate_port('external_state_machine/uz_debug_switch_measurements/Delay10', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_debug_switch_measurements/Delay11', 'user2');
annotate_port('gm_external_state_machine/uz_debug_switch_measurements/Delay11', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/uz_debug_switch_measurements/Delay11', 'user2');
annotate_port('external_state_machine/uz_debug_switch_measurements/Delay11', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_debug_switch_measurements/Delay12', 'user2');
annotate_port('gm_external_state_machine/uz_debug_switch_measurements/Delay12', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/uz_debug_switch_measurements/Delay12', 'user2');
annotate_port('external_state_machine/uz_debug_switch_measurements/Delay12', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_debug_switch_measurements/Delay13', 'user2');
annotate_port('gm_external_state_machine/uz_debug_switch_measurements/Delay13', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/uz_debug_switch_measurements/Delay13', 'user2');
annotate_port('external_state_machine/uz_debug_switch_measurements/Delay13', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_debug_switch_measurements/Delay14', 'user2');
annotate_port('gm_external_state_machine/uz_debug_switch_measurements/Delay14', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/uz_debug_switch_measurements/Delay14', 'user2');
annotate_port('external_state_machine/uz_debug_switch_measurements/Delay14', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_debug_switch_measurements/Delay15', 'user2');
annotate_port('gm_external_state_machine/uz_debug_switch_measurements/Delay15', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/uz_debug_switch_measurements/Delay15', 'user2');
annotate_port('external_state_machine/uz_debug_switch_measurements/Delay15', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_debug_switch_measurements/Delay16', 'user2');
annotate_port('gm_external_state_machine/uz_debug_switch_measurements/Delay16', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/uz_debug_switch_measurements/Delay16', 'user2');
annotate_port('external_state_machine/uz_debug_switch_measurements/Delay16', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_debug_switch_measurements/Delay17', 'user2');
annotate_port('gm_external_state_machine/uz_debug_switch_measurements/Delay17', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/uz_debug_switch_measurements/Delay17', 'user2');
annotate_port('external_state_machine/uz_debug_switch_measurements/Delay17', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_debug_switch_measurements/Delay18', 'user2');
annotate_port('gm_external_state_machine/uz_debug_switch_measurements/Delay18', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/uz_debug_switch_measurements/Delay18', 'user2');
annotate_port('external_state_machine/uz_debug_switch_measurements/Delay18', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_debug_switch_measurements/Delay19', 'user2');
annotate_port('gm_external_state_machine/uz_debug_switch_measurements/Delay19', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/uz_debug_switch_measurements/Delay19', 'user2');
annotate_port('external_state_machine/uz_debug_switch_measurements/Delay19', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_debug_switch_measurements/Delay2', 'user2');
annotate_port('gm_external_state_machine/uz_debug_switch_measurements/Delay2', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/uz_debug_switch_measurements/Delay2', 'user2');
annotate_port('external_state_machine/uz_debug_switch_measurements/Delay2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_debug_switch_measurements/Delay20', 'user2');
annotate_port('gm_external_state_machine/uz_debug_switch_measurements/Delay20', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/uz_debug_switch_measurements/Delay20', 'user2');
annotate_port('external_state_machine/uz_debug_switch_measurements/Delay20', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_debug_switch_measurements/Delay21', 'user2');
annotate_port('gm_external_state_machine/uz_debug_switch_measurements/Delay21', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/uz_debug_switch_measurements/Delay21', 'user2');
annotate_port('external_state_machine/uz_debug_switch_measurements/Delay21', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_debug_switch_measurements/Delay22', 'user2');
annotate_port('gm_external_state_machine/uz_debug_switch_measurements/Delay22', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/uz_debug_switch_measurements/Delay22', 'user2');
annotate_port('external_state_machine/uz_debug_switch_measurements/Delay22', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_debug_switch_measurements/Delay23', 'user2');
annotate_port('gm_external_state_machine/uz_debug_switch_measurements/Delay23', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/uz_debug_switch_measurements/Delay23', 'user2');
annotate_port('external_state_machine/uz_debug_switch_measurements/Delay23', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_debug_switch_measurements/Delay24', 'user2');
annotate_port('gm_external_state_machine/uz_debug_switch_measurements/Delay24', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/uz_debug_switch_measurements/Delay24', 'user2');
annotate_port('external_state_machine/uz_debug_switch_measurements/Delay24', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_debug_switch_measurements/Delay25', 'user2');
annotate_port('gm_external_state_machine/uz_debug_switch_measurements/Delay25', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/uz_debug_switch_measurements/Delay25', 'user2');
annotate_port('external_state_machine/uz_debug_switch_measurements/Delay25', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_debug_switch_measurements/Delay26', 'user2');
annotate_port('gm_external_state_machine/uz_debug_switch_measurements/Delay26', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/uz_debug_switch_measurements/Delay26', 'user2');
annotate_port('external_state_machine/uz_debug_switch_measurements/Delay26', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_debug_switch_measurements/Delay27', 'user2');
annotate_port('gm_external_state_machine/uz_debug_switch_measurements/Delay27', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/uz_debug_switch_measurements/Delay27', 'user2');
annotate_port('external_state_machine/uz_debug_switch_measurements/Delay27', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_debug_switch_measurements/Delay28', 'user2');
annotate_port('gm_external_state_machine/uz_debug_switch_measurements/Delay28', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/uz_debug_switch_measurements/Delay28', 'user2');
annotate_port('external_state_machine/uz_debug_switch_measurements/Delay28', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_debug_switch_measurements/Delay29', 'user2');
annotate_port('gm_external_state_machine/uz_debug_switch_measurements/Delay29', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/uz_debug_switch_measurements/Delay29', 'user2');
annotate_port('external_state_machine/uz_debug_switch_measurements/Delay29', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_debug_switch_measurements/Delay3', 'user2');
annotate_port('gm_external_state_machine/uz_debug_switch_measurements/Delay3', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/uz_debug_switch_measurements/Delay3', 'user2');
annotate_port('external_state_machine/uz_debug_switch_measurements/Delay3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_debug_switch_measurements/Delay4', 'user2');
annotate_port('gm_external_state_machine/uz_debug_switch_measurements/Delay4', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/uz_debug_switch_measurements/Delay4', 'user2');
annotate_port('external_state_machine/uz_debug_switch_measurements/Delay4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_debug_switch_measurements/Delay5', 'user2');
annotate_port('gm_external_state_machine/uz_debug_switch_measurements/Delay5', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/uz_debug_switch_measurements/Delay5', 'user2');
annotate_port('external_state_machine/uz_debug_switch_measurements/Delay5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_debug_switch_measurements/Delay6', 'user2');
annotate_port('gm_external_state_machine/uz_debug_switch_measurements/Delay6', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/uz_debug_switch_measurements/Delay6', 'user2');
annotate_port('external_state_machine/uz_debug_switch_measurements/Delay6', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_debug_switch_measurements/Delay7', 'user2');
annotate_port('gm_external_state_machine/uz_debug_switch_measurements/Delay7', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/uz_debug_switch_measurements/Delay7', 'user2');
annotate_port('external_state_machine/uz_debug_switch_measurements/Delay7', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_debug_switch_measurements/Delay8', 'user2');
annotate_port('gm_external_state_machine/uz_debug_switch_measurements/Delay8', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/uz_debug_switch_measurements/Delay8', 'user2');
annotate_port('external_state_machine/uz_debug_switch_measurements/Delay8', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_debug_switch_measurements/Delay9', 'user2');
annotate_port('gm_external_state_machine/uz_debug_switch_measurements/Delay9', 1, 1, 'Block not characterized');
hilite_system('external_state_machine/uz_debug_switch_measurements/Delay9', 'user2');
annotate_port('external_state_machine/uz_debug_switch_measurements/Delay9', 1, 1, 'Block not characterized');
