open_system('external_state_machine');
open_system('gm_external_state_machine');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_park_transformation/Sine HDL Optimized/Look-Up Table', 'user1');
annotate_port('gm_external_state_machine/uz_park_transformation/Sine HDL Optimized/Look-Up Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('external_state_machine/uz_park_transformation/Sine HDL Optimized/sincos hdl/cos_hdl/Look-Up Table', 'user1');
annotate_port('external_state_machine/uz_park_transformation/Sine HDL Optimized/sincos hdl/cos_hdl/Look-Up Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_external_state_machine/uz_park_transformation/Sine HDL Optimized/Look-Up Table1', 'user1');
annotate_port('gm_external_state_machine/uz_park_transformation/Sine HDL Optimized/Look-Up Table1', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('external_state_machine/uz_park_transformation/Sine HDL Optimized/sincos hdl/sin_hdl/Look-Up Table', 'user1');
annotate_port('external_state_machine/uz_park_transformation/Sine HDL Optimized/sincos hdl/sin_hdl/Look-Up Table', 0, 1, 'Lookup Table mapped to RAM');
