SLStudio.Utils.RemoveHighlighting(get_param('Encoder_Zynq', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_Encoder_Zynq', 'handle'));
annotate_port('gm_Encoder_Zynq/IncreEncoder_V22/Check_Direction', 0, 1, '');
annotate_port('Encoder_Zynq/IncreEncoder_V22/Check_Direction', 0, 1, '');
annotate_port('gm_Encoder_Zynq/IncreEncoder_V22/Counter_theta', 0, 1, '');
annotate_port('Encoder_Zynq/IncreEncoder_V22/Counter_theta', 0, 1, '');
annotate_port('gm_Encoder_Zynq/IncreEncoder_V22/Counter_theta_ele', 0, 1, '');
annotate_port('Encoder_Zynq/IncreEncoder_V22/Counter_theta_ele', 0, 1, '');
annotate_port('gm_Encoder_Zynq/IncreEncoder_V22/omega_by_count_lines', 0, 1, '');
annotate_port('Encoder_Zynq/IncreEncoder_V22/omega_by_count_lines', 0, 1, '');
annotate_port('gm_Encoder_Zynq/IncreEncoder_V22/C_1//rps->1//omega', 0, 1, '');
annotate_port('Encoder_Zynq/IncreEncoder_V22/C_1//rps->1//omega', 0, 1, '');
annotate_port('gm_Encoder_Zynq/IncreEncoder_V22/Constant', 0, 1, '');
annotate_port('Encoder_Zynq/IncreEncoder_V22/Constant', 0, 1, '');
annotate_port('gm_Encoder_Zynq/IncreEncoder_V22/HDL Reciprocal', 0, 1, '');
annotate_port('gm_Encoder_Zynq/IncreEncoder_V22/HDL Reciprocal', 0, 1, '');
annotate_port('Encoder_Zynq/IncreEncoder_V22/HDL Reciprocal', 0, 1, '');
annotate_port('gm_Encoder_Zynq/IncreEncoder_V22/HDL Reciprocal', 1, 1, '');
annotate_port('Encoder_Zynq/IncreEncoder_V22/HDL Reciprocal', 1, 1, '');
annotate_port('gm_Encoder_Zynq/IncreEncoder_V22/Logical2', 0, 1, '');
annotate_port('Encoder_Zynq/IncreEncoder_V22/Logical2', 0, 1, '');
annotate_port('gm_Encoder_Zynq/IncreEncoder_V22/Mul_rps_omega_out_dtc', 0, 1, '');
annotate_port('gm_Encoder_Zynq/IncreEncoder_V22/Mul_rps_omega', 0, 1, '');
annotate_port('gm_Encoder_Zynq/IncreEncoder_V22/omega_by_measure_time', 0, 1, '');
annotate_port('gm_Encoder_Zynq/IncreEncoder_V22/Data Type Conversion2', 0, 1, '');
annotate_port('gm_Encoder_Zynq/IncreEncoder_V22/rd_11', 1, 1, '');
annotate_port('gm_Encoder_Zynq/IncreEncoder_V22/Product_theta_el', 0, 1, '');
annotate_port('Encoder_Zynq/IncreEncoder_V22/Product_theta_el', 0, 1, '');
annotate_port('Encoder_Zynq/IncreEncoder_V22/Product_theta_mech', 0, 1, '');
annotate_port('gm_Encoder_Zynq/IncreEncoder_V22/Average/Add', 1, 1, '');
annotate_port('Encoder_Zynq/IncreEncoder_V22/Average/Add', 1, 1, '');
annotate_port('gm_Encoder_Zynq/IncreEncoder_V22/omega_by_measure_time/count_old1', 0, 1, '');
annotate_port('gm_Encoder_Zynq/IncreEncoder_V22/omega_by_measure_time/ProtectOverflow_rps', 0, 1, '');
annotate_port('gm_Encoder_Zynq/IncreEncoder_V22/omega_by_measure_time/ProtectToUseOmegaIfThetaJump1', 0, 1, '');
annotate_port('gm_Encoder_Zynq/IncreEncoder_V22/omega_by_measure_time/T_count_switch', 0, 1, '');
