open_system('Encoder_Zynq');
open_system('gm_Encoder_Zynq');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Encoder_Zynq/IncreEncoder_V22/Check_Direction', 'user1');
annotate_port('gm_Encoder_Zynq/IncreEncoder_V22/Check_Direction', 0, 1, 'Potential numerical mismatch');
hilite_system('Encoder_Zynq/IncreEncoder_V22/Check_Direction', 'user1');
annotate_port('Encoder_Zynq/IncreEncoder_V22/Check_Direction', 0, 1, 'Potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Encoder_Zynq/IncreEncoder_V22/Counter_theta', 'user1');
annotate_port('gm_Encoder_Zynq/IncreEncoder_V22/Counter_theta', 0, 1, 'Potential numerical mismatch');
hilite_system('Encoder_Zynq/IncreEncoder_V22/Counter_theta', 'user1');
annotate_port('Encoder_Zynq/IncreEncoder_V22/Counter_theta', 0, 1, 'Potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Encoder_Zynq/IncreEncoder_V22/Counter_theta_ele', 'user1');
annotate_port('gm_Encoder_Zynq/IncreEncoder_V22/Counter_theta_ele', 0, 1, 'Potential numerical mismatch');
hilite_system('Encoder_Zynq/IncreEncoder_V22/Counter_theta_ele', 'user1');
annotate_port('Encoder_Zynq/IncreEncoder_V22/Counter_theta_ele', 0, 1, 'Potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Encoder_Zynq/IncreEncoder_V22/omega_by_count_lines', 'user1');
annotate_port('gm_Encoder_Zynq/IncreEncoder_V22/omega_by_count_lines', 0, 1, 'Potential numerical mismatch');
hilite_system('Encoder_Zynq/IncreEncoder_V22/omega_by_count_lines', 'user1');
annotate_port('Encoder_Zynq/IncreEncoder_V22/omega_by_count_lines', 0, 1, 'Potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Encoder_Zynq/IncreEncoder_V22/C_1//rps->1//omega', 'user1');
annotate_port('gm_Encoder_Zynq/IncreEncoder_V22/C_1//rps->1//omega', 0, 1, 'Potential numerical mismatch');
hilite_system('Encoder_Zynq/IncreEncoder_V22/C_1//rps->1//omega', 'user1');
annotate_port('Encoder_Zynq/IncreEncoder_V22/C_1//rps->1//omega', 0, 1, 'Potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Encoder_Zynq/IncreEncoder_V22/Constant', 'user1');
annotate_port('gm_Encoder_Zynq/IncreEncoder_V22/Constant', 0, 1, 'Potential numerical mismatch');
hilite_system('Encoder_Zynq/IncreEncoder_V22/Constant', 'user1');
annotate_port('Encoder_Zynq/IncreEncoder_V22/Constant', 0, 1, 'Potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Encoder_Zynq/IncreEncoder_V22/HDL Reciprocal', 'user1');
annotate_port('gm_Encoder_Zynq/IncreEncoder_V22/HDL Reciprocal', 0, 1, 'Potential numerical mismatch');
hilite_system('Encoder_Zynq/IncreEncoder_V22/HDL Reciprocal', 'user1');
annotate_port('Encoder_Zynq/IncreEncoder_V22/HDL Reciprocal', 0, 1, 'Potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Encoder_Zynq/IncreEncoder_V22/Logical2', 'user1');
annotate_port('gm_Encoder_Zynq/IncreEncoder_V22/Logical2', 0, 1, 'Potential numerical mismatch');
hilite_system('Encoder_Zynq/IncreEncoder_V22/Logical2', 'user1');
annotate_port('Encoder_Zynq/IncreEncoder_V22/Logical2', 0, 1, 'Potential numerical mismatch');
