open_system('gm_Encoder_Zynq');
open_system('Encoder_Zynq');
clearhighlighting;
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Encoder_Zynq/IncreEncoder_V22/Product_theta_el', 'user1');
annotate_port('gm_Encoder_Zynq/IncreEncoder_V22/Product_theta_el', 0, 1, 'Sharing Group 1');
hilite_system('Encoder_Zynq/IncreEncoder_V22/Product_theta_el', 'user1');
annotate_port('Encoder_Zynq/IncreEncoder_V22/Product_theta_el', 0, 1, 'Sharing Group 1');
hilite_system('Encoder_Zynq/IncreEncoder_V22/Product_theta_mech', 'user1');
annotate_port('Encoder_Zynq/IncreEncoder_V22/Product_theta_mech', 0, 1, 'Sharing Group 1');
