#ifndef UZ_INVERTER_ADAPTER_HW_H
#define UZ_INVERTER_ADAPTER_HW_H
#include <stdint.h>

uint32_t uz_inverter_adapter_get_PWMFreqTicks_H1(uint32_t base_address);
uint32_t uz_inverter_adapter_get_PWMhightimeTicks_H1(uint32_t base_address);
uint32_t uz_inverter_adapter_get_PWMlowtimeTicks_H1(uint32_t base_address);
float uz_inverter_adapter_get_PWMdutyCycNormalized_H1(uint32_t base_address);
uint32_t uz_inverter_adapter_get_PWMFreqTicks_L1(uint32_t base_address);
uint32_t uz_inverter_adapter_get_PWMhightimeTicks_L1(uint32_t base_address);
uint32_t uz_inverter_adapter_get_PWMlowtimeTicks_L1(uint32_t base_address);
float uz_inverter_adapter_get_PWMdutyCycNormalized_L1(uint32_t base_address);
uint32_t uz_inverter_adapter_get_PWMFreqTicks_H2(uint32_t base_address);
uint32_t uz_inverter_adapter_get_PWMhightimeTicks_H2(uint32_t base_address);
uint32_t uz_inverter_adapter_get_PWMlowtimeTicks_H2(uint32_t base_address);
float uz_inverter_adapter_get_PWMdutyCycNormalized_H2(uint32_t base_address);
uint32_t uz_inverter_adapter_get_PWMFreqTicks_L2(uint32_t base_address);
uint32_t uz_inverter_adapter_get_PWMhightimeTicks_L2(uint32_t base_address);
uint32_t uz_inverter_adapter_get_PWMlowtimeTicks_L2(uint32_t base_address);
float uz_inverter_adapter_get_PWMdutyCycNormalized_L2(uint32_t base_address);
uint32_t uz_inverter_adapter_get_PWMFreqTicks_H3(uint32_t base_address);
uint32_t uz_inverter_adapter_get_PWMhightimeTicks_H3(uint32_t base_address);
uint32_t uz_inverter_adapter_get_PWMlowtimeTicks_H3(uint32_t base_address);
float uz_inverter_adapter_get_PWMdutyCycNormalized_H3(uint32_t base_address);
uint32_t uz_inverter_adapter_get_PWMFreqTicks_L3(uint32_t base_address);
uint32_t uz_inverter_adapter_get_PWMhightimeTicks_L3(uint32_t base_address);
uint32_t uz_inverter_adapter_get_PWMlowtimeTicks_L3(uint32_t base_address);
float uz_inverter_adapter_get_PWMdutyCycNormalized_L3(uint32_t base_address);
uint32_t uz_inverter_adapter_get_OC(uint32_t base_address);
uint32_t uz_inverter_adapter_get_FAULT(uint32_t base_address);
uint32_t uz_inverter_adapter_get_I_DIAG(uint32_t base_address);
void uz_inverter_adapter_hw_set_PWM_EN(uint32_t base_address, uint32_t PWM_on_off);


#endif // UZ_INVERTER_ADAPTER_HW_H
