open_system('uz_pmsm_model_9ph_21b_all_double');
open_system('gm_uz_pmsm_model_9ph_21b_all_double');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/Delay', 'user2');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/Delay', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/Delay', 'user2');
annotate_port('uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/Delay', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/Delay1', 'user2');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/Delay1', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/Delay1', 'user2');
annotate_port('uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/Delay1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/Delay2', 'user2');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/Delay2', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/Delay2', 'user2');
annotate_port('uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/Delay2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/Delay3', 'user2');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/Delay3', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/Delay3', 'user2');
annotate_port('uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/Delay3', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/Unit Delay', 'user2');
annotate_port('gm_uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/Unit Delay', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/Unit Delay', 'user2');
annotate_port('uz_pmsm_model_9ph_21b_all_double/uz_pmsm_model_9ph/Unit Delay', 1, 1, 'Obstacle to clock-rate pipelining');
