open_system('gm_uz_mpc_delay_comp');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Detect Rise Positive', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Detect Rise Positive', 0, 1, 'cp : 1.374 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/delay_compensation', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/delay_compensation', 1, 1, 'cp : 1.726 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay', 'user1');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/From7', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/From7', 0, 1, 'cp : 1.726 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Goto5', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Goto5', 0, 1, 'cp : 1.726 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Switch28', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Switch28', 0, 1, 'cp : 1.726 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Detect Rise Positive/FixPt Relational Operator', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Detect Rise Positive/FixPt Relational Operator', 0, 1, 'cp : 1.374 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Detect Rise Positive/Positive', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Detect Rise Positive/Positive', 0, 1, 'cp : 0.687 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/delay_compensation/delay_compensation', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/delay_compensation/delay_compensation', 1, 1, 'cp : 1.726 ns');
