open_system('uz_mpc_delay_comp');
open_system('gm_uz_mpc_delay_comp');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Detect Rise Positive', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Detect Rise Positive', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Detect Rise Positive', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Detect Rise Positive', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay1', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay1', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay1', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay10', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay10', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay10', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay10', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay11', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay11', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay11', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay11', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay12', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay12', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay12', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay12', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay13', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay13', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay13', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay13', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay14', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay14', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay14', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay14', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay15', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay15', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay15', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay15', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay16', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay16', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay16', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay16', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay17', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay17', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay17', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay17', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay2', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay2', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay2', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay25', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay25', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay25', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay25', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay26', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay26', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay26', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay26', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay27', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay27', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay27', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay27', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay28', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay28', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay28', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay28', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay29', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay29', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay29', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay29', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay3', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay3', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay3', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay30', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay30', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay30', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay30', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay31', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay31', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay31', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay31', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay32', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay32', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay32', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay32', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay33', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay33', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay33', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay33', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay34', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay34', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay34', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay34', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay35', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay35', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay35', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay35', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay36', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay36', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay36', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay36', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay37', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay37', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay37', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay37', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay38', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay38', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay38', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay38', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay39', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay39', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay39', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay39', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay4', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay4', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay4', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay40', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay40', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay40', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay40', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay43', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay43', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay43', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay43', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay44', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay44', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay44', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay44', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay5', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay5', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay5', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay57', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay57', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay57', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay57', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay58', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay58', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay58', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay58', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay59', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay59', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay59', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay59', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay6', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay6', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay6', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay6', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay60', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay60', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay60', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay60', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay62', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay62', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay62', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay62', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay63', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay63', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay63', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay63', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay64', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay64', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay64', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay64', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay65', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay65', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay65', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay65', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay7', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay7', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay7', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay7', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay70', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay70', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay70', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay70', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay71', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay71', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay71', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay71', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay72', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay72', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay72', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay72', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay73', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay73', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay73', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay73', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay75', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay75', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay75', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay75', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay8', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay8', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay8', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay8', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay9', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay9', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/Delay9', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/Delay9', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay10_ctrl_delay', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay10_ctrl_delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/Delay75_ctrl_delay', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/Delay75_ctrl_delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/delay_compensation/delay_compensation', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/delay_compensation/delay_compensation', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_mpc_delay_comp/delay_comp/delay_compensation/delay_compensation', 'user2');
annotate_port('gm_uz_mpc_delay_comp/delay_comp/delay_compensation/delay_compensation', 1, 1, 'Block not characterized');
hilite_system('uz_mpc_delay_comp/delay_comp/delay_compensation', 'user2');
annotate_port('uz_mpc_delay_comp/delay_comp/delay_compensation', 1, 1, 'Block not characterized');
