SLStudio.Utils.RemoveHighlighting(get_param('FCS_MPC_3Phase_SPMSM_V1', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_FCS_MPC_3Phase_SPMSM_V1', 'handle'));
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/Detect Rise Positive', 1, 1, '');
annotate_port('FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/Detect Rise Positive', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/Data Type Conversion3', 1, 1, '');
annotate_port('FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/Data Type Conversion3', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/Data Type Conversion4', 1, 1, '');
annotate_port('FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/Data Type Conversion4', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/Data Type Conversion12', 1, 1, '');
annotate_port('FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/Data Type Conversion12', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/Data Type Conversion2', 1, 1, '');
annotate_port('FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/Data Type Conversion2', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/Data Type Conversion1', 1, 1, '');
annotate_port('FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/Data Type Conversion1', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/t1', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/Detect Rise Positive/t', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function/Assignment', 1, 1, '');
annotate_port('FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function/gain', 1, 1, '');
annotate_port('FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function/Assignment1', 1, 1, '');
annotate_port('FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function/Assignment2', 1, 1, '');
annotate_port('FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function/Assignment3', 1, 1, '');
annotate_port('FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function/Assignment4', 1, 1, '');
annotate_port('FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function/Assignment5', 1, 1, '');
annotate_port('FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function/Assignment6', 1, 1, '');
annotate_port('FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function/Assignment7', 1, 1, '');
annotate_port('FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function/t', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function/t1', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1/switch', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1/switch1', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1/Assignment', 1, 1, '');
annotate_port('FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1/switch2', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1/Assignment1', 1, 1, '');
annotate_port('FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1', 1, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1/switch4', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1/switch6', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1/switch8', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1/switch10', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1/relop6', 0, 1, '');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1/relop_outbuff5', 0, 1, '');
