open_system('gm_FCS_MPC_3Phase_SPMSM_V1');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1', 'user2');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1', 0, 1, 'cp : 4.227 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/t1', 'user1');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/t1', 1, 1, 'cp : 4.488 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1/switch', 'user2');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1/switch', 0, 1, 'cp : 4.227 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1/switch1', 'user2');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1/switch1', 0, 1, 'cp : 3.837 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1/switch2', 'user2');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1/switch2', 0, 1, 'cp : 3.447 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1/switch4', 'user2');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1/switch4', 0, 1, 'cp : 3.057 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1/switch6', 'user2');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1/switch6', 0, 1, 'cp : 2.667 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1/switch8', 'user2');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1/switch8', 0, 1, 'cp : 2.277 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1/switch10', 'user2');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1/switch10', 0, 1, 'cp : 1.887 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1/relop6', 'user1');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1/relop6', 0, 1, 'cp : 1.535 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1/relop_outbuff5', 'user2');
annotate_port('gm_FCS_MPC_3Phase_SPMSM_V1/Microcontroller Software/Subsystem1/MATLAB Function1/relop_outbuff5', 0, 1, 'cp : 1.535 ns');
