SLStudio.Utils.RemoveHighlighting(get_param('UZ_D_GaN_Inverter', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_UZ_D_GaN_Inverter', 'handle'));
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection_instance1', 0, 1, '');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Delay', 1, 1, '');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Delay', 1, 1, '');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Delay1', 1, 1, '');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Delay1', 1, 1, '');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Delay2', 1, 1, '');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Delay2', 1, 1, '');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Delay3', 1, 1, '');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Delay3', 1, 1, '');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Delay4', 1, 1, '');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Delay4', 1, 1, '');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/delayMatch', 1, 1, '');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/delayMatch', 1, 1, '');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/delayMatch', 1, 1, '');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/delayMatch', 1, 1, '');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection/Detect Rise Positive', 1, 1, '');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection/Detect Fall Nonpositive', 1, 1, '');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection/Delay17', 1, 1, '');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection/Delay18', 1, 1, '');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection/Delay4', 1, 1, '');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection/Delay19', 1, 1, '');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection/Delay3', 1, 1, '');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection/Delay2', 1, 1, '');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection/Delay5', 1, 1, '');
