open_system('gm_UZ_D_GaN_Inverter');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection_instance1', 'user2');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection_instance1', 0, 1, 'cp : 2.761 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection_instance1/Detect Rise Positive1', 'user2');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection_instance1/Detect Rise Positive1', 0, 1, 'cp : 1.374 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection_instance1/HDL Counter1', 'user1');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection_instance1/HDL Counter1', 1, 1, 'cp : 2.761 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection_instance1/Delay15', 'user1');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection_instance1/Delay15', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection_instance1/Logical Operator3', 'user2');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection_instance1/Logical Operator3', 0, 1, 'cp : 2.367 ns');
