open_system('UZ_D_GaN_Inverter');
open_system('gm_UZ_D_GaN_Inverter');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Delay', 'user2');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Delay', 1, 1, 'Block not characterized');
hilite_system('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Delay', 'user2');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Delay1', 'user2');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Delay1', 1, 1, 'Block not characterized');
hilite_system('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Delay1', 'user2');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Delay1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Delay2', 'user2');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Delay2', 1, 1, 'Block not characterized');
hilite_system('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Delay2', 'user2');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Delay2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Delay3', 'user2');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Delay3', 1, 1, 'Block not characterized');
hilite_system('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Delay3', 'user2');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Delay3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Delay4', 'user2');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Delay4', 1, 1, 'Block not characterized');
hilite_system('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Delay4', 'user2');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/Delay4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/delayMatch', 'user2');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/delayMatch', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/delayMatch', 'user2');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/delayMatch', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/delayMatch', 'user2');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/delayMatch', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/delayMatch', 'user2');
annotate_port('gm_UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/delayMatch', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection/Detect Rise Positive', 'user2');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection/Detect Rise Positive', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection/Detect Fall Nonpositive', 'user2');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection/Detect Fall Nonpositive', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection/Delay17', 'user2');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection/Delay17', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection/Delay18', 'user2');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection/Delay18', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection/Delay4', 'user2');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection/Delay4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection/Delay19', 'user2');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection/Delay19', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection/Delay3', 'user2');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection/Delay3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection/Delay2', 'user2');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection/Delay2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection/Delay5', 'user2');
annotate_port('UZ_D_GaN_Inverter/UZ_D_GaN_Inverter/PWMdutyFreqDetection/Delay5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
