vlib work
vcom  UZ_D_GaN_Inverter_src_UZ_D_GaN_Inverter_pkg.vhd
vcom  UZ_D_GaN_Inverter_src_Detect_Rise_Positive1.vhd
vcom  UZ_D_GaN_Inverter_src_Detect_Fall_Nonpositive1.vhd
vcom  UZ_D_GaN_Inverter_src_PWMdutyFreqDetection.vhd
vcom  UZ_D_GaN_Inverter_src_UZ_D_GaN_Inverter.vhd
