-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\ELSYS_PC\Documents\repos\ultrazohm_sw\ip_cores\uz_EnDat_IPCore\hdl_prj\hdlsrc\UZ_EnDat\uz_EnDat_src_CLKCNTER_ACT.vhd
-- Created: 2024-02-08 19:08:16
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: uz_EnDat_src_CLKCNTER_ACT
-- Source Path: UZ_EnDat/UZ_ENDAT/CLKCNTER_ACT
-- Hierarchy Level: 2
-- Model version: 2.642
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY uz_EnDat_src_CLKCNTER_ACT IS
  PORT( clk                               :   IN    std_logic;
        reset_x                           :   IN    std_logic;
        enb                               :   IN    std_logic;
        CLK_1                             :   IN    std_logic;
        CLK2CNT                           :   IN    std_logic;
        ResetCNT                          :   IN    std_logic;
        CNT                               :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END uz_EnDat_src_CLKCNTER_ACT;


ARCHITECTURE rtl OF uz_EnDat_src_CLKCNTER_ACT IS

  -- Component Declarations
  COMPONENT uz_EnDat_src_Positional_Counter_block
    PORT( clk                             :   IN    std_logic;
          reset_x                         :   IN    std_logic;
          enb                             :   IN    std_logic;
          valueout                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          Trigger                         :   IN    std_logic;
          divider                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
          );
  END COMPONENT;

  COMPONENT uz_EnDat_src_SetZero32modified
    PORT( clk                             :   IN    std_logic;
          reset_x                         :   IN    std_logic;
          enb                             :   IN    std_logic;
          valin                           :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          setzero                         :   IN    std_logic;
          Trigger                         :   IN    std_logic;
          valueout                        :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : uz_EnDat_src_Positional_Counter_block
    USE ENTITY work.uz_EnDat_src_Positional_Counter_block(rtl);

  FOR ALL : uz_EnDat_src_SetZero32modified
    USE ENTITY work.uz_EnDat_src_SetZero32modified(rtl);

  -- Signals
  SIGNAL stateControl_1                   : std_logic;
  SIGNAL rd_1_reg                         : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL stateControl_2                   : std_logic;
  SIGNAL rd_0_reg                         : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL CLK_2                            : std_logic;
  SIGNAL SetZero32modified_out1           : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Positional_Counter_out1          : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL SetZero32modified_out1_1         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL SetZero32modified_out1_unsigned  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL SetZero32modified_out1_2         : unsigned(31 DOWNTO 0);  -- uint32

BEGIN
  u_Positional_Counter : uz_EnDat_src_Positional_Counter_block
    PORT MAP( clk => clk,
              reset_x => reset_x,
              enb => enb,
              valueout => std_logic_vector(SetZero32modified_out1),  -- uint32
              Trigger => CLK2CNT,
              divider => Positional_Counter_out1  -- uint32
              );

  u_SetZero32modified : uz_EnDat_src_SetZero32modified
    PORT MAP( clk => clk,
              reset_x => reset_x,
              enb => enb,
              valin => Positional_Counter_out1,  -- uint32
              setzero => ResetCNT,
              Trigger => CLK_2,
              valueout => SetZero32modified_out1_1  -- uint32
              );

  stateControl_1 <= '1';

  rd_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        rd_1_reg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        rd_1_reg(0) <= stateControl_1;
        rd_1_reg(1) <= rd_1_reg(0);
      END IF;
    END IF;
  END PROCESS rd_1_process;

  stateControl_2 <= rd_1_reg(1);

  rd_0_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        rd_0_reg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        rd_0_reg(0) <= CLK_1;
        rd_0_reg(1) <= rd_0_reg(0);
      END IF;
    END IF;
  END PROCESS rd_0_process;

  CLK_2 <= rd_0_reg(1);

  SetZero32modified_out1_unsigned <= unsigned(SetZero32modified_out1_1);

  
  SetZero32modified_out1_2 <= SetZero32modified_out1 WHEN stateControl_2 = '0' ELSE
      SetZero32modified_out1_unsigned;

  rd_2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        SetZero32modified_out1 <= to_unsigned(0, 32);
      ELSIF enb = '1' THEN
        SetZero32modified_out1 <= SetZero32modified_out1_2;
      END IF;
    END IF;
  END PROCESS rd_2_process;


  CNT <= std_logic_vector(SetZero32modified_out1);

END rtl;

