open_system('uz_pmsm_model_6ph_dq');
open_system('gm_uz_pmsm_model_6ph_dq');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion14', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion14', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion14', 'user2');
annotate_port('uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion14', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion3', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion3', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion3', 'user2');
annotate_port('uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion3', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion11', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion11', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion11', 'user2');
annotate_port('uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion11', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion4', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion4', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion4', 'user2');
annotate_port('uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion4', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion12', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion12', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion12', 'user2');
annotate_port('uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion12', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion5', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion5', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion5', 'user2');
annotate_port('uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion5', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion2', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion2', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion2', 'user2');
annotate_port('uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion2', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion7', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion7', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion7', 'user2');
annotate_port('uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion7', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Compare To Constant1_relop', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Compare To Constant1_relop', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Compare To Constant_relop', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Compare To Constant_relop', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion13', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion13', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion13', 'user2');
annotate_port('uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion13', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion6', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion6', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion6', 'user2');
annotate_port('uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion6', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion51', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion51', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion9', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion9', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion8', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion8', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion8', 'user2');
annotate_port('uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion8', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion21', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion21', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion1', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion1', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion1', 'user2');
annotate_port('uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion1', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion41', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion41', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion71', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion71', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion31', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion31', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion81', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion81', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion61', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion61', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion10', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion10', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion10', 'user2');
annotate_port('uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion10', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion15', 'user2');
annotate_port('gm_uz_pmsm_model_6ph_dq/uz_pmsm_model_9ph_dq/Data Type Conversion15', 1, 1, 'Block not characterized for this configuration');
