SLStudio.Utils.RemoveHighlighting(get_param('uz_ninephase_VSD_transformation', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_uz_ninephase_VSD_transformation', 'handle'));
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Unit Delay', 1, 1, '');
annotate_port('uz_ninephase_VSD_transformation/abc_to_dq/Unit Delay', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized', 0, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/t', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/t', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/vectorized_in0', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Row2Col_in0', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Row2Col_in1', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/reshape_dotProduct', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/reshape_mmulResult', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/t', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/vectorized_in0', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Row2Col_in0', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Row2Col_in1', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/reshape_dotProduct', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/reshape_mmulResult', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/t', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/vectorized_in0', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Row2Col_in0', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Row2Col_in1', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/reshape_dotProduct', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/reshape_mmulResult', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/t', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/vectorized_in0', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Row2Col_in0', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Row2Col_in1', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/reshape_dotProduct', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/reshape_mmulResult', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/t', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/vectorized_in0', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Row2Col_in0', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Row2Col_in1', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/reshape_dotProduct', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/reshape_mmulResult', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/t', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/vectorized_in0', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Row2Col_in0', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Row2Col_in1', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/reshape_dotProduct', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/reshape_mmulResult', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/t', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/t', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/t', 1, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/Point50', 0, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/Look-Up Table', 0, 1, '');
annotate_port('uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/sincos hdl/cos_hdl/Look-Up Table', 0, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/CastU16En2', 0, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/CastU16En3', 0, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/CastU16En4', 0, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/LTEp25', 0, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/LTEp50', 0, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/Look-Up Table', 0, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/Look-Up Table', 0, 1, '');
annotate_port('uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/sincos hdl/sin_hdl/Look-Up Table', 0, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/QuadHandle1', 0, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/QuadHandle2', 0, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/Saturation', 0, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/Switch', 0, 1, '');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/PipelineRegister', 1, 1, '');
