open_system('gm_uz_ninephase_VSD_transformation');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized', 'user2');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized', 0, 1, 'cp : 6.303 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/Point50', 'user1');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/Point50', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/CastU16En2', 'user2');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/CastU16En2', 0, 1, 'cp : 2.395 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/CastU16En3', 'user2');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/CastU16En3', 0, 1, 'cp : 3.283 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/CastU16En4', 'user2');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/CastU16En4', 0, 1, 'cp : 2.395 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/LTEp25', 'user2');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/LTEp25', 0, 1, 'cp : 2.043 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/LTEp50', 'user2');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/LTEp50', 0, 1, 'cp : 0.85 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/Look-Up Table', 'user2');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/Look-Up Table', 0, 1, 'cp : 6.042 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/QuadHandle1', 'user2');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/QuadHandle1', 0, 1, 'cp : 1.202 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/QuadHandle2', 'user2');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/QuadHandle2', 0, 1, 'cp : 2.395 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/Saturation', 'user2');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/Saturation', 0, 1, 'cp : 4.501 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/Switch', 'user2');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/Switch', 0, 1, 'cp : 4.785 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/PipelineRegister', 'user1');
annotate_port('gm_uz_ninephase_VSD_transformation/abc_to_dq/Sine HDL Optimized/PipelineRegister', 1, 1, 'cp : 6.303 ns');
