SLStudio.Utils.RemoveHighlighting(get_param('uz_pmsm_model_9ph', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_uz_pmsm_model_9ph', 'handle'));
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay', 1, 1, '');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay1', 1, 1, '');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay1', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay2', 1, 1, '');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay2', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay3', 1, 1, '');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay3', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion11', 1, 1, '');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion11', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion5', 1, 1, '');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion5', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion33', 1, 1, '');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion33', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion21', 1, 1, '');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion21', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion3', 1, 1, '');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion3', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion22', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion12', 1, 1, '');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion12', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion31', 1, 1, '');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion31', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion23', 1, 1, '');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion23', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion13', 1, 1, '');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion13', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Product6', 0, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion14', 1, 1, '');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion14', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion81', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion331', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion32', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion24', 1, 1, '');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion24', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion141', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion25', 1, 1, '');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion25', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion15', 1, 1, '');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion15', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion26', 1, 1, '');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion26', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion16', 1, 1, '');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion16', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion27', 1, 1, '');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion27', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion17', 1, 1, '');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion17', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion28', 1, 1, '');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion28', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion18', 1, 1, '');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion18', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion29', 1, 1, '');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion29', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion19', 1, 1, '');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion19', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion30', 1, 1, '');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion30', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion20', 1, 1, '');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion20', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/abc   to   alpha_beta_0/vectorized_in0', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/abc   to   alpha_beta_0/Row2Col_in0', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/abc   to   alpha_beta_0/Row2Col_in1', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/abc   to   alpha_beta_0/reshape_dotProduct', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/abc   to   alpha_beta_0/reshape_mmulResult', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/abc   to   alpha_beta_0/t', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/alpha_beta_0   to   abc/vectorized_in0', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/alpha_beta_0   to   abc/Row2Col_in0', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/alpha_beta_0   to   abc/Row2Col_in1', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/alpha_beta_0   to   abc/reshape_dotProduct', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/alpha_beta_0   to   abc/reshape_mmulResult', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/alpha_beta_0   to   abc/t', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/abc   to   alpha_beta_0/vectorized_in0', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/abc   to   alpha_beta_0/Row2Col_in0', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/abc   to   alpha_beta_0/Row2Col_in1', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/abc   to   alpha_beta_0/reshape_dotProduct', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/abc   to   alpha_beta_0/reshape_mmulResult', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/abc   to   alpha_beta_0/t', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/alpha_beta_0   to   abc/vectorized_in0', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/alpha_beta_0   to   abc/Row2Col_in0', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/alpha_beta_0   to   abc/Row2Col_in1', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/alpha_beta_0   to   abc/reshape_dotProduct', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/alpha_beta_0   to   abc/reshape_mmulResult', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/alpha_beta_0   to   abc/t', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/abc   to   alpha_beta_0/vectorized_in0', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/abc   to   alpha_beta_0/Row2Col_in0', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/abc   to   alpha_beta_0/Row2Col_in1', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/abc   to   alpha_beta_0/reshape_dotProduct', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/abc   to   alpha_beta_0/reshape_mmulResult', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/abc   to   alpha_beta_0/t', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/alpha_beta_0   to   abc/vectorized_in0', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/alpha_beta_0   to   abc/Row2Col_in0', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/alpha_beta_0   to   abc/Row2Col_in1', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/alpha_beta_0   to   abc/reshape_dotProduct', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/alpha_beta_0   to   abc/reshape_mmulResult', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/alpha_beta_0   to   abc/t', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/t1', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/t2', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd1', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd2', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd3', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd4', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd5', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd6', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd7', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd8', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd9', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd10', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd11', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd12', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd13', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd14', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd15', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd16', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd17', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd18', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd19', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd20', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd21', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd22', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd23', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd24', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd25', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd26', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd27', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd28', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd29', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd30', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd31', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd32', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd33', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd34', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd35', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd36', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd37', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd38', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd39', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd40', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd41', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd42', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd43', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd44', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd45', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd46', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd47', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd48', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd49', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd50', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd51', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd52', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd53', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd54', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd55', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd56', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd57', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd58', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd59', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd60', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd61', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd62', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd63', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd64', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd65', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd66', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd67', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd68', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd69', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd70', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd71', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd72', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd73', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd74', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd75', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd76', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd77', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd78', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd79', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd80', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/t1', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/t2', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Wrapped State DTI/Compare To Constant1_relop', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Wrapped State DTI/Compare To Constant_relop', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC/t', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC1/t', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC2/t', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC3/t', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC4/t', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC5/t', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC6/t', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC7/t', 1, 1, '');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC8/t', 1, 1, '');
