open_system('uz_pmsm_model_9ph');
open_system('gm_uz_pmsm_model_9ph');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion11', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion11', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion11', 'user2');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion11', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion5', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion5', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion5', 'user2');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion5', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion33', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion33', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion33', 'user2');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion33', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion21', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion21', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion21', 'user2');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion21', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion3', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion3', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion3', 'user2');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion3', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion22', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion22', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion12', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion12', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion12', 'user2');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion12', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion31', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion31', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion31', 'user2');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion31', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion23', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion23', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion23', 'user2');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion23', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion13', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion13', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion13', 'user2');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion13', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion14', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion14', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion14', 'user2');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion14', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion81', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion81', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion331', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion331', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion32', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion32', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion24', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion24', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion24', 'user2');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion24', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion141', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion141', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion25', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion25', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion25', 'user2');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion25', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion15', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion15', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion15', 'user2');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion15', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion26', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion26', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion26', 'user2');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion26', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion16', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion16', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion16', 'user2');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion16', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion27', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion27', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion27', 'user2');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion27', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion17', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion17', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion17', 'user2');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion17', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion28', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion28', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion28', 'user2');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion28', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion18', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion18', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion18', 'user2');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion18', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion29', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion29', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion29', 'user2');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion29', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion19', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion19', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion19', 'user2');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion19', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion30', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion30', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion30', 'user2');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion30', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion20', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion20', 1, 1, 'Block not characterized for this configuration');
hilite_system('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion20', 'user2');
annotate_port('uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion20', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/abc   to   alpha_beta_0/vectorized_in0', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/abc   to   alpha_beta_0/vectorized_in0', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/abc   to   alpha_beta_0/Row2Col_in0', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/abc   to   alpha_beta_0/Row2Col_in0', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/abc   to   alpha_beta_0/Row2Col_in1', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/abc   to   alpha_beta_0/Row2Col_in1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/abc   to   alpha_beta_0/reshape_dotProduct', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/abc   to   alpha_beta_0/reshape_dotProduct', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/abc   to   alpha_beta_0/reshape_mmulResult', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/abc   to   alpha_beta_0/reshape_mmulResult', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/abc   to   alpha_beta_0/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/abc   to   alpha_beta_0/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/alpha_beta_0   to   abc/vectorized_in0', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/alpha_beta_0   to   abc/vectorized_in0', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/alpha_beta_0   to   abc/Row2Col_in0', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/alpha_beta_0   to   abc/Row2Col_in0', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/alpha_beta_0   to   abc/Row2Col_in1', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/alpha_beta_0   to   abc/Row2Col_in1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/alpha_beta_0   to   abc/reshape_dotProduct', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/alpha_beta_0   to   abc/reshape_dotProduct', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/alpha_beta_0   to   abc/reshape_mmulResult', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/alpha_beta_0   to   abc/reshape_mmulResult', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/alpha_beta_0   to   abc/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage/alpha_beta_0   to   abc/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/abc   to   alpha_beta_0/vectorized_in0', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/abc   to   alpha_beta_0/vectorized_in0', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/abc   to   alpha_beta_0/Row2Col_in0', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/abc   to   alpha_beta_0/Row2Col_in0', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/abc   to   alpha_beta_0/Row2Col_in1', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/abc   to   alpha_beta_0/Row2Col_in1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/abc   to   alpha_beta_0/reshape_dotProduct', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/abc   to   alpha_beta_0/reshape_dotProduct', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/abc   to   alpha_beta_0/reshape_mmulResult', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/abc   to   alpha_beta_0/reshape_mmulResult', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/abc   to   alpha_beta_0/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/abc   to   alpha_beta_0/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/alpha_beta_0   to   abc/vectorized_in0', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/alpha_beta_0   to   abc/vectorized_in0', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/alpha_beta_0   to   abc/Row2Col_in0', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/alpha_beta_0   to   abc/Row2Col_in0', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/alpha_beta_0   to   abc/Row2Col_in1', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/alpha_beta_0   to   abc/Row2Col_in1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/alpha_beta_0   to   abc/reshape_dotProduct', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/alpha_beta_0   to   abc/reshape_dotProduct', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/alpha_beta_0   to   abc/reshape_mmulResult', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/alpha_beta_0   to   abc/reshape_mmulResult', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/alpha_beta_0   to   abc/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage1/alpha_beta_0   to   abc/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/abc   to   alpha_beta_0/vectorized_in0', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/abc   to   alpha_beta_0/vectorized_in0', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/abc   to   alpha_beta_0/Row2Col_in0', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/abc   to   alpha_beta_0/Row2Col_in0', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/abc   to   alpha_beta_0/Row2Col_in1', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/abc   to   alpha_beta_0/Row2Col_in1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/abc   to   alpha_beta_0/reshape_dotProduct', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/abc   to   alpha_beta_0/reshape_dotProduct', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/abc   to   alpha_beta_0/reshape_mmulResult', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/abc   to   alpha_beta_0/reshape_mmulResult', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/abc   to   alpha_beta_0/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/abc   to   alpha_beta_0/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/alpha_beta_0   to   abc/vectorized_in0', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/alpha_beta_0   to   abc/vectorized_in0', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/alpha_beta_0   to   abc/Row2Col_in0', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/alpha_beta_0   to   abc/Row2Col_in0', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/alpha_beta_0   to   abc/Row2Col_in1', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/alpha_beta_0   to   abc/Row2Col_in1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/alpha_beta_0   to   abc/reshape_dotProduct', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/alpha_beta_0   to   abc/reshape_dotProduct', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/alpha_beta_0   to   abc/reshape_mmulResult', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/alpha_beta_0   to   abc/reshape_mmulResult', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/alpha_beta_0   to   abc/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Line-Line to Phase voltage2/alpha_beta_0   to   abc/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/t1', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/t1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/t2', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/t2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd1', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd2', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd3', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd4', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd5', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd6', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd6', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd7', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd7', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd8', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd8', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd9', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd9', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd10', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd10', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd11', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd11', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd12', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd12', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd13', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd13', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd14', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd14', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd15', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd15', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd16', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd16', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd17', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd17', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd18', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd18', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd19', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd19', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd20', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd20', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd21', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd21', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd22', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd22', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd23', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd23', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd24', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd24', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd25', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd25', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd26', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd26', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd27', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd27', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd28', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd28', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd29', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd29', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd30', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd30', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd31', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd31', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd32', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd32', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd33', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd33', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd34', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd34', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd35', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd35', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd36', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd36', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd37', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd37', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd38', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd38', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd39', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd39', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd40', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd40', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd41', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd41', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd42', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd42', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd43', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd43', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd44', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd44', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd45', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd45', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd46', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd46', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd47', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd47', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd48', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd48', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd49', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd49', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd50', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd50', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd51', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd51', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd52', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd52', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd53', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd53', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd54', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd54', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd55', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd55', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd56', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd56', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd57', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd57', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd58', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd58', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd59', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd59', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd60', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd60', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd61', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd61', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd62', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd62', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd63', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd63', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd64', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd64', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd65', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd65', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd66', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd66', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd67', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd67', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd68', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd68', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd69', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd69', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd70', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd70', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd71', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd71', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd72', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd72', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd73', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd73', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd74', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd74', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd75', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd75', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd76', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd76', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd77', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd77', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd78', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd78', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd79', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd79', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd80', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/_adder_MultiplyAdd80', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/t1', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/t1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/t2', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/t2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Wrapped State DTI/Compare To Constant1_relop', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Wrapped State DTI/Compare To Constant1_relop', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Wrapped State DTI/Compare To Constant_relop', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Wrapped State DTI/Compare To Constant_relop', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC1/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC1/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC2/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC2/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC3/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC3/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC4/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC4/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC5/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC5/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC6/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC6/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC7/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC7/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC8/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC8/t', 1, 1, 'Block not characterized');
