open_system('gm_uz_pmsm_model_9ph');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/From11', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/From11', 0, 1, 'cp : 2.506 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Goto10', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Goto10', 0, 1, 'cp : 2.506 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Goto71', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Goto71', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/From8', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/From8', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/reset_in6', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/reset_in6', 0, 1, 'cp : 121.509 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/bus_selector', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/bus_selector', 0, 7, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion1', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion1', 0, 1, 'cp : 2.506 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Divide3', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Divide3', 0, 1, 'cp : 75.696 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Divide3_outbuff', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Divide3_outbuff', 0, 1, 'cp : 75.696 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Sum36', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Sum36', 0, 1, 'cp : 121.119 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Sum3_outbuff6', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Sum3_outbuff6', 0, 1, 'cp : 121.119 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Add1', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Add1', 0, 1, 'cp : 98.393 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Add1_outbuff', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Add1_outbuff', 0, 1, 'cp : 98.393 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Divide2', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Divide2', 0, 1, 'cp : 86.771 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Divide2_outbuff', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Divide2_outbuff', 0, 1, 'cp : 86.771 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Gain6', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Gain6', 0, 1, 'cp : 109.468 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Gain_outbuff6', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Gain_outbuff6', 0, 1, 'cp : 109.468 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay1_toDel2', 'user1');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay1_toDel2', 1, 1, 'cp : 121.509 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/in4_repeat', 'user1');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/in4_repeat', 0, 1, 'cp : 0 ns');
