open_system('uz_pmsm_model_9ph');
open_system('gm_uz_pmsm_model_9ph');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Demux1_out1', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Demux1_out1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Demux1_out2', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Demux1_out2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Demux1_out3', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Demux1_out3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion6_out1', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion6_out1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay1_toDel', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay1_toDel', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay1_toDel1', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay1_toDel1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay1_toDel2', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay1_toDel2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay1_toDel3', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay1_toDel3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay1_toDel4', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay1_toDel4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay1_toDel5', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay1_toDel5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay1_toDel6', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay1_toDel6', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay1_toDel7', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay1_toDel7', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay1_toDel8', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay1_toDel8', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Sum_out1', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Sum_out1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Mux_out1', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Mux_out1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay1_toDel9', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay1_toDel9', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay1_toDel10', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Delay1_toDel10', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion17_out1', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Data Type Conversion17_out1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/t1', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/t1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/t2', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/t2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/t1', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/t1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/t2', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/t2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC/PipelineRegister', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC/PipelineRegister', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC1/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC1/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC1/PipelineRegister', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC1/PipelineRegister', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC2/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC2/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC2/PipelineRegister', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC2/PipelineRegister', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC3/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC3/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC3/PipelineRegister', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC3/PipelineRegister', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC4/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC4/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC4/PipelineRegister', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC4/PipelineRegister', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC5/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC5/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC5/PipelineRegister', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC5/PipelineRegister', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC6/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC6/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC6/PipelineRegister', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC6/PipelineRegister', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC7/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC7/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC7/PipelineRegister', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC7/PipelineRegister', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC8/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC8/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC8/PipelineRegister', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation1/Transformation1_MAC8/PipelineRegister', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC/PipelineRegister', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC/PipelineRegister', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC1/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC1/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC1/PipelineRegister', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC1/PipelineRegister', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC2/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC2/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC2/PipelineRegister', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC2/PipelineRegister', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC3/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC3/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC3/PipelineRegister', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC3/PipelineRegister', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC4/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC4/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC4/PipelineRegister', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC4/PipelineRegister', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC5/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC5/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC5/PipelineRegister', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC5/PipelineRegister', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC6/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC6/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC6/PipelineRegister', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC6/PipelineRegister', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC7/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC7/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC7/PipelineRegister', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC7/PipelineRegister', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC8/t', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC8/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC8/PipelineRegister', 'user2');
annotate_port('gm_uz_pmsm_model_9ph/uz_pmsm_model_9ph/Transformation/Transformation_MAC8/PipelineRegister', 1, 1, 'Block not characterized');
