SLStudio.Utils.RemoveHighlighting(get_param('uz_6ph_pu_vsd_voltages', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_uz_6ph_pu_vsd_voltages', 'handle'));
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Detect Rise Positive', 0, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Detect Rise Positive', 1, 1, '');
annotate_port('uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Detect Rise Positive', 1, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/finite_control_set', 1, 4, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay', 0, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay', 1, 1, '');
annotate_port('uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay', 1, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay1', 1, 1, '');
annotate_port('uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay1', 1, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay10', 1, 1, '');
annotate_port('uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay10', 1, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay11', 1, 1, '');
annotate_port('uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay11', 1, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay12', 1, 1, '');
annotate_port('uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay12', 1, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay13', 1, 1, '');
annotate_port('uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay13', 1, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay14', 1, 1, '');
annotate_port('uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay14', 1, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay15', 1, 1, '');
annotate_port('uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay15', 1, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay16', 1, 1, '');
annotate_port('uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay16', 1, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay17', 1, 1, '');
annotate_port('uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay17', 1, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay18', 1, 1, '');
annotate_port('uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay18', 1, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay19', 1, 1, '');
annotate_port('uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay19', 1, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay2', 1, 1, '');
annotate_port('uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay2', 1, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay20', 1, 1, '');
annotate_port('uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay20', 1, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay3', 1, 1, '');
annotate_port('uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay3', 1, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay4', 1, 1, '');
annotate_port('uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay4', 1, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay5', 1, 1, '');
annotate_port('uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay5', 1, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay56', 1, 1, '');
annotate_port('uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay56', 1, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay6', 1, 1, '');
annotate_port('uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay6', 1, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay7', 1, 1, '');
annotate_port('uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay7', 1, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay8', 1, 1, '');
annotate_port('uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay8', 1, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay9', 1, 1, '');
annotate_port('uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay9', 1, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay14_ctrl_delay', 1, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay16_ctrl_delay', 1, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay8_ctrl_delay', 1, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Switch', 0, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Switch5', 0, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Detect Rise Positive/FixPt Relational Operator', 0, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Detect Rise Positive/Positive', 0, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/finite_control_set/finite_control_set', 1, 4, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/finite_control_set/finite_control_set', 1, 1, '');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/finite_control_set/finite_control_set', 1, 1, '');
annotate_port('uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/finite_control_set', 1, 1, '');
