open_system('gm_uz_6ph_pu_vsd_voltages');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Detect Rise Positive', 'user2');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Detect Rise Positive', 0, 1, 'cp : 1.374 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/finite_control_set', 'user2');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/finite_control_set', 1, 4, 'cp : 2.847 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay', 'user1');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Delay', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Switch', 'user2');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Switch', 0, 1, 'cp : 2.847 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Switch5', 'user2');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Switch5', 0, 1, 'cp : 1.726 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Detect Rise Positive/FixPt Relational Operator', 'user2');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Detect Rise Positive/FixPt Relational Operator', 0, 1, 'cp : 1.374 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Detect Rise Positive/Positive', 'user2');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/Detect Rise Positive/Positive', 0, 1, 'cp : 0.687 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/finite_control_set/finite_control_set', 'user2');
annotate_port('gm_uz_6ph_pu_vsd_voltages/uz_6ph_pu_voltages_vsd/finite_control_set/finite_control_set', 1, 4, 'cp : 2.847 ns');
