SLStudio.Utils.RemoveHighlighting(get_param('IPCore_3Level_PWM', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_IPCore_3Level_PWM', 'handle'));
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM', 1, 4, '');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/MinPWM_instance1', 0, 1, '');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/t', 0, 1, '');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/Multiport Switch', 0, 1, '');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/mux', 0, 1, '');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/PWM_carrier_comparison', 1, 3, '');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Switch2', 0, 1, '');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Relational Operator2', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Relational Operator2', 0, 1, '');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Relational Operator3', 0, 1, '');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Relational Operator3', 0, 1, '');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/PWM_carrier_comparison/Data Type Conversion', 0, 1, '');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/PWM_carrier_comparison/delayMatch', 1, 1, '');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/MinPWM_instance1/range checker1', 0, 1, '');
