open_system('gm_IPCore_3Level_PWM');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM', 'user2');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM', 1, 4, 'cp : 9.766 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/MinPWM_instance1', 'user2');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/MinPWM_instance1', 0, 1, 'cp : 8.539 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/t', 'user2');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/t', 0, 1, 'cp : 8.539 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/Multiport Switch', 'user1');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/Multiport Switch', 0, 1, 'cp : 1.023 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/mux', 'user2');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/mux', 0, 1, 'cp : 1.023 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/PWM_carrier_comparison', 'user2');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/PWM_carrier_comparison', 1, 3, 'cp : 9.766 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Switch2', 'user2');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/Switch2', 0, 1, 'cp : 8.823 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/PWM_carrier_comparison/Data Type Conversion', 'user2');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/PWM_carrier_comparison/Data Type Conversion', 0, 1, 'cp : 9.505 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/PWM_carrier_comparison/delayMatch', 'user1');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/PWM_carrier_comparison/delayMatch', 1, 1, 'cp : 9.766 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/MinPWM_instance1/range checker1', 'user2');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/MinPWM_instance1/range checker1', 0, 1, 'cp : 4.123 ns');
