open_system('gm_IPCore_3Level_PWM');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM', 'user2');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM', 0, 1, 'cp : 5.53 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen', 'user2');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen', 0, 1, 'cp : 5.53 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide/Divide', 'user2');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/CarrierGen/Divide/Divide', 0, 1, 'cp : 5.53 ns');
