open_system('IPCore_3Level_PWM');
open_system('gm_IPCore_3Level_PWM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/PWM_Direct_Comparison/Relational Operator', 'user1');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/PWM_Direct_Comparison/Relational Operator', 0, 1, 'Blocks delay absorption: 46 cycles');
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/PWM_Direct_Comparison/Relational Operator', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/PWM_Direct_Comparison/Relational Operator', 0, 1, 'Blocks delay absorption: 46 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/PWM_Direct_Comparison/Relational Operator1', 'user1');
annotate_port('gm_IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/PWM_Direct_Comparison/Relational Operator1', 0, 1, 'Blocks delay absorption: 46 cycles');
hilite_system('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/PWM_Direct_Comparison/Relational Operator1', 'user1');
annotate_port('IPCore_3Level_PWM/IP_Core_3-Level_PWM/GenPWM/PWM_Direct_Comparison/Relational Operator1', 0, 1, 'Blocks delay absorption: 46 cycles');
