SLStudio.Utils.RemoveHighlighting(get_param('Phase_voltages_per_switching_state_MPC_6Phase', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_Phase_voltages_per_switching_state_MPC_6Phase', 'handle'));
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Detect Rise Positive1', 1, 1, '');
annotate_port('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Detect Rise Positive1', 1, 1, '');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function', 0, 1, '');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Data Type Conversion1', 1, 1, '');
annotate_port('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Data Type Conversion1', 1, 1, '');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Data Type Conversion10', 1, 1, '');
annotate_port('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Data Type Conversion10', 1, 1, '');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Data Type Conversion2', 1, 1, '');
annotate_port('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Data Type Conversion2', 1, 1, '');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Data Type Conversion3', 1, 1, '');
annotate_port('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Data Type Conversion3', 1, 1, '');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Data Type Conversion6', 1, 1, '');
annotate_port('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Data Type Conversion6', 1, 1, '');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Detect Rise Positive1/Positive', 1, 1, '');
annotate_port('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Detect Rise Positive1/Positive', 1, 1, '');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/Assignment', 1, 1, '');
annotate_port('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function', 1, 1, '');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/Assignment1', 1, 1, '');
annotate_port('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function', 1, 1, '');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/Assignment2', 1, 1, '');
annotate_port('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function', 1, 1, '');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/Assignment3', 1, 1, '');
annotate_port('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function', 1, 1, '');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/t', 1, 1, '');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/t1', 1, 1, '');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/t2', 1, 1, '');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/t3', 1, 1, '');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/t4', 1, 1, '');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/t5', 1, 1, '');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/cos_to_sincos', 0, 1, '');
