open_system('Phase_voltages_per_switching_state_MPC_6Phase');
open_system('gm_Phase_voltages_per_switching_state_MPC_6Phase');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Detect Rise Positive1', 'user2');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Detect Rise Positive1', 1, 1, 'Block not characterized');
hilite_system('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Detect Rise Positive1', 'user2');
annotate_port('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Detect Rise Positive1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Data Type Conversion1', 'user2');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Data Type Conversion1', 1, 1, 'Block not characterized for this configuration');
hilite_system('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Data Type Conversion1', 'user2');
annotate_port('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Data Type Conversion1', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Data Type Conversion10', 'user2');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Data Type Conversion10', 1, 1, 'Block not characterized for this configuration');
hilite_system('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Data Type Conversion10', 'user2');
annotate_port('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Data Type Conversion10', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Data Type Conversion2', 'user2');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Data Type Conversion2', 1, 1, 'Block not characterized for this configuration');
hilite_system('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Data Type Conversion2', 'user2');
annotate_port('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Data Type Conversion2', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Data Type Conversion3', 'user2');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Data Type Conversion3', 1, 1, 'Block not characterized for this configuration');
hilite_system('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Data Type Conversion3', 'user2');
annotate_port('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Data Type Conversion3', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Data Type Conversion6', 'user2');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Data Type Conversion6', 1, 1, 'Block not characterized for this configuration');
hilite_system('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Data Type Conversion6', 'user2');
annotate_port('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Data Type Conversion6', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Detect Rise Positive1/Positive', 'user2');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Detect Rise Positive1/Positive', 1, 1, 'Block not characterized');
hilite_system('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Detect Rise Positive1/Positive', 'user2');
annotate_port('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/Detect Rise Positive1/Positive', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/Assignment', 'user2');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/Assignment', 1, 1, 'Block not characterized');
hilite_system('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function', 'user2');
annotate_port('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/Assignment1', 'user2');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/Assignment1', 1, 1, 'Block not characterized');
hilite_system('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function', 'user2');
annotate_port('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/Assignment2', 'user2');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/Assignment2', 1, 1, 'Block not characterized');
hilite_system('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function', 'user2');
annotate_port('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/Assignment3', 'user2');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/Assignment3', 1, 1, 'Block not characterized');
hilite_system('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function', 'user2');
annotate_port('Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/t', 'user2');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/t1', 'user2');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/t1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/t2', 'user2');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/t2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/t3', 'user2');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/t3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/t4', 'user2');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/t4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/t5', 'user2');
annotate_port('gm_Phase_voltages_per_switching_state_MPC_6Phase/HDL_DUT/MATLAB Function/t5', 1, 1, 'Block not characterized');
