#ifndef PT1_CONTROL_CONFIG_H
#define PT1_CONTROL_CONFIG_H

#define PT1_CONTROL_AGENT_DQN 1U
#define PT1_CONTROL_AGENT_DDPG 2U

#ifndef PT1_CONTROL_AGENT
#define PT1_CONTROL_AGENT PT1_CONTROL_AGENT_DQN
#endif

#if (PT1_CONTROL_AGENT != PT1_CONTROL_AGENT_DQN) && (PT1_CONTROL_AGENT != PT1_CONTROL_AGENT_DDPG)
#error PT1_CONTROL_AGENT must be PT1_CONTROL_AGENT_DQN or PT1_CONTROL_AGENT_DDPG
#endif

#ifndef PT1_CONTROL_PLANT_BASE_ADDRESS
#ifdef DQN_PT1_PLANT_BASE_ADDRESS
#define PT1_CONTROL_PLANT_BASE_ADDRESS DQN_PT1_PLANT_BASE_ADDRESS
#else
#define PT1_CONTROL_PLANT_BASE_ADDRESS XPAR_UZ_USER_UZ_PLANTMODEL_PT1_0_BASEADDR
#endif
#endif

#define PT1_CONTROL_PLANT_IP_CORE_FREQUENCY_HZ 100000000U
#define PT1_CONTROL_DECIMATION 100U
#define PT1_CONTROL_GAIN 1.0f
#define PT1_CONTROL_TIME_CONSTANT_S 0.2f
#define PT1_CONTROL_INITIAL_SETPOINT 0.0f
#define PT1_CONTROL_ACTION_MIN (-1.0f)
#define PT1_CONTROL_ACTION_MAX 1.0f

#ifndef DQN_PT1_PLANT_BASE_ADDRESS
#define DQN_PT1_PLANT_BASE_ADDRESS PT1_CONTROL_PLANT_BASE_ADDRESS
#endif
#ifndef DQN_PT1_PLANT_IP_CORE_FREQUENCY_HZ
#define DQN_PT1_PLANT_IP_CORE_FREQUENCY_HZ PT1_CONTROL_PLANT_IP_CORE_FREQUENCY_HZ
#endif
#ifndef DQN_PT1_CONTROL_DECIMATION
#define DQN_PT1_CONTROL_DECIMATION PT1_CONTROL_DECIMATION
#endif
#ifndef DQN_PT1_GAIN
#define DQN_PT1_GAIN PT1_CONTROL_GAIN
#endif
#ifndef DQN_PT1_TIME_CONSTANT_S
#define DQN_PT1_TIME_CONSTANT_S PT1_CONTROL_TIME_CONSTANT_S
#endif
#ifndef DQN_PT1_INITIAL_SETPOINT
#define DQN_PT1_INITIAL_SETPOINT PT1_CONTROL_INITIAL_SETPOINT
#endif

#endif
