#ifndef PT1_CONTROL_CONFIG_H
#define PT1_CONTROL_CONFIG_H

#define PT1_CONTROL_AGENT_DQN 1U
#define PT1_CONTROL_AGENT_DDPG 2U

#include "../uz/uz_global_configuration.h"

#ifndef PT1_CONTROL_AGENT
#define PT1_CONTROL_AGENT PT1_CONTROL_AGENT_DQN
#endif

#if (PT1_CONTROL_AGENT != PT1_CONTROL_AGENT_DQN) && (PT1_CONTROL_AGENT != PT1_CONTROL_AGENT_DDPG)
#error PT1_CONTROL_AGENT must be PT1_CONTROL_AGENT_DQN or PT1_CONTROL_AGENT_DDPG
#endif

#define PT1_CONTROL_GAIN 1.0f
#define PT1_CONTROL_TIME_CONSTANT_S 0.002f
#define PT1_CONTROL_INITIAL_SETPOINT 0.0f

#ifndef PT1_EVAL_PROFILE_EPISODE_SECONDS
#define PT1_EVAL_PROFILE_EPISODE_SECONDS 0.05f
#endif

#define PT1_CONTROL_ACTION_MIN (-1.0f)
#define PT1_CONTROL_ACTION_MAX 1.0f

#endif
