SLStudio.Utils.RemoveHighlighting(get_param('test_RS_flipflop_statemachine', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_test_RS_flipflop_statemachine', 'handle'));
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict', 0, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/cost_and_optim/Detect Rise Positive', 1, 1, '');
annotate_port('test_RS_flipflop_statemachine/mpc/cost_and_optim/Detect Rise Positive', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/cost_and_optim/Delay', 1, 1, '');
annotate_port('test_RS_flipflop_statemachine/mpc/cost_and_optim/Delay', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/cost_and_optim/Delay1', 1, 1, '');
annotate_port('test_RS_flipflop_statemachine/mpc/cost_and_optim/Delay1', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/delay_comp/Detect Rise Positive', 1, 1, '');
annotate_port('test_RS_flipflop_statemachine/mpc/delay_comp/Detect Rise Positive', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/delay_comp/Detect Rise Positive1', 1, 1, '');
annotate_port('test_RS_flipflop_statemachine/mpc/delay_comp/Detect Rise Positive1', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/delay_comp/Delay', 1, 1, '');
annotate_port('test_RS_flipflop_statemachine/mpc/delay_comp/Delay', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/delay_comp/Delay1', 1, 1, '');
annotate_port('test_RS_flipflop_statemachine/mpc/delay_comp/Delay1', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/delay_comp/Delay5', 1, 1, '');
annotate_port('test_RS_flipflop_statemachine/mpc/delay_comp/Delay5', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/delay_comp/Delay6', 1, 1, '');
annotate_port('test_RS_flipflop_statemachine/mpc/delay_comp/Delay6', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/delay_comp/Delay7', 1, 1, '');
annotate_port('test_RS_flipflop_statemachine/mpc/delay_comp/Delay7', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/delay_comp/Subsystem/Unit Delay_ctrl_delay', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Detect Rise Positive', 1, 1, '');
annotate_port('test_RS_flipflop_statemachine/mpc/predict/Detect Rise Positive', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Detect Rise Positive1', 1, 1, '');
annotate_port('test_RS_flipflop_statemachine/mpc/predict/Detect Rise Positive1', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Detect Rise Positive2', 0, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Detect Rise Positive2', 1, 1, '');
annotate_port('test_RS_flipflop_statemachine/mpc/predict/Detect Rise Positive2', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Subsystem', 0, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Delay', 1, 1, '');
annotate_port('test_RS_flipflop_statemachine/mpc/predict/Delay', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Delay1', 1, 1, '');
annotate_port('test_RS_flipflop_statemachine/mpc/predict/Delay1', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Delay11', 0, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Delay11', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Delay11', 1, 1, '');
annotate_port('test_RS_flipflop_statemachine/mpc/predict/Delay11', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Delay12', 1, 1, '');
annotate_port('test_RS_flipflop_statemachine/mpc/predict/Delay12', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Delay13', 1, 1, '');
annotate_port('test_RS_flipflop_statemachine/mpc/predict/Delay13', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Delay5', 1, 1, '');
annotate_port('test_RS_flipflop_statemachine/mpc/predict/Delay5', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Delay6', 1, 1, '');
annotate_port('test_RS_flipflop_statemachine/mpc/predict/Delay6', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Delay7', 1, 1, '');
annotate_port('test_RS_flipflop_statemachine/mpc/predict/Delay7', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Delay8', 1, 1, '');
annotate_port('test_RS_flipflop_statemachine/mpc/predict/Delay8', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Delay5_ctrl_delay', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Delay6_ctrl_delay', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Delay7_ctrl_delay', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Logical Operator1', 0, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Relational Operator1', 0, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Switch1', 0, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Switch4', 0, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Detect Rise Positive2/FixPt Relational Operator', 0, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Detect Rise Positive2/Positive', 0, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Subsystem/Data Type Conversion2', 0, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Subsystem/Logical Operator', 0, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Subsystem/Logical Operator4', 0, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Subsystem/Logical Operator5', 0, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Subsystem/Switch1', 0, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/vsd_dq_voltages/Detect Rise Positive', 1, 1, '');
annotate_port('test_RS_flipflop_statemachine/mpc/vsd_dq_voltages/Detect Rise Positive', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/vsd_dq_voltages/Delay', 1, 1, '');
annotate_port('test_RS_flipflop_statemachine/mpc/vsd_dq_voltages/Delay', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/vsd_dq_voltages/Delay1', 1, 1, '');
annotate_port('test_RS_flipflop_statemachine/mpc/vsd_dq_voltages/Delay1', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/vsd_dq_voltages/Delay5', 1, 1, '');
annotate_port('test_RS_flipflop_statemachine/mpc/vsd_dq_voltages/Delay5', 1, 1, '');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/vsd_dq_voltages/Delay6', 1, 1, '');
annotate_port('test_RS_flipflop_statemachine/mpc/vsd_dq_voltages/Delay6', 1, 1, '');
