open_system('gm_test_RS_flipflop_statemachine');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/predict', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict', 0, 1, 'cp : 6.248 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/predict/Detect Rise Positive2', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Detect Rise Positive2', 0, 1, 'cp : 1.374 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/predict/Subsystem', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Subsystem', 0, 1, 'cp : 3.816 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/predict/Delay11', 'user1');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Delay11', 0, 1, 'cp : 0 ns');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Delay11', 1, 1, 'cp : 6.248 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/predict/Logical Operator1', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Logical Operator1', 0, 1, 'cp : 6.248 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/predict/Relational Operator1', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Relational Operator1', 0, 1, 'cp : 5.388 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/predict/Switch1', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Switch1', 0, 1, 'cp : 4.52 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/predict/Switch4', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Switch4', 0, 1, 'cp : 4.168 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/predict/Detect Rise Positive2/FixPt Relational Operator', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Detect Rise Positive2/FixPt Relational Operator', 0, 1, 'cp : 1.374 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/predict/Detect Rise Positive2/Positive', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Detect Rise Positive2/Positive', 0, 1, 'cp : 0.687 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/predict/Subsystem/Data Type Conversion2', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Subsystem/Data Type Conversion2', 0, 1, 'cp : 1.374 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/predict/Subsystem/Logical Operator', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Subsystem/Logical Operator', 0, 1, 'cp : 1.658 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/predict/Subsystem/Logical Operator4', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Subsystem/Logical Operator4', 0, 1, 'cp : 3.488 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/predict/Subsystem/Logical Operator5', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Subsystem/Logical Operator5', 0, 1, 'cp : 2.546 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/predict/Subsystem/Switch1', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Subsystem/Switch1', 0, 1, 'cp : 3.816 ns');
