open_system('test_RS_flipflop_statemachine');
open_system('gm_test_RS_flipflop_statemachine');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/cost_and_optim/Detect Rise Positive', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/cost_and_optim/Detect Rise Positive', 1, 1, 'Block not characterized');
hilite_system('test_RS_flipflop_statemachine/mpc/cost_and_optim/Detect Rise Positive', 'user2');
annotate_port('test_RS_flipflop_statemachine/mpc/cost_and_optim/Detect Rise Positive', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/cost_and_optim/Delay', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/cost_and_optim/Delay', 1, 1, 'Block not characterized');
hilite_system('test_RS_flipflop_statemachine/mpc/cost_and_optim/Delay', 'user2');
annotate_port('test_RS_flipflop_statemachine/mpc/cost_and_optim/Delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/cost_and_optim/Delay1', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/cost_and_optim/Delay1', 1, 1, 'Block not characterized');
hilite_system('test_RS_flipflop_statemachine/mpc/cost_and_optim/Delay1', 'user2');
annotate_port('test_RS_flipflop_statemachine/mpc/cost_and_optim/Delay1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/delay_comp/Detect Rise Positive', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/delay_comp/Detect Rise Positive', 1, 1, 'Block not characterized');
hilite_system('test_RS_flipflop_statemachine/mpc/delay_comp/Detect Rise Positive', 'user2');
annotate_port('test_RS_flipflop_statemachine/mpc/delay_comp/Detect Rise Positive', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/delay_comp/Detect Rise Positive1', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/delay_comp/Detect Rise Positive1', 1, 1, 'Block not characterized');
hilite_system('test_RS_flipflop_statemachine/mpc/delay_comp/Detect Rise Positive1', 'user2');
annotate_port('test_RS_flipflop_statemachine/mpc/delay_comp/Detect Rise Positive1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/delay_comp/Delay', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/delay_comp/Delay', 1, 1, 'Block not characterized');
hilite_system('test_RS_flipflop_statemachine/mpc/delay_comp/Delay', 'user2');
annotate_port('test_RS_flipflop_statemachine/mpc/delay_comp/Delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/delay_comp/Delay1', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/delay_comp/Delay1', 1, 1, 'Block not characterized');
hilite_system('test_RS_flipflop_statemachine/mpc/delay_comp/Delay1', 'user2');
annotate_port('test_RS_flipflop_statemachine/mpc/delay_comp/Delay1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/delay_comp/Delay5', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/delay_comp/Delay5', 1, 1, 'Block not characterized');
hilite_system('test_RS_flipflop_statemachine/mpc/delay_comp/Delay5', 'user2');
annotate_port('test_RS_flipflop_statemachine/mpc/delay_comp/Delay5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/delay_comp/Delay6', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/delay_comp/Delay6', 1, 1, 'Block not characterized');
hilite_system('test_RS_flipflop_statemachine/mpc/delay_comp/Delay6', 'user2');
annotate_port('test_RS_flipflop_statemachine/mpc/delay_comp/Delay6', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/delay_comp/Delay7', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/delay_comp/Delay7', 1, 1, 'Block not characterized');
hilite_system('test_RS_flipflop_statemachine/mpc/delay_comp/Delay7', 'user2');
annotate_port('test_RS_flipflop_statemachine/mpc/delay_comp/Delay7', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/delay_comp/Subsystem/Unit Delay_ctrl_delay', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/delay_comp/Subsystem/Unit Delay_ctrl_delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/predict/Detect Rise Positive', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Detect Rise Positive', 1, 1, 'Block not characterized');
hilite_system('test_RS_flipflop_statemachine/mpc/predict/Detect Rise Positive', 'user2');
annotate_port('test_RS_flipflop_statemachine/mpc/predict/Detect Rise Positive', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/predict/Detect Rise Positive1', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Detect Rise Positive1', 1, 1, 'Block not characterized');
hilite_system('test_RS_flipflop_statemachine/mpc/predict/Detect Rise Positive1', 'user2');
annotate_port('test_RS_flipflop_statemachine/mpc/predict/Detect Rise Positive1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/predict/Detect Rise Positive2', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Detect Rise Positive2', 1, 1, 'Block not characterized');
hilite_system('test_RS_flipflop_statemachine/mpc/predict/Detect Rise Positive2', 'user2');
annotate_port('test_RS_flipflop_statemachine/mpc/predict/Detect Rise Positive2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/predict/Delay', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Delay', 1, 1, 'Block not characterized');
hilite_system('test_RS_flipflop_statemachine/mpc/predict/Delay', 'user2');
annotate_port('test_RS_flipflop_statemachine/mpc/predict/Delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/predict/Delay1', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Delay1', 1, 1, 'Block not characterized');
hilite_system('test_RS_flipflop_statemachine/mpc/predict/Delay1', 'user2');
annotate_port('test_RS_flipflop_statemachine/mpc/predict/Delay1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/predict/Delay11', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Delay11', 1, 1, 'Block not characterized');
hilite_system('test_RS_flipflop_statemachine/mpc/predict/Delay11', 'user2');
annotate_port('test_RS_flipflop_statemachine/mpc/predict/Delay11', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/predict/Delay12', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Delay12', 1, 1, 'Block not characterized');
hilite_system('test_RS_flipflop_statemachine/mpc/predict/Delay12', 'user2');
annotate_port('test_RS_flipflop_statemachine/mpc/predict/Delay12', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/predict/Delay13', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Delay13', 1, 1, 'Block not characterized');
hilite_system('test_RS_flipflop_statemachine/mpc/predict/Delay13', 'user2');
annotate_port('test_RS_flipflop_statemachine/mpc/predict/Delay13', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/predict/Delay5', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Delay5', 1, 1, 'Block not characterized');
hilite_system('test_RS_flipflop_statemachine/mpc/predict/Delay5', 'user2');
annotate_port('test_RS_flipflop_statemachine/mpc/predict/Delay5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/predict/Delay6', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Delay6', 1, 1, 'Block not characterized');
hilite_system('test_RS_flipflop_statemachine/mpc/predict/Delay6', 'user2');
annotate_port('test_RS_flipflop_statemachine/mpc/predict/Delay6', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/predict/Delay7', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Delay7', 1, 1, 'Block not characterized');
hilite_system('test_RS_flipflop_statemachine/mpc/predict/Delay7', 'user2');
annotate_port('test_RS_flipflop_statemachine/mpc/predict/Delay7', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/predict/Delay8', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Delay8', 1, 1, 'Block not characterized');
hilite_system('test_RS_flipflop_statemachine/mpc/predict/Delay8', 'user2');
annotate_port('test_RS_flipflop_statemachine/mpc/predict/Delay8', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/predict/Delay5_ctrl_delay', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Delay5_ctrl_delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/predict/Delay6_ctrl_delay', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Delay6_ctrl_delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/predict/Delay7_ctrl_delay', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/predict/Delay7_ctrl_delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/vsd_dq_voltages/Detect Rise Positive', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/vsd_dq_voltages/Detect Rise Positive', 1, 1, 'Block not characterized');
hilite_system('test_RS_flipflop_statemachine/mpc/vsd_dq_voltages/Detect Rise Positive', 'user2');
annotate_port('test_RS_flipflop_statemachine/mpc/vsd_dq_voltages/Detect Rise Positive', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/vsd_dq_voltages/Delay', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/vsd_dq_voltages/Delay', 1, 1, 'Block not characterized');
hilite_system('test_RS_flipflop_statemachine/mpc/vsd_dq_voltages/Delay', 'user2');
annotate_port('test_RS_flipflop_statemachine/mpc/vsd_dq_voltages/Delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/vsd_dq_voltages/Delay1', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/vsd_dq_voltages/Delay1', 1, 1, 'Block not characterized');
hilite_system('test_RS_flipflop_statemachine/mpc/vsd_dq_voltages/Delay1', 'user2');
annotate_port('test_RS_flipflop_statemachine/mpc/vsd_dq_voltages/Delay1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/vsd_dq_voltages/Delay5', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/vsd_dq_voltages/Delay5', 1, 1, 'Block not characterized');
hilite_system('test_RS_flipflop_statemachine/mpc/vsd_dq_voltages/Delay5', 'user2');
annotate_port('test_RS_flipflop_statemachine/mpc/vsd_dq_voltages/Delay5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_test_RS_flipflop_statemachine/mpc/vsd_dq_voltages/Delay6', 'user2');
annotate_port('gm_test_RS_flipflop_statemachine/mpc/vsd_dq_voltages/Delay6', 1, 1, 'Block not characterized');
hilite_system('test_RS_flipflop_statemachine/mpc/vsd_dq_voltages/Delay6', 'user2');
annotate_port('test_RS_flipflop_statemachine/mpc/vsd_dq_voltages/Delay6', 1, 1, 'Block not characterized');
