#ifndef UZ_U_F_CONTROL_H
#define UZ_U_F_CONTROL_H
#include "../uz_Space_Vector_Modulation/uz_space_vector_modulation.h"
typedef struct uz_u_f_control_t uz_u_f_control_t;
enum uz_u_f_control_safe_operating_region_violation {uz_u_f_control_no_violation=0,uz_u_f_control_dc_link_voltage_violation_lower,uz_u_f_control_dc_link_voltage_violation_upper,uz_u_f_control_duty_cycle_violation_lower,uz_u_f_control_duty_cycle_violation_upper};
struct uz_u_f_control_config_t {float frequency_setpoint_Hz,max_frequency_Hz,frequency_ramp_Hz_per_s,ratio_V_per_Hz,boost_voltage_V,max_voltage_V,minimum_pulse_width,dc_link_voltage_lower_bound_V,dc_link_voltage_upper_bound_V; struct uz_DutyCycle_t default_duty_cycle;};
struct uz_u_f_control_data_t {float frequency_command_Hz,electrical_phase_rad,applied_voltage_magnitude_V;};
uz_u_f_control_t *uz_u_f_control_init(struct uz_u_f_control_config_t config);
struct uz_DutyCycle_t uz_u_f_control_sample(uz_u_f_control_t*,float,float);
void uz_u_f_control_set_frequency(uz_u_f_control_t*,float);
void uz_u_f_control_reset(uz_u_f_control_t*);
const struct uz_u_f_control_data_t *uz_u_f_control_get_data(uz_u_f_control_t*);
enum uz_u_f_control_safe_operating_region_violation uz_u_f_control_get_safe_operating_area_violation(uz_u_f_control_t*);
void uz_u_f_control_acknowledge_and_reset_error(uz_u_f_control_t*,float);
#endif
