-- -------------------------------------------------------------
-- 
-- File Name: C:\ultrazohm_sw\ip_cores\test_switching_states_6Phase_without_delays\hdlsrc\test_switching_states_6Phase_without_delays\test_swithcing_states_6Phase_without_delays_src_Positive.vhd
-- Created: 2022-10-14 16:22:04
-- 
-- Generated by MATLAB 9.12 and HDL Coder 3.20
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: test_swithcing_states_6Phase_without_delays_src_Positive
-- Source Path: test_switching_states_6Phase_without_delays/HDL_DUT2/Detect Rise Positive/Positive
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY test_swithcing_states_6Phase_without_delays_src_Positive IS
  PORT( u                                 :   IN    std_logic;
        y                                 :   OUT   std_logic
        );
END test_swithcing_states_6Phase_without_delays_src_Positive;


ARCHITECTURE rtl OF test_swithcing_states_6Phase_without_delays_src_Positive IS

  -- Signals
  SIGNAL Constant_out1                    : std_logic;
  SIGNAL Compare_relop1                   : std_logic;

BEGIN
  Constant_out1 <= '0';

  
  Compare_relop1 <= '1' WHEN u > Constant_out1 ELSE
      '0';

  y <= Compare_relop1;

END rtl;

