#pragma once
#ifndef TEST

// Hardware version of the UltraZohm
#define UZ_HARDWARE_VERSION 4U

#define D1_A_GAIN  12.555f // 12.2f //12.262f
#define D1_B_GAIN  12.564f // 12.2f // 11.808f
#define D1_C_GAIN  12.552f // 12.2f // 12.125f
#define D1_A_OFFSET 0.0078201f
#define D1_B_OFFSET 0.0029715f
#define D1_C_OFFSET -0.011468

#define D2_A_GAIN 12.547f // 12.216f
#define D2_B_GAIN 12.551f //14.083f
#define D2_C_GAIN 12.544f //12.073f
#define D2_A_OFFSET -0.014776f
#define D2_B_OFFSET -0.0052169f
#define D2_C_OFFSET -0.0027063f

#define D1_A_VOLTAGE_GAIN 12.01f
#define D1_B_VOLTAGE_GAIN 12.005f
#define D1_C_VOLTAGE_GAIN 12.008f
#define D1_A_VOLTAGE_OFFSET 0.037846f
#define D1_B_VOLTAGE_OFFSET 0.058787f
#define D1_C_VOLTAGE_OFFSET 0.051362f

#define D2_A_VOLTAGE_GAIN 11.925f
#define D2_B_VOLTAGE_GAIN 11.996f
#define D2_C_VOLTAGE_GAIN 12.002f
#define D2_A_VOLTAGE_OFFSET -0.30423f
#define D2_B_VOLTAGE_OFFSET 0.073247f
#define D2_C_VOLTAGE_OFFSET 0.04081f
// If Hardware version is v4 and the external STOP should be used, this define has to be set to 1. Otherwise, the external stop does nothing.
// For Version 3, the external STOP always works, but the hardware loopback is required if no external stop is used.
#define UZ_USE_EXTERNAL_STOP_ON_V4 1U

#if (UZ_HARDWARE_VERSION != 4U) && (UZ_USE_EXTERNAL_STOP_ON_V4 == 1U)
#error The UZ_USE_EXTERNAL_STOP_ON_V4 flag must not be used on hardware version 3. For hardware version 3, external stop can be used without the flag, prior versions to 3 do not have this feature.
#endif

#define PRIME_MOVER_SETPOINT_FILTER_CUTTOFF_FREQUENCY 1.0f

#define BECKHOFF 1
#define BUEHLER 2
#define HOERNER 3
#define BROSE 4
#define EBM 5
#define HEIDRIVE_D2 6
#define HEIDRIVE_D1 7

// Verfügbare agenten
// Heidrive
// a202_l1_td3_gaussian_heidrive
// a201_sidmoid_td3_gaussian_heidrive
// a277_sidmoid_td3_gaussian_heidrive_500k_30seeds
// a290_sig_td3_int_more_obs_heidrive_250k_2tau

// Brose
// a214_l1_td3_gaussian_brose
// a211_sidmoid_td3_gaussian_brose
// a252_sidmoid_td3_gaussian_brose_500k_updates
// a287_sig_td3_int_more_obs_brose_250k_2tau

// Buehler
// a221_l1_td3_gaussian_buehler
// a234_sigmoid_td3_gaussian_buehler
// a255_sidmoid_td3_gaussian_buehler_500k_updates
// a289_sig_td3_int_more_obs_buehler_250k_2tau

// EBMPabst
// a217_l1_td3_gaussian_ebmpabst
// a218_sidmoid_td3_gaussian_ebmpabst
// a254_sidmoid_td3_gaussian_ebm_500k_updates
// a288_sig_td3_int_more_obs_ebm_250k_2tau

// Beckhoff
// a215_l1_td3_gaussian_beckhoff
// a216_sidmoid_td3_gaussian_beckhoff
// a253_sidmoid_td3_gaussian_beckhoffe_500k_updates
// a291_sig_td3_int_more_obs_beckhoff_250k_2tau

#define CIL_1_TAU 1 // CIL uses 2tau if 0, 1 tau if one
#define READ_VCD 1 // Reads V_dc if 1, otherwise 48 V is assumed

//#define PROFILE_SETPOINT_DURATION_IN_ISR_TICKS 5000U // 11290U
#define PROFILE_SETPOINT_DURATION_IN_ISR_TICKS 20000U // 11290U

#define SETPOINT_PROFILE_ORIGINAL 1
#define SETPOINT_PROFILE_RS 2
#define SETPOINT_PROFILE_PARAID 3

#define SETPOINT_PROFILE SETPOINT_PROFILE_PARAID

#define DUT_MACHINE BROSE
#define AGENT 214
#define D1_MACHINE BROSE    // EBM, Brose, Hoerner, HEIDRIVE_D1
#define D2_MACHINE BECKHOFF // HEIDRIVE_D2, BUEHLER, BECKHOFF
// #define D1_IS_PRIME_MOVER 1U // Auto-calculate this define from DUT_MACHINE?

#if !((DUT_MACHINE == D1_MACHINE) || (DUT_MACHINE == D2_MACHINE))
#error DUT machine not connected!
#endif

#if (DUT_MACHINE == HOERNER) || (DUT_MACHINE == BROSE) || (DUT_MACHINE == EBM)
#define D1_IS_PRIME_MOVER 0U
#else
#define D1_IS_PRIME_MOVER 1U
#endif
#define D2_IS_PRIME_MOVER !D1_IS_PRIME_MOVER //

/** ISR trigger source
 *
 * chose here which of the above interrupt trigger you want to use:
 * 0 for Interrupt_2L_max_min
 * 1 for Interrupt_2L_min
 * 2 for Interrupt_2L_max
 * 3 for Interrupt_3L_start_center
 * 4 for Interrupt_3L_start
 * 5 for Interrupt_3L_center
 * 6 for Interrupt_timer_fcc
 */
#define INTERRUPT_ISR_SOURCE_USER_CHOICE 1U
#define INTERRUPT_ADC_TO_ISR_RATIO_USER_CHOICE 1U

#if D1_MACHINE == BROSE // Hoerner (2k), EBM (2k), Brose (5k)
#define UZ_D5_1_INCREMENTAL_ENCODER_RESOLUTION 5000.0f
#elif D1_MACHINE == HEIDRIVE_D1
#define UZ_D5_1_INCREMENTAL_ENCODER_RESOLUTION 256.0f // HEIDRIVE_D1
#else
#define UZ_D5_1_INCREMENTAL_ENCODER_RESOLUTION 2000.0f
#endif

#define UZ_D5_2_INCREMENTAL_ENCODER_RESOLUTION 256.0f  // always HEIDRIVE_D2
#define UZ_D5_3_INCREMENTAL_ENCODER_RESOLUTION 5000.0f // buehler

#define UZ_D5_1_MOTOR_POLE_PAIR_NUMBER 1.0f // handled in uz_pmsm_control
#define UZ_D5_2_MOTOR_POLE_PAIR_NUMBER 1.0f //
#define UZ_D5_3_MOTOR_POLE_PAIR_NUMBER 1.0f //
#define UZ_PWM_FREQUENCY 10.0e3f

// Configuration defines for the number of used instances
#define UZ_WAVEGEN_CHIRP_MAX_INSTANCES 0U
#define UZ_MYIP2_MAX_INSTANCES 0U
#define UZ_ADCLTC2311_MAX_INSTANCES 3U
#define UZ_PI_CONTROLLER_MAX_INSTANCES 12U
#define UZ_CURRENTCONTROL_MAX_INSTANCES 10U
#define UZ_INCREMENTALENCODER_MAX_INSTANCES 3U
#define UZ_PWM_SS_2L_MAX_INSTANCES 4U
#define UZ_NN_LAYER_MAX_INSTANCES 4U
#define UZ_NN_MAX_INSTANCES 2U
#define UZ_PMSMMODEL_MAX_INSTANCES 1U
#define UZ_DQ_TRANSFORMATION_IP_CORE_MAX_INSTANCES 0U
#define UZ_MUX_AXI_MAX_INSTANCES 1U
#define UZ_SPEEDCONTROL_MAX_INSTANCES 2U
#define UZ_IIR_FILTER_MAX_INSTANCES 24U
#define UZ_PARAMETERID_MAX_INSTANCES 0U
#define UZ_DAC_INTERFACE_MAX_INSTANCES 0U
#define UZ_PMSM6PH_TRANSFORMATION_MAX_INSTANCES 0U
#define UZ_PMSM9PH_TRANSFORMATION_MAX_INSTANCES 0U
#define UZ_SETPOINT_MAX_INSTANCES 2U
#define UZ_PMSM_MODEL6PH_DQ_MAX_INSTANCES 0U
#define UZ_PMSM_MODEL9PH_DQ_MAX_INSTANCES 0U
#define UZ_INVERTER_3PH_MAX_INSTANCES 3U
#define UZ_RESONANT_CONTROLLER_MAX_INSTANCES 0U
#define UZ_MOVINGAVERAGEFILTER_MAX_INSTANCES 0U
#define UZ_INVERTER_ADAPTER_MAX_INSTANCES 3U
#define UZ_TEMPERATURE_CARD_MAX_INSTANCES 0U
#define UZ_RESOLVERIP_MAX_INSTANCES 3U
#define UZ_SYSMON_PS_MAX_INSTANCES 0U // Can only be 1 or 0!
#define UZ_RESOLVER_PL_INTERFACE_MAX_INSTANCES 3U
#define UZ_AXI_GPIO_MAX_INSTANCES 0U
#define UZ_6PH_OPEN_PHASE_FAULT_DETECTION 0U
#define UZ_ENCODER_OFFSET_ESTIMATION_MAX_INSTANCES 1U
#define UZ_FILTER_CUMULATIVEAVG_MAX_INSTANCES 5U
#define UZ_DQ_SETPOINT_FILTER_MAX_INSTANCES 2U
#define UZ_SUBSYSTEM_RESONANT_CONTROL_MAX_INSTANCES 0U
#define UZ_TRAJECTORY_MAX_INSTANCES 0U
#define UZ_HARMONICCURRENTINJECTION_MAX_INSTANCES 0U
#define UZ_APPROXIMATE_FLUX_MAX_INSTANCES 2U
#define UZ_CURRENTCONTROL_KP_ADJUSTMENT_MAX_INSTANCES 2U
#define UZ_FLUX_PREDICTION_MAX_INSTANCES 2U
#define UZ_MLP_THREE_LAYER_IP_MAX_INSTANCES 2U
#define UZ_PMSM_CONTROL_MAX_INSTANCES 2U
#define UZ_RLCC_MAX_INSTANCES 1U

#endif

// Configuration defines for the number of used instances for testing with ceedling
#ifdef TEST
#define UZ_WAVEGEN_CHIRP_MAX_INSTANCES 13U
#define UZ_DAC_INTERFACE_MAX_INSTANCES 10U
#define UZ_MYIP2_MAX_INSTANCES 5U
#define UZ_MYIP_MAX_INSTANCES 5U
#define UZ_ADCLTC2311_MAX_INSTANCES 50U
#define UZ_PI_CONTROLLER_MAX_INSTANCES 100U
#define UZ_CURRENTCONTROL_MAX_INSTANCES 100U
#define UZ_INCREMENTALENCODER_MAX_INSTANCES 20U
#define UZ_NN_LAYER_MAX_INSTANCES 100U
#define UZ_NN_MAX_INSTANCES 20U
#define UZ_PWM_SS_2L_MAX_INSTANCES 50U
#define UZ_MATRIX_MAX_INSTANCES 201U
#define UZ_PMSMMODEL_MAX_INSTANCES 11U
#define UZ_PLANTPT1_MAX_INSTANCES 6U
#define UZ_DQ_TRANSFORMATION_IP_CORE_MAX_INSTANCES 11U
#define UZ_FILTER_1ST_ORDER_INSTANCES 20U
#define UZ_MUX_AXI_MAX_INSTANCES 10U
#define UZ_MLP_THREE_LAYER_IP_MAX_INSTANCES 20U
#define UZ_SPEEDCONTROL_MAX_INSTANCES 50U
#define UZ_IIR_FILTER_MAX_INSTANCES 20U
#define UZ_INVERTER_3PH_MAX_INSTANCES 20U
#define UZ_PMSM6PH_TRANSFORMATION_MAX_INSTANCES 20U
#define UZ_PARAMETERID_MAX_INSTANCES 100U
#define UZ_PMSM9PH_TRANSFORMATION_MAX_INSTANCES 20U
#define UZ_PMSM_MODEL6PH_DQ_MAX_INSTANCES 20U
#define UZ_PMSM_MODEL9PH_DQ_MAX_INSTANCES 20U
#define UZ_SETPOINT_MAX_INSTANCES 50U
#define UZ_INVERTER_3PH_MAX_INSTANCES 20U
#define UZ_RESONANT_CONTROLLER_MAX_INSTANCES 6U
#define UZ_SUM_MAX_INSTANCES 5U
#define UZ_MOVINGAVERAGEFILTER_MAX_INSTANCES 50U
#define UZ_INVERTER_ADAPTER_MAX_INSTANCES 20U
#define UZ_EXP_SMOOTH_MAX_INSTANCES 5U
#define UZ_TEMPERATURE_CARD_MAX_INSTANCES 10U
#define UZ_RESOLVERIP_MAX_INSTANCES 40U
#define UZ_SYSMON_PS_MAX_INSTANCES 10U
#define UZ_RESOLVER_PL_INTERFACE_MAX_INSTANCES 30U
#define UZ_AXI_GPIO_MAX_INSTANCES 10U
#define UZ_6PH_OPEN_PHASE_FAULT_DETECTION 2U
#define UZ_ENCODER_OFFSET_ESTIMATION_MAX_INSTANCES 10U
#define UZ_FILTER_CUMULATIVEAVG_MAX_INSTANCES 20U
#define UZ_DQ_SETPOINT_FILTER_MAX_INSTANCES 10U
#define UZ_SUBSYSTEM_RESONANT_CONTROL_MAX_INSTANCES 10U
#define UZ_TRAJECTORY_MAX_INSTANCES 50U
#define UZ_HARMONICCURRENTINJECTION_MAX_INSTANCES 20U
#define UZ_APPROXIMATE_FLUX_MAX_INSTANCES 5U
#define UZ_CURRENTCONTROL_KP_ADJUSTMENT_MAX_INSTANCES 5U
#define UZ_FLUX_PREDICTION_MAX_INSTANCES 5U
#define UZ_PMSM_CONTROL_MAX_INSTANCES 5U
#define UZ_RLCC_MAX_INSTANCES 15U
#endif
