open_system('uz_resolver_pl_interface');
open_system('gm_uz_resolver_pl_interface');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Detect Rise Positive', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Detect Rise Positive', 1, 1, 'Block not characterized');
hilite_system('uz_resolver_pl_interface/uz_resolver_pl_interface/Detect Rise Positive', 'user2');
annotate_port('uz_resolver_pl_interface/uz_resolver_pl_interface/Detect Rise Positive', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay1', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay1', 1, 1, 'Block not characterized');
hilite_system('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay1', 'user2');
annotate_port('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay10', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay10', 1, 1, 'Block not characterized');
hilite_system('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay10', 'user2');
annotate_port('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay10', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay11', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay11', 1, 1, 'Block not characterized');
hilite_system('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay11', 'user2');
annotate_port('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay11', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay13', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay13', 1, 1, 'Block not characterized');
hilite_system('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay13', 'user2');
annotate_port('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay13', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay15', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay15', 1, 1, 'Block not characterized');
hilite_system('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay15', 'user2');
annotate_port('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay15', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay17', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay17', 1, 1, 'Block not characterized');
hilite_system('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay17', 'user2');
annotate_port('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay17', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay19', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay19', 1, 1, 'Block not characterized');
hilite_system('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay19', 'user2');
annotate_port('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay19', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay2', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay2', 1, 1, 'Block not characterized');
hilite_system('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay2', 'user2');
annotate_port('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay23', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay23', 1, 1, 'Block not characterized');
hilite_system('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay23', 'user2');
annotate_port('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay23', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay24', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay24', 1, 1, 'Block not characterized');
hilite_system('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay24', 'user2');
annotate_port('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay24', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay25', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay25', 1, 1, 'Block not characterized');
hilite_system('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay25', 'user2');
annotate_port('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay25', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay26', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay26', 1, 1, 'Block not characterized');
hilite_system('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay26', 'user2');
annotate_port('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay26', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay27', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay27', 1, 1, 'Block not characterized');
hilite_system('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay27', 'user2');
annotate_port('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay27', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay6', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay6', 1, 1, 'Block not characterized');
hilite_system('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay6', 'user2');
annotate_port('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay6', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay9', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay9', 1, 1, 'Block not characterized');
hilite_system('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay9', 'user2');
annotate_port('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay9', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay12_ctrl_delay', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay12_ctrl_delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay5_ctrl_delay', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay5_ctrl_delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch1', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch2', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch3', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch4', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch5', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch6', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch6', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch7', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch7', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch8', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch8', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch9', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch9', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch10', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch10', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch11', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch11', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch12', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch12', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch13', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch13', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch14', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch14', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch15', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch15', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch16', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch16', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch17', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch17', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch18', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch18', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch19', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch19', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch20', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch20', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch21', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch21', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch22', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch22', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch23', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch23', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch24', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch24', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch25', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch25', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch26', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/delayMatch26', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay4', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay4', 1, 1, 'Block not characterized');
hilite_system('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay4', 'user2');
annotate_port('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay5', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay5', 1, 1, 'Block not characterized');
hilite_system('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay5', 'user2');
annotate_port('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay3', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay3', 1, 1, 'Block not characterized');
hilite_system('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay3', 'user2');
annotate_port('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay12', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay12', 1, 1, 'Block not characterized');
hilite_system('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay12', 'user2');
annotate_port('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay12', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay28', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay28', 1, 1, 'Block not characterized');
hilite_system('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay28', 'user2');
annotate_port('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay28', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay16', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay16', 1, 1, 'Block not characterized');
hilite_system('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay16', 'user2');
annotate_port('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay16', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay18', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay18', 1, 1, 'Block not characterized');
hilite_system('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay18', 'user2');
annotate_port('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay18', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay20', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/Delay20', 1, 1, 'Block not characterized');
hilite_system('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay20', 'user2');
annotate_port('uz_resolver_pl_interface/uz_resolver_pl_interface/Delay20', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/revolution_counter/revolution_counter', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/revolution_counter/revolution_counter', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/revolution_counter/revolution_counter', 'user2');
annotate_port('gm_uz_resolver_pl_interface/uz_resolver_pl_interface/revolution_counter/revolution_counter', 1, 1, 'Block not characterized');
hilite_system('uz_resolver_pl_interface/uz_resolver_pl_interface/revolution_counter', 'user2');
annotate_port('uz_resolver_pl_interface/uz_resolver_pl_interface/revolution_counter', 1, 1, 'Block not characterized');
