webtalk_init -webtalk_dir C:/XilinxEyke/MPSOC/007_AXI_TCM/AXI2TCM_sim_VHDL/AXI2TCM_sim_VHDL.sim/sim_1/behav/xsim/xsim.dir/tb_axi2tcm_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Nov 13 10:25:04 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211408329_1777531524_210690665_203" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d196b5cc-6c03-4219-93d8-ad4424b9e544" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "052cea282c814f6092436daf3ea2dfc1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2112 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "25.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "500 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.12_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "13504_KB" -context "xsim\\usage"
webtalk_transmit -clientid 315003575 -regid "211408329_1777531524_210690665_203" -xml C:/XilinxEyke/MPSOC/007_AXI_TCM/AXI2TCM_sim_VHDL/AXI2TCM_sim_VHDL.sim/sim_1/behav/xsim/xsim.dir/tb_axi2tcm_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/XilinxEyke/MPSOC/007_AXI_TCM/AXI2TCM_sim_VHDL/AXI2TCM_sim_VHDL.sim/sim_1/behav/xsim/xsim.dir/tb_axi2tcm_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/XilinxEyke/MPSOC/007_AXI_TCM/AXI2TCM_sim_VHDL/AXI2TCM_sim_VHDL.sim/sim_1/behav/xsim/xsim.dir/tb_axi2tcm_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
