name: documentation

on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: ultrazohm/ultrazohm_remote_container
    steps:
      - uses: actions/checkout@v3
        with: 
         lfs: 'true'
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt
      - name: sphinx build
        run: |
          cd docs
          make docs
      - name: Fix permissions
        run: |
          ls
          chmod -c -R +rX "docs/build/html/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
            done
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

# Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
