open_system('gm_uz_inverter_status');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_status/uz_inverter_status/Bit Slice Temp4', 'user1');
annotate_port('gm_uz_inverter_status/uz_inverter_status/Bit Slice Temp4', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_status/uz_inverter_status/Logical Operator10', 'user2');
annotate_port('gm_uz_inverter_status/uz_inverter_status/Logical Operator10', 0, 1, 'cp : 0.994 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_status/uz_inverter_status/Logical Operator3', 'user2');
annotate_port('gm_uz_inverter_status/uz_inverter_status/Logical Operator3', 0, 1, 'cp : 1.882 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uz_inverter_status/uz_inverter_status/Switch', 'user1');
annotate_port('gm_uz_inverter_status/uz_inverter_status/Switch', 0, 1, 'cp : 2.166 ns');
