open_system('gm_VSD_6ph_30deg_HDL');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Detect Rise Positive', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Detect Rise Positive', 0, 1, 'cp : 1.374 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/VSD_6ph_30deg', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/VSD_6ph_30deg', 1, 1, 'cp : 1.726 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay6', 'user1');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay6', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Switch', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Switch', 0, 1, 'cp : 1.726 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Detect Rise Positive/FixPt Relational Operator', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Detect Rise Positive/FixPt Relational Operator', 0, 1, 'cp : 1.374 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Detect Rise Positive/Positive', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Detect Rise Positive/Positive', 0, 1, 'cp : 0.687 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/VSD_6ph_30deg/VSD_6ph_30deg', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/VSD_6ph_30deg/VSD_6ph_30deg', 1, 1, 'cp : 1.726 ns');
