open_system('VSD_6ph_30deg_HDL');
open_system('gm_VSD_6ph_30deg_HDL');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Detect Rise Positive', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Detect Rise Positive', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Detect Rise Positive', 'user2');
annotate_port('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Detect Rise Positive', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay', 'user2');
annotate_port('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay1', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay1', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay1', 'user2');
annotate_port('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay10', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay10', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay10', 'user2');
annotate_port('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay10', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay11', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay11', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay11', 'user2');
annotate_port('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay11', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay12', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay12', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay12', 'user2');
annotate_port('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay12', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay13', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay13', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay13', 'user2');
annotate_port('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay13', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay14', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay14', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay14', 'user2');
annotate_port('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay14', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay15', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay15', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay15', 'user2');
annotate_port('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay15', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay16', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay16', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay16', 'user2');
annotate_port('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay16', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay17', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay17', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay17', 'user2');
annotate_port('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay17', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay18', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay18', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay18', 'user2');
annotate_port('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay18', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay19', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay19', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay19', 'user2');
annotate_port('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay19', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay2', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay2', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay2', 'user2');
annotate_port('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay20', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay20', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay20', 'user2');
annotate_port('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay20', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay21', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay21', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay21', 'user2');
annotate_port('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay21', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay22', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay22', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay22', 'user2');
annotate_port('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay22', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay23', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay23', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay23', 'user2');
annotate_port('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay23', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay24', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay24', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay24', 'user2');
annotate_port('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay24', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay25', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay25', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay25', 'user2');
annotate_port('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay25', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay3', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay3', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay3', 'user2');
annotate_port('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay4', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay4', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay4', 'user2');
annotate_port('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay5', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay5', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay5', 'user2');
annotate_port('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay6', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay6', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay6', 'user2');
annotate_port('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay6', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay7', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay7', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay7', 'user2');
annotate_port('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay7', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay8', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay8', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay8', 'user2');
annotate_port('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay8', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay9', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay9', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay9', 'user2');
annotate_port('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/Delay9', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/VSD_6ph_30deg/VSD_6ph_30deg', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/VSD_6ph_30deg/VSD_6ph_30deg', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/VSD_6ph_30deg/VSD_6ph_30deg', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/VSD_6ph_30deg/VSD_6ph_30deg', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/VSD_6ph_30deg', 'user2');
annotate_port('VSD_6ph_30deg_HDL/uz_vsd_6ph_30deg/VSD_6ph_30deg', 1, 1, 'Block not characterized');
