open_system('VSD_6ph_30deg_HDL');
open_system('gm_VSD_6ph_30deg_HDL');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/VSD_6ph_30deg/Detect Rise Positive', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/VSD_6ph_30deg/Detect Rise Positive', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/VSD_6ph_30deg/Detect Rise Positive', 'user2');
annotate_port('VSD_6ph_30deg_HDL/VSD_6ph_30deg/Detect Rise Positive', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/VSD_6ph_30deg/Delay', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/VSD_6ph_30deg/Delay', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/VSD_6ph_30deg/Delay', 'user2');
annotate_port('VSD_6ph_30deg_HDL/VSD_6ph_30deg/Delay', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/VSD_6ph_30deg/Delay1', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/VSD_6ph_30deg/Delay1', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/VSD_6ph_30deg/Delay1', 'user2');
annotate_port('VSD_6ph_30deg_HDL/VSD_6ph_30deg/Delay1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/VSD_6ph_30deg/Delay2', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/VSD_6ph_30deg/Delay2', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/VSD_6ph_30deg/Delay2', 'user2');
annotate_port('VSD_6ph_30deg_HDL/VSD_6ph_30deg/Delay2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/VSD_6ph_30deg/Delay3', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/VSD_6ph_30deg/Delay3', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/VSD_6ph_30deg/Delay3', 'user2');
annotate_port('VSD_6ph_30deg_HDL/VSD_6ph_30deg/Delay3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/VSD_6ph_30deg/Delay4', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/VSD_6ph_30deg/Delay4', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/VSD_6ph_30deg/Delay4', 'user2');
annotate_port('VSD_6ph_30deg_HDL/VSD_6ph_30deg/Delay4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/VSD_6ph_30deg/Delay5', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/VSD_6ph_30deg/Delay5', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/VSD_6ph_30deg/Delay5', 'user2');
annotate_port('VSD_6ph_30deg_HDL/VSD_6ph_30deg/Delay5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/VSD_6ph_30deg/VSD_6ph_30deg/VSD_6ph_30deg', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/VSD_6ph_30deg/VSD_6ph_30deg/VSD_6ph_30deg', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_VSD_6ph_30deg_HDL/VSD_6ph_30deg/VSD_6ph_30deg/VSD_6ph_30deg', 'user2');
annotate_port('gm_VSD_6ph_30deg_HDL/VSD_6ph_30deg/VSD_6ph_30deg/VSD_6ph_30deg', 1, 1, 'Block not characterized');
hilite_system('VSD_6ph_30deg_HDL/VSD_6ph_30deg/VSD_6ph_30deg', 'user2');
annotate_port('VSD_6ph_30deg_HDL/VSD_6ph_30deg/VSD_6ph_30deg', 1, 1, 'Block not characterized');
